### ISSUE TITLE
Replace yaml-cpp with libyaml + rapidjson

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#1004]
If you use tangram-es on a phone, you have probably noticed that it's a little slow to start up. In some cases, like loading the bubble-wrap style on an iPhone 4S, it can take **over 5 seconds** before the scene is ready to begin rendering anything. This is not acceptable performance. 

Here's a time trace of the scenario I described:
[load-bubble-wrap-iphone-4s.trace.zip](https://github.com/tangrams/tangram-es/files/514178/load-bubble-wrap-iphone-4s.trace.zip)

It doesn't take long to see that almost all of the time cost here can be attributed to yaml-cpp operations. I have theories about why yaml-cpp performs so poorly on mobile devices, but I don't think the cause matters very much because it is simply impractical for us to spend time optimizing or re-architecting yaml-cpp. 

I want to try an alternative. [libyaml](https://github.com/yaml/libyaml) is a SAX-style yaml parser written in C, it's generally considered to be the reference parser for yaml. [rapidjson](https://github.com/miloyip/rapidjson/) is the SAX-or-DOM-style json parser used in tangram-es, it's the fastest and best-written json library that I know of. I want to use libyaml to parse yaml documents into a rapidjson DOM. 

A json document doesn't do everything that a yaml document can do, but we're aiming for compatibility with tangram-js, which represents yaml as a js object, so we don't lose any information that would have been useful to us anyway. 

The semantic structures of json and yaml are quite similar and the library interfaces match up very well, so it should be simple to connect the two. 

What I hope to end up with is a simpler, faster parser and a more compact, efficient document representation. I anticipate that the biggest challenge of implementing this will be adapting our current code to use rapidjson document types where it now uses yaml-cpp types, which will be tedious but uncomplicated.

**Comment by tallytalwar** [comment]
I will surely love to bid good bye to yaml-cpp. Though it was a good friend to begin with, its relationship with tangram-es has grown complex and all because of its own tantrums :D.

Will go through the libyaml library and add more.
Thanks for creating this issue.

**Comment by blair1618** [comment]
Work on this is here: https://github.com/tangrams/y2j

Initial profiling on a raspberry pi showed an increase in parsing speed of roughly 10x. 

The new approach would also make it simple to dump a parsed scene file as min-ified JSON and use it as a cache on subsequent runs. Parsing a JSON version of the scene is roughly another 10x faster than parsing the original YAML.

**Comment by nvkelso** [comment]
JSON ftw, future tangram-bundler option?

**Comment by blair1618** [comment]
Yeah totally possible, and JSON is a strict subset of YAML 1.2 so it would even be backwards compatible!

**Comment by matteblair** [comment]
In the time since I created this issue our fork of yaml-cpp has gotten waaaaay faster - I think I can safely close this now.
