### ISSUE TITLE
Problem with build demo apk

### ISSUE THREAD

**Issue by willu2** [tangrams/tangram-es#1008]
Can somebody write by steps or make video, how to build this project on android emulator?
1. I download this project and open in Android studio.(open gradle from android folder). After import  have two folders: demo and tangram in browser.
2.I have SDK, NDK and path for them. (Windows 7)
3. Next i create emulator like Nexus 5 API 23 Android 7.0 arm64-v8a
when press button "Run 'demo'", I get exeption :couldn't find "libtangram.so"
In README.md i read that i must run "make android [ANDROID_ARCH=[x86|armeabi-v7a|armeabi]]"
and ./android/run.sh.
But how i can do this, what terminal i have to use? 
I have never used C++(libs) in android app.
Please help.

**Comment by willu2** [comment]
make android --- this command does not work in Win7.  
I installed "Cygwin64 Terminal" with shell and bash. Add to bash_profile some path: 
export ANDROID_SDK=`cygpath -u "$ANDROID_HOME"`
export ANDROID_NDK=`cygpath -u "$ANDROID_NDK"` ;
but command: "make android [ANDROID_ARCH=[x86|armeabi-v7a|armeabi]]" doesn't work;
error:
-bash: armeabi-v7a: command not found
-bash: armeabi]]: command not found

**Comment by blair1618** [comment]
Hello!

There is not currently a good way to build the tangram-es native libraries for android on Windows. However, if you only want to use the library in an application and you don't need to modify the library itself, you can just use tangram-es as a Gradle dependency. There is a collection of demo apps that use the library as a Gradle dependency here: https://github.com/tangrams/tangram-android-demos

**Comment by willu2** [comment]
Thank you very much.
