### ISSUE TITLE
change azimuth of sprite?

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1009]

**Comment by blair1618** [comment]
If I understand correctly, you want to change the orientation of a sprite drawn with a point style. This can be done with the `angle` draw parameter, as described in this recent change: https://github.com/tangrams/tangram-es/pull/925

**Comment by karimnaaji** [comment]
The angle of the marker would can be updated from https://github.com/tangrams/tangram-es/pull/925 using stylesheet update, but having an api to update the angle by `MarkerId` would still be convenient for the user.
