### ISSUE TITLE
MapData

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1011]
I find a problem with DataLayer. It's similar whith #843, sometimes text disappear. With points and lines everything is ok

> ```
> parking15:
>     data: { source: parking15}
>     filter: {$zoom: 15 }
>     draw:
>         sdk-point-overlay-parking-cluster:
>             size: 49px
>             interactive: false
>             collide: false
>             sprite: icon-merged-zones
>             visible: true
>         text-cluster:
>             text_wrap: false
>             text_source: 'parkingId'
>             anchor: center
>             font:
>                 fill: white
>                 family: Helvetica
>                 size: 7px
> ```

I use android SDK 0.4.2

**Comment by karimnaaji** [comment]
Hi @ivangorelow , this issue should be fixed once we move to the new marker API on android. Current work in progress is on https://github.com/tangrams/tangram-es/tree/android-marker.

We will keep you posted!

**Comment by ivangorelow** [comment]
And how can I build this branch to use in my project?

**Comment by karimnaaji** [comment]
Make sure to follow [those instructions](https://github.com/tangrams/tangram-es#android) to have a valid `NDK` installed on your machine.

Then from the branch, build the library all of the architectures you are targetting:
```sh
make android-native-lib ANDROID_ARCH=YOUR_ARCH
```
As in our [travis build](https://github.com/tangrams/tangram-es/blob/master/scripts/travis/script_deploy_android_snapshot.sh#L12).

Then generate the `.aar` library file:

```sh
make android-tangram-apk
```

We will update instructions in https://github.com/tangrams/tangram-es/issues/1048.

**Comment by ivangorelow** [comment]
I have created aar. I try to make getMapAsync, but I have exception:
`com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-support-annotations-25.0.0_25332bfb6773386bbe31d6e8c268e443a9a4ed71-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-slf4j-api-1.7.13_08566136412ba19bba53fcc92327ce5857580e80-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-junidecode-v0.2_566f84ae960490de2ac810d46d9a4f79ee38a2b4-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-jersey-core-1.8_9c50c8ab1cbdc0a805aa41d0ee48af8d259510f8-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-jersey-client-1.8_4d2f8c2529633fc42072150b580d133547d68622-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-internal_impl-25.0.0_b1149ed5ed95545fd52e2b31544e162d3be4795a-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-internal_impl-25.0.0_9a38f40caac72d5b0a1dcbbd2b36731e54267c90-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-internal_impl-24.2.1_d7067a67d514e268101487e4946566873be5df59-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-internal_impl-24.2.1_7b9d99524a3327f910af1744f036a4144f03985b-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-internal_impl-24.2.1_21a0f267a78eb42ef77bad4834f1ff7673a42631-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-intermediates-exploded-aar-tangram-debug_575f007939d6fdfcb34be181e891d4c330c359f9-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-droidparts-2.9.6_74bc1c9688029068a703ebacf1eb6da81356338b-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.jmedeisis-draglinearlayout-1.1.0_55bce5460511ade39d2787144d7ec58185d2def8-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.google.android.gms-play-services-maps-6.5.87_7ceb031751a32334d328f137e55e17cf60bde36a-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.google.android.gms-play-services-base-6.5.87_63167ba2760e6834bc39f1630ee0c1568fb7185c-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.github.rahatarmanahmed-circularprogressview-2.5.0_cf528bdeef209b9ef4d4eba43a1275b593290aba-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.github.JakeWharton-ViewPagerIndicator-2.4.1_c1be3cd2aeb5fab31291c8e33623dd864ee4e994-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.volley-volley-1.0.0_902910792e24c725f9c9425ce5b336de12958fb3-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-support-vector-drawable-24.2.1_cb34a509dfef4bdd4fd16f7227f25af346567602-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-support-v4-24.2.1_d5c9c4ca9d561d30802f69284aaf07f9015dc63e-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-support-media-compat-24.2.1_d2197d762ad3d52f9f36d520a01f3d925bb2a0f3-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-support-fragment-24.2.1_04c30d1c65875cc292e40cd0f9f1d7b4babb7b82-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-support-core-utils-24.2.1_0ee398bef216d739467ce9c045057ed2976872fd-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-support-core-ui-25.0.0_b40eccaf3a5d0aac9c7c8d9219bb3459a86e0089-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-support-compat-25.0.0_06bcdde4673f15413fc142d86fdd666369394f53-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-recyclerview-v7-25.0.0_a62484f7b8def0b916553f67a99413fdf29198f1-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-gridlayout-v7-24.2.1_d4eea363c8ea8694f5833e47dd3ae6d981984b3e-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-design-24.2.1_1496d0a0a1c75d448aee1997bf5a10ecec84d5cf-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-appcompat-v7-24.2.1_84b516bb251b41d3b0740112e2d80f7137c1d6e2-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-24.2.1_6db467088e76124a0c545b7926bbe58dde486dd2-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-butterknife-6.0.0_ccaa4c0efb0a21a59ef568ba0cec500e8f6dac37-classes.dex", dex file "/data/data/com.impulsm.mobileclientcodd/files/instant-run/dex/slice-Android-Universal-Image-Loader-v1.9.5_d9006a2f49e6f087078a64362d3231a99e20ce97-classes.dex"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64, /vendor/lib64, /system/lib64]]] couldn't find "libtangram.so"`

**Comment by karimnaaji** [comment]
More complete instructions to build for Android have been added here https://github.com/tangrams/tangram-es/tree/master/platforms/android. If this is still an issue with the new instructions feel free to reopen.
