### ISSUE TITLE
3d object such as stairs

### ISSUE THREAD

**Issue by am2222** [tangrams/tangram-es#1018]
Hi,
Is there any way to show 3d objects such as stairs?sth like gltf files and etc..

**Comment by blair1618** [comment]
Hi Majid,

tangram-es doesn't support 3D model files as a data source right now. To create 3D geometry you can encode your model in one of the currently supported data formats like GeoJSON. Models in these formats are currently limited to sets of polygons with "height" and "min_height" properties used for extrusion, but this covers a surprising amount of cases!

**Comment by am2222** [comment]
@blair1618  thanks for your help,
Is there any examples or tools to examine how for example manage to create an stairs in geojson format?

**Comment by blair1618** [comment]
A very simple tool for making GeoJSON is http://geojson.io but there are probably others. The basic idea is to create "polygon" features for each portion of your geometry that needs to be extruded to a different height. The "min_height" and  "height" members of the feature's "properties" should specify the minimum and maximum height in meters for that polygon.

**Comment by am2222** [comment]
@blair1618 thanks for your good explanation
