### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#1020]
I have only question whether do you have some roadmap of when new major version of Tangram-ES is coming out? Something like 0.4.3 or 0.5 maybe? Thank you.

**Comment by blair1618** [comment]
We don't have a roadmap of official releases right now, but we plan to release a major update to the android sdk (probably 0.5) with a new marker interface within the next two weeks.

**Comment by rwrx** [comment]
Thank you for info.
