### ISSUE TITLE
VS2015 version

### ISSUE THREAD

**Issue by charlenni** [tangrams/tangram-es#1025]
Is it possible to compile Tangram-ES with VS2015? It would be helpfull when using it with Xamarin projects. It would be phantastic to have an open source map library, that works directly with Xamarin.

**Comment by tallytalwar** [comment]
Hey

Tangram-es provides a c++ interface, and it seems Xamarin, needs C# bindings. You will have to work on getting the C# bindings for our c++ interface. 

You can also look at this cartoDB renderer which already provides C# bindings: https://github.com/CartoDB/mobile-sdk.

That being said, we have a PR from an outside contributor, to provide windows support: https://github.com/tangrams/tangram-es/pull/836. You can also look at this and see if its helpful to you.

**Comment by charlenni** [comment]
I know about CartoDB and the mobile SDK. They bought Nutiteq for this. But there are on problem for a small open source project: [the price](https://developer.nutiteq.com/).

The tip with #836 is very good. I try to study this. Perhaps you have an idee, when this PR is commited?

Is it possible to create a dynamically (Android) or statically (iOS) library of core?

**Comment by matteblair** [comment]
Looks like this issue got abandoned - sorry about that! Xamarin bindings are not a current priority for Tangram. Windows build support is a priority, but it doesn't seem like VS 2015 has sufficient compiler support for us to use it. Closing this issue.
