### ISSUE TITLE
Publish iOS binary Framework built from CI

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#1028]
https://github.com/mapzen/ios/issues/77

Also relevant https://github.com/tangrams/ios-framework/issues/5 and https://github.com/tangrams/tangram-es/pull/1003#discussion_r84091941

**Comment by matteblair** [comment]
CircleCI is already configured to build binary frameworks, so we can take this output artifact and push it to an S3 bucket the same way that we do for Android snapshots.

**Comment by msmollin** [comment]
This has been implemented as part of the 0.7.1 release updates.
