### ISSUE TITLE
zoom eased

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1047]
I'd like to create such animayion:
1) make  small zoom (for example 12)
2)change position 
3) set bigger zoom (for example 18)

Is it possible?

**Comment by blair1618** [comment]
Yes. The functions for setting and easing position and zoom are defined [here](https://github.com/tangrams/tangram-es/blob/master/core/src/tangram.h#L88-L102) for the C++ interface and [here](https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/MapController.java#L230-L317) for the Android interface.

**Comment by ivangorelow** [comment]
I know about this function, but I'd like to make it step by step. Nowadays if I make zoom(12) and after make zoom(16) map will have effect only for last function

**Comment by rwrx** [comment]
I know what do you mean. I am missing such functionality in Tangram-ES too. For example in Google Maps Android API this could be done by callbacks in camera animation functions.

**Comment by blair1618** [comment]
Ah, I misunderstood the question. What you want here is sometimes called "choreography", let's call it that for convenience. We don't have built-in functionality for camera choreography the way that the Google Maps API does, you would have to write additional code to manage that yourself. I've added an issue that describes this feature, where we'll track any decisions or progress on the feature: https://github.com/tangrams/tangram-es/issues/1050
