### ISSUE TITLE
Feature selection shaders should be built at initialization

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#1051]
The current implementation of feature selection uses lazy initialization of our shaders; this works fine for shader that are intended to be drawn on every frame since those shaders would be built for the first frame ever drawn, but for feature selection we should rather _warm up_ those shaders and  and draw a dummy frame on the background at tangram initialization to allocate enough graphics memory for the framebuffer / shaders and assemble the corresponding shaders from the scene.

`applySourceBlocks` is particularly a problem and would need to be optimized, since it's consuming a lot of time at both scene initialization and in that particular use case.

Here is a trace on a complex scene:
![screen shot 2016-10-31 at 4 40 27 pm](https://cloud.githubusercontent.com/assets/7061573/19870857/c3a3ce28-9f88-11e6-8788-3496675c348b.png)

[time-frame-iphone.trace.zip](https://github.com/tangrams/tangram-es/files/562862/time-frame-iphone.trace.zip)

**Comment by blair1618** [comment]
Whoa, good digging. I kind of figured that `std::regex` was slow, but this is worse than I feared 😞. We can definitely improve the performance of `applySourceBlocks`, that may be a good first step. 

A theoretical benefit of lazily compiling shaders is that if we never encounter a feature using a certain style, then we never have to compile the shaders for that style. I wonder if we could compile the selection shaders for a style whenever we compile its normal shaders.

Alternatively, maybe we should just compile all shaders at startup.

**Comment by bcamper** [comment]
What's the regex for? Can you take a substring to look for `global.` at the beginning of the string, and another to match on property name? (Maybe we already do this :)

**Comment by blair1618** [comment]
This the code for finding and replacing `#pragma tangram:` with shader source blocks. A regex search isn't strictly necessary, we were just very careful about finding the injection points correctly.

**Comment by bcamper** [comment]
Oh sorry :)

**Comment by karimnaaji** [comment]
Confirmed to happen on RELEASE builds.

**Comment by blair1618** [comment]
Bummer. Can you take a shot at improving the speed of `applySourceBlocks`?

**Comment by karimnaaji** [comment]
Improvements made as part of https://github.com/tangrams/tangram-es/pull/1060.

We can reopen if this shows up again on the profiler and give more thoughts to force selection shaders creation at an earlier stage.
