### ISSUE TITLE
Marker polyline crash on gl context destroy 

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#1052]
A crash that happened to me while testing polyline markers on desktop app.

Steps to reproduce on desktop demo app:
- add a marker polyline with geometry
- destroy the context (`delete` key)
- A crash should happen on `glDrawElements`

This issue could only happen on the desktop application (not on actual android context loss), but would be worth investigating to see if this happens once we have the marker interface on android.

Can be tested on this branch https://github.com/tangrams/tangram-es/tree/polyline-crash.

**Comment by blair1618** [comment]
Does this happen for other marker types, or just polylines?

**Comment by karimnaaji** [comment]
It didn't happen with point, it possibly happens with polygons, I haven't tested yet.
