### ISSUE TITLE
Point marker setVisible not working

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#1057]
Point marker visibility can't be updated from the API. 
Those markers are not using the style draw method to be drawn, and this is where visibility is used to skip render https://github.com/tangrams/tangram-es/blob/master/core/src/style/style.cpp#L400. It doesn't seem that point labels use that marker property anywhere else.

cc @sarahlensing

**Comment by blair1618** [comment]
Resolved by #1058
