### ISSUE TITLE
Add completion callback for applying scene updates

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1061]
It would be nice to be able to get a callback when scene updates complete (after calling `applySceneUpdate`) in the event you wish to update/add/remove certain UI elements based upon if the map is changing or not.

**Comment by tallytalwar** [comment]
This is not `ios` specific I guess. Should we remove that tag?

**Comment by msmollin** [comment]
Sure! I just noticed it on iOS so I didn't know if it was specific or not :)
