### ISSUE TITLE
Add an optional constructor/initializer to allow for pre-setting certain stylesheet keys before parsing

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1063]
In certain scenarios it would be advantageous for Tangram-es to allow pre-setting certain keys before parsing of a stylesheet begins in order to avoid re-parsing the entire style sheet later just to add URL query parameters. The current system leans towards developers use the synchronous scene loading functions in order to preempt things like tiles downloading so we can configure items such as URL query parameters or modify the stylesheet based on runtime configuration. The issue with using synchronous scene loading is this impacts performance on main application thread which on mobile OSes (iOS, Android, etc.) is generally frowned upon as it can impact UI performance and could lead to watchdog processes force-closing your application.

**Comment by tallytalwar** [comment]
Should be valid for all platforms tangram-es is supported. We should remove `android`, `ios` tags here!

**Comment by tallytalwar** [comment]
I believe we do provide a way to apply scene updates during initial scene load now, which should take care of this.
