### ISSUE TITLE
No effect of `setPixelScale()` once is set for the first time

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-es#1071]
How to replicate this:

- set the pixel scale to something
- load a scene (that have fonts) with it
- set the pixel scale to something else

Result: no effect of the last pixel scale change

**Comment by blair1618** [comment]
You're right, there's a bit of a bug here. Setting a new value in `setPixelScale()` does not _completely_ change the density of the scene, labels in the scene won't use the new pixel scale until their tile is re-built. We should make this happen automatically inside `setPixelScale()` and document the potential performance impact. For now, if an application _really_ needs to change pixel scale dynamically, it can call `setupGL()` to force all tiles to rebuild.
