### ISSUE TITLE
Reduce the size of tangram executable/library

### ISSUE THREAD

**Issue by gusti-andika** [tangrams/tangram-es#1077]
The resulting size of executable(linux) or library(android) is big, near 100M.
Is it possible to reduce the size?

**Comment by blair1618** [comment]
Non-debug builds on Linux should produce libraries under 10MB in size. The latest Android release archive is 11.7MB. I agree that it would be good to make the library smaller than it currently is, but if your builds are near 100MB in size then something is going wrong!

**Comment by hjanetzek** [comment]
To get smaller executables on desktop you can use `-DUSE_SYSTEM_FONT_LIBS=1 -DUSE_SYSTEM_GLFW_LIBS=1` cmake options. Tangram binary is 3.5MB for 64bit linux here.

**Comment by gusti-andika** [comment]
Thanks for update, my build is somehow messed up, now I can produce 4.5M for linux64 and 8.8M for armeabi-v7a.
