### ISSUE TITLE
Nested Imports on Android

### ISSUE THREAD

**Issue by ac87** [tangrams/tangram-es#1078]
Just updated to 0.4.6-SNAPSHOT.

I have 2 primary scene files vector.yaml and raster.yaml in the Assets folder. They are just lists of imports sharing some common imports these imports are in a subfolder 'assets/imports'

assets/raster.yaml looks like this
`import: [imports/globals.yaml, imports/styles.yaml, imports/textures.yaml, imports/layers-data.yaml, imports/raster.yaml]`

The debug window in Android Studio shows 'Failed to read file at path:' for all these imports/*.yaml

I can make it work by removing the nesting so I know its not the yaml itself.

Is this a bug or by design? It worked on 0.4.5.

EDIT:

Moved the outer yaml vector files imports to the file to the imports/vector.yaml and pointed at that to avoid the nesting problem on the yaml imports now I have also found a related issue on urls for the image import

> D/Tangram: Failed to open asset at path: imports/imports/imports/imports/imports/imports/imports/images/sprite.png

assets/imports/textures.yaml 
`textures:
    pois:
        url: images/sprite.png
        filtering: mipmap
        sprites:
...
`

**Comment by blair1618** [comment]
Hi @ac87, the handling of relative URLs in imports was changed just yesterday (https://github.com/tangrams/tangram-es/pull/1067), so that may explain why you are seeing different behavior. We have pretty good test coverage for this functionality, but I'll see if I can reproduce the sort of problem you're describing.

**Comment by blair1618** [comment]
Ok, I'm able to produce similar problems to what you're describing. Strangely it seems to only happen on Android! I'll follow-up when I have an explanation or a solution.

**Comment by blair1618** [comment]
Now I understand what's happening here. On Android, the paths we use to specify resources in the asset bundle are all technically relative URLs. This means that each time our scene importer evaluates the URLs in a scene, it will resolve these relative URLs against their parent scene's URL to try to arrive at the resource's absolute location - but there is no "anchoring" absolute URL in the Android asset bundle, so the URLs get resolved as relative paths over and over again!

We'll need to establish some kind of absolute URL for files in an Android asset bundle, we might internally give them a "asset://" scheme or something like that.
