### ISSUE TITLE
Improve Scene file not found / parsing errors

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1080]
Currently, if parsing fails due to not being able to load a scene.yaml because of an incorrect path, `sceneLoader` objects return a warning like:

`WARNING sceneLoader.cpp:160: No source defined in the yaml scene configuration.`

 Traversing through the code, there should probably be some error produced either at this line:

https://github.com/tangrams/tangram-es/blob/master/core/src/scene/sceneLoader.cpp#L57

or perhaps something inside of the actual scene importer (https://github.com/tangrams/tangram-es/blob/master/core/src/scene/importer.cpp)

It would be ideal to be able to surface this error all the way through to the implementing developers in order to be able to handle scene loading failures, but clearer logging messages would be a start.

**Comment by blair1618** [comment]
This is something I've gotten used to from working with tangram-es for so long, but I can see the need for better error reporting here. We may want to address this at the level of file/resource access functions - right now if you ask for a file that doesn't exist, you don't get a crash or an error message, you just get zero bytes back. We could redesign our file access interface to return a status as well as raw data, to distinguish empty files from non-existent files and report file-not-found errors as needed.

**Comment by matteblair** [comment]
The platform SDKs for Tangram now provide error details when loading a scene fails, e.g. for iOS: https://github.com/tangrams/tangram-es/blob/master/platforms/ios/framework/src/TGMapViewDelegate.h#L84
