### ISSUE TITLE
Use system libraries on linux

### ISSUE THREAD

**Issue by pnorman** [tangrams/tangram-es#1081]
With https://github.com/tangrams/tangram-es/blob/master/CMakeLists.txt#L6-L7 I see there is a way to use system libraries in the CMake file, but I can't find any documentation on this, or what options to pass `make`, because there's another level of indirection there.

**Comment by hjanetzek** [comment]
Hey! I've added this option to speed up compilation during development. Yeah, we should also document it for also others. You can pass cmake options through the Makefile with

`CMAKE_OPTIONS=" -DUSE_SYSTEM_GLFW_LIBS=1 -DUSE_SYSTEM_FONT_LIBS=1" make linux`

Or use cmake without the convenience Makefile directly
```
cmake ..  -DPLATFORM_TARGET=linux -DCMAKE_BUILD_TYPE=Release \
 -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DUSE_SYSTEM_FONT_LIBS=1 \
 -DUSE_SYSTEM_GLFW_LIBS=1
```

**Comment by pnorman** [comment]
I'm preparing a PR to add the GL and font library documentation to the linux part of the readme.

What about other libraries like variant? This can also be a system library. I'm not sure what the status is on Ubuntu is, but it's in Debian stretch and will make it to Ubuntu if it's not already there.
