### ISSUE TITLE
Allow scene updates to be applied before scene begins loading

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1090]
Currently there is no straightforward way to guarantee that scene updates are applied before a scene starts loading. It's technically possible if the implementing developer uses the synchronous scene loading and updating functions, but this has ramifications on mobile devices where anytime spent blocking the main thread has the potential of force-closing the implementing application.

Ideally there should be additional callbacks, along the lines of `sceneDidFinishParsing` and `sceneWillBeginLoading` so that we can have hooks into the asynchronous scene loading system but be able to inject modifications before tile loading / rendering begins.

**Comment by blair1618** [comment]
Would this solve the problem you're encountering? https://github.com/tangrams/tangram-es/issues/1063

**Comment by msmollin** [comment]
I forgot I opened that other one. Sorry :)
