### ISSUE TITLE
Make applySceneUpdates() synchronous, and create a separate applySceneUpdatesAsync()

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1091]
Currently it's non-obvious from an interface perspective that `applySceneUpdates()` is actually an asynchronous call. https://github.com/tangrams/tangram-es/blob/master/core/src/tangram.cpp#L265

Ideally this function should be synchronous while there should be another asynchronous version of this function. 

@hjanetzek noted in discussion that:
"One thing to take care of is that the Scene::m_config is shared with the derived Scene (to apply updates to). So make sure to not have sync and async scene updates taking place at the same time,  
since scene (and m_config) updates take place on a single worker thread they are synchronized this way."

**Comment by matteblair** [comment]
This has been resolved by substantially revising the scene loading/updating interface: https://github.com/tangrams/tangram-es/blob/master/platforms/ios/src/TangramMap/TGMapViewController.h#L492-L585
