### ISSUE TITLE
fatal error: aabb.h

### ISSUE THREAD

**Issue by 91yuan** [tangrams/tangram-es#1093]
Hello, when compile "tangram-es/core/src/labels/label.cpp", has error 'not found aabb.h' where can i find it

**Comment by blair1618** [comment]
Those files are in a submodule of this repository, which you'll have to check out using git:
```
git submodule update --init --recursive
```
This is described in the readme as well: https://github.com/tangrams/tangram-es#build

**Comment by 91yuan** [comment]
thanks, i had used "git submodule update --init --recursive", but some submodule does not download, so i download it manual，thank you for your reply
