### ISSUE TITLE
Marker with text styling

### ISSUE THREAD

**Issue by ac87** [tangrams/tangram-es#1094]
With the new Marker things (I'm specifically looking in Android), Is it possible to add a point marker with a text style?

```
...

Marker marker = mapController.addMarker();
marker.setPoint(coords);
marker.setStyling("{ style: 'text', text_source: function() { return 'Test'; }, font: { size: 14px } }");

...
```

Currently Tangram crashes on the setStyling line, Taking out the function works but I can't think of a work around to put text in there without a function? 

(On Android at least) any invalid yaml in setStyling kills the app with just which made playing with the new markers a little more tricky:

```
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 31076 (id.tangramstest)                                                             
[17 13:50:05.517  3029: 3029 W/         ] debuggerd: handling request: pid=31076 uid=10224 gid=10224 tid=31076
```

**Comment by blair1618** [comment]
I think the problem here is that the `{}` in the function definition look like YAML structures - so it can't be parsed. If you put the whole function string in quotes it may work:
```
marker.setStyling("{ style: 'text', text_source: \"function() { return 'Test'; }\", font: { size: 14px } }");
```
(you may also want to add `collide: false` to make sure that it isn't occluded by another label)

However, we should definitely not be crashing when invalid YAML is put in the styling string. That's a bug.

**Comment by ac87** [comment]
Ah, didn't think to try escaping it. That does indeed fix it for one marker...

If I add multiple markers with the same text, (aka the same function) they all appear 
If I try to change the text by changing the style, none of them appear! I see the following appear in the log:

`D/Tangram: ERROR styleContext.cpp:298: EvalFilterFn - function 59 not set`

I assume there's some optimization going on taking out the near identical 'styles'?

```
private void markerTest() {
    mapController.setPosition(new LngLat(-122.422345, 37.826570)); // alcatraz
    mapController.setZoom(10);

    addLabelMarker("Cam 1", new LngLat(-122.422345, 37.826570));
    // if this line is uncommented neither marker appears
    //addLabelMarker("Cam 2", new LngLat(-122.422695, 37.826288));
}

private void addLabelMarker(String label, LngLat coords) {
    Marker marker = mapController.addMarker();
    marker.setPoint(coords);
    marker.setStyling(getTextStyle(label));
}

private String getTextStyle(String text) {
    return "{ style: 'text', text_source: \"function() { return '"+ text +"'; }\", collide: false, font: { size: 64px, fill: '#ffffff', stroke: { color: '#000000', width: 2px } } }";
}
```

**Comment by blair1618** [comment]
There's no intentional 'optimization' that would have this effect, I don't know exactly what's going on there yet but I'll look more closely.

**Comment by ac87** [comment]
Thanks, would be good to have markers with text.

I believe the crash I'm seeing might be caused by the other issue #1078 as I still have invalid files being loaded and just trying to edit the main maps yaml style is causing odd crashes too. Reverting to 4.5 fixes these.

**Comment by ac87** [comment]
Just checked, a js function in any property for the marker style seems to cause this same bug, its not limited to text_source.

**Comment by blair1618** [comment]
Thanks for the info!
