### ISSUE TITLE
URLs in 'global' values are not resolved

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#1095]
Consider two scenes:

__/a.yaml__
```
import: dir/b.yaml
textures:
  icons:
    url: global.t
```

__/dir/b.yaml__
```
global:
  t: tex.png
```

The author of these scenes might expect that in the complete, merged scene of `/a.yaml`, the value of `textures.icons.url` would be `/dir/tex.png`. The actual value would be `tex.png`. 

The `global.` substitutions only happen after the importing and URL resolving process is finished, so a URL in one of these values will not be resolved against the location of the scene file where it is defined. This differs from the handling of other URL values, and the difference would not be obvious to a user who is unfamiliar with the implementation. 

It would initially seem like we should attempt to resolve any URLs in global values, however we cannot unambiguously determine whether any string in a global value could be a URL. During `global.` substitution, we would know whether the value is in a URL-like context, but at that point it is too late to resolve the URL because we don't know which document that node originally came from!

This is currently an open question that impacts both tangram and tangram-es.

**Comment by blair1618** [comment]
The simplest resolution I can think of for this is to restrict the semantics of `global.` such that it only performs __verbatim substitution__ and to state that clearly in the documentation.

With this restriction, the "right" way to make something like the example above would be:

__/a.yaml__
```
import: dir/b.yaml
```

__/dir/b.yaml__
```
textures:
  icons:
    url: tex.png
```

That is, if you want to make a resource with a URL available for importing then you should declare that resource globally instead of putting it in a `global.` value.

**Comment by bcamper** [comment]
I think verbatim substitution makes sense. The amount of work to make these URLs resolve like others seems like a poor tradeoff, at least with current usage.

**Comment by tallytalwar** [comment]
I guess https://github.com/tangrams/tangram-es/pull/1089 fixes this.
