### ISSUE TITLE
iOS Marker API not setting markers when referencing resources from a scene file

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1099]
Basic setup:
Scene file: bubble wrap from the no-api-key branch

Test Code (Swift):

```
import UIKit
import TangramMap
class TangramVC:  TGMapViewController{

    override func viewDidLoad() {
        super.viewDidLoad()
        self.loadSceneFile("scene.yaml")
    }

    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        let marker = markerAdd()
        let point = TGGeoPoint(longitude: -122.44880676269531, latitude: 37.76155490343394)
        markerSetStyling(marker, styling: "{ style: ux-location-gem-overlay, interactive: true, sprite: ux-current-location, size: 36px, collide: false }")
        markerSetPoint(marker, coordinates: point)
        markerSetVisible(marker, visible: true)
        animateToPosition(point, withDuration: 2.0)
        animateToZoomLevel(15, withDuration: 2.0)
    }
}
```

Note that if we use a style string not dependent on a style sheet, for example `{ style: 'points', color: 'white', size: [25px, 25px], order:500, collide: false }` then everything works and a 25px white circle appears on the map.

**Comment by blair1618** [comment]
On Android, the mechanism for loading a scene file is to launch an asynchronous task and then receive a callback when loading is complete and scene resources are available. We may want a similar mechanism for iOS so that we can rely on having scene resources available.

Markers can also use an arbitrary user-supplied bitmap, which would obviate the scene dependency.

**Comment by msmollin** [comment]
@blair1618 totally agreed, and we already have that functionality in the form of a `TGMapViewDelegate` callback. However, this particular problem is a little more vexing. Regardless of using either the "synchronous" method above, or the async method, neither get the gem to appear.

What's odd is that by applying a marker to the map, there seems to be a scene reload occurring, at least according to the logs I'm seeing. Perhaps there's a race condition where we're attempting to reference the scene file that has not yet completed parsing?

As for user supplied bitmaps, we haven't had a chance to expose that yet in the Objective-C wrapper.
