### ISSUE TITLE
"make ios" result in an error

### ISSUE THREAD

**Issue by RobertMathieu** [tangrams/tangram-es#1103]
When I try to do "make ios" i got this message : 

`
make: *** [ios-framework] Error 1
`

cmake is version 3.7.0 and Xcode 8.1.

When i open tangram.xcodeproj in /build/ios-framework with Xcode and I build "ALL_BUILD" I got a build succeeded.

I tried to do "make cmake-ios" and the result is the same.

**Comment by karimnaaji** [comment]
Does the solution of https://github.com/tangrams/tangram-es/issues/1042, fixes your issue?

```
gem install xcpretty
```

**Comment by RobertMathieu** [comment]
That's right, installing xcpretty solved this. Thanks.
