### ISSUE TITLE
how can i use offline .geojson data in Android

### ISSUE THREAD

**Issue by yuxingxing1988** [tangrams/tangram-es#1106]
for example my local url is :

sources:
    osm:
        type: geojson
        url:  data/data/local/ttt3d.geojson
        max_zoom: 16
        url_params:
            api_key: vector-tiles-tyHL4AY

how can i use it.

thank you for your help!

**Comment by blair1618** [comment]
Hello @yuxingxing1988! I can think of three things to try here:

1. The "type" of the data source should be "GeoJSON" (it is case-sensitive)

2. If the data file is not in the asset bundle for your Android application, then the "url" should be an absolute path. Try "/data/data/local/ttt3d.geojson". 

3. You don't need to specify "url_params" for a local file data source, you should try removing that section. With your current "url_params", tangram-es would look for a file called "data/data/local/ttt3d.geojson?api_key=vector-tiles-tyHL4AY", which probably isn't right!

Hope this helps.
