### ISSUE TITLE
emuglGLESv2 errors on on Android 4.2 (API 17)

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1109]
When scrolling the map (using the cinnabar style 4.0.0, if that makes any difference), I get tons of these error messages in the log:

```E/emuglGLESv2_enc: a vertex attribute index out of boundary is detected. Skipping corresponding vertex attribute.```

I tested it on Android 5.0, 6.0 and 4.2. **It only happens on 4.2**.
Also, otherwise the errors don't seem to have any effect on the rendering, everything looks fine.

[Interestingly, the people over at Mapbox seem to have a similar problem with GLES on Android 4.2](https://github.com/mapbox/mapbox-gl-native/issues/5868). Unfortunately, they (also) seem to have no clue where this is coming from.

**Comment by blair1618** [comment]
I can't think of any obvious reasons for this. What are the steps to reproduce this?

**Comment by westnordost** [comment]
Oh, it's enough to just have a MapView in your activity. Can you not reproduce it with any MapView on 4.2?

**Comment by blair1618** [comment]
I don't think I have a device running Android 4.2 available. Did you see this on an emulated device?

**Comment by westnordost** [comment]
Me neither ;-)
Yes, I do use an emulator. Not sure if there is any difference, but it is Nexus 4 API 17.

**Comment by westnordost** [comment]
I am not sure of how much of a bug this really is. I tested (my app) with emulators from API 17 to 24 and got other weird problems with I think API 18 and API 19 as well. I think API 18 does not know a location provider called `"gps"` and API 19 does not know a location provider `null`, even though LOST uses the Android `GPS_PROVIDER` constant.
I know, LOST is another project. My point is that perhaps this is just some Emulator weirdness. I think perhaps it is not worth investigating this bug until someone can get his hands on a real API 17 device.

**Comment by blair1618** [comment]
I see! Yeah, this could be an oddity of a particular emulator environment. This issue will remain low-priority until we see it reproduced on an actual device or a newer API level, or until we run out of other things to fix :)

**Comment by westnordost** [comment]
Yeah so I will close this. No sense to hunt for bugs that may just be emulator problems, plus, API 17 will be gone in a year or two.
