### ISSUE TITLE
Default scene pois fail to load

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#1113]
Our current scene loader fails to load the poi atlas texture on desktop for our default scene https://github.com/tangrams/tangram-es/blob/master/scenes/scene.yaml.

The Url gets replaced from `img/poi_icons_32.png` to `/img/poi_icons_32.png` in the scene importer while resolving scene urls, and fails to load later on in the scene loading pipeline. 

Possibly related issue https://github.com/tangrams/tangram-es/issues/1099.

**Comment by blair1618** [comment]
_Actually_ resolved by https://github.com/tangrams/tangram-es/pull/1174
