### ISSUE TITLE
compile error raspberry-pi

### ISSUE THREAD

**Issue by ric96** [tangrams/tangram-es#113]
pi@raspberrypi ~/tangram-es $ sudo apt-get install cmake g++-4.7 libcurl4-openssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
cmake is already the newest version.
g++-4.7 is already the newest version.
libcurl4-openssl-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi ~/tangram-es $ make rpi
-- Platform chosen : RASPBERRYPI
-- Including raspberrypi dependent cmake file : /home/pi/tangram-es/toolchains/raspberrypi.cmake
CMake Error at toolchains/raspberrypi.cmake:14 (message):
  Please install g++ version 4.7 or greater
Call Stack (most recent call first):
  CMakeLists.txt:50 (include)

-- Configuring incomplete, errors occurred!
Makefile:164: recipe for target 'cmake-rpi' failed
make: *** [cmake-rpi] Error 1
pi@raspberrypi ~/tangram-es $ 

i am getting the following error on raspberry pi both 1& 2 model.
it was compiling fine a few days back...

**Comment by tallytalwar** [comment]
Hello Sahaj

Can you check whats the default gcc/g++ version for you? 
If its not 4.7 or greater, once you install g++4.7 you can set the CC and CXX environment variable respectively to gcc-4.7 and g++-4.7.

You can refer the raspberry pi build instructions, which were updated recently. https://github.com/tangrams/tangram-es#raspberry-pi.

Let us know if this helps or if you still having issues building tangram on rpi.

Thanks

**Comment by tallytalwar** [comment]
Also, we moved to gcc 4.8, because it offers better c++11 support.

**Comment by ric96** [comment]
oh yeah,
forgot the export bit as i was still following the older instructions at raspberrypi.org.
thanx
