### ISSUE TITLE
[Android Studio on Windows] incbin.sh: line 100: od: command not found

### ISSUE THREAD

**Issue by Guillaume227** [tangrams/tangram-es#1139]
I am on the android-cmake branch and trying to run the demo app.
I have Android Studio 2.2.2 with ndk 13 on a windows 7 machine.

I am not able to build the demo app due to the following error:
`tangram-s\scripts\incbin.sh: line 100: od: command not found`

It seems to me more like an Android Studio setup issue than a tangram specific one, but i have been unable to get to the bottom of it. Has anyone seen that before ?

Cheers,
Guillaume

**Comment by blair1618** [comment]
Hi Guillaume! We don't "officially" support building tangram-es on Windows yet, but you can try renaming `scripts/incbin.sh` to `scripts/incbin.bat` and replacing the name in https://github.com/tangrams/tangram-es/blob/master/core/CMakeLists.txt#L102 too. 

That script has paths to run as either a Windows batch file or a Unix shell file, and currently it seems to be trying the Unix path on your Windows machine.

**Comment by Guillaume227** [comment]
thanks for the suggestion !
A new development is that I have successfully run the demo app from a Windows 10 machine, without making any of the changes you advocate.
I took care to align the Android Studio, SDK, tools etc. with the windows 7 machine I have the original problem on, but still no luck on that older OS.
So that could be down to some of the linux compatibility changes in Windows 10, like power shell and ubuntu on Windows.

**Comment by blair1618** [comment]
That's great news! Does the Windows 10 machine have "Bash on Ubuntu on Windows" installed? That would explain why the shell script worked. 

It sounds like the ".sh" -> ".bat" change didn't solve the problem on the Windows 7 machine?

**Comment by Guillaume227** [comment]
The ".sh" -> ".bat" didn't help in my case but I didn't investigate why in depth after noticing the different behavior on windows 10.

It turns out I don't even have the "Bash on Ubuntu on Windows" feature activated.
So maybe that's just the powershell and windows 10 out of the box.
Anyway it's pretty cool.

Thanks Matt.

**Comment by blair1618** [comment]
:+1:

**Comment by Guillaume227** [comment]
For the record: I found out the key difference between my two setups wasn't the windows version.
Instead, what made the incbin.sh work was that one machine had git bash for windows, while the other didn't. The *.sh were automatically opened using that bash version with all the right tools.

So now the Android demo is building on windows 7 as well as 10.
'Git for windows installer' has all the required deps.
