### ISSUE TITLE
README.txt in NDK-Directory is obsolete

### ISSUE THREAD

**Issue by MyZeD** [tangrams/tangram-es#1148]
Problem like: https://github.com/tensorflow/tensorflow/issues/1468#issuecomment-196133186

Got this Problem with CMake.
Source in https://github.com/tangrams/tangram-es/blob/master/toolchains/android.cmake#L11

Thanks :)

**Comment by blair1618** [comment]
We currently require NDK r10e for building the master branch, as noted in our README: https://github.com/tangrams/tangram-es#android

As you say, NDK versions r11 and newer don't contain this file, but they also make substantial changes to the layout of the NDK files and are therefore not backwards compatible with many build processes. 

We have a work-in-progress branch that supports building with newer versions of the NDK using Android Studio: https://github.com/tangrams/tangram-es/tree/android-cmake

**Comment by MyZeD** [comment]
Okay, thank you
