### ISSUE TITLE
Markers don't show (Android)

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1162]
I am testing the new marker api for Android. I want to display the current location as a marker. However, it does not seem to show at all. There is no error or info message on the log.

Android 5.1, Tangram-ES 0.4.6.

I do the following:
- When the map controller becomes available:
```
ownLocation = controller.addMarker();
ownLocation.setDrawable(R.drawable.ic_star_white_24dp);
ownLocation.setStyling("{ style: 'points', size: [27px, 27px], order: 2000, collide: false }");
```
- in `onLocationChanged(Location location)`
```
if(ownLocation != null)
{
	ownLocation.setVisible(true);
	ownLocation.setPointEased(
			new LngLat(location.getLongitude(), location.getLatitude()),
			1000, MapController.EaseType.CUBIC);
}
```
and finally `ownLocation.setVisible(false);` when ending to listen for location changes.

**Comment by blair1618** [comment]
Try adding `color: white` to the styling string. This won't actually change the color of your icon but it is currently a required parameter for styling rules, for complicated reasons. There are certainly ways we can make it easier to style markers :\
