### ISSUE TITLE
Registering clicks on markers (Android)

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1163]
This is a question regarding the new marker API on Android:
_How do I register clicks on markers and how do I get the information which marker was clicked?_

It seems there is neither a `setClickListener` on the `Marker` class nor a `setMarkerClickListener(int markerId)` on the `MapController`. So, if for markers, the `setFeaturePickListener` is used as well, then how do I know the marker ID?

**Comment by karimnaaji** [comment]
Hey, this is currently a work in progress, you can follow the core library work on https://github.com/tangrams/tangram-es/pull/1161, this will follow in iOS and Android platform layer update. Thoughts are welcome!
You can expect this feature to come in the next release of Tangram.

**Comment by westnordost** [comment]
Okay, then I close this issue.

**Comment by karimnaaji** [comment]
We can leave this open until https://github.com/tangrams/tangram-es/pull/1161 is on master.
