### ISSUE TITLE
Props list in onFeaturePick empty

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1164]
In 0.4.5, the map passed to `onFeaturePick(Map<String, String> props, float positionX, float positionY)` would include whatever keys and values were present for the picked feature.

In 0.4.6 without having changed my code, the map is simply empty.

The relevant code is (that I do register the feature pick listener goes without saying).
```
@Override
public void onFeaturePick(Map<String, String> props, float positionX, float positionY)
{
	/* shortened. My actual code checks for existence of a certain key and does a certain action 
depending on the value. It did not trigger in 0.4.6. Investigating, I found that props is always empty. */
	Log.i("PICK", (props != null && !props.isEmpty()) ? "ok" : "empty!");
}

@Override public boolean onSingleTapUp(float x, float y)
{
	return false;
}

@Override public boolean onSingleTapConfirmed(float x, float y)
{
	controller.pickFeature(x,y);
	return true;
}
```

**Comment by karimnaaji** [comment]
Hi @westnordost ,

We are sorry that this behavior was not properly mentioned on the release update, but this has been changed on https://github.com/tangrams/tangram-es/pull/1076. 

We found more appropriate to have a 1:1 relation between the user feature request, and the callback, meaning that every request finishes with a callback even if this one didn't result in an actual selection of a feature. This way, the user would be able to have a proper notification on whether the query actually failed (empty map) or succeeded.

**Comment by westnordost** [comment]
Hmm, I don't really get how the change reflects in how tangram-ES is to be used. So the onFeaturePick(...) callback does not exist anymore and is replaced by another callback that contains more/other information? I don't understand.

**Comment by karimnaaji** [comment]
>So the onFeaturePick(...) callback does not exist anymore and is replaced by another callback that contains more/other information? Or what? I don't understand.

`pickFeature ` selects geometry features https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/MapController.java#L654.
`pickLabel` selects label features https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/MapController.java#L674

We were not able to select geometry features on previous version of tangram-es, this has been introduced on [0.4.5-android](https://github.com/tangrams/tangram-es/releases/tag/0.4.5-android) release.

Depending on which version of tangram-es you are moving from, those behavior have been updated. 

If you were previously selecting labels/poi from `pickFeature` and expect to select _only_ labels, you would have to update your code to register a listener on [onLabelPick](https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/MapController.java#L88).
If you don't want to select geometry features, you would have to update your code to remove the listener associated with `pickFeature`.

**Comment by westnordost** [comment]
I think what I do not understand is what is (the difference between) a label feature / geometry feature? Can a label feature have geometry? Can a geometry feature have properties (i.e. "building=yes", "my_custom_property=x")?

**Comment by karimnaaji** [comment]
I hope I'm not making this as complicated as pronouncing my name:
- Geometry feature: anything fitting under polygons and polylines styles.
- Label feature: anything fitting under text and icon styles.
And yes both are those would have their properties associated with it! (so anything that was in the tile data: "building=yes", "my_custom_property=x"...)

OT: I'm actually not sure! But hearing the creativity of people on that always impresses me :)

**Comment by westnordost** [comment]
Ah, I see. Thanks for clearing that up!

OT: My friend's last name was pronounced "Naʤ" (like Du**tch**). I think he changes his name by now because it got on his nerves that people kept pronouncing his name wrong though ;-).

**Comment by ivangorelow** [comment]
Now I can't see props in pickFuture and in pickLabel also

**Comment by karimnaaji** [comment]
Hi @ivangorelow , did you marked the feature that needs to be picked as interactive? https://mapzen.com/documentation/tangram/draw/#interactive

**Comment by ivangorelow** [comment]
yes, pickFuture works with lines, but nothing works whith icons?

**Comment by karimnaaji** [comment]
>nothing works whith icons?

Icons are under the point style, more on https://mapzen.com/documentation/tangram/Styles-Overview/#points (also refer to that https://github.com/tangrams/tangram-es/issues/1164#issuecomment-266538524),  they should be marked with `interactive`, a `LabelPickListener` should be set to the map controller, and `pickLabelAt` called. Can you verify that all of this is correctly done in your application?

**Comment by ivangorelow** [comment]
What is pickLabelAt? is it pickLabel?

**Comment by karimnaaji** [comment]
Yes, https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/MapController.java#L679
