### ISSUE TITLE
Can't "make ios" 

### ISSUE THREAD

**Issue by RobertMathieu** [tangrams/tangram-es#1178]
Hi,
When i try to do a "make ios" I got some errors during compile.
I print all errors I got : 

`▸ Compiling sceneLoader.cpp

❌  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2194:15: no matching constructor for initialization of 'alfons::InputSource'

              __second_(_VSTD::forward<_Args2>(_VSTD::get<_I2>(__second_args))...)
              ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

❌  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2194:15: no matching constructor for initialization of 'alfons::InputSource'

              __second_(_VSTD::forward<_Args2>(_VSTD::get<_I2>(__second_args))...)
    ^

▸ Compiling fontContext.cpp

❌  /Users/polestar/Documents/Dev/tangram-es/core/src/text/fontContext.cpp:34:57: no viable conversion from 'std::__1::shared_ptr<alfons::InputSource>' to 'alfons::InputSource'

                m_font[i] = m_alfons.addFont("default", source, size);
    ^

❌  /Users/polestar/Documents/Dev/tangram-es/core/src/text/fontContext.cpp:36:57: no viable conversion from 'std::__1::shared_ptr<alfons::InputSource>' to 'const FontFace::Descriptor'

                m_font[i]->addFace(m_alfons.addFontFace(source, size));
                                                                 ^

❌  /Users/polestar/Documents/Dev/tangram-es/core/src/text/fontContext.cpp:232:44: no viable conversion from 'std::shared_ptr<alfons::InputSource>' to 'const FontFace::Descriptor'

        font->addFace(m_alfons.addFontFace(_source, size));
                                                                      ^

❌  /Users/polestar/Documents/Dev/tangram-es/core/src/text/fontContext.cpp:288:44: no viable conversion from 'std::__1::shared_ptr<alfons::InputSource>' to 'const FontFace::Descriptor'

        font->addFace(m_alfons.addFontFace(source, fontSize));
                                                                      ^

❌  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2194:15: no matching constructor for initialization of 'alfons::InputSource'

              __second_(_VSTD::forward<_Args2>(_VSTD::get<_I2>(__second_args))...)
                                                                      ^

** BUILD FAILED **

The following build commands failed:
	CompileC build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/i386/sceneLoader.o core/src/scene/sceneLoader.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/i386/fontContext.o core/src/text/fontContext.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/x86_64/sceneLoader.o core/src/scene/sceneLoader.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/x86_64/fontContext.o core/src/text/fontContext.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	Libtool build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/i386/libcore.a normal i386
	Libtool build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/x86_64/libcore.a normal x86_64
	CreateUniversalBinary build/ios-framework-sim/lib/Release/libcore.a normal i386\ x86_64
	Ld build/ios-framework-sim/tangram.build/Release-iphonesimulator/TangramMap.build/Objects-normal/i386/TangramMap normal i386
	Ld build/ios-framework-sim/tangram.build/Release-iphonesimulator/TangramMap.build/Objects-normal/x86_64/TangramMap normal x86_64
	CreateUniversalBinary build/ios-framework-sim/lib/Release/TangramMap.framework/TangramMap normal i386\ x86_64
(10 failures)

❌  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2194:15: no matching constructor for initialization of 'alfons::InputSource'

              __second_(_VSTD::forward<_Args2>(_VSTD::get<_I2>(__second_args))...)
    ^

▸ Compiling sceneLoader.cpp

❌  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2194:15: no matching constructor for initialization of 'alfons::InputSource'

              __second_(_VSTD::forward<_Args2>(_VSTD::get<_I2>(__second_args))...)
    ^

❌  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2194:15: no matching constructor for initialization of 'alfons::InputSource'

              __second_(_VSTD::forward<_Args2>(_VSTD::get<_I2>(__second_args))...)
    ^

▸ Compiling fontContext.cpp

❌  /Users/polestar/Documents/Dev/tangram-es/core/src/text/fontContext.cpp:34:57: no viable conversion from 'std::__1::shared_ptr<alfons::InputSource>' to 'alfons::InputSource'

                m_font[i] = m_alfons.addFont("default", source, size);
    ^

❌  /Users/polestar/Documents/Dev/tangram-es/core/src/text/fontContext.cpp:36:57: no viable conversion from 'std::__1::shared_ptr<alfons::InputSource>' to 'const FontFace::Descriptor'

                m_font[i]->addFace(m_alfons.addFontFace(source, size));
                                                                 ^

❌  /Users/polestar/Documents/Dev/tangram-es/core/src/text/fontContext.cpp:232:44: no viable conversion from 'std::shared_ptr<alfons::InputSource>' to 'const FontFace::Descriptor'

        font->addFace(m_alfons.addFontFace(_source, size));
                                                                      ^

❌  /Users/polestar/Documents/Dev/tangram-es/core/src/text/fontContext.cpp:288:44: no viable conversion from 'std::__1::shared_ptr<alfons::InputSource>' to 'const FontFace::Descriptor'

        font->addFace(m_alfons.addFontFace(source, fontSize));
                                                                      ^

❌  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2194:15: no matching constructor for initialization of 'alfons::InputSource'

              __second_(_VSTD::forward<_Args2>(_VSTD::get<_I2>(__second_args))...)
                                                                      ^

❌  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2194:15: no matching constructor for initialization of 'alfons::InputSource'

              __second_(_VSTD::forward<_Args2>(_VSTD::get<_I2>(__second_args))...)
    ^

▸ Building library libcore.a

❌  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/polestar/Documents/Dev/tangram-es/build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/i386/sceneLoader.o (No such file or directory)

❌  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/polestar/Documents/Dev/tangram-es/build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/i386/fontContext.o (No such file or directory)

▸ Building library libcore.a

❌  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/polestar/Documents/Dev/tangram-es/build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/x86_64/sceneLoader.o (No such file or directory)

❌  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/polestar/Documents/Dev/tangram-es/build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/x86_64/fontContext.o (No such file or directory)

❌  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/polestar/Documents/Dev/tangram-es/build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/i386/libcore.a (No such file or directory)

❌  error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't open file: /Users/polestar/Documents/Dev/tangram-es/build/ios-framework-sim/core/tangram.build/Release-iphonesimulator/core.build/Objects-normal/x86_64/libcore.a (No such file or directory)

▸ Building tangram/TangramMap [Release]
▸ Check Dependencies
▸ Linking TangramMap

❌  clang: error: no such file or directory: '/Users/polestar/Documents/Dev/tangram-es/build/ios-framework-sim/lib/Release/libcore.a'

▸ Linking TangramMap

❌  clang: error: no such file or directory: '/Users/polestar/Documents/Dev/tangram-es/build/ios-framework-sim/lib/Release/libcore.a'

❌  fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/polestar/Documents/Dev/tangram-es/build/ios-framework-sim/tangram.build/Release-iphonesimulator/TangramMap.build/Objects-normal/i386/TangramMap (No such file or directory)

▸ Touching TangramMap.framework
lipo build/ios-framework/lib/Release/TangramMap.framework/TangramMap \
		build/ios-framework-sim/lib/Release/TangramMap.framework/TangramMap \
		-create -output build/ios-framework-universal/Release/TangramMap.framework/TangramMap
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: build/ios-framework/lib/Release/TangramMap.framework/TangramMap (No such file or directory)
`

I hope it will help you.

**Comment by karimnaaji** [comment]
hi @RobertMathieu, thanks for trying out tangram-es , it could be that some submodules are out of sync. Can you try:

```
git submodule update
```

**Comment by RobertMathieu** [comment]
Hi @karimnaaji, you are right, this solved the problem and know i got build success.

But now when I try to launch the project i have an "No code signature found."  error.
I know it's not the subject of this post but i don't know what to do. I cleaned many times and tried other things but nothing works so i'm a little out of ideas.

**Comment by karimnaaji** [comment]
This is something mentioned in our README, you need to codesign the iOS framework.

Can you try the last step mentioned here https://github.com/tangrams/tangram-es#ios-demo-application?

**Comment by RobertMathieu** [comment]
I feel dumb to not have seen this line.
By checking this box all works fine. Thanks a lot and good job for this app !
