### ISSUE TITLE
Directional arrows on road

### ISSUE THREAD

**Issue by sheikh-iffi** [tangrams/tangram-es#1179]
Hi

I was wondering if there is a way to show directional arrows on road. e.g.
![google](https://cloud.githubusercontent.com/assets/12157369/21220876/e4690764-c2dc-11e6-9bca-3b98df256a0c.png)

**Comment by bcamper** [comment]
There is support for this in Tangram JS, with this syntax: https://github.com/tangrams/tangram/blob/master/demos/scene.yaml#L425-L434

We have not added this functionality to Tangram ES yet, but we will soon. @blair1618, I think we may need an issue added for this and related shield / point-on-line placement features?

**Comment by blair1618** [comment]
@bcamper yes, this is in our queue but we don't currently have an issue describing the feature. Are there relevant PRs from Tangram JS that we could use as reference?

**Comment by bcamper** [comment]
Yep - it's described pretty well in the [v0.11.0 release notes](https://github.com/tangrams/tangram/releases/tag/v0.11.0), with linked PRs in https://github.com/tangrams/tangram/pull/409 and https://github.com/tangrams/tangram/pull/441.

**Comment by blair1618** [comment]
https://github.com/tangrams/tangram-es/issues/1183
