### ISSUE TITLE
Animation in map

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1189]
Is it possible that animation works whith element only one times.
I'd like to change line's color smoothly

**Comment by ivangorelow** [comment]
![image](https://cloud.githubusercontent.com/assets/20596378/21353933/34536ecc-c6d9-11e6-94f4-725d1217221a.png)
something like that

**Comment by matteblair** [comment]
Hello!

I'm not sure I understand your question. Do you want to change the color of a line over time?

**Comment by ivangorelow** [comment]
no.
I want that line appear smoothy

**Comment by ivangorelow** [comment]
something like transition

**Comment by ivangorelow** [comment]
http://tangrams.github.io/shaders-demo/#16/40.7036/-74.0050

like rainbow here

**Comment by skorasaurus** [comment]
ivangorelow, 

I think you trying to describe a color gradient? (which, in a sense, is what the 'rainbow' selection in the link you mentioned above, is doing - the pixels' hues change incrementally (or 'smoothly' as you said' above ). 

I'm interested in doing the same thing (using this for polygons like small bodies of water, etc) and used some code from @patriciogonzalezvivo  - see https://mapzen.com/blog/behind-the-scenes-tron2/  for the basis of my code ) 

and started working on it with this https://thebookofshaders.com/edit.php?log=160726010850

**Comment by patriciogonzalezvivo** [comment]
Hi @ivangorelow! If I understand correctly you want to fade in a rainbow... but never fade it back... right?

A way to do that is to use `u_time` uniform but clamp it to a range between 0. and 1. So the timer on the map will achieve 1. seconds and stay in that value. Check line 40 of this example https://thebookofshaders.com/edit.php?log=170119144638

Note that in that example I'm looping through time with a `fract` in line 34. You probably don't want that.

**Comment by ivangorelow** [comment]
and how van I use your examples in my map whith android?
