### ISSUE TITLE
Allow for 0px size sprites (while point remains visible)

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-es#1193]
This is needed so locality labels can initially have townspot icons (point with text attachment) and then have a 0px sized townspot sprite while retaining the text attachment).

Support for this was added in [Tangram v0.11.5](https://github.com/tangrams/tangram/releases/tag/v0.11.5):

- Optimize handling of 0px-size points/labels (assists in showing only the text portion when using a points-based style) 825c6d9 300d4cc

**Comment by matteblair** [comment]
Upon initial inspection, this seems to "just work".

I'll look more closely and confirm that we aren't generating any problematic  "NaN" values or something.
