### ISSUE TITLE
Possible race condition/incorrect texture binding on texture atlas for text

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#1196]
![img_0002](https://cloud.githubusercontent.com/assets/7061573/21436457/962c101c-c84c-11e6-9da1-a1e1d9ff1e1e.PNG)

**Comment by matteblair** [comment]
I̡ ̴s̸e̛e ͟n̵o̧thing͠ w̶ro͘ng͡ her̴e
