### ISSUE TITLE
core/src/scene/stops.cpp did not handling      auto upper = nearestHigherFrame(_key); properly.

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#1203]
When the upper  is equal to the begnning of the vector.
`auto lower = upper - 1;` would cause lower to be a wild pointer(INVALID on MSVC).
And should not be accessed under Linux.

**Comment by matteblair** [comment]
Certainly it would be an error to dereference `lower` when `upper == frames.begin()`. Fortunately, our usage of these iterators carefully avoids ever doing that, as you can see in `Stops::evalFloat` https://github.com/tangrams/tangram-es/blob/master/core/src/scene/stops.cpp#L295-L311 

Are you aware of an execution path that would cause an invalid pointer to be _dereferenced_ here?

If you have a suggested revision to this piece of code then feel free to submit it in a PR and link it here.

**Comment by tallytalwar** [comment]
As mentioned above please submit a PR or a scenario which causes this issue. Please feel free to reopen if its still an issue with more information. Thanks
