### ISSUE TITLE
Crash after screen orientation change on Nexus 5X

### ISSUE THREAD

**Issue by placz** [tangrams/tangram-es#1206]
Tangram is consistently crashing for me on my nexus 5x when changing the device orientation (portrait <-> landscape). I managed to reproduce it in a way that hopefully will work for you:

Fire up the simplemap demo with a Nexus 5X emulator.
Zoom in somewhere (you have to move the camera).
Rotate the screen and you should crash:

01-05 16:51:01.228 3803-4095/com.mapzen.tangram.demos.simplemap A/libc: Invalid address 0xdf611000 passed to free: value not allocated
01-05 16:51:01.228 3803-4095/com.mapzen.tangram.demos.simplemap A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4095 (GLThread 196)

I used the x86_64 Lollipop and Marshmallow images with Google APIs and was able to reproduce it.  I was *not* able to reproduce it using a Nexus 6 or 5 configuration, which makes me think it is something unique with the 5x. This happens on my actual device as well (Nougat), so I don't think it's an emulator issue.  I've also seen less predictable crashes occasionally during onDestroy going in and out of the activity; I'm not sure if it's related.

**Comment by karimnaaji** [comment]
Hi @placz , 
Do you mind giving a try at this branch and see if this crash happens on your device?
https://github.com/tangrams/tangram-es/tree/gl-context-loss

**Comment by placz** [comment]
That seems to have done the trick; I haven't been able to make it crash on my device by rotating it - thank you!

**Comment by karimnaaji** [comment]
Ok thanks for testing! The fix should be in https://github.com/tangrams/tangram-es/pull/1234.
