### ISSUE TITLE
Reorganize project structure

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#1212]
Tangram-es has grown and changed over its life. Now that we have spent time working with, in, and around it, several of us on the tangram-es team have ideas of how to make the project structure more clear and useful.

Any contributors to tangram-es are free to voice ideas here for discussion!

**Comment by matteblair** [comment]
A suggestion for revising the directory structure:
```
tangram-es
  - bench
    - benchmark
    - src
    - CMakeLists.txt
  - core
    - deps (external projects used in 'core')
      - alfons
      - benchmark
      - ...
    - include (all public headers for 'core')
      - tangram
        - map.h
        - platform.h
        - ...
    - src (sources and private headers for 'core')
      - (all current folders in /core/src)
      - shaders
      - map.cpp
    - CMakeLists.txt (for building libcore)
  - docs (new folder for documentation and guides)
  - platforms
    - android
      - (all current folders in /android)
      - android.cmake
    - common
      - platform_gl.h/.cpp
      - glfw
    - ios
      - (all current folders in /ios)
      - ios.cmake
      - ios.framework.cmake
      - ios.toolchain.cmake
    - linux
      - include
      - src
      - linux.cmake
    - osx
      - include
      - src
      - darwin.cmake (rename to osx.cmake?)
    - rpi
      - include
      - src
      - raspberrypi.cmake
    - tizen
      - include
      - src
      - tizen.cmake
      - tizen.toolchain.cmake
  - scenes
  - scripts
  - tests
  - CMakeLists.txt (delegates to core and platform cmake scripts)
  - README, Makefile, etc.
```
If anything about this is not obvious, let me know and I'll add detail

**Comment by karimnaaji** [comment]
I think it's in pretty good shape already! The one part that I would suggest modifying in this structure is:

```
  - core
    - 3rdparty/deps (external projects used in 'core')
      - alfons
      - benchmark
      - ...
      + Header only libraries (if not already assumed to be there)
    - include (all public headers for 'core')
      - map.h
    - src (sources and private headers for 'core')
      - (all current folders in /core/src)
      - shaders
      - map.cpp
```
I think it's possible to only provide a single header `map.h` that would make it much easier to distribute the library as a single shared/static file + this single header.

I like the name deps but I think that `3rdparty` is a good alternative too.

The one thing that would be nice to have would be a way for a user using `CMake` and tangram-es as a submodule to simply use `add_subdirectory(tangram-submodule)` and be ready to start (where some outputs variable would be set as `TANGRAM_SOURCES`/`TANGRAM_INCLUDES`/`TANGRAM_PLATFORM_SOURCES` etc.. along with a couple of other options that could be provided in the lines of `set(TANGRAM_BUILD_OSX_PLATFORM` for example.

**Comment by matteblair** [comment]
I like the idea of defining useful CMake variables for projects that include tangram-es.

I agree about moving header-only libraries to the other dependencies, I had intended that but didn't make it explicit.

Another suggestion: For stable dependencies (i.e. those we don't update frequently) we should directly copy the source code for a released version. For projects like `benchmark`, `glfw`, `glm`, `rapidjson`, `duktape`, and probably others, we get no real benefit from having a submodule. We can make clones faster and reduce the total project size by keeping just the released files that we need for those projects rather than copying the whole history and all of their development files.

**Comment by hjanetzek** [comment]
I would prefer having external sources and submodules in one top-level directory. Everything else sounds good to me. 
Not sure about the single public header. Certainly we can provide a merge header containing all types necessary for the public api if that helps - on the other hand e.g. including `tangram.h` in `label.h` for `LabelType` is confusing to me. I think it would be better to have a type per file in the public headers directory.

**Comment by matteblair** [comment]
I too am unsure whether a single all-inclusive header makes sense for the core library. If we aim to provide a convenient way to use the public headers in code, we could provide a `tangram.h` whose only contents are `#include` statements for the other public headers. In terms of file management, I don't think copying a folder of header files would be an undue burden for users - or as Hannes suggested we could have an amalgamated header for distribution.

As for where to keep external sources and submodules: I can see some value in keeping them all in one top-level directory, but to me that would make it unclear where and how the dependencies are used. For instance, we currently keep out test-runner dependency in the `tests` folder and I think we're all happy with that.

**Comment by karimnaaji** [comment]
Between copying a folder and amalgamating the header it seems better to leave the user copy the folder of public headers; amalgamation can create complex header file that are hard to step through and read. For us it's the public interface and should be clear and well-documented since it's most likely used to understand the API before stepping through more advanced documentation. It's also true that we should have a type per file in that case since our sources shouldn't have to include `tangram.h` in general.

For dependencies, I also agree that those should be within the level that needs the dependency (e.g. glfw under `platform/` where it's being used, core dependencies within `core/`, test dependencies under `test`... It makes it more clear on what area of the code depends on something within the repository.

**Comment by tallytalwar** [comment]
I agree with most of this discussed above.

1. Public Headers: I agree with a directory containing all the necessary public headers and the user including that directory. (This can also be defined with the CMAKE variables @karimnaaji mentioned above).
2. Public/Private Headers: In most projects I have seen before, there is some explicit distinction between private and public header. Example: All private headers are caps, or something else obvious.
3. Linux/OSX: I am fine with merging these platforms and calling it Desktop (hopefully windows will/could be included in this in future?).

**Comment by MyZeD** [comment]
Please don't name the library "libcore", rather "libtangram-es" etc.
This Library isn't the middle of the world ;)
I have much librarys to include, so it isn't the perfect name-scheme.

**Comment by karimnaaji** [comment]
@MyZeD Thanks for the suggestion! This will be fixed in https://github.com/tangrams/tangram-es/pull/1547.
