### ISSUE TITLE
clustering

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1222]
Will uou make clustering for markers?

**Comment by matteblair** [comment]
Point clustering is not on our roadmap for the near future.

**Comment by rugk** [comment]
Really? Still not planned?

This is really an essential feature for all applications, which have many markers…
And instead of just hiding the markers (which results in users missing these) they should be "grouped together".

**Comment by rugk** [comment]
And for the far future? Anyone?

**Comment by tallytalwar** [comment]
We will be discussing some new future planning tasks soon and will consider this during the discussion process. Thanks for the patience.

**Comment by LeeWong** [comment]
Any update on this feature?
