### ISSUE TITLE
blend_order for markers

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1223]
How can I set blend order for the marker?

**Comment by tallytalwar** [comment]
`blend_order` is a style property. If you have a `style` in your scene which is assigned a `blend_order`, you can set the styling of the marker to use this style.

Example: If you are using our `bubble-wrap` style:
https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L1052

You can style a marker using the `icons` style as:
```
map->markerSetStyling(markerID, "{ style: 'icons', interactive: true, sprite: volcano }");
```
