### ISSUE TITLE
Tolerance with Marker Selection

### ISSUE THREAD

**Issue by Guillaume227** [tangrams/tangram-es#1226]
I have been trying out the new marker picking code, it's neat thanks.
It takes a (x,y) as input and so it can be pretty hard to hit a small size marker with the finger the first time around.
Would we consider adding an extra parameter to specify a tolerance, in effect the radius of a selection circle at which to probe for marker presence ?
Note that it could mean more than one marker is returned if that circle covers several markers.
Or we could only return the one closest to the exact (x,y) point in that case.

The same modification would also enhance the selection experience with labels and features.

**Comment by matteblair** [comment]
I agree! In fact we have started implementing this, but have not yet chosen a final approach. 
See this issue: https://github.com/tangrams/tangram-es/issues/1065
