### ISSUE TITLE
Is it possible to illustrate some shapes such as windows and doors in 3d using ymal?

### ISSUE THREAD

**Issue by am2222** [tangrams/tangram-es#1229]
Hi,
I can make 3d walls using tangram but I have some problems to create objects such as stairs, doors, and windows' can you please give me an idea how to create those shapes?Is it even possible to illustrate their 3d shapes?

**Comment by matteblair** [comment]
Creating complex 3D shapes is not really what vector tile data was intended for. Tangram can currently only create extruded shapes from polygons with a "height" property. With many extruded shapes together, you can theoretically create a wide range of shapes. However, this isn't a feature that tangram was designed for and we aren't able to provide support for it.
