### ISSUE TITLE
Is there are pickmarkerhandler in iOS (swift)?

### ISSUE THREAD

**Issue by seubseub** [tangrams/tangram-es#1231]
Hi I'm Newbie in tangram.

At First, Sorry about my English capability.

I'm trying to implement tangram in swift.

But I met problem.

I implemented 'markerpoint' in map. And then  When I tried to select marker, 

Nothing handled.

`  func mapView(_ mapView: TGMapViewController, didSelectMarker markerPickResult: TGMarkerPickResult?, atScreenPosition position: CGPoint) {
        print(markerPickResult?.coordinates as Any)
        print(markerPickResult?.identifier as Any)
        print("marker select good!!!!")
    } 
`
I think this method call 'selectmarker'

I set breakpoint here, but nothing happened.

So 'RecognizeSingleTapGesture' with this method,

mapview has pickLabel, pickfeature.

but not pickmarker !

I set delegate, recognizedelegate too.

what can i do?

Thank you for reading my problem.

**Comment by karimnaaji** [comment]
Hi @seubseub , can you share the styling code for this marker? Make sure that the property `interactive` is set, see the [documentation for this parameter](https://mapzen.com/documentation/tangram/draw/#interactive).

**Comment by seubseub** [comment]
@karimnaaji  Thank you for replying.  I just use styles in demo + interactive : true. list this. { style: 'points', interactive : true,  color: 'white', size: [10px, 10px], order:2000, collide: false }, { style: 'lines', interactive : true,  color: 'red', width: 5px, order: 1000 }. I use only point, polyline. but nothing show up. Thank you

**Comment by karimnaaji** [comment]
Does anything is being shown at all?

**Comment by seubseub** [comment]
@karimnaaji map, marker and polyline show well. sorry. but marker doesn't interactive.

**Comment by seubseub** [comment]
As I saw code, "pickMarkerAt" handler in tangram-es/core/src/tangram.cpp 401line. But, When I use TangramMap.framework, In TGMapViewController.h, Just 'pickFeatureAt' , 'pickLabelAt' Not 
'pickMarketAt'.

**Comment by seubseub** [comment]
I solved by adding "pickMarkerAt" method to ios/src/TGMapViewController.h. And 'make iOS'  to get new framework. Thank you for replying answer @karimnaaji

**Comment by karimnaaji** [comment]
Thanks @seubseub ! Your PR is now merged in, closing this.

**Comment by seubseub** [comment]
Great!
