### ISSUE TITLE
how to support geoserver？

### ISSUE THREAD

**Issue by yangzhedeID** [tangrams/tangram-es#1232]
like [http://gis.sicnu.edu.cn/data/1005/pc/{z}/{x}/{y}.jpg](http://gis.sicnu.edu.cn/data/1005/pc/1/1/1.jpg)

**Comment by matteblair** [comment]
Tangram-es supports rendering static "raster" tiles like this example through its scene file configuration. You can add a raster tile source to your scene file as described in the documentation here: https://mapzen.com/documentation/tangram/Raster-Overview/

**Comment by am2222** [comment]
@matteblair Hi,
Is it possible to feed source from a jeojson in runtime?As we can do in JS?sth like this
`	layer.scene.setDataSource('dynamic_data', { type: 'GeoJSON', data: json});`

**Comment by matteblair** [comment]
@am2222 Yes, you can add GeoJson data to the map at run-time. In the Android interface, you would create a `MapData` object with `MapController$addDataLayer(layerName)` and then add your GeoJson to that object with `MapData$addGeoJson(geoJsonString)`.

**Comment by matteblair** [comment]
Closing this issue since there don't seem to be further questions about the original topic.
