### ISSUE TITLE
TGMapViewDelegate causing crash #iOS

### ISSUE THREAD

**Issue by sajadkhan** [tangrams/tangram-es#1237]
In TGMapViewDelegate all the methods are 'optional' but the implementation to call the delegate method really make it 'mandatory' as it will crash if delegate doesn't implement these method. In TGMapViewController.mm the method ` - (void)pickFeatureAt:(CGPoint)screenPosition`  contains 
`if (!self.mapViewDelegate && ![self.mapViewDelegate respondsToSelector:@selector(mapView:didSelectFeature:atScreenPosition:)]) {
            return;
        }`
This will not execute if delegate is set but optional method `@selector(mapView:didSelectMarker:atScreenPosition:)` is not implemented and it makes the code below this point execute which includes `[self.mapViewDelegate mapView:self didSelectFeature:dictionary atScreenPosition:position];` and it will crash as this is not implemented in delegate. 
**-[ViewController mapView:didSelectLabel:atScreenPosition:]: unrecognized selector sent to instance 0x14a838a00**

**Comment by karimnaaji** [comment]
Hello @sajadkhan,
Thanks for the issue, those tests are missing something and should be
```
if (!self.mapViewDelegate || (self.mapViewDelegate && ![self.mapViewDelegate respondsToSelector:@selector(mapView:didSelectFeature:atScreenPosition:)])) { return; }
```
and they would work as you expect.
A fix will be in shortly!

**Comment by sajadkhan** [comment]
Thanks I had made those changes already and it works fine.
