### ISSUE TITLE
Proposal: styling flexibility for markers to use draw rules from layers defined in a scene file

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#1239]
In a discussion with @ecgreb and @msmollin, it would be better for a developer to reference draw /styling rules for a marker from a layer defined in the scene file:

Example: 
```
mz_route_line:
        data: { source: mz_route_line }
        draw:
            ux-route-line-overlay:
                color: '#06a6d4'
                order: 500
                width: [[0,3.5px],[5,5px],[9,7px],[10,6px],[11,6px],[13,8px],[14,9px],[15,10px],[16,11px],[17,12px],[18,10px]]
```

Referring `mz_route_line` for a marker should grab draw rules defined in the layer for drawing of this marker
```
map.markerSetStyling(markerID, "layer: mz-route-line");
```

In the above API, if a `layer` is defined, one can grab draw rules for that layer and use it to draw this marker. If no `layer` is defined and draw rules are defined explicitly, then these explicit draw rules are used to draw the marker.

One question I have with this "grabbing draw rules from a layer for a marker styling" is what happens when a layer being references is a sub-layer?
- should the syntax allow full layer name qualification, example: "uberLayerName:subLayerName"
  In this case merged set of draw rules will be applied to the marker.
- we can also not allow sub-layer assigned for markers!! Won't be good though :/

**Comment by matteblair** [comment]
I am concerned that this will end up being even more complicated and difficult to understand than our current approach to styling markers.

Associating dynamic map features with an existing data layer is the approach that we used for `MapData` in our first attempt at adding markers to the map. This was not without problems. First, it was very brittle to changes in the scene file; if a layer's name changed in the scene file then the related code in the application/sdk would stop working without being modified at all, and there would be no way to know until run-time. Second, keeping the styling information in a separate location from the rest of the code related to markers makes it inconvenient to check and edit the styling; the developer has to open a separate (very large) file to see what a marker is supposed to look like. Additionally, to apply this approach to individual features we would have to choose new logic for combining (or not combining) draw rules from nested layers, as Varun described above.

**Comment by tallytalwar** [comment]
I agree on all these points. We will have to weigh the use cases @ecgreb and @msmollin are thinking about for this proposal to be implemented. Balls in their court now :D.

**Comment by ecgreb** [comment]
One of the goals of the mobile SDKs is to provide an easy to use interface for a default set of commonly used markers (points, lines, polygons) styled to match each house style.

In the Android SDK this feature is currently implemented using client `MapData` and does not require any knowledge of the stylesheet by a developer using the SDK.

Using the new marker API a developer now has to open the stylesheet and copy/paste the draw rules from a default marker layer into code to take advantage of our default marker styles. This kind of defeats the purpose of having default marker styles in the stylesheet does it not? 

I agree applying a similar styling approach from `MapData` styles to the new marker API is not without potential pitfalls but let's consider the alternative.

> First, it was very brittle to changes in the scene file; if a layer's name changed in the scene file then the related code in the application/sdk would stop working without being modified at all, and there would be no way to know until run-time.

This is why we standardized the use of the `mz_*` named layers across all house styles for things like search pins and route lines.

With the new marker API we have introduced the opposite issue which is when the draw rules change for default markers in the house styles an app using that copied style will not be updated until it copies and pastes the new set of properties.

> Second, keeping the styling information in a separate location from the rest of the code related to markers makes it inconvenient to check and edit the styling; the developer has to open a separate (very large) file to see what a marker is supposed to look like.

This is not the case for developers who want to use the default markers. Currently using the default markers in the Android SDK requires no knowledge of the stylesheet. The new API does however require opening the stylesheet to copy/paste the draw rules into code.

Your point does ring true for developers using custom markers with the new API. In this case relying on the stylesheet does add another layer of abstraction and specifying the draw rules inline may be preferable.

Would it be possible to support both inline draw rules and referencing a layer in the stylesheet with the new marker API?

> Additionally, to apply this approach to individual features we would have to choose new logic for combining (or not combining) draw rules from nested layers, as Varun described above.

I don't know enough about how Tangram-es works with respect to nested layers to comment on this point specifically but I can see how it might get tricky. What are our options here?

**Comment by matteblair** [comment]
I think the challenge here is that we are trying to simultaneously satisfy groups with different needs:

 - Developers using Mapzen house styles and UI, who just want to use the things that are already in the scene files (applies to most of our internal work).
 - Developers making their own scenes or UI, who expect to control the appearance of map UI in code like every other piece of UI (applies to most external feedback we receive).

The in-line marker styling is certainly not perfect, but layer-name-based styling presents comparable problems for other use cases: If a developer wants to support several switchable scenes but keep marker appearance consistent, it is easier to style markers in code than to copy the same style into all of the scenes (this is, in fact, how we use markers in the tizen maps plugin).

To explain the issue with nested layers, consider this section of a scene file:
```yaml
layers:
  my-marker-layer:
    style: points
    order: 100
    color: blue
    my-marker-sublayer:
      color: red
```
If you created a marker and assigned its styling with the layer `my-marker-layer`, what color would you expect it to be? Using the normal scene file logic, any feature matched to the layer `my-marker-layer` would become *red* because the sublayer here matches all features and it's `color` rule would override the parent's. This is definitely a contrived example, but my point is that we're going to have to invent and explain rules for corner cases here and I'd rather just avoid that complication if at all possible.

**Comment by tallytalwar** [comment]
> One of the goals of the mobile SDKs is to provide an easy to use interface for a default set of commonly used markers (points, lines, polygons) styled to match each house style.

@ecgreb if this is the case, can we not hide styling of a marker in the android/ios sdk? Which can then be updated accordingly with the updates to style sheet?

**Comment by tallytalwar** [comment]
So if a developer using our SDK wants to add default SDK markers they can directly use an API call which bundles the apt styling with it. However if they want to style their marker explicitly they can still use the `markerSetStyling` interface.

**Comment by ecgreb** [comment]
@tallytalwar good point we could hide the inline styling in the SDK but given that we support 5 different bundled house styles with currently 14 `mz_*` marker styles each we would need to include (and update) inline styles for potentially 70 different draw rules when there are changes to the house styles?

**Comment by ecgreb** [comment]
@matteblair I agree we are trying to cover two separate use cases with one set of functionality.

Based on feedback we have received on the Android SDK there are also external developers who want to use the bundled styles and default markers so I think both use cases are valid.

Now I see the issue with nested styles but I don't think it applies to any of the `mz_*` layers so one option would be to document that the behavior is undefined for nested layers at this time and avoid using it ourselves?

**Comment by matteblair** [comment]
Allow me to rebut me from 15 minutes ago:

> If a developer wants to support several switchable scenes but keep marker appearance consistent, it is easier to style markers in code than to copy the same style into all of the scenes

For these cases the developer could just update the scene files after they are loaded to include the styling layer that they want. A little awkward, but manageable.

> This is definitely a contrived example, but my point is that we're going to have to invent and explain rules for corner cases here

As I just demonstrated, we already have rules for these cases and I just explained one in a sentence. Results may be unexpected for some scene files but it's nothing truly new.

Styling markers using layer names seems like it's worth trying as an experiment.

**Comment by ecgreb** [comment]
Lol cool I am down with an experiment its kind of what we do 🔬 ⌛️ 💉 💥 

Let me know if I can do anything to help

**Comment by tallytalwar** [comment]
On experiment, I already started something this morning, while we were discussing. So might have something to test by the end of this week.

**Comment by tallytalwar** [comment]
I am going to ignore any "sublayer" assignments for the first pass.
