### ISSUE TITLE
Reduce default log verbosity

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#1245]
The default "debug" logging behavior can be incredibly verbose, especially the logs from font loading and text styling. Detailed logs can be invaluable for debugging, but there are costs to excessive verbosity:
 - Verbose logs can drown the output from other libraries or applications.
 - Repetitive, uninformative logging produces a tendency for developers to ignore the logs entirely.
 - Excessive non-critical logging makes critical error messages less apparent.
 - Printing log messages has a small but non-negligible performance cost.

Specific log statements that are annoying:
 - `DEBUG textStyleBuilder.cpp:480: invalid params: '' 16.000000` no need to log this.
 - `DEBUG fontContext.cpp:132: Empty text line` no need to log this.
 - `DEBUG styleContext.cpp:462: duk evaluates JS method to null or undefined.` null is a valid, handled result from JS functions and should not be logged.
 - `NOTIFY textStyleBuilder.cpp:506: stroke_width too large: 12.000000 / 2.000000` this should be printed once at most; though its current frequency indicates an issue that we should address soon in the text pipeline.
- `platform_android.cpp:207: Creating font handle ...` this is normal behavior, no need to log.
- `DEBUG hardware.cpp:41: GL Extensions available: ...` the only extensions worth logging routinely are those we try to use.
- `Alfons: LOADED Font: ...` this is normal behavior, no need to log.

**Comment by karimnaaji** [comment]
Merged as part of https://github.com/tangrams/tangram-es/pull/1258
