### ISSUE TITLE
Cherry-pick library symbols export to control visibility

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#1246]
There are several advantages of not exposing all library symbols (loading time, memory usage, collisions...); by default we should set visibility to hidden for export of tangram library symbols (`-fvisibility=hidden`). We currently expose symbols for all of the external library we use:
```sh
> nm -g android/tangram/libs/armeabi-v7a/libtangram.so | wc -l
    6244
```
For this architecture this seems to be ~200kb and can be easily reduced to a few kb only.

We should conditionally set defines to surround the symbols we want to expose on the published library based on the compiler.

More reads on the subject and the advantages:
- https://gcc.gnu.org/wiki/Visibility
- http://www.ibm.com/developerworks/aix/library/au-aix-symbol-visibility/

**Comment by hjanetzek** [comment]
Using `-fvisibility=hidden` is a good idea. For Android it should be sufficient to just enable this option as JNIEXPORT is defined as `#define JNIEXPORT  __attribute__ ((visibility ("default")))`

**Comment by karimnaaji** [comment]
Yes, more generally we could have a separate `#define TANGRAM_EXPORT` to do so. 
On android, I assume that only the JNI part should be exposed, iOS would only need the `TGMapController` interface and for the C++ shared library whatever is needed from `tangram.h` (depends on https://github.com/tangrams/tangram-es/issues/1034).

**Comment by matteblair** [comment]
This was fixed as part of https://github.com/tangrams/tangram-es/pull/1947 🎉
