### ISSUE TITLE
iOS framework CI should deploy builds with debug symbols

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#1253]
We should produce 'snapshot' builds of the iOS framework that include debugging symbols so that we can attach a debugger and profiler when testing out new builds.

These builds should be hosted on S3, since hosting a large number of builds in the ios-framework repo will quickly balloon it's size.

**Comment by msmollin** [comment]
@matteblair now that we are deploying to S3 instead of github, is this still planned?

**Comment by matteblair** [comment]
I _think_ this is already happening in our snapshot deployments: https://github.com/tangrams/tangram-es/blob/master/circle.yml#L20-L33 so in theory we'll have debuggable snapshots for all master builds, but I haven't tested it yet.

**Comment by tallytalwar** [comment]
I think we should all have access to these s3 buckets to grab these pods explicitly if need be.

**Comment by matteblair** [comment]
Late follow-up: we now only publish our iOS framework snapshot builds as CI artifacts, but the snapshot frameworks _do_ have debug symbols now.
