### ISSUE TITLE
offset in yaml

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1254]
Doesn't work right

**Comment by tallytalwar** [comment]
Can you give more description on what are you trying to do here? Are you talking about the draw parameter [`offset`](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/draw.md#offset)?

Can you also include the scene file with some screen shots to give us some more context to the problem you are having?

Thanks

**Comment by tallytalwar** [comment]
I am going to close this, as `offset` works in all our examples. Please reopen with the details of what issues you are seeing with `offset`.
