### ISSUE TITLE
Demo app fails to load Refill style (Android)

### ISSUE THREAD

**Issue by ecgreb** [tangrams/tangram-es#1265]
Steps to reproduce:

1. Clone https://github.com/tangrams/refill-style-more-labels into `[PROJECT_ROOT]/scenes` folder.
2. Update `MainActivity.java` line 57 to load Refill style.

```java
view.getMapAsync(this, "refill-style-more-labels/refill-style-more-labels.yaml");
```

3. Launch demo app and notice no map is loaded (black screen). Setting other house styles in this fashion successfully loads a map (tested with Bubble Wrap and Cinnibar).

**Comment by matteblair** [comment]
Verified - this is not specific to Android, it's a bug in a core library dependency. The commit of yaml-cpp that we use currently has a bug that causes a byte-order mark in a YAML file to cause a parsing error. 

We've fixed this temporarily in tangram-es by just skipping a BOM before we pass the scene file to the parser.

**Comment by ecgreb** [comment]
👍
