### ISSUE TITLE
MapData.addGeoJson function bug with special characters

### ISSUE THREAD

**Issue by jingyibo123** [tangrams/tangram-es#1269]
Hello everyone,

I'm using the android framework, trying to overlay some vector data with the MapData.addGeoJson function. 
When the the geoJson data contains special characters such as "é", "à", "ç", etc , the app crashes and gives the following error message in Android Studio:

```
A/libc: /usr/local/google/buildbot/src/android/ndk-r13-release/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:74: void abort_message(const char *, ...): assertion "terminating with uncaught exception of type std::runtime_error: Invalid GeoJSON" failed
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 31527 (tangram.android)
```
I'm not sure if it's a bug with tangram or which external module?

**Comment by matteblair** [comment]
This appears to be originating from one of our dependencies, geojson-vt-cpp: https://github.com/tangrams/geojson-vt-cpp/blob/acf68233caf1f5f0324ef74f93ebf9678e8af252/src/geojsonvt.cpp#L30

Going further in, this seems to result from a parsing error in RapidJSON, which geojson-vt-cpp uses to parse JSON strings. RapidJSON seems to think the input string is not valid JSON, at least using the default parsing settings.

Do you have a sample of your GeoJSON that produces this error? If you could share a sample that would be a big help for us debugging this. :)

**Comment by matteblair** [comment]
Hmmm this might be related to Java's uhh, special, relationship to UTF-8: https://developer.android.com/training/articles/perf-jni.html#UTF_8_and_UTF_16_strings

**Comment by jingyibo123** [comment]
Hi matteblair thanks for the response. Here's an example file that caused the problem. The file is encoded in UTF-8 without BOM.

```
{
	"type": "FeatureCollection",
	"timestamp": "2017-01-31T09:41:03Z",
	"features": [{
		"type": "Feature",
		"id": "way/19793323",
		"properties": {
			"@id": "way/19793323",
			"cycleway": "lane",
			"highway": "residential",
			"lanes:bus:backward": "1",
			"lcn": "yes",
			"name": "Rue Georges Wodli",
			"name:de": "Kronenburger Straße",
			"oneway": "yes",
			"source": "observation",
			"@relations": [{
					"role": "",
					"rel": "6271726",
					"reltags": {
						"colour": "#00008b",
						"from": "Espace Européen de l'Entreprise",
						"name": "CTS G Espace Euroéen de l'Entreprise - Gare Centrale",
						"operator": "CTS",
						"ref": "G",
						"route": "bus",
						"to": "Gare Centrale",
						"type": "route"
					}
				}
			]
		},
		"geometry": {
			"type": "LineString",
			"coordinates": [[7.7386542, 48.5877634], [7.7385433, 48.5878123], [7.73802, 48.5880657], [7.7360483, 48.5855179], [7.7362284, 48.5856125]]
		}
	}]
}
```

**Comment by matteblair** [comment]
Thanks for the sample! I just tried this out and it seems to be loading without a crash for me. 

I copied and pasted your JSON into a file in my project at `src/main/res/raw/test.json`. Then I loaded the file with:
```
InputStream stream = getResources().openRawResource(R.raw.test);
Scanner scanner = new Scanner(stream, "UTF-8").useDelimiter("\\A");
String testGeoJson = scanner.next();
```
I was able to put this into a layer with `MapData.addGeoJson()` without any errors. 

Depending on how you are loading the JSON strings in your application, the text could be reformatted or missing quotes or something. tangram-es should be a little better about reporting error causes for things like this, but for now I would suggest printing out the strings before sending them to tangram to make sure that they look the way you expect.

**Comment by jingyibo123** [comment]
Thanks a lot for the response. I did tried multiple way to read the file including yours, always the same error. And I did check the file String value before calling MapData.addGeoJson(). Everything works fine. I suppose I should have some kind of configuration problem. Thanks a lot anyway!
