### ISSUE TITLE
code signing for demo ios app on simulator

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#1275]
In my fresh machine/xcode setup, I had to do following things different than what we have documented in the readme:

1. Change bundle identifier to something not `com.mapzen.tangram`
2. Click on `code sign on copy` for the TangramFramework under: `build phases -> copy phase -> framework`
  ![screen shot 2017-02-02 at 12 53 03 pm](https://cloud.githubusercontent.com/assets/360641/22561760/a1120556-e947-11e6-8c7d-dc5a12d21d67.png)

Someone should confirm these 2 points above and I will update the Readme aptly.

**Comment by matteblair** [comment]
Number 2 is already noted in the iOS build section of the README. I've never had an issue with the bundle identifier, as far as I know I've always used `com.mapzen.tangram`. Have you tried changing it back to that and seeing if it works?

**Comment by tallytalwar** [comment]
Number 2 is there only for when one is trying to deploy on a device, which is not the case for me when I tried to run it on a simulator.

Yes, I did try reverting it back, which results in failing of code signing.

**Comment by matteblair** [comment]
Ah you're right - the note about "Code Sign On Copy" should apply to running on the simulator as well, I just verified that on my machine.

I can't reproduce the issue with the bundle identifier though, the simulator is happy to run using `com.mapzen.tangram`. 

Maybe @ecgreb can try the same process on his machine, since he has a fresh environment too.

**Comment by tallytalwar** [comment]
Yup, he is on it. Will give it a try today.

**Comment by ecgreb** [comment]
I will give the instructions a try and report back here.

**Comment by ecgreb** [comment]
I also needed to check the code sign box but did not need to rename the bundle to run on the simulator.

Also it appears the following step is undocumented:

```
gem install xcpretty
```

Otherwise everything worked like a charm!

**Comment by tallytalwar** [comment]
Ahh I wonder why I have been having this bundle ID issue :|. 

Anyways will update the readme for `xcpretty` install and code signing on copy check box.

**Comment by tallytalwar** [comment]
With respect to renaming the bundle id, does it allow you (@ecgreb)  to run on a device if you have the bundle id as `com.mapzen.tangram`?

**Comment by karimnaaji** [comment]
By changing to a different apple id account I had similar issues to what @tallytalwar had.

![screen shot 2017-02-07 at 3 35 37 pm](https://cloud.githubusercontent.com/assets/7061573/22710389/198bdf00-ed4b-11e6-9af6-93934b0e8cba.png)

Using my original apple id account, I never had such issues.

**Comment by tallytalwar** [comment]
Addressed by #1297
