### ISSUE TITLE
Marker Visibility

### ISSUE THREAD

**Issue by sajadkhan** [tangrams/tangram-es#1276]
markerSetVisible is not working as expected. 
1. when visible is set to false it hides the marker but when tap on the area where marker was shown it throws the callback for marker selection.
2. when visible is set to false it hides the marker but on panning or pinching as the marker rebuilt itself it start showing.

**Comment by tallytalwar** [comment]
Thanks Sajad 

This sounds legit, will verify this and update and fix this issue.
