### ISSUE TITLE
Point marker size in meter

### ISSUE THREAD

**Issue by Guillaume227** [tangrams/tangram-es#1282]
I gather from the doc that the `size:` item that applies to `points` is interpreted as pixels units.
I would like to have a round marker that has a fixed sized with respect to the ground, no matter the zoom level.
Is there anyway to achieve that?

**Comment by matteblair** [comment]
You are correct, point features can only be sized in pixels. To create a feature that covers a fixed area on the ground, you may be better off creating a polygon feature with the dimensions you want. Would this work for your use case?

**Comment by karimnaaji** [comment]
Another feature request describing the same issue in https://github.com/tangrams/tangram-es/issues/1121.

**Comment by Guillaume227** [comment]
@karimnaaji Thanks, I did a quick check of open issues before but somehow missed that one. 
@matteblair I agree I could use a polygon as a workaround with enough vertices so it looks like a circle but that sounds rather contorted.

I am ok to close that thread then and follow up there.
