### ISSUE TITLE
LabelPickListener.onLabelPicked(...) returns int values as floating point string

### ISSUE THREAD

**Issue by ecgreb** [tangrams/tangram-es#1283]
Tile data includes `id` and `area` as JSON integer values however when the map of properties is returned by `LabelPickListener.onLabelPicked(...)` trailing zeros are added to both values resulting in `"377620411.000000"` and `"216.000000"` instead of `"377620411"` and `"216"`.

Would it be possible to return these values without adding a decimal point and trailing zeros?

```json
{
	type: "Point",
	properties: {
		kind: "restaurant",
		name: "Nat's Pizza",
		area: 216,
		source: "openstreetmap.org",
		min_zoom: 15.88,
		id: 377620411
	},
	coordinates: [
		1284,
		3530
	]
}
```

```
properties = {HashMap@5172}  size = 6
 0 = {HashMap$HashMapEntry@5180} "name" -> "Nat's Pizza"
 1 = {HashMap$HashMapEntry@5181} "kind" -> "restaurant"
 2 = {HashMap$HashMapEntry@5182} "source" -> "openstreetmap.org"
 3 = {HashMap$HashMapEntry@5183} "id" -> "377620411.000000"
 4 = {HashMap$HashMapEntry@5184} "area" -> "216.000000"
 5 = {HashMap$HashMapEntry@5185} "min_zoom" -> "15.880000"
```

**Comment by matteblair** [comment]
We can change how these number strings are formatted. What are you using it for exactly?

**Comment by ecgreb** [comment]
The `id` is used to construct a gid when making a request against the Pelias /place endpoint to fetch additional details about a POI that is displayed on the map.

Not a big deal but right now we have to split the string and remove the decimal plus trailing zeros before converting to an integer.

Currently we are only checking for the presence of the `area` key and not parsing the value.

https://github.com/mapzen/android/pull/302
