### ISSUE TITLE
Raspberry Pi 2 with fresh Jessie image unable to compile

### ISSUE THREAD

**Issue by ericjj123** [tangrams/tangram-es#1292]
I've tried with both a RPi 2 and RPi 3 with fresh Jessie Images.  Both give the same error.

pi@raspberrypi:~ $ uname -r
4.4.34-v7+

pi@raspberrypi:~/tangram-es $ sudo make rpi
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Platform chosen : RASPBERRYPI
-- Including raspberrypi dependent cmake file : /home/pi/tangram-es/toolchains/raspberrypi.cmake
-- Performing Test FLAG_WEXTRA
-- Performing Test FLAG_WEXTRA - Success
-- Creating directory /home/pi/tangram-es/build/rpi/external/harfbuzz-icu-freetype/freetype-2.6/include/freetype/config
-- Creating file /home/pi/tangram-es/build/rpi/external/harfbuzz-icu-freetype/freetype-2.6/include/freetype/config/ftconfig.h
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Creating file /home/pi/tangram-es/build/rpi/external/harfbuzz-icu-freetype/freetype-2.6/include/freetype/config/ftoption.h
-- harfbuzzfreetypeicucommon
-- Looking for GLM
-- GLM include /home/pi/tangram-es/external/../core/include/glm
-- CMAKE_CXX_COMPILER '/usr/bin/c++' 'GNU' '4.9.2'
-- CMAKE_CXX_FLAGS                ' -Wall -fpermissive -g -std=c++14'
-- CMAKE_CXX_FLAGS_RELEASE        '-O3 -DNDEBUG'
-- SQLITECPP_RUN_CPPLINT OFF
-- SQLITECPP_RUN_CPPCHECK OFF
-- SQLITECPP_RUN_DOXYGEN OFF
-- SQLITECPP_BUILD_EXAMPLES OFF
-- SQLITECPP_BUILD_TESTS OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/tangram-es/build/rpi
make[1]: Entering directory '/home/pi/tangram-es/build/rpi'
make[2]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
Scanning dependencies of target sdf_fs
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
[  1%] Generating ../../../core/include/shaders/sdf_fs.h
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[  1%] Built target sdf_fs
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
Scanning dependencies of target duktape
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
[  2%] Building C object external/CMakeFiles/duktape.dir/duktape/duktape.c.o
*
*
*
[ 99%] Building CXX object CMakeFiles/tangram.dir/rpi/src/context.cpp.o
/home/pi/tangram-es/rpi/src/context.cpp: In function ‘void initGL(int, char**)’:
/home/pi/tangram-es/rpi/src/context.cpp:244:13: warning: variable ‘success’ set but not used [-Wunused-but-set-variable]
     int32_t success = 0;
             ^
/home/pi/tangram-es/rpi/src/context.cpp:245:16: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
     EGLBoolean result;
                ^
/home/pi/tangram-es/rpi/src/context.cpp: In function ‘bool getRenderRequest()’:
/home/pi/tangram-es/rpi/src/context.cpp:471:45: error: ‘isContinuousRendering’ was not declared in this scope
     return bRender || isContinuousRendering();
                                             ^
/home/pi/tangram-es/rpi/src/context.cpp:472:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
In file included from /home/pi/tangram-es/rpi/src/context.h:3:0,
                 from /home/pi/tangram-es/rpi/src/context.cpp:1:
/home/pi/tangram-es/core/common/platform_gl.h: At global scope:
/home/pi/tangram-es/core/common/platform_gl.h:59:13: warning: ‘void glBindVertexArray(GLuint)’ defined but not used [-Wunused-function]
 static void glBindVertexArray(GLuint array) {}
             ^
/home/pi/tangram-es/core/common/platform_gl.h:60:13: warning: ‘void glDeleteVertexArrays(GLsizei, const GLuint*)’ defined but not used [-Wunused-function]
 static void glDeleteVertexArrays(GLsizei n, const GLuint *arrays) {}
             ^
/home/pi/tangram-es/core/common/platform_gl.h:61:13: warning: ‘void glGenVertexArrays(GLsizei, GLuint*)’ defined but not used [-Wunused-function]
 static void glGenVertexArrays(GLsizei n, GLuint *arrays) {}
             ^
CMakeFiles/tangram.dir/build.make:62: recipe for target 'CMakeFiles/tangram.dir/rpi/src/context.cpp.o' failed
make[3]: *** [CMakeFiles/tangram.dir/rpi/src/context.cpp.o] Error 1
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
CMakeFiles/Makefile2:78: recipe for target 'CMakeFiles/tangram.dir/all' failed
make[2]: *** [CMakeFiles/tangram.dir/all] Error 2
make[2]: Leaving directory '/home/pi/tangram-es/build/rpi'
Makefile:149: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/tangram-es/build/rpi'
Makefile:277: recipe for target 'rpi' failed
make: *** [rpi] Error 2

**Comment by tallytalwar** [comment]
@patriciogonzalezvivo can you give this a look please?

Thanks

**Comment by patriciogonzalezvivo** [comment]
I will

**Comment by patriciogonzalezvivo** [comment]
Yes... seams some of the cmake rules for raspberrry Pi have change in the last week... https://github.com/tangrams/tangram-es/commit/dbd321560a227dd62e34f11cf4aaf508363912af#diff-f7807da3f36f54f6d7d1e79b15025294 I'll work on it an push PR when I get it running again

**Comment by ericjj123** [comment]
I appreciate the quick response.  Thanks guys.

**Comment by patriciogonzalezvivo** [comment]
Sure! Our pleasure! I'm working on a PR right now... hopefully this will be solve soon : )

**Comment by patriciogonzalezvivo** [comment]
@ericjj123 this is compiling on my end https://github.com/tangrams/tangram-es/pull/1296 You can give it a try from the PR. Or wait until the rest of the folks review and merge this in.

**Comment by karimnaaji** [comment]
@ericjj123 should be fixed by https://github.com/tangrams/tangram-es/pull/1296.
