### ISSUE TITLE
Incorrect shaped text

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#1293]
While looking at curved text PR, I noticed some of hindi text are incorrectly shaped and specifically missing last glyph (shaped).

Example: 
- Delhi (दिल्ली) is rendered as: दिल्ल
- Kolkata (कोलकाता) is rendered as: कोलकात
- Noida (नोएडा) is rendered as: नोएड
- Mussoorie (मसूरी) is rendered as: मसूर
- Ambala (अम्बाला) is rendered as: अम्बाल

The common error in the above example is that these are missing last (shaped) glyph. I have not found this last shaped glyph missing in other labels, example in the case of river Yamuna, it correctly renders it as यमुना. But thats the only correct one I am seeing so far.

Investigating this a bit more to see where in the code it messes up rendering the last shaped glyph. Will update more here.

cc. @hjanetzek

**Comment by hjanetzek** [comment]
Looking into it - seems to be the TextBatch draw logic for glyph clusters. Fortunately not TextShaper :)

**Comment by tallytalwar** [comment]
Ahh I am looking at the shaper code,  which seems to be doing the correct
thing with delhi example. But I got familiar with this code a bit :).

**Comment by tallytalwar** [comment]
No doubt I am seeing it only for the place labels and not for anything else like all the river labels are good.

**Comment by tallytalwar** [comment]
Looks like this piece of code: https://github.com/tangrams/tangram-es/blob/master/core/src/text/textUtil.cpp#L37-L55 is incorrectly breaking on `ल` for `दिल्ली`.

**Comment by tallytalwar** [comment]
Resolved by #1294
