### ISSUE TITLE
Map styles library created by other developers

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#1316]
I just wanted to ask whether there is some library of user's created map styles or if you are planning such library in order for developers to share their map styles.

**Comment by nvkelso** [comment]
@rwrx neat idea! do you have any styles to share &/or highlight in such a library?

We've created a few basemap styles at Mapzen, you have preview them here:

- https://mapzen.com/products/maps/

**Comment by rwrx** [comment]
Yes, I did know about Mapzen basemap styles. I was just wondering if there is some library with user created styles. Unfortunately I don't have any styles, but in a short time I want to create some simple styles.

**Comment by matteblair** [comment]
Not a bug or feature for the Tangram ES engine. Closing!
