### ISSUE TITLE
got a SIGSEGV signal

### ISSUE THREAD

**Issue by 91yuan** [tangrams/tangram-es#1319]
Hello，i had build and run tangram-es with qtCreator 3.5.1 Based on Qt 5.5.1(GCC 4.9.1 20140922) in Ubuntu  Kylin 14.04 32bits, and got a segmentation fault.
the error code  is at "labelCollider.cpp":155;
this is the crash stack!
0	Tangram::LabelCollider::<lambda(auto:13&, auto:14&)>::operator()<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair, isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair>(isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair &, isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair &) const	labelCollider.cpp	155	0x866b88c	
1	__gnu_cxx::__ops::_Iter_comp_iter<Tangram::LabelCollider::process(Tangram::TileID, float, float)::<lambda(auto:13&, auto:14&)>>::operator()<__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair>>, __gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair>>>(__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, __gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>)	predefined_ops.h	123	0x866b9c5	
2	std::__unguarded_partition<__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair>>, __gnu_cxx::__ops::_Iter_comp_iter<Tangram::LabelCollider::process(Tangram::TileID, float, float)::<lambda(auto:13&, auto:14&)>>>(__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, __gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, __gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, __gnu_cxx::__ops::_Iter_comp_iter<Tangram::LabelCollider::process(Tangram::TileID, float, float)::<lambda(auto:13&, auto:14&)>>)	stl_algo.h	1900	0x866c120	
3	std::__unguarded_partition_pivot<__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair>>, __gnu_cxx::__ops::_Iter_comp_iter<Tangram::LabelCollider::process(Tangram::TileID, float, float)::<lambda(auto:13&, auto:14&)>>>(__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, __gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, __gnu_cxx::__ops::_Iter_comp_iter<Tangram::LabelCollider::process(Tangram::TileID, float, float)::<lambda(auto:13&, auto:14&)>>)	stl_algo.h	1918	0x866b844	
4	std::__introsort_loop<__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair>>, int, __gnu_cxx::__ops::_Iter_comp_iter<Tangram::LabelCollider::process(Tangram::TileID, float, float)::<lambda(auto:13&, auto:14&)>>>(__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, __gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, int, __gnu_cxx::__ops::_Iter_comp_iter<Tangram::LabelCollider::process(Tangram::TileID, float, float)::<lambda(auto:13&, auto:14&)>>)	stl_algo.h	1948	0x866b1ad	
5	std::__sort<__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair>>, __gnu_cxx::__ops::_Iter_comp_iter<Tangram::LabelCollider::process(Tangram::TileID, float, float)::<lambda(auto:13&, auto:14&)>>>(__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, __gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, __gnu_cxx::__ops::_Iter_comp_iter<Tangram::LabelCollider::process(Tangram::TileID, float, float)::<lambda(auto:13&, auto:14&)>>)	stl_algo.h	1963	0x866af31	
6	std::sort<__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0u>>::Pair>>, Tangram::LabelCollider::process(Tangram::TileID, float, float)::<lambda(auto:13&, auto:14&)>>(__gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, __gnu_cxx::__normal_iterator<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair *, std::vector<isect2d::ISect2D<glm::tvec2<float, (glm::precision)0>>::Pair>>, Tangram::LabelCollider::<lambda(auto:13&, auto:14&)>)	stl_algo.h	4729	0x866ae0a	
7	Tangram::LabelCollider::process	labelCollider.cpp	167	0x866a54e	
8	Tangram::TileBuilder::build	tileBuilder.cpp	137	0x863bfb3	
9	Tangram::TileTask::process	tileTask.cpp	23	0x85776b2	
10	Tangram::TileWorker::run	tileWorker.cpp	94	0x8578314	
11	std::_Mem_fn_base<void (Tangram::TileWorker:: *)(Tangram::TileWorker::Worker *), true>::operator()<Tangram::TileWorker::Worker *, void>(Tangram::TileWorker *, Tangram::TileWorker::Worker *&&) const	functional	600	0x857b433	
12	std::_Bind_simple<std::_Mem_fn<void (Tangram::TileWorker:: *)(Tangram::TileWorker::Worker *)> (Tangram::TileWorker *, Tangram::TileWorker::Worker *)>::_M_invoke<0u, 1u>(std::_Index_tuple<0u, 1u>)	functional	1531	0x857b3cf	
13	std::_Bind_simple<std::_Mem_fn<void (Tangram::TileWorker:: *)(Tangram::TileWorker::Worker *)> (Tangram::TileWorker *, Tangram::TileWorker::Worker *)>::operator()()	functional	1520	0x857b2ba	
14	std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (Tangram::TileWorker:: *)(Tangram::TileWorker::Worker *)> (Tangram::TileWorker *, Tangram::TileWorker::Worker *)>>::_M_run()	thread	115	0x857b271	
15	??			0xb7cb37be	
16	start_thread	/usr/lib/debug/lib/i386-linux-gnu/libpthread-2.19.so	312	0xb7df2f72	
17	clone	/usr/lib/debug/lib/i386-linux-gnu/libc-2.19.so	129	0xb7b10f8e

**Comment by karimnaaji** [comment]
Hi,

We don't support Qt as a platform yet, have you been able to reproduce this issue in the platforms we currently support (iOS, Android, Ubuntu Linux, OS X)? If so, that would make things much easier for us to debug and track this issue.

I will close for the time being, but feel free to reopen if you manage to reproduce on those platforms.
