### ISSUE TITLE
Polygon marker opacity

### ISSUE THREAD

**Issue by horvayev** [tangrams/tangram-es#1320]
Hello, I'm trying to display polygon marker with opacity but it doesn't work. Style I use:
```js
{ style: 'polygons', color: [1.0, 1.0, 1.0, 0.5], order: 2000, collide: false, blend: overlay }
```
I noticed it works for point markers and polygons within datalayers.

**Comment by karimnaaji** [comment]
Hi @horvayev ,

The blending mode is a parameter of the style, when setting a marker you set the strings that corresponds to a [draw rule](https://github.com/tangrams/tangram-es/blob/master/core/include/tangram/tangram.h#L211_L213). I would refer the documentation on how to setup a style for a specific blending mode [here](https://mapzen.com/documentation/tangram/styles/#blend).

Also, I notice that `collide` is being used here for a polygon, this parameter only affects `points` and `text` styles.

Something that would work for you, add a style with this blend mode in the stylesheet, that inherits from the base style `polygons`:

```yaml
styles:
    overlay_polygons:
        base: polygons
        blend: overlay
```

In you codebase when setting a marker styling:

```c++
map->markerSetStyling(polygonMarker, "{ style: 'overlay_polygons', color: [1.0, 1.0, 1.0, 0.5], order: 500 }");
```

Let us know how that goes!

**Comment by horvayev** [comment]
It was it. Thank you @karimnaaji .
