### ISSUE TITLE
`Tangram::update()` returns `true` before the scene finish loading

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-es#1324]
I'm using last version of Tangram-Es Map at paparazzi, here https://github.com/tangrams/paparazzi/blob/rearch/worker/src/paparazzi.cpp#L152 and returns true way before finishing... producing incomplete scenes screenshots : /

**Comment by tallytalwar** [comment]
Gave this a shot today. Can not repro this explicitly on tangram-es demo app. But its reproducible in paparazzi from my machine. Still debugging (post S3 fire).
