### ISSUE TITLE
Cannot run Android demo app under Windows

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#1334]
When I try to run Android demo app under Windows 7 with Android Studio 2.2.3, I get these errors:

`core/src/gl/renderState.cpp - fatal error: 'defaultPointTextureData.h' file not found`
`core/src/gl/primitives.cpp - fatal error: 'debugPrimitive_vs.h' file not found`
`core/src/gl/shaderSource.cpp - fatal error: 'selection_fs.h' file not found`

I have done new `git clone` command and `git submodule update --init --recursive`. Also I have latest Clang installed as well as latest Android NDK. I have checked if that files are missing in cloned repository, but they was present there. Maybe there are some errors in include paths in the project.

**Comment by karimnaaji** [comment]
Hey @rwrx ,

I think to fully support Android Studio on Windows we would need to update a little bit our build system that generates the shaders' headers. We use that script to simplify distribution of the library, so we don't have any dependent resources along with the binary.

Would you mind giving a try at this branch https://github.com/tangrams/tangram-es/tree/patch-android-studio-windows and see if that fixes your issue?

Thanks!

**Comment by rwrx** [comment]
Hello, thank you for rapid response! I tried to run it on that branch. Now I get only one error, but it is rather long, so I added it to this file: [error.txt](https://github.com/tangrams/tangram-es/files/812382/error.txt).

**Comment by karimnaaji** [comment]
The actual error seems to be at the very end:

```
FAILED: cmd.exe /C "cd /D D:\Tomas\Programovanie\Git\tangram-es && bash D:/Tomas/Programovanie/Git/tangram-es/core/../scripts/incbin.bat D:/Tomas/Programovanie/Git/tangram-es/core/shaders/rasters.glsl core/generated/rasters_glsl.h rasters_glsl"
'bash' is not recognized as an internal or external command,
  operable program or batch file.
  FAILED: cmd.exe /C "cd /D D:\Tomas\Programovanie\Git\tangram-es && bash D:/Tomas/Programovanie/Git/tangram-es/core/../scripts/incbin.bat D:/Tomas/Programovanie/Git/tangram-es/core/shaders/debug.fs core/generated/debug_fs.h debug_fs"
'bash' is not recognized as an internal or external command,
  operable program or batch file.
  FAILED: cmd.exe /C "cd /D D:\Tomas\Programovanie\Git\tangram-es && bash D:/Tomas/Programovanie/Git/tangram-es/core/../scripts/incbin.bat D:/Tomas/Programovanie/Git/tangram-es/core/shaders/directionalLight.glsl core/generated/directionalLight_glsl.h directionalLight_glsl"
'bash' is not recognized as an internal or external command,
  operable program or batch file.
  ninja: build stopped: subcommand failed.
```

Looking more!

**Comment by karimnaaji** [comment]
Can you give it another try with https://github.com/tangrams/tangram-es/commit/82ea86e0858f4fc6574ba869a154395cfb6fae93?

**Comment by rwrx** [comment]
Thank you. Something has changed a little bit but basically the same error: [error.txt](https://github.com/tangrams/tangram-es/files/813153/error.txt).

**Comment by karimnaaji** [comment]
I suspect that the CMake variable `CMAKE_SYSTEM_NAME` is not equal to `Windows` when building from Android Studio. 

I commented the lines in question in commit https://github.com/tangrams/tangram-es/commit/f90f324d1183e03f2476fbab0468083117a9c0a8, if you checkout the branch again that might fix your issue. If it still doesn't work you could add:
```CMake
message(STATUS "System name " ${CMAKE_SYSTEM_NAME})
```
Around the same lines to see what this variable actually is when using Android Studio with CMake.

**Comment by rwrx** [comment]
Thank you, but still without no luck. I fetched your new commit and issue is back as was in first message in this issue thread - all three files not found. I've also added that line but I don't know where I could see that message printed.

**Comment by rwrx** [comment]
I was able to get it working using [this](https://github.com/rmitton/incbin/blob/master/incbin.bat) incbin.bat file instead of one which is in scripts folder. Also I kept commented these lines:

```
#if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
   set(INCBIN_SCRIPT ${PROJECT_SOURCE_DIR}/../scripts/incbin.bat)
#else()
#   set(INCBIN_SCRIPT "bash" ${PROJECT_SOURCE_DIR}/../scripts/incbin.sh)
#endif()
```

When I remove uncomment these lines it won't work again.

**Comment by matteblair** [comment]
I believe this is fixed now - our shader source script is no longer a shell script. If not then please re-open!
