### ISSUE TITLE
Tangram::udpate() returns true prematurely only the first time

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-es#1345]
So... now... is returning true when ALL tiles finish composing the geometry of what seams to be landuse (that in the case of tron use elevation raster tiles)

![screen shot 2017-03-07 at 11 50 03 am](https://cloud.githubusercontent.com/assets/346914/23667956/883ec17c-032d-11e7-898a-6e1e5de992d5.png)

That's how it looks... the rest of the calls are 100% fine... is just that first one time

**Comment by bcamper** [comment]
Boring map

**Comment by matteblair** [comment]
We've made a number of updates to this logic since this issue was opened and I believe it's been resolved now - if not please re-open!
