### ISSUE TITLE
Allow loading scene file from custom NSBundle

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#1346]
Currently all scene files are loaded from the main bundle:
https://github.com/tangrams/tangram-es/blob/master/platforms/ios/src/TangramMap/platform_ios.mm#L35

But, in the sdk, as we move from using submodules to pods for the dependent stylesheets we will want to pass in custom bundles to load the scenes from. Could we provide a version of `resolvePath` which takes a bundle parameter?
```
NSString* resolvePath(const char* _path, NSBundle bundle)
```
https://developer.apple.com/reference/foundation/bundle
https://guides.cocoapods.org/syntax/podspec.html#resource_bundles
https://www.cocoanetics.com/2012/05/resource-bundles/

**Comment by karimnaaji** [comment]
Yep it is be possible to add fallback resolution that would target the iOS SDK bundle. We had a similar way to handle framework resources for fonts that were bundled into the Tangram framework, until we added platform system fonts where we moved away from it.

What we would need is an optional setter on `TGMapViewController` to add a bundle fallback, if the resource hasn't been found from the main bundle, then we would try url resolution from this fallback bundle.

**Comment by karimnaaji** [comment]
For this we might provide an option to set the root to which resources should be resolved against. If empty we would fallback to the main bundle (which would be the `mainBundle` we already use), otherwise it would use it as the root. @sarahlensing how do you feel about this?

From the iOS SDK that would look like that:
```objc
// com.mapzen.iosSDK is the name ios SDK framework
NSBundle* sdkFramework = [NSBundle bundleWithIdentifier:@"com.mapzen.iosSDK"]; 
[tangramViewController setResourceRoot:[sdkFramework resourceURL]];
```

**Comment by matteblair** [comment]
Bundles can be treated as file paths right? Would this issue be solved by using the absolute file path of a resource in a bundle? Resources that specified in the scene with relative paths will be correctly resolved against the scene's absolute path.

**Comment by karimnaaji** [comment]
>Would this issue be solved by using the absolute file path of a resource in a bundle? 

Yes, in the proposed example `setResourceRoot` would be setting an absolute path to the resource in the bundle to use.

**Comment by sarahlensing** [comment]
@karimnaaji I think that will work well. One thing we might want to consider is coupling its exposure with loading a scene file since the only time we care about resource bundles is when we are loading scene files.

So something like:
```objc
NSBundle* sdkFramework = [NSBundle bundleWithIdentifier:@"com.mapzen.iosSDK"]; 
[tangramViewController loadSceneFile:sceneFile resourceUrl:resourceUrl]
```
