### ISSUE TITLE
Make error: does not contain a CMakeLists.txt file

### ISSUE THREAD

**Issue by todrobbins** [tangrams/tangram-es#135]
When I `make osx`, I get the following error:

```
You have called ADD_LIBRARY for library libtess2 without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at core/CMakeLists.txt:15 (add_subdirectory):
  The source directory

    ~/tangram-es/core/dependencies/yaml-cpp

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

Am I missing something from the install? Cheers!

**Comment by tallytalwar** [comment]
Ohh, I guess you forgot to do a "git submodule init" and "git submodule update".

Can you try that and see if it fixes this?

Thanks for trying tangram-es :D.

**Comment by todrobbins** [comment]
That was it. I missed that step in my excitement. :laughing: Thanks!
