### ISSUE TITLE
Android demo app should allow easily loading custom scenes from GUI

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#1362]
This could be as simple as a text field to enter a url for an arbitrary scene file. A person with an Android phone should be able to download this demo from android.mapzen.com and put in their own scene file to quickly evaluate it.

@nvkelso @sensescape The goal of this is to make it easier for you to test scene files with tangram-es. Do you have other ideas of how we could facilitate this? We could probably do something similar with iOS, or distribute an OS X tangram.app that you could just drag-and-drop scene files onto.

**Comment by nvkelso** [comment]
I like both options (text field and on OS X drag-and-drop in addition to
text field).
