### ISSUE TITLE
Android: Support VectorDrawables for markers

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1364]
Currently, a Marker seems to accept any Drawable as its picture on the interface, but in reality, it always assumes this drawable to be a BitmapDrawable:
```
    public boolean setDrawable(Drawable drawable) {
        int density = context.getResources().getDisplayMetrics().densityDpi;
        BitmapDrawable bitmapDrawable = (BitmapDrawable) drawable;
        ...
```

It would be nice if Tangram-ES for Android would support vector drawables for markers out of the box for Api 21+.
For Apis below 21, Android Studio creates bitmap icons for the different dimensions by default during the build process, so there is no necessity to use a compatibility library. Users who use the compatibility library instead of the automatic bitmap drawable creation during the build process, can wrap their VectorDrawableCompat like this `(DrawableCompat.wrap(drawable)).mutate();`.

[Here is a stackoverflow question](http://stackoverflow.com/questions/33696488/getting-bitmap-from-vector-drawable) on how to draw any drawable into a Bitmap. It's pretty straightforward.

**Comment by westnordost** [comment]
To use vector drawables anyway, I use this function now:

```
	private BitmapDrawable createBitmapDrawableFrom(int resId)
	{
		Drawable drawable = getResources().getDrawable(resId);
		if(drawable instanceof BitmapDrawable) return (BitmapDrawable) drawable;

		Bitmap bitmap = Bitmap.createBitmap(drawable.getIntrinsicWidth(),
				drawable.getIntrinsicHeight(), Bitmap.Config.ARGB_8888);
		Canvas canvas = new Canvas(bitmap);
		drawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
		drawable.draw(canvas);
		return new BitmapDrawable(getResources(), bitmap);
	}
```

**Comment by westnordost** [comment]
Hmm, actually, nevermind. I reckon that Tangram-ES always needs a Bitmap(Drawable)  to copy over to the native part, so supporting Vector- and other Drawables should perhaps be up to the user instead of creating another layer of indirection. 

It is a bit like

```
void applyData(Collection c) {
  if(!(c instanceof Set)) c = new HashSet(c);
  // .... do things
}
```
If Tangram-ES needs a Bitmap(Drawable), it should be simply be clear about it and that's it, in my opinion.

**Comment by matteblair** [comment]
Yep, you got it. We don't have an SVG renderer in the native library, so the only way to render an SVG in a Marker would be to rasterize it to a bitmap like in your example. 

As you said though, we should be clear about the precise kind of Drawable we expect in our API!
