### ISSUE TITLE
TGMarker error handling

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#1370]
We will need a way to handle errors when adding markers to the map. Maybe tangram can throw an exception when `TGMarker#map` is set for an invalid marker?

cc/ @karimnaaji @msmollin

**Comment by msmollin** [comment]
Throwing exceptions is deprecated in objective-c for a few years now. The generally accepted / recommended approach is passing in a `nil` reference to a NSError, and then checking to see afterwards if it's still `nil` or not. Swift 3 will correctly handle this and convert it into a `throws` function then. See references here:
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/AdoptingCocoaDesignPatterns.html#//apple_ref/doc/uid/TP40014216-CH7-ID10

As for how to construct the NSError, typical there's an enum built for the different error types and a constant for the error domain. There's a basic example of that in `OnTheRoad` here: https://github.com/mapzen/on-the-road_ios/blob/master/OTRRouting/OTRRoutingController.m#L41
