### ISSUE TITLE
Feature request: Callback for when the map view changes

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1371]
A callback for when the area that is displayed on the map changes would be very nice, so when the map is tilted, rotated, zoomed or another position is set.

**Possible use cases:**

- updating the size of certain markers (to reflect a value in on-ground meters). The use case might not make sense anymore if #1121 is implemented 
- putting new data from a custom data source for a new area that comes into view. This use case might not be so relevant anymore if tangram would manage pulling data form a custom data source (see #1135)
- displaying an arrow at the border of the screen that points to a certain point that is currently off screen while it is off screen, i.e. a "goal"/next WP marker. Also done in "Civilization 4: Colonization", at least
<img src=https://static.muve.pl/uploads/product-gallery/0000/0512/civilization-4-colonization-pc-pl-3.jpg>(lower right corner).
- maintaining arbitrary views that "stick" to the map just like markers, only more flexible. For example, to animate objects flying to/from a certain point on the map into the menu. Or, to have an animated location dot.

Currently, for my use case of displaying an accuracy circle around the user's current position, I had to register all the touch input listeners and everywhere where I set the zoom and position programmatically call a `viewUpdated ` manually. But this does not cover everything I would need to cover, I don't get updates for during flinging of the view (zoom or move) and on ZoomEased.

**Comment by nvkelso** [comment]
Nice example!

**Comment by westnordost** [comment]
So, this seems to have been implemented in 0.10
