### ISSUE TITLE
Reverse the buliding procedure, circleci building linux, travis building osx

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#1374]

**Comment by matteblair** [comment]
Is there a reason you think the CI build targets should change? We found that running OS X builds on Travis led to unacceptable delays waiting for available machines.

**Comment by lygstate** [comment]
When I creating a pull request, and I have a circleci account, it's request me pay for the OsX instance.

**Comment by matteblair** [comment]
I just enabled our Circle CI project to build forked pull requests, so your should be working now. Thanks for the heads up!
