### ISSUE TITLE
Improve Marker Selection

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#1377]
It is currently very hard to select markers. Pressing on top of them is not triggering the selection delegate to be called with a `TGMarkerPickResult`. Increasing the pick radius does not seem to improve marker selection when tapping directing on the marker (it does increase the area around the marker that is selectable though).

To reproduce:
1. Clone the iOS demo app repo:
```
git clone git@github.com:mapzen/ios.git
```
2. Install app to phone
3. Press "Toggle Marker" button to make sample marker visible
4. Press on marker
5. Observe that alert is not shown to indicate selection

Here is a video showing what happens when the pick radius is set to 2:
https://www.dropbox.com/s/21auvjk3c51zh5z/20170309_161650.mp4?dl=0

cc/ @karimnaaji @matteblair

**Comment by matteblair** [comment]
We should check whether the size and position of the tangram framebuffer and the input event coordinates are all in the ranges we would expect. 

This issue doesn't manifest in the Android or desktop demos, so I'm trying to think about this in terms of things that are different in the iOS SDK demo.

**Comment by msmollin** [comment]
Here's where we're doing the manipulation of the TGMapViewController for parent/child. You can also see how we're sizing the view with constraints - https://github.com/mapzen/ios/commit/e0cee3e75a2b9c7e66bcfa70413869c5a7b02a52

**Comment by sarahlensing** [comment]
It looks like the location we receive in `TGRecognizerDelegate` is not based on an upper left origin. When I remove the sample app's tab bar translucency making the `TGMapViewController` view extend to the bottom of the screen, and I tap in roughly the same location on the screen I get y-values which vary by about the height of the tab bar. Are the positions we receive in `TGRecognizerDelegate` expected to be based on an upper-left-origin of the screen? `pickMarker` seems to expect a location based on lower left origin. If this is the intended behavior we can do the transformation in the sdk, otherwise we should update them to be consistent and update the documentation.

**Comment by karimnaaji** [comment]
The positions are expected to be whatever is the UIKit standard, but that's confirming my first thought of the UI interfering with the position given by the view. 

Does removing parenting affects this behavior? I'm thinking particularly of `translatesAutoResizingMaskIntoConstraints`, what is the meaning of this boolean?

**Comment by sarahlensing** [comment]
Removing parenting doesnt affect the behavior. `translatesAutoResizingMaskIntoConstraints` when true automatically translates the view's mask values into constraints. To set custom constraints on the view, this has to be false.
