### ISSUE TITLE
Dynamic polyline marker ?

### ISSUE THREAD

**Issue by fokin33** [tangrams/tangram-es#1395]
Hello!
How can I draw a dynamically changing line - for example, the path passed by the object (add points to the line with OnLocationChanged)? Or until there is no such possibility? Thank you!

**Comment by matteblair** [comment]
Hello @fokin33!

A polyline marker can be created and updated with `Map::markerSetPolyline` in the C++ interface or `Marker$setPolyline` in the Android interface. To draw an updating polyline, you would want to keep your own list of points, then each time you get a new point, add it to the list and set the Marker's polyline to the updated list.

Hope that helps!

**Comment by tallytalwar** [comment]
Hey @fokin33, hope the above description helped you. I am closing this issue, feel free to reopen if you still have questions for the same.

Thanks

**Comment by fokin33** [comment]
I try to place simple line for test, but it is not visible on map.
            ArrayList<LngLat> lngLats = new ArrayList<>();
            lngLats.add(new LngLat(37.0,55.0));
            lngLats.add(new LngLat(35.0,58.0));    
            Marker m = mapController.addMarker();
            Map<String, String> props = new HashMap<>();
            props.put("type", "line");
            props.put("color", "black");
            m.setPolyline(new Polyline(lngLats,props));
            m.setDrawOrder(20000);
What is wrong in this code ? 
Thanks!
