### ISSUE TITLE
iOS - removeMarker at tangram-es 0.5.1 version

### ISSUE THREAD

**Issue by seubseub** [tangrams/tangram-es#1398]
Hi I'm using tangram and this is awesome.

but one problem is happened.

I used tangram-es 0.5.0 version before. but when I update tangram-es 0.5.1 by cocoa pods,

I cannot find removemarker method. 

in 0.5.0 version, there were 'markerremove(TGMapMarkerId)'

and This Version, Android have 'markerremove(Marker)'.

I want to know about this 'marker remove' method in 0.5.1 version in iOS

Thank you for reading my issue :)

**Comment by karimnaaji** [comment]
Hi @seubseub thanks for the nice words! You can remove a marker from the map by simply settings its map to `nil`:

```objc
marker.map = nil;
```

**Comment by seubseub** [comment]
@karimnaaji  Thank you for replying! I'll try it :)

Thank you!
