### ISSUE TITLE
Polish names are broken on lower zooms

### ISSUE THREAD

**Issue by kdebowski** [tangrams/tangram-es#1413]
When on lower zooms (like from 1 to 6) polish city names (and I suppose not only polish) are broken. There are no diacritic characters . I've uploaded example screenshot, when there is Kraknw instead of Kraków, Lddz instead of Łódź. Even Ukraininan names like Kiev are written in ukraininan only on higher zoomes (like from 6 to upper ones).

![screenshot from 2017-03-30 15-00-34](https://cloud.githubusercontent.com/assets/2165223/24505572/a0e77c16-155a-11e7-9183-03927d102c65.png)

We are using tangram-es library, with Montserrat font loaded directly from local directory. When we are zooming in, diacritic characters suddenly become visible - so I think it's not case connected with bad font. 

UPDATE 1:
In file describing part of Poland we can see those wrong city names: 
[https://tile.mapzen.com/mapzen/vector/v1/all/6/35/21.topojson?api_key=mapzen-ACmL23W&](https://tile.mapzen.com/mapzen/vector/v1/all/6/35/21.topojson?api_key=mapzen-ACmL23W&)

The part of this file looks like:
`{"source":"naturalearthdata.com","kind":"locality","name":"Kraknw"`
which is obviously wrong. It could be named Krakow with 'o' instead of 'ó', but not Kraknw.

**Comment by hjanetzek** [comment]
Thanks for the report! This is an issue with the tile data, you can track it here https://github.com/tilezen/vector-datasource/issues/1140
