### ISSUE TITLE
Markers: setStylingFromString overrides setVisible(false)

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1423]
For the following code, the locationMarker will be visible, even though I explicitly set it to false. I'd expect that setStylingFromString does not override the setting I did with setVisible.

```
locationMarker.setVisible(false);
locationMarker.setStylingFromString("{ style: 'points', color: 'white', size: 30px, order: 2000, flat: true, collide: false }");
```

As usual, if you think this is intended behavior, a documentation update would be nice.

**Comment by matteblair** [comment]
Good find - that is not the intended behavior! We'll look into fixing that and post updates here.

**Comment by tallytalwar** [comment]
https://github.com/tangrams/tangram-es/pull/1416 might have addressed this issue also.
