### ISSUE TITLE
In Android, How to block longitude range?

### ISSUE THREAD

**Issue by JunsuLime** [tangrams/tangram-es#1431]
I want to block longitude range by force. But I don't know how to do that.

Is there any method check where i am callback, when map is moved? OR any method block longitude range.

always thank you for your help and kindness

**Comment by sheikh-iffi** [comment]
Hi @JunsuLime 

I think you can restrict lat long ranges by using **setLimitsY**  & **setLimitsX** methods given in [viewConstraint.cpp](https://github.com/tangrams/tangram-es/blob/master/core/src/view/viewConstraint.cpp)

Note: I think they take values in meters.

**Comment by JunsuLime** [comment]
How can I use that method *setLimitsY* & *setLimitsX* in android??

I tried to find it. But cannot do that T_T

**Comment by sheikh-iffi** [comment]
setLimitsY method is being used in [view.cpp](https://github.com/tangrams/tangram-es/blob/master/core/src/view/view.cpp) to limit lat.
You can see that for reference.

**Comment by JunsuLime** [comment]
Oh Thank you so much!! 

Have a good day!! :)

**Comment by tallytalwar** [comment]
Hey @JunsuLime 

We are not exposing `ViewConstraints` in any of the platform code. However, we can look to expose these in future tangram releases. As a stop gap workaround you can do the math in your android app and make sure your constraints are respected when setting map position, till or rotation.

**Comment by JunsuLime** [comment]
@tallytalwar 
Thank you !!! :)

**Comment by matteblair** [comment]
Superseded by #2034
