### ISSUE TITLE
GLThread error is occured with SEGSEGV error

### ISSUE THREAD

**Issue by JunsuLime** [tangrams/tangram-es#1432]
04-04 15:44:32.516 2314-10253/com.pinonmap.map.dev E/Alfons: Font is broken or irrelevant...
04-04 15:44:32.527 2314-10253/com.pinonmap.map.dev E/Alfons: Missing font: error: 1 /system/fonts/DroidSansFallback.ttf

Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 10247 (GLThread 14229)
                                                           
[ 04-04 15:44:50.603   364:  364 W/         ]                                            
debuggerd: handling request: pid=2314 uid=10267 gid=10267 tid=10247

I'll describe about this case.

===============    <- current activity (new)

===============    <- activity that includes map fragment (older)

and I send broadcast that draw markers on map.  and finish current activity.

And My Application broke down with this message.

I want your help, thank you :)

**Comment by JunsuLime** [comment]
04-14 18:41:03.047 6600-6870/com.pinonmap.map.dev A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x656c797473208b in tid 6870 (GLThread 17002)
                                                          
                                                          [ 04-14 18:41:03.048   363:  363 W/         ]
                                                          debuggerd: handling request: pid=6600 uid=10282 gid=10282 tid=6870
04-14 18:41:03.143 12691-12691/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-14 18:41:03.144 12691-12691/? A/DEBUG: Build fingerprint: 'google/bullhead/bullhead:7.1.1/N4F26O/3582057:user/release-keys'
04-14 18:41:03.144 12691-12691/? A/DEBUG: Revision: 'rev_1.0'
04-14 18:41:03.144 12691-12691/? A/DEBUG: ABI: 'arm64'
04-14 18:41:03.144 12691-12691/? A/DEBUG: pid: 6600, tid: 6870, name: GLThread 17002  >>> com.pinonmap.map.dev <<<
04-14 18:41:03.144 12691-12691/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x656c797473208b
04-14 18:41:03.144 12691-12691/? A/DEBUG:     x0   00000079c692f100  x1   00000079d3becc50  x2   0000000000000001  x3   00000079ccb1f5e0
04-14 18:41:03.144 12691-12691/? A/DEBUG:     x4   1620e93263ac4793  x5   1620e93263ac4793  x6   0000000000000000  x7   0000000000000007
04-14 18:41:03.144 12691-12691/? A/DEBUG:     x8   3a656c797473207b  x9   00000079c9b68230  x10  0000000000000000  x11  0000000000000000
04-14 18:41:03.144 12691-12691/? A/DEBUG:     x12  0000000000000013  x13  0000000000000013  x14  0000000000000001  x15  0000000000000001
04-14 18:41:03.144 12691-12691/? A/DEBUG:     x16  00000079cd891a78  x17  00000079cd402298  x18  0000000000000000  x19  0000000000000001
04-14 18:41:03.144 12691-12691/? A/DEBUG:     x20  00000079ca787b98  x21  00000079cef32240  x22  00000079d3becc50  x23  00000079c692f100
04-14 18:41:03.144 12691-12691/? A/DEBUG:     x24  00000079c8ff9ad8  x25  0000000000004000  x26  0000000000000000  x27  0000000000000000
04-14 18:41:03.144 12691-12691/? A/DEBUG:     x28  00000079c9b68000  x29  00000079cd1739c0  x30  00000079cd47c968
04-14 18:41:03.144 12691-12691/? A/DEBUG:     sp   00000079cd173960  pc   00000079cd47c9c4  pstate 0000000080000000
04-14 18:41:03.190 12691-12691/? A/DEBUG: backtrace:
04-14 18:41:03.190 12691-12691/? A/DEBUG:     #00 pc 00000000002019c4  /data/app/com.pinonmap.map.dev-2/lib/arm64/libtangram.so (_ZN7Tangram15DynamicQuadMeshINS_12SpriteVertexEE4drawERNS_11RenderStateERNS_13ShaderProgramEi+208)
04-14 18:41:03.190 12691-12691/? A/DEBUG:     #01 pc 00000000002018c4  /data/app/com.pinonmap.map.dev-2/lib/arm64/libtangram.so (_ZN7Tangram10PointStyle16onBeginDrawFrameERNS_11RenderStateERKNS_4ViewERNS_5SceneE+116)
04-14 18:41:03.190 12691-12691/? A/DEBUG:     #02 pc 000000000016b8d0  /data/app/com.pinonmap.map.dev-2/lib/arm64/libtangram.so (_ZN7Tangram3Map6renderEv+896)
04-14 18:41:03.190 12691-12691/? A/DEBUG:     #03 pc 00000000000dbd10  /system/lib64/libart.so (art_quick_generic_jni_trampoline+144)
04-14 18:41:03.190 12691-12691/? A/DEBUG:     #04 pc 000000000003dd60  /dev/ashmem/dalvik-jit-code-cache (deleted)
04-14 18:41:05.815 397-397/? E/lowmemorykiller: Error writing /proc/6600/oom_score_adj; errno=22

**Comment by JunsuLime** [comment]
This error happened when i close activity on return to MainActivity MapView

**Comment by hjanetzek** [comment]
Hi! Which tangram-es version are you using?

**Comment by JunsuLime** [comment]
My current tangram version is 0.5.1

and this problem occur 0.5.0 also.   Thank you!! 👍

**Comment by karimnaaji** [comment]
@JunsuLime We didn't have any other report of this issue on newer versions of Tangram, please reopen if you are still having this issue on latest Tangram.
