### ISSUE TITLE
polyline breaks at different zoom levels (ClientGeoJsonSource->addLine)

### ISSUE THREAD

**Issue by FarazKhalidZaki** [tangrams/tangram-es#1444]
I am facing problem with Polyline added using ClientGeoJsonSource->addLine from 0.5.1 release. Polyline is broken into different segments at different zoom levels i.e. some segments are visible at one zoom level and other segments are not drawn.
I am facing this problem on both android and ios.

**Comment by tallytalwar** [comment]
Thanks for the patience here @FarazKhalidZaki.

The fix for this went into master with #1517. Closing this issue.
