### ISSUE TITLE
iOS(swift) - TGMapdata clear Again

### ISSUE THREAD

**Issue by seubseub** [tangrams/tangram-es#1445]
Hi

I saw your release 0.5.1 and 0.6.0.

And About #1405 , I tried again about TGMapdata.

It also cause our app dead.

So I thought that our style sheet may different, but when I try again with your ScenFile 

"https://tangrams.github.io/walkabout-style/walkabout-style.yaml". but It also cause app dead too.

So, I think my code may wrong.. please one more time review about my code or Can you tell me about

how to use TGMapdata.clear() to clear my line?

here is my code.

```
var mapData : TGMapData!

override func requestRender() {
        super.requestRender()
}

override func viewWillAppear(_ animated: Bool) {
     super.loadSceneFile("https://tangrams.github.io/walkabout-style/walkabout-style.yaml")
     mapData = self.addDataLayer("mz_route_line_transit") or our scenfile
}
```
```
func drawLine(Trip : TripList) {
        clearLine()
        var lastPoint : TGGeoPoint? = nil
        let properties = ["type": "line", "color": "#D2655F"]
        for selectTripPin in Trip.pins {
             if(selectTripPin.lat <= 90 && selectTripPin.lng <= 180) {
                  let currentPoint = TGGeoPoint(longitude: selectTripPin.lng, latitude: selectTripPin.lat)
                  if(lastPoint != nil) {
                        let line = TGGeoPolyline()
                        line.add(lastPoint!)
                        line.add(currentPoint)
                        mapData?.add(line, withProperties: properties)
                  }
                 lastPoint = currentPoint
              }
       }
}
```
```
fun clearLine() {
     mapData.clear()
}
```

Thank you for reading my issue!

I'm always thank you for your kindness reply :)

**Comment by karimnaaji** [comment]
Hey @seubseub

Thanks for sharing the code, we'll debug this today and let you know what could possibly go wrong!

**Comment by karimnaaji** [comment]
Can you give more info on when `drawLine` is called, is it possible that this method is called before `mapData` is initialized?

**Comment by seubseub** [comment]
@karimnaaji 

Thanks for your reply. I just call `drawLine` when marker is picked. I call `onScrapPinClick `

 method. And This is my method about marker clicked

```
func onScrapPinClick(pin : PinList) {
        .... // This Code is about Overview(use `icarousel`)
        drawLine(Trip: convertedTrip)
    }
```

then `onScrapPinClick` method, I call this `drawLine` method.  so never call `drawline` before I pick 

marker. and I also debug about may draw line before mapData = self.addDatalayer~, but It was not 

happen. One thing curious was I have override method viewDidLoad, viewWillAppear and I called 

super.loadScenFile each. So May this wrong, but when I delete super.loadScenFile in viewWillAppear, 

then dead too. What can I do debug more about this happen?? Anyway @karimnaaji Thank you for 

trying my code! :)

**Comment by karimnaaji** [comment]
I haven't been able to reproduce this issue with the code sample you provided and I don't see any obvious bug in the code path you described, I would suggest you to download the debug version that we provided in [the release of 0.6.0](https://github.com/tangrams/tangram-es/releases/download/0.6.0/TangramMap.framework-0.6.0-Debug.zip) and give us the exact backtrace of the crash you are dealing with.

**Comment by seubseub** [comment]
@karimnaaji 
yes I think.. my code that I post is so partial. I'll try to make exact backtrace about release of 0.6.0 that 

you gave to me.

And then I post about crash! :)

**Comment by seubseub** [comment]
@karimnaaji 

Hi Again! First of all, I post my tangram test.

And I'm apologize for my mistake. I thought that every tangram's methods do in main thread,

but markerpickresult didn't do in main thread.

and I tested TGmapdata.clear() at some tangram's method such as, 'didRecognizeLongPressGesture', 

'didRecognizeSingleTapGesture', 'didRecognizeRotationGesture', 'mapViewDidCompleteLoading' then 

those method work well. but when I call TGMapData.clear() at 'didSelectMarker', App dead. so I do 

block in mapData.clear() with main thread at my function that called by 'didSelectMarker'. and then 

operate well!

Anyway @karimnaaji thanks for code reviewing :).

Thanks Again.



[TangramTest.zip](https://github.com/tangrams/tangram-es/files/916263/TangramTest.zip)

**Comment by karimnaaji** [comment]
Hey thanks, glad it worked out! Closing this issue then.
