### ISSUE TITLE
local storage

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1446]
is it possible to create something like that?

> sources:
    mapzen:
        type: MVT
        url: file:///storage/emulated/0/tiles/{z}/{x}/{y}.mvt
        max_zoom: 16

**Comment by matteblair** [comment]
This probably doesn't work in the current version of tangram-es. However we are _actively_ working to support more general URL requests for data sources (including `file://` URLs). I expect this to be released within the next month.

**Comment by ivangorelow** [comment]
Nowadays is it impossible to use your map offline?

**Comment by matteblair** [comment]
It's not impossible, but it's not as easy as we'd like it to be! A solution now is to create an MBTiles database with the set of tiles that you want to store, then set that as the URL of your data source. You can generate MBTiles files using [existing tools](https://github.com/mapbox/mbtiles-spec/wiki/Implementations) but in the future we hope to make it easier to get usable files without building them yourself.

**Comment by ivangorelow** [comment]
and which util do you use for creating mbtiles?

**Comment by matteblair** [comment]
Resolved by #1659 

P.S. https://github.com/tilezen/tilepacks is a tool for creating MBTiles packs.
