### ISSUE TITLE
Textures flicker in the middle of the screen 

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1449]
Happens on Android 4.4.4/CM11, tangram-ES 0.6.0

It is a bit difficult to describe, so, here is a picture. The user describes:

> The small icons are not visible all the time, they are shown and hidden like 4 times in a second or so. Sadly that makes the usage quite problematic.
<img src="https://farm4.staticflickr.com/3931/33831648441_bc5681f825_o.png"/>

This is the YAML in which the styles are defined:
https://github.com/westnordost/StreetComplete/blob/master/app/src/main/assets/streetcomplete.yaml

Original issue here https://github.com/westnordost/StreetComplete/issues/119

**Comment by westnordost** [comment]
The user reverted the tangram-ES version back to 0.5.1, he reports that he does not have the issue with the old tangram version.

**Comment by hjanetzek** [comment]
Thanks - that's an interesting issue. I can't reproduce it on my Android 5 - 7 devices. 
The relevant change could be the switch to 'vertex array objects'. I could try to build a patched version of StreetComplete with this option disabled. I.e. `useVao = false` here https://github.com/tangrams/tangram-es/blob/master/core/src/gl/dynamicQuadMesh.h#L105

@karimnaaji do you have an idea?

**Comment by karimnaaji** [comment]
Yeah it's quite interesting, I will give it a try on my phone and see if I can reproduce this issue!

**Comment by westnordost** [comment]
Here are some more pictures from a new error report: https://github.com/westnordost/StreetComplete/issues/130

**Comment by westnordost** [comment]
Oh, forgot to close it. The newest version fixed the problem
