### ISSUE TITLE
Custom placeholder when loading scene asynchronously

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#1450]
We recently updated the iOS SDK sample app to load scene files asynchronously. When making that change we noticed that the map background is black before any of the tiles load. This doesn't occur when loading the scene file synchronously (the background is gray). 

Could we update tangram to provide a gray background in all cases by default and also to allow users to designate a custom background color (or view) to display before tiles load?

[Here](https://github.com/tangrams/ios-framework/tree/tab-bar) is an updated example which highlights the issue by creating two `TGMapViewController` subclasses within a tab bar and sets the background to be red before the tiles finish loading.

**Comment by nvkelso** [comment]
I vote for white by default.

**Comment by matteblair** [comment]
That is an odd difference, I agree that it would be preferable to make the behavior more consistent. 

To clarify, we're talking about the application background while the _scene_ is loading, yes? There is already an option in the scene file to specify a background color where _tiles_ are loading, but of course we can't apply that option before the scene is parsed and loaded.

**Comment by karimnaaji** [comment]
@sarahlensing have you tried changing the background color in the interface builder?

![screen shot 2017-04-11 at 10 57 18 am](https://cloud.githubusercontent.com/assets/7061573/24915699/de43478a-1ea5-11e7-9087-8208bee8bea8.png)

In tangram, setting the clear color in the first GL call that happens in like so:
```diff
diff --git a/core/src/tangram.cpp b/core/src/tangram.cpp
index a9e19f0..4ed3a50 100644
--- a/core/src/tangram.cpp
+++ b/core/src/tangram.cpp
@@ -864,6 +864,8 @@ void Map::setupGL() {
 
     LOG("setup GL");
 
+    impl->renderState.clearColor(1.0, 0.0, 0.0, 1.0);
+
     impl->renderState.invalidate();
 
     impl->tileManager.clearTileSets();
(END)

```
Doesn't seem to resolve the issue, even though it would still be good to add that diff to provide a default color before the scene is loaded.

**Comment by sarahlensing** [comment]
"To clarify, we're talking about the application background while the scene is loading, yes?"
@matteblair we're talking about the `GLKView` background while the scene is loading

@karimnaaji I tried that but it didnt have any effect. I was able to change the color with this code:
```swift
override func glkView(_ view: GLKView, drawIn rect: CGRect) {
    super.glkView(view, drawIn: rect)
    if(!loaded) {
      glClearColor(1.0, 0.0, 0.1, 1.0);
      glClear(GLbitfield(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT));
    }
  }
```

Clients could achieve this desired outcome by subclassing `TGMapViewController` and adding this but it seems like we might want to provide a more consistent default at the core level

**Comment by matteblair** [comment]
Yeahhhh ok so I think I understand what's making this color. When we load a scene asynchronously, the render loop in tangram-es is running - but with an empty scene. The default background color for a scene is `0x000000` and so that's all we render. 

We could try simply returning early in our `drawInRect` implementation if the map doesn't have a scene loaded. Ideally, that would allow any external methods of setting a background (e.g. Interface Builder) work as expected.

**Comment by matteblair** [comment]
Another idea: if we add an interface to the tangram-es core that lets you specify a "default clear color" then our iOS platform wrapper might be able to query the background color set to the view in interface builder and pass that into the core.
