### ISSUE TITLE
Remove API keys and document Mapzen key requirements

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#1452]
The demo applications and scenes in this repository have historically used a single Mapzen API key designated for test use of vector tiles. Our intent with this key was that users could check out the code for the demo applications and run them without any modifications, then get their own key when/if they decided to continue developing an application. 

There are several reasons that it's important for developers to use their own API key:
 - Better quality of service! If one application starts abusing the vector tiles API using the demo key, we have to shut off service for that key. Any other innocent applications using that key will also have their service shut off without warning.
 - More information for developers! Using your own API key, you can track the usage of Mapzen APIs in your own application with the Mapzen Developer dashboard.
 - More information for Mapzen! We are always trying to figure out what our API users need more of, and with individual user keys this job is much easier.

However, we've observed that a large number of developers have ended up copy-pasting our demo API key into their applications, rather than obtaining and using their own key. Here are some incremental steps we can take to prevent the accidental or intentional usage of our demo API key in other applications:

1. Improve documentation of key requirements: We should document that the Mapzen services used in our demos require an API key, and link to the relevant Mapzen pages.
2. Refresh the demo API key: We'll replace the API key in our demo applications with a new key and shut off service to the old one. Any applications using the old demo key will then be forced to obtain a new key if they want to continue using the vector tiles service.
3. Remove API keys from code: We can remove all usage of API keys from the repository and rely instead on environment variables or other local configuration files to provide keys. This will prevent any future users from accidentally using an API key from the demo code.

**Progress:**
- [x] Remove API keys from Android demo
- [x] Remove API keys from iOS demo
- [x] Remove API keys from desktop demos

**Comment by tallytalwar** [comment]
Some of the work being done here: https://github.com/tangrams/tangram-es/pull/1466 (cc. @karimnaaji)

**Comment by matteblair** [comment]
cc @msmollin @karimnaaji What do we think is the easiest way to pull environment variables like API keys into an iOS project?

**Comment by karimnaaji** [comment]
I think we can safely add it into the plist and query the value from the sample app code if that makes sense with you @msmollin .
By default we would leave the spot empty and mention that the user would need to fill it from the documentation.

**Comment by matteblair** [comment]
But don't we track the plist in git? It might get annoying to add and remove a local API key from the plist when one wants to do git operations, especially since plist files can't be nicely diff'ed.

**Comment by tallytalwar** [comment]
Kinda agree with @matteblair, if you look at how we are doing for other platforms is that the API key is controlled from a file which is not tracked by git.

Android: either environment variable or setting a gradle.property (local or global)
osx/linux/rpi: setting an environment variable.

**Comment by karimnaaji** [comment]
Yeah the default plist is tracked on the git project. It's possible though to have another plist configuration file that gets generated by cmake at build time and inject a command line option for the API key, or directly pull it from an environment variable and inject it as a define.

**Comment by matteblair** [comment]
Oh so it would be part of the "project generation" step? That makes sense. We can read an environment variable in CMake, inject it into a plist file that lives in the build directory, and then read that in the application - is that the idea?

**Comment by karimnaaji** [comment]
Yes that's the idea, the only user need in that case would be to do either an `export` command with the API key or pass a command line argument to the generation step with `make cmake-ios -DAPI_KEY=???`

**Comment by msmollin** [comment]
Agreed. This is how the Mapzen SDK sample app injects it stuff in Circle CI. You can also have the Objective-C code read in from a unix environment variable, but I think it's better to inject it at project generation time.

**Comment by matteblair** [comment]
The last step here is to de-activate the key that was previously committed in demos. This may disrupt tile service for any applications that copied that key, so we should provide whatever warning we can. In the release notes for version 0.7 I'll make a big notice about how API keys are required now and how the old demo key will stop working.

**Comment by nvkelso** [comment]
When we did the same thing for the Mapzen house styles we gave people 1
month warning that they should switch to using their own key, then
monitored the usage. It took a couple more weeks till usage trailed off (a
couple additional weeks of grace period), then we disabled the old demo
key(s).
