### ISSUE TITLE
Long working with mbtiles

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1455]
I noticed that when I changed zoom level from 12 to 16, tangram loaded 13 zoom then 14 then 15 and only after that it loaded 16. 

I use android

**Comment by matteblair** [comment]
Please provide more detail about your question. 

Are you using the Tangram Android SDK? What version?

What does this have to do with MBTiles?

What parts of the interface did you use?

What did you expect to happen?

What actually happened? Do you have a record of it?

**Comment by matteblair** [comment]
Closed due to inactivity
