### ISSUE TITLE
problems with text in the latest release

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#1457]
metro:
        data: { source: mapzen, layer: pois}
        filter: { $zoom: { min: 11} }
        ufterzoomfilter:
            filter:
                is_subway: 'true'
                kind: station
            draw:
                icons2:
                    priority: 2
                    size: 16px
                    interactive: true
                    visible: true
                    sprite: metro
            labels:
                filter: {  $zoom: { min: 12 } }
                draw:
                    text-blend:
                        visible: true
                        text_wrap: false
                        move_into_tile: false
                        anchor: [bottom]
                        offset: [0, 17px]
                        priority: 3
                        font:
                            family: Helvetica
                            size: 10px
                            fill: blue
                            stroke: { color: white, width: 3 }

I have such style and it works perfectly in 0.5.1! but in 0.6.0 I don't see text

**Comment by nvkelso** [comment]
With recent Tangram versions it’s better to “nest” or “attach” the text
directly to the point renderer – for you this would mean something like:

icons2:
    …
    text:
        …

**Comment by matteblair** [comment]
The first filter should read `is_subway: true` (without quotes). The value for the `is_subway` tag in the tile data is a Boolean value, not a string. Tangram-es used to incorrectly treat these as the same type of data.
