### ISSUE TITLE
Marker crash after new scene is loaded

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#1464]
When we load a new scene, we rebuild all the markers against that new scene and we end up with two cases:
- a marker is attached to a style that exists in both the previously loaded and new scene, 
- the marker doesn't find a new style to be built against

Inconsistency can happen in both those cases; a style can be found with the same name but have  different resources, where we result in a bad access or, the marker wouldn't show if a style was available in the previous scene but not in the new one.

To resolve this inconsistency, the best solution seems to drop all markers whenever a scene gets reloaded, since those are in fact tightly coupled with the scene itself when they get created.

**Comment by tallytalwar** [comment]
To add to @karimnaaji, we can document the behavior such that the user handles readding of any marker in the asyncSceneLoad/Update callback.
