### ISSUE TITLE
Linker Hell.. not a bug.. but need help please! :)

### ISSUE THREAD

**Issue by tschesnok** [tangrams/tangram-es#1481]
Is there are definitive link order for the lib files? Do I need to link with more than just the 13 libxxx.a files in /build/rpi/lib???

Background: 

First: AWESOME! Tangrams-es on the RPI is AMAZING. Super Fast. Very nice work!

I have the full lib and demo "main.cpp" building and running for the RPI. 

I am now trying to use it with my own project. It builds. but I'm getting linker hell. If I don't link to any of the .a files I get the expected few missing functions. When I start adding libraries I get 1000's of missed dependant functions.

I'm not that strong with CMAKE and makefiles. Parsing the full build instructions seems beyond my capabilities.

MY current Makefile:

CPPFLAGS+=-g -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM -Wno-psabi

LDFLAGS+=-L/opt/vc/lib/ -L/home/pi/tangram-es/build/rpi/lib -lEGL -lGLESv2 -lbcm_host -lvcos -lvchiq_arm -lpthread -lrt \
-ldl -licucommon -lsqlite3 -lyaml-cpp -lharfbuzz -lalfons -lSQLiteCpp -lfreetype -lduktape -ldouble-conversion -lcss-color-parser-cpp -lminiz -llinebreak -lcore

INCLUDES+=-I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I/home/pi/tangram-es/platforms/rpi/src -I/home/pi/tangram-es/core/include/tangram -I/home/pi/tangram-es/platforms/common -I/home/pi/tangram-es/core/deps/glm -I/home/pi/tangram-es/platforms/linux/src

all: Globe.exe

%.o: %.c
	@rm -f $@ 
	$(CC) $(CFLAGS) $(INCLUDES) -g -c $< -o $@ -Wno-deprecated-declarations

%.o: %.cpp
	@rm -f $@ 
	$(CXX) $(CPPFLAGS) $(INCLUDES) -std=c++11 -g -c $< -o $@ -Wno-deprecated-declarations

Globe.exe: main.o font.o renderStats.o shaderLoader.o util/bitmap.o util/ktx.o util/native.o UVSphereModel.o MouseIO.o GlobeClock.o GlobeGlobalDisplayMode.o GlobeMaps.o GlobeDisplayEngine.o GlobeUI.o GlobeCV.o 
	$(CXX) main.o font.o renderStats.o shaderLoader.o util/bitmap.o util/ktx.o util/native.o UVSphereModel.o MouseIO.o GlobeClock.o GlobeGlobalDisplayMode.o GlobeMaps.o GlobeDisplayEngine.o GlobeUI.o GlobeCV.o -o $@  $(LDFLAGS) 

clean:
	for i in main.o font.o renderStats.o shaderLoader.o util/bitmap.o util/ktx.o util/native.o UVSphereModel.o MouseIO.o GlobeClock.o GlobeGlobalDisplayMode.o GlobeMaps.o GlobeDisplayEngine.o GlobeUI.o GlobeCV.o; do (if test -e "$$i"; then ( rm $$i ); fi ); done

**Comment by tschesnok** [comment]
Got it working.. If anyone else wants help on this hit me up..

**Comment by hjanetzek** [comment]
It would easier with linking when you build tangram as a shared library. 
e.g. this may work when added to toolchains/raspberrypi.cmake
```
add_library(tangram SHARED
  ${COMMON_SOURCES} ${LINUX_SOURCES})
target_link_libraries(tangram
  ${CORE_LIBRARY} -lcurl)
```
