### ISSUE TITLE
Error Loading Shader

### ISSUE THREAD

**Issue by tschesnok** [tangrams/tangram-es#1483]
Main.cpp Demo App works fine - no errors.

Got my own app to build, link and run on RPI but am getting the following errors during startup:
ERROR shaderProgram.cpp:83: Shader compilation failed for 
ERROR hardware.cpp:51: glGetString( GL_EXTENSIONS ) returned NULL
TANGRAM hardware.cpp:77: Hardware max texture size 22959476
TANGRAM hardware.cpp:78: Hardware max combined texture units 22959476
TANGRAM tangram.cpp:324: resize: 800 x 600
ERROR shaderProgram.cpp:83: Shader compilation failed for 
WARNING sceneLoader.cpp:1760: Can't find data source touch for layer touch

I'm trying to figure out if I have a path issues with the shaders - but I'm clueless as to how this is handled in the code (seems to be pre-built with c-make and linked via a header file???? - then why does it fail to load?

Any help would be appreciated such as:
Is there are relative path I should put the shader files?
Where can I change the path for the shaders (I can find it in no place  in the code)

Or any other ideas as to the errors?

**Comment by matteblair** [comment]
From the GL errors here, it sounds like there isn't a valid GL context when that app is running. It's hard to say more about why that would happen without knowing what code is in your app.

Tangram-es has some GLSL shaders that are built into the map rendering pipeline and, as you noticed, they are translated into "data headers" using a CMake script. These shaders interact with our pipeline in very specific, non-obvious ways, so editing them is not a good way to change the appearance of your rendered output. The appearance of your map should be entirely configured through the _scene file_ (`scene.yaml`) in our demos. Information about writing scene files is here: https://mapzen.com/documentation/tangram/

Let me know if I misunderstood your problem!

**Comment by tschesnok** [comment]
Many thanks for the tip.. I will look into when / how I create a GL context.

**Comment by tschesnok** [comment]
That did the trick! Many thanks!
