### ISSUE TITLE
Marker blinking problem in android

### ISSUE THREAD

**Issue by JunsuLime** [tangrams/tangram-es#1488]
When I call mapController.setPosition(..),  sometimes maker disappear or blink or  its shape is broken

At 0.5.1, this phenomenon  does not occur.
And I upgrade version 0.6.1, this problem come out.

**Comment by hjanetzek** [comment]
Hi @JunsuLime - this issue is probably fixed in 0.6.2 release. Please report back if the issue still exists

**Comment by tallytalwar** [comment]
Closing this. Kindly reopen this or file another issue if you are still having issues with this.
