### ISSUE TITLE
screenPositionToLngLat or getZoom return wrong data

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1492]
So, here is a bug I have been hunting down for a while. It seems to be almost impossible to reproduce, but in StreetComplete 0.8 I added some fail-fast logging with which I was able to track it down a bit. Now, it seems that `MapController.screenPositionToLngLat` is very seldomly returning data that is inconsistent to `MapController.getZoom`. I'll leave the details how this affects my app aside and come to the point with an illustration:

This is a snapshot of the area that was supposedly displayed on the screen when my app detected and logged that the returned screenPositionToLngLat doesn't fit to the returned zoom:
![toolarge](https://cloud.githubusercontent.com/assets/4661658/25764651/32d26fe6-31e9-11e7-836d-730918caab40.png)
As you see, the returned bounding box contradicts the returned zoom level. The zoom level should be around 11-12 here (or resp. the area be smaller).
I can tell because the displayed area seen here are 5x8 tiles at z14. At zoom level 14, usually at most 1-2 tiles at z14 fit into the view.

The screen borders are conceptually calculated as follows ([source](https://github.com/westnordost/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/tangram/QuestsMapFragment.java#L343)):
```
Point size = new Point(getView().getMeasuredWidth(), getView().getMeasuredHeight());
LngLat[] positions = new LngLat[4];
positions[0] = controller.screenPositionToLngLat(new PointF(0,0));
positions[1] = controller.screenPositionToLngLat(new PointF(size.x, 0));
positions[2] = controller.screenPositionToLngLat(new PointF(0,size.y));
positions[3] = controller.screenPositionToLngLat(new PointF(size));
```

A wild guess for where this bug is coming from: Perhaps the zoom level is updated at other times than `screenPositionToLngLat `or in other words, `screenPositionToLngLat `is always newly calculated and `getZoom `is only refreshed on certain events?

(The related issue is [StreetComplete #137](https://github.com/westnordost/StreetComplete/issues/137)  but this is not really relevant).

**Comment by hjanetzek** [comment]
It's possible that the map view position gets updated on the GL thread between calls to `screenPositionToLngLat` and `getZoom`. To make sure that all values returned are for the same view you should synchronize this block on the `MapController` object

```
synchronized(controller) {
  zoom = controller.getZoom();
  Point size = new Point(getView().getMeasuredWidth(), getView().getMeasuredHeight());
  LngLat[] positions = new LngLat[4];
  positions[0] = controller.screenPositionToLngLat(new PointF(0,0));
  positions[1] = controller.screenPositionToLngLat(new PointF(size.x, 0));
  positions[2] = controller.screenPositionToLngLat(new PointF(0,size.y));
  positions[3] = controller.screenPositionToLngLat(new PointF(size));
}
```

And, yes, this needs better documentation..

**Comment by westnordost** [comment]
Ah, I see. I'll not close this issue in case you want to use it as a reminder to add a sentence to the documentation there, but I don't mind if you do.
