### ISSUE TITLE
Geometry added with GeoJson flicker depending on zoom level

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1499]
I add line geometry which is directly derived from OSM data as a new layer to the map (`geometryLayer.addPolyline`), using an own style to render it half-transparently.

Some users are reporting the following effect when zooming in and out. See this video for an illustration:
https://files.natenom.com/nidx/nobackup/bug204.mp4

I myself can not reproduce it, but what I can reproduce is that sections of the way seem to be rendered duplicate, this might be related.
![img](https://cloud.githubusercontent.com/assets/13040148/25828146/fcb50654-344e-11e7-99a0-77fd90c15649.png)

Related StreetComplete issue: https://github.com/westnordost/StreetComplete/issues/204

Using Tangram-ES Version 0.6.2

**Comment by westnordost** [comment]
The video was made with LineageOS 14.1, Android 7.1.2 on a Samsung Galaxy S5.

**Comment by tallytalwar** [comment]
Hey @westnordost 

Thanks for keeping us on our toes :D. There are 2 issues pointed here and one of which ("sections of the way seem to be rendered duplicate") is resolved by https://github.com/tangrams/tangram-es/pull/1496, the other issue of disappearing of certain client data source geometry at certain zoom level is same as being discussed in https://github.com/tangrams/tangram-es/issues/1463. We are aware of this and will try to get it resolved soon. I am going to close this issue in favor of #1463.

Thanks

**Comment by matteblair** [comment]
(The polylines will overlap less after the fix from #1496 is applied, but the round caps at the ends will still overlap - you can change those to 'butt' to keep them from extending past the end of the line https://mapzen.com/documentation/tangram/draw/#cap)

**Comment by westnordost** [comment]
Right, cool. Sorry for the duplicate.

**Comment by tallytalwar** [comment]
@westnordost The fix for this should be in master. Refer #1517
