### ISSUE TITLE
Node images become invisible on certain zoom levels

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1500]
This is not a duplicate of #1415, as that issue was solved by adding priority:0 to the draw rule in question. Now with tangram-es 0.6.2, some people are experiencing the same bug, but with the right priority already set in the draw rule. I cannot say of course if this behavior existed before 0.6.2, it also does not appear too often.

Note the red marker with the question mark. It vanishes at a certain zoom level, even though the geojson for that layer is not changed.

![gif](https://cloud.githubusercontent.com/assets/899988/26034134/213d5eb4-38b8-11e7-81dd-27dd9fa619ff.gif)
The video was made with a Android 6.0.1 MMB29M, Redmi 4 device, StreetComplete 0.10.

I reproduced it like this right now:
1. turn on "show all notes" in the StreetComplete options
2. go here: http://www.openstreetmap.org/#map=19/50.06217/19.93807 and scan for quests. A red marker should appear on the northern end of the long building
3. zoom in and out, see that the marker appears and disappears depending on the zoom.

It is  conspicuous that markers seem to vanish whenever a text (road name) is displayed at the same location.
But not always. You see this effect with other markers on that plaza, for example there is an orange clock marker on the small building on the western side of this plaza which also shows the same behavior but there is no street name close to there.

The style I use: https://github.com/westnordost/StreetComplete/blob/master/app/src/main/assets/streetcomplete.yaml

Related StreetComplete bug: https://github.com/westnordost/StreetComplete/issues/225

**Comment by tallytalwar** [comment]
@westnordost Going to mark this resolved. Fix for this went in master with #1517 and I also tested this with `StreetComplete`'s `master` branch.
