### ISSUE TITLE
iOS framework may missing info.plist file - app upload rejection.(Error)

### ISSUE THREAD

**Issue by seubseub** [tangrams/tangram-es#1506]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
 1. I use your library from cocoa pods. and then when I see other library in pods project, then 
tangram may missed info.plist file.

like this picture.

![2017-05-17 7 23 32](https://cloud.githubusercontent.com/assets/16539714/26149723/5b2eb6ce-3b36-11e7-8a74-60534f6c35b0.png)

And then I want to upload app from make 'archive' and 'export' app, then 'xcode' -> 'open developer tool' -> 'application loader' to upload my app.ipa file. then error happened.

**RESULT:**

This is Error.
<img width="694" alt="2017-05-17 7 25 28" src="https://cloud.githubusercontent.com/assets/16539714/26149861/e01d0e58-3b36-11e7-97fd-2dab9377fc70.png">

**EXPECTED RESULT:**
Not above message called and app upload at iTunes.

**ENVIRONMENT:**
OS : Sierra version : 10.12.5
device : iPhone6s.
I use tangram-es version 0.6.2 in cocoa pods

**OTHER:**
I thought that it was my project problem. but when I make new project and just install tangram-es 0.6.2 from cocoa pods, same occurred. 
like this picture
<img width="256" alt="2017-05-17 7 32 03" src="https://cloud.githubusercontent.com/assets/16539714/26150007/92cafb82-3b37-11e7-8450-cd9c1a6d5b27.png">
 
so Could you explain why this thing happen??

Also, I love your library :) Thank you for reading my issue.

**Comment by karimnaaji** [comment]
Hi @seubseub ,

That's a good find, the plist file is actually provided with the framework. If you right click on the framework from XCode you should be able to find it, for some reason XCode only shows the public headers of the framework.

The value is, as mentioned in your error, empty for `CFBundleVersion`
<img width="812" alt="screen shot 2017-05-17 at 11 22 21 am" src="https://cloud.githubusercontent.com/assets/7061573/26162139/e6e5c010-3af3-11e7-8ed9-7af3a657e770.png">

This value should be the build number of the framework, we will make sure that this is set from our build system in the next releases. To make sure that this fixes your issue, can you manually set this value to the Tangram framework version that you are currently using?

Let us know how it goes!

**Comment by seubseub** [comment]
@karimnaaji  Thanks for replying. I put current tangram version 0.6.2 in build version, then I can upload at iTunes connect! Thank you for kind help :)

**Comment by matteblair** [comment]
This is fixed in the latest release, closing the issue now.
