### ISSUE TITLE
2D Texture mapping

### ISSUE THREAD

**Issue by Guillaume227** [tangrams/tangram-es#1507]
I am trying to map an image to the outline of a building (e.g. a cross on top of a hospital building).
From the [documentation there](https://mapzen.com/documentation/tangram/textures/) I read:

> If a texture is provided for a lines style, the texture is repeated across the line, with the width of the texture matching the width of the line, and the texture y coordinate scaled to match the aspect ratio of the image (its height over its width).

I have an image that has the same aspect ratio as the rectangle making up the building outline.
So I am using a textured line (see my scene.yaml below) with uv mapping (I could also try with a textured polygon but my buildings are all rectangles for now).
In code (c++) I create a ClientGeoJsonSource on which I call addLine() with the right start/end coordinates and the right width (in meters) to match the building footprint.

However the image ends up scaled in one direction (yielding a bad aspect ratio) and truncated.
Any idea why? Does anyone see an alternative approach?

Original image:
![white_cross](https://cloud.githubusercontent.com/assets/9445488/26245682/8506e56a-3c95-11e7-8e60-f1af4508c6d4.png)

Textured result:
![screenshot_20170517-130351](https://cloud.githubusercontent.com/assets/9445488/26245490/91902f36-3c94-11e7-849d-a6d278b2b2ce.png)

I am on Android (nexus 5X) using the latest code from master.

scene.yaml:

```
textures:
    building_top_raster:
        url: img/white_cross.png # path to the image I want to texture with
            
styles:
    building_top_raster:
        base: lines
        texcoords: true
        material:
           diffuse:
               texture: building_top_raster
               mapping: uv
layers:
    building_top_raster:
        data: { source: building_top_raster }
        poly:
            draw:
              building_top_raster:
                color: function () { return feature.color || '#00FFFFFF'; } #color is required but not used as we texture the whole line 
                width: function () { return feature.width || 10; }

**Comment by Guillaume227** [comment]
I now understand why the aspect ratio looks different from the original image: the line expects a width property in mercator meter, I was passing plain meters.

So now I have the right aspect ratio but I am still wondering why the texture gets cropped in that way:
![screenshot_20170519-131404](https://cloud.githubusercontent.com/assets/9445488/26245641/4f3c346c-3c95-11e7-9f58-a1810e6b079e.png)

**Comment by Guillaume227** [comment]
In case anyone is interested I found that adjusting the zoom level passed to the uv mapping coordinates by a factor of 2 addresses the issue:
 ```
   float zoom = m_overzoom2;
    m_builder.addVertex = [&](const glm::vec3& coord, const glm::vec2& normal, const glm::vec2& uv) {
        -_mesh.vertices.push_back({{ coord.x,coord.y }, normal, { uv.x, uv.y * zoom },
        +_mesh.vertices.push_back({{ coord.x,coord.y }, normal, { uv.x, uv.y * zoom * 2},
                                  _att.width, _att.height, _att.color, selection});
    };

```

That's around line 430 of polylineStyle.cpp, in `void PolylineStyleBuilder<V>::buildLine `

**Comment by matteblair** [comment]
Apologies for not getting around to this issue! Tangram doesn't have much to help mapping a texture to a specific geometry, since most cartography doesn't work that way. It sounds like you found a solution for your use, so I'll close this issue. If you have more questions or suggestions feel free to open a new one!
