### ISSUE TITLE
Convert Objective-C CGPoint struct parameters to pointer refs in shouldRecognize delegate callbacks

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1511]
This allows the touch point location to be modified before processing, enabling scenarios like changing the location of the pinch gesture while location tracking is enabled.

https://github.com/tangrams/tangram-es/blob/master/platforms/ios/src/TangramMap/TGMapViewController.h#L60

**Comment by karimnaaji** [comment]
Resolved via #1548
