### ISSUE TITLE
Expose iOS gesture recognizers publicly to allow for modification

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1512]
Currently the gesture recognizer chain is internal and no reference to them is maintained, which makes it difficult to either disable or override certain behaviors. Implementing developers may for example want to disable simultaneous gesture recognition or setup dependency chains so if a pinch gesture is recognizing we shouldn't go into a shove or a pan. We should maintain publicly accessible references to the gesture recognizers to allow for this.
https://github.com/tangrams/tangram-es/blob/master/platforms/ios/src/TangramMap/TGMapViewController.mm#L531

There are probably some sensible defaults to setup for this as well. Open to thoughts on that.

**Comment by karimnaaji** [comment]
Resolved via #1550.
