### ISSUE TITLE
Myanmar/Burmese script rendering incorrectly

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-es#1513]
Based on on-going work on [Tangram JS](https://github.com/tangrams/tangram/pull/555), I was checking Tangram ES text rendering and noticed that Myanmar/Burmese script is currently not rendering properly. In the screens below, the characters with "dotted lines" should not be shown -- they should be combined via text shaping with other characters. Perhaps there's a text shaping option we don't have enabled?

You can reproduce this by going to Yangon, the capital of Myanmar.

Note: I have tested this on **iOS**, but have not yet verified on other platforms. 

![img_5471](https://cloud.githubusercontent.com/assets/16733/26209028/a85121ca-3bb9-11e7-9e92-f16311d491be.PNG)

![img_5468](https://cloud.githubusercontent.com/assets/16733/26209063/c69546ca-3bb9-11e7-9857-d4d0b3f5d9e3.PNG)

**Comment by tallytalwar** [comment]
Some results on testing on this here: https://github.com/tangrams/tangram-es/pull/1558#issuecomment-313808942

**Comment by matteblair** [comment]
This issue doesn't seem to occur on Android, see the attached screen capture.

I suspected this might be a result of the font family pruning we added on iOS recently (https://github.com/tangrams/tangram-es/blob/master/platforms/ios/src/TangramMap/iosPlatform.mm#L116-L125) but even with all font files allowed we still get missing code points in Myanmar on iOS.

![screenshot_20170718-173413](https://user-images.githubusercontent.com/3371850/28345458-76bde17e-6bdf-11e7-8d81-9a846c84dbaf.png)

**Comment by tallytalwar** [comment]
Couple of screen shots showing issues with "Tibetan" and "Thai" scripts. In these the `dotted circle` appears behind a glyph.

Tibetan Script (dzongkha):
![image uploaded from ios](https://user-images.githubusercontent.com/360641/29422397-ef936952-832c-11e7-9633-3e372f79759e.jpg)

Thai:
![image uploaded from ios 1](https://user-images.githubusercontent.com/360641/29422427-01974b00-832d-11e7-8f47-61cf25c3bbc4.jpg)

**Comment by matteblair** [comment]
Apple Maps on macOS has the same issues with Burmese, which strongly suggests to me that this isn't an artifact of our handling of text shaping or font loading, but rather something incorrect in the font itself.

<img width="148" alt="screen shot 2017-08-17 at 10 12 37 am" src="https://user-images.githubusercontent.com/3371850/29424551-09688684-8335-11e7-84d7-8ff53606d862.png">
<img width="186" alt="screen shot 2017-08-17 at 10 12 59 am" src="https://user-images.githubusercontent.com/3371850/29424558-0e079ae0-8335-11e7-91b3-5b9497343577.png">
<img width="225" alt="screen shot 2017-08-17 at 10 13 15 am" src="https://user-images.githubusercontent.com/3371850/29424564-12873ae4-8335-11e7-9481-8bd78daa5a6a.png">

**Comment by tallytalwar** [comment]
Hmm.. I am not something like this on my end. Plus ours look extreme. (Similar area as the screenshot above near Yangon.

<img width="990" alt="screen shot 2017-08-17 at 11 01 51 am" src="https://user-images.githubusercontent.com/360641/29426469-96c43888-833b-11e7-9611-558433dcb024.png">
<img width="999" alt="screen shot 2017-08-17 at 10 59 07 am" src="https://user-images.githubusercontent.com/360641/29426468-96b19016-833b-11e7-87d9-ca1076d86f27.png">

**Comment by tallytalwar** [comment]
I think what you are seeing @matteblair could be the `Burmese နု် (U+1014 U+102F U+103A)` issue we talked about yesterday.

**Comment by tallytalwar** [comment]
Another example of Khmer having issues on ES but all good on apple maps:

This is Phnom Penh International Airport. (I am also very happy that Cambodia has such great osm data including POIs).

![img_0019](https://user-images.githubusercontent.com/360641/29427145-d1756c16-833d-11e7-9191-28dd6de91c6e.PNG)

<img width="231" alt="screen shot 2017-08-17 at 11 16 31 am" src="https://user-images.githubusercontent.com/360641/29427138-c8b76728-833d-11e7-8a6f-042cbbc0fb2f.png">

**Comment by tallytalwar** [comment]
Another example for Thai font here (Bangkok):

<img width="737" alt="screen shot 2017-08-17 at 2 03 49 pm" src="https://user-images.githubusercontent.com/360641/29433672-092ad440-8355-11e7-9465-333427db54ca.png">

**Comment by bcamper** [comment]
Yes but those labels render correctly on Tangram JS :)

**Comment by matteblair** [comment]
@bcamper Actually they don't! This bug is pervasive in macOS/iOS

<img width="175" alt="screen shot 2017-08-17 at 11 44 47 am" src="https://user-images.githubusercontent.com/3371850/29435790-4075cf6a-835d-11e7-80ea-d18f9b9b6c19.png">

https://mapzen.com/products/maps/refill/more-labels/#lat=16.77944&lng=96.17382&z=16.6292

**Comment by bcamper** [comment]
Oh wow! Sorry, I thought we were talking about a broader set of labels.

**Comment by matteblair** [comment]
I should clarify: It looks like there may be several categories of buggy labels in Tangram ES, but the labels with this glyph that macOS mishandles are rendered incorrectly in basically every application on macOS and iOS.

**Comment by tallytalwar** [comment]
To clarify further, there are 3 different categories of font bugs here:

1. Bad Data: The JS screenshot @matteblair posted above.
2. Bad glyph with iOS/osx burmese font: https://mapzen.com/tangram/view/?api=16/898#17.64030/40.74470/-73.99149
3. The mysterious ES errors.
