### ISSUE TITLE
FeaturePickListener not returning properties

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#1514]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Set `FeaturePickListener` on `MapController`
- Set `TouchInput.TapResponder` on `MapController` 
- Pick feature `onSingleTapConfirmed` with given x,y
- Add MapData:`mapData = mapController.addDataLayer("mz_search_result");`
- Add properties to `mapData`:
```
HashMap<String, String> properties = new HashMap<>();
properties.put("searchIndex", "1");
mapData.addPoint(point, properties);
```
- Touch search result icon

**RESULT:**

- Observe that returned properties in `FeaturePickListener` are empty

**EXPECTED RESULT:**

- Expect properties to contain `"searchIndex" : "1"`

**ENVIRONMENT:**
- Galaxy S6 Edge, Android 6.0.1
- Tangram 0.4.6 and newer
- Last working tangram version was 0.4.5

**Comment by tallytalwar** [comment]
Had a chat with @sarahlensing offline about this.

Post 0.4.5 we added the ability to pick any feature drawn on the map, and with this change `featurePickListener` was modified to work for any non-point (text) styled geometry and `labelPickListener` was added for any point(/text) styled geometry (even for MapData sources).

In the above example and in the android sdk, featurePickListener was being used with `points` styled MapData, which should work with `labelPickListener`.

We can probably discuss ideas for the sdk to provide an unified interface for this for the sdk users.
Closing this issue.
