### ISSUE TITLE
OnMapReady callback, addMarker does not work.

### ISSUE THREAD

**Issue by JunsuLime** [tangrams/tangram-es#1520]
Tangram 0.7 version error

**RESULT:**

At onMapReady() function, I write code

```java
marker = mapController.addMarker();
marker.setStylingFromString(U.clickEffectStyle);
marker.setDrawable(U.selectedCircleDrawable);
marker.setDrawOrder(0);
```

But this marker did not appear.

**ENVIRONMENT:**

Nexus 5X, Naugat 7.1.1
Tangram 0.7.0

**OTHER:**

To solve this problem I write code

```java
new Handler().postDelayed(new Runnable() {
                        @Override
                        public void run() {
                            marker = mapController.addMarker();
                            marker.setStylingFromString(U.clickEffectStyle);
                            marker.setDrawable(U.selectedCircleDrawable);
                            marker.setDrawOrder(0);
                        }
                    }, 150);
```

and It works. I think that marker can be drawn after some internal tangram task ...

**Comment by hjanetzek** [comment]
Thanks for the report! This is interesting. Don't you set any geometry on the marker, e.g. `setPoint()`?

I've tested this snippet in `onMapReady` in the demo app and it works:
```
     LngLat startPoint = new LngLat(-74.00976419448854, 40.70032700869127);
     Marker p = map.addMarker();
     p.setStylingFromPath(pointStylingPath);
     p.setPoint(startPoint);
     pointMarkers.add(p);
     map.setPosition(startPoint);
```

**Comment by JunsuLime** [comment]
I write wrong sample code on top

I write my code

```java
public Marker getMarker() {
  Marker marker = mapController.addMarker();
   marker.setStylingFromString(U.clickEffectStyle);
   marker.setDrawable(U.selectedCircleDrawable);
   marker.setDrawOrder(0);
   return marker;
}

@Override
public void onMapReady(MapController mc) {

  // ...
   Marker maker = getMaker();
   marker.setPoint(position);
}

```

and It doesn't work at onMapReady function.

MyMapView is on Fragment and ViewPager have fragment. I guess this structure causes problem. But I don't know exact cause.

At click callback or after 150 or more after onMapReady drawing marker works well, but only in onMapReady it doesn't work

**Comment by JunsuLime** [comment]
Oh I found why My code does not work!!

At onMapReady function

```java
@Override 
public void onMapReady(MapController mapController) {

  List<SceneUpdate> sceneUpdateList = new ArrayList<>();
  // add scene ...
  mapController.queueSceneUpdate(sceneUpdateList);
  mapController.applySceneUpdates();

  // draw marker, getMaker  function is same as above code
  Marker maker = getMaker();
  marker.setPoint(position);
}
```

I think that after sceneUpdate is done, map is initialized.

so I do sceneUpdate at getMapAsync() . and It works thank you

**Comment by matteblair** [comment]
Glad to hear you found a solution! You can also apply your scene updates the first time the map is loaded by passing a list of updates as the 3rd argument to `getMapAsync()`, if that simplifies your application.
