### ISSUE TITLE
can't load .pbf data from the geoserver?

### ISSUE THREAD

**Issue by shanligang** [tangrams/tangram-es#1523]
>When I used my yaml file, the following error occurred. What's the reason?
![image](https://cloud.githubusercontent.com/assets/8465913/26517726/7afdde06-42d1-11e7-9736-ab7fb89b4cbd.png)

**Comment by matteblair** [comment]
Are you trying to load image files in a PDF format? PDF isn't a supported image file format, use JPEG, PNG, GIF, or TGA instead.

That said, the error message here doesn't look like the format is unsupported, it looks like the file can't be accessed for some reason. Can you share any more information about your scene file or the URLs you are trying to access?

**Comment by shanligang** [comment]
Sorry, this is my spelling mistake. It's PBF format, not pdf.The data is published by Geosever. 
For example  
  https://shanligang.github.io/geoserverdata/{z}/{x}/{y}.pbf
the center point of data is  LngLat(119.97213043325388, 30.543462384495687); There only  twelfth levels of data in area.

**Comment by shanligang** [comment]
I found my mistake on the scene file.Thank You very mach! @matteblair
