### ISSUE TITLE
iOS(swift) - Rotation Gesture about Compass

### ISSUE THREAD

**Issue by seubseub** [tangrams/tangram-es#1524]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
I'm trying to make compass Btn.
I set gesturedelegate.
```
self.gestureDelegate = self
```
and about transform code is Here
```
func mapView(_ view: TGMapViewController, recognizer: UIGestureRecognizer, shouldRecognizeRotationGesture location: CGPoint) -> Bool{
        DispatchQueue.main.async {
            self.compassBtn.transform = CGAffineTransform(rotationAngle: CGFloat(self.rotation))
            self.layoutAboutCompassBtn() // This code is set compassBtn's frame.
        }
        return true
    }
```
and compassButton rotate like 3D.
How I can fix at 2D?

and if I delete about self.layoutAboutCompassBtn() which is about setting compassBtn's frame.
rotation is okay. but when I move compass button, then compass button is weird.
like this.
<img width="184" alt="2017-05-29 5 55 01" src="https://cloud.githubusercontent.com/assets/16539714/26543559/61ab1a1c-4499-11e7-818a-fa9de12c515b.png">

**RESULT:**
This picture is compass button that not rotate.
<img width="213" alt="2017-05-29 5 54 50" src="https://cloud.githubusercontent.com/assets/16539714/26543565/6bb907e4-4499-11e7-842f-52b46aaca57c.png">

and this picture is rotated picture.
<img width="184" alt="2017-05-29 5 55 01" src="https://cloud.githubusercontent.com/assets/16539714/26543607/892f3f96-4499-11e7-9062-4e7da85dd009.png">

I just want rotate compass button 2D, but It rotate like 3D.

**EXPECTED RESULT:**
not 3D just rotate compass button 2D.

**ENVIRONMENT:**

operating system : 
OS : Sierra version : 10.12.5
device : iPhone6s.
I use tangram-es version 0.6.2 in cocoa pods

**OTHER:**
I really thank you for your library lol :).
Could you solve my problem?

**Comment by karimnaaji** [comment]
Hey @seubseub!

This kind of feature is out of the scope of Tangram, but we have a higher level [SDK](https://github.com/mapzen/ios/) where you might want to open an issue for a feature request for support of a compass similar to you what you need here. (cc @msmollin)

Concerning your specific problem, I am quite unsure of what happens in `layoutAboutCompassBtn` that could interfere with your transform? I don't see any wrong usage of `CGAffineTransform` here after looking at https://developer.apple.com/reference/coregraphics/cgaffinetransform/1455666-init. Maybe you can also explain the need of `DispatchQueue.main.async` in the callback, I am not sure that this is necessary.

**Comment by seubseub** [comment]
@karimnaaji yes I thought that this may be out of the scope of Tangram too. I apologize for my issue. sorry. 

About ```DispatchQueue.main.async```,  I thought that maybe your callback is not ui thread like my previous issue about mapData.clear() #1445, which don't do in main thread.  but I tried without ```DispatchQueue.main.async```, It works well. I'll delete them :).

About ```layoutAboutCompassBtn``` : It just set compassBtn's frame again. like  ```self.compassBtn.frame = CGRect(x: x, y:  y, width: width, height:height)```

and transform works well. but when I just move button's y value, button's appearance is weird like my picture that I uploaded. 

Maybe My mistake... I'll try again. Thank you for kind reply.  👍

**Comment by seubseub** [comment]
@karimnaaji I solve problems. thank's for your help. I rotate my compass. so I change transform to layer transform. like

```
self.compassBtn.transform = CGAffineTransform(rotationAngle: CGFloat(self.rotation))
```
to
```
self.compassBtn.layer.transform = CATransform3DMakeRotation(CGFloat(self.rotation), 0, 0, 1.0)
```
then It works like a charm! Thank you!

**Comment by karimnaaji** [comment]
Glad it worked out :)

Concerning `DispatchQueue.main.async`, this is indeed not required on our callbacks since all of them are already called from the main thread.
