### ISSUE TITLE
Proper way to handle Markers on Scene Update

### ISSUE THREAD

**Issue by ac87** [tangrams/tangram-es#1525]
I've updated to the latest version and now have the change to fix #1464, so if the scene changes all markers are invalidated/removed, subsequently my test app now crashes toggling raster/vector.

I see the comment from @tallytalwar "document the behavior such that the user handles readding of any marker in the asyncSceneLoad/Update callback."

Before I make my own events to update all markers, does this callback not yet exist (in Android)? or am I looking in the wrong place?

**Comment by hjanetzek** [comment]
Hi @ac87, thanks for the report! There is indeed no good way to recreate markers on scene updates at the moment. I'll look into this now.

**Comment by hjanetzek** [comment]
It probably works if you set a `ViewCompleteListener` after the call to `applySceneUpdates` like this
```
mapController.setViewCompleteListener(new ViewCompleteListener() {
   mapController.removeAllMarkers();
   ... recreate markers ...
});

**Comment by ac87** [comment]
The 0.8.0 update for this is working well for me thanks.

One subtle additional change (in case anyone else was using it) was where I was previously advised to use something like:
 
```
mapController.queueEvent(reloadRunnable);
 
private Runnable reloadRunnable = new Runnable() {
        @Override
        public void run() {
            mapController.loadSceneFile(getBaseScene(isVector), getSceneUpdates());
        }
    };
```

This queuing to the mapcontroller is no longer required and if left in causes concurrent modification exceptions, the scene can now be loaded directly without the queue.
