### ISSUE TITLE
Line breaks are not honoured in labels on Android

### ISSUE THREAD

**Issue by Teester** [tangrams/tangram-es#1529]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Using the Cinnabar style with the following modifications:
  - `text_visible_building: true    # false for default`
  - `text_visible_address: true`

**RESULT:**

In cinnabar, the label is computed as 'name \n number' (Derryveigh\n25' in this case) The '\n' in the label is ignored.
StreetComplete produces:

![screenshot_20170601-014624](https://cloud.githubusercontent.com/assets/13661397/26659973/cfc1afe6-466c-11e7-96b5-3bf52afc23d6.png)

**EXPECTED RESULT:**

The building label is displayed as expected.
Tangram Play produces:

![screenshot from 2017-06-01 01-38-53](https://cloud.githubusercontent.com/assets/13661397/26659771/311171f2-466b-11e7-91e0-7a7ebade8b6c.png)

**ENVIRONMENT:**

 - Android 5.1 on a Nexus 4 using the StreetComplete app (https://github.com/westnordost/StreetComplete) with a modified cinnabar style. The app is using tangram-es 0.6.3.

**OTHER:**

I've used the same version of cinnabar in StreetComplete (modified from the release version) and Tangram Play

**Comment by nvkelso** [comment]
Looks like this is also a problem in our Mapzen iOS SDK demo app.
