### ISSUE TITLE
Compile only the library - CMake

### ISSUE THREAD

**Issue by MyZeD** [tangrams/tangram-es#1535]
Great work from you!

Can you provide a variable in CMake, so you do not have to compile the demo, but only the library with?

**Comment by matteblair** [comment]
You can probably already do this (depending on what you mean by "library").

The Linux and OSX targets check a CMake variable called `APPLICATION`. When `APPLICATION` is false, only the core library will be built. (https://github.com/tangrams/tangram-es/blob/master/toolchains/darwin.cmake#L17).

For Android, we consider the "library" to be the AAR for the Tangram Android SDK. You can build this by invoking the `tangram` target explicitly in Gradle: `gradlew tangram:assembleDebug`

For iOS, the "library" is the TangramMap Framework. This is built with `make ios-framework-universal`.

This is probably more complicated than expected - but did I answer your question?

**Comment by MyZeD** [comment]
yes, very nice!
Thank you very much :)

I'm very sorry about the circumstances.
