### ISSUE TITLE
Proguard for Android

### ISSUE THREAD

**Issue by placz** [tangrams/tangram-es#1537]
It would be nice to have a maintained proguard file for release builds on android that is updated when https://github.com/tangrams/tangram-es/blob/master/platforms/android/tangram/src/main/cpp/platform_android.cpp changes.

Here is the configuration I've been using: [proguard-tangram.txt](https://github.com/tangrams/tangram-es/files/1078429/proguard-tangram.txt)

**Comment by matteblair** [comment]
Hi @placz thanks for the suggestion! I don't have much experience using proguard, can you help me understand what proguard enables for a library project like Tangram ES?

**Comment by tallytalwar** [comment]
cc. @sarahlensing for opinions.

**Comment by placz** [comment]
Sure,
People use proguard to minimize and obfuscate the code that gets packaged in an android app. It usually used only for release builds because it's slow to execute in every build but it also renames everything. The rules tell it what's not okay to throw away or rename.

Since JNI uses those names to reference classes, they can't be renamed. You also need to tell it that some of the methods are actually used otherwise it might strip away that code.

Here are a couple references for more reading:
  - [Shrinking your release build with proguard](https://developer.android.com/studio/build/shrink-code.html)
  - [Android library documentation](https://developer.android.com/studio/projects/android-library.html) has some comments specifically about how to distribute proguard files with libraries.

**Comment by placz** [comment]
I just re-read your question and probably didn't answer it quite right -- packaging the proguard file along with the library just makes client devs' life easier. We don't need to be digging into the code to figure out the right configuration (or have to watch for changes that would break it).

**Comment by sarahlensing** [comment]
I think its reasonable to include proguard recommendations. Updating the Android README should be sufficient. Square uses this approach
https://github.com/square/wire

**Comment by matteblair** [comment]
Oh I see! This makes sense to me - a user of the library should be able to apply proguard without understanding the JNI interactions we use.

It seems easiest solution for users is for us to embed a proguard file in the AAR of the library. According to the [docs](https://developer.android.com/studio/projects/android-library.html#Considerations) we just need to:
 - Add a proguard.txt for the Tangram Android library project
 - Specify the proguard file location in the library build, e.g.
```
android {
    defaultConfig {
        consumerProguardFiles 'tangram-proguard-rules.txt'
    }
    ...
}
```

**Comment by placz** [comment]
I'd definitely prefer what Matt proposed, but either's fine as long as it's updated.. I filed this after having to dig through the code and update the rules I just sent (I had procrastinated upgrading for a while). It's probably worth noting that Tangram-es doesn't work out-of-the-box when enabling proguard.

**Comment by msmollin** [comment]
FWIW @sarahlensing pointed out that Jake Wharton recently noted pretty blatantly that library managers should leave Proguard implementation to end users and provide recommendations via documentation (he works at Square, so that's probably why they do that):
https://twitter.com/JakeWharton/status/876530803420917761
https://twitter.com/JakeWharton/status/876541923036733442

If you take a look at Google Play Services for example, they are *very* "keepy" to avoid Proguard interfering with the code execution, and I imagine for good reasons.

**Comment by matteblair** [comment]
Thanks for pointing that out, I imagine it's pretty easy to be overly zealous with proguard options. In our case though, I still feel that it makes sense to include proguard rules as part of the library. 

Proguard is fundamentally a Java tool and it's unable to reason about interactions through JNI, which we leverage for nearly every behavior in the library. If a user were to apply a typical proguard configuration to tangram, the symbol names needed by our JNI code would fail _at run-time_ in confusing ways. Preserving our JNI behavior is essential to the function of the library, so I feel that a proguard configuration to achieve that is also essential.
