### ISSUE TITLE
Allow customization of request headers in HttpHandler

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#1542]
Currently there isn't a way to add custom request headers in `HttpHandler` subclasses because the underlying http client is private. The Android SDK will need this ability when implementing https://github.com/mapzen/android/issues/382 and EM relies on the ability to customize headers when adding the "do not track" header https://github.com/mapzen/eraser-map/blob/master/app/src/main/kotlin/com/mapzen/erasermap/model/TileHttpHandler.kt#L19

I propose adding a header `Map` parameter to `onRequest` and updating the implementation to construct a `Request` using this map:

```
public boolean onRequest(String url, Map<String, String> headers, Callback cb) {
  Request request = new Request.Builder()
    .url(url)
    .headers(Headers.of(headers))
    .build();
  okClient.newCall(request).enqueue(cb);
  return true;
}
```

**Comment by matteblair** [comment]
We could also just make the HTTP client member `protected` to allow access for subclasses. This would enable header customization as well as any future tweaks that we might want for URL requests. Do you see major downsides to that approach @sarahlensing?

**Comment by sarahlensing** [comment]
@matteblair I can't think of any, I think that is a fine way forward.

**Comment by msmollin** [comment]
FWIW on iOS I just exposed the underlying NSURLSession HTTP Headers object (mostly because I hadn't seen this thread) - https://github.com/tangrams/tangram-es/pull/1578 

It would be easier to also expose the NSURLSession `session` object to the Obj-c subclasses so this could be modified as well. If that's the path we're set on, I can make that change as well.

**Comment by tallytalwar** [comment]
Closing this as https://github.com/tangrams/tangram-es/pull/1587 takes care of providing some flexibility to extend HttpHandler to customize headers.
