### ISSUE TITLE
Support for zipped MVT tiles

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#1552]
I was able to use mbtiles created with this tool https://github.com/tilezen/tilepacks in Tangram ES. However I noticed that it produces a big files when trying to download 15 and 16 max zooms so I tried to zip that mbtiles and it reduced theirs size by 50%. Then I had a look wheter MVT inside mbtiles can be zipped and if Tangram ES can unzip zipped MVT tiles and I found this issue: https://github.com/tangrams/tangram-es/pull/1343 . But as I had a look into Tangram ES code I didn't find anywhere part which is unzipping zipped MVT tiles. Is unzipping zipped MVT tiles possible in Tangram ES? If not are you considering add such feature, because it will be a huge help for using mbtiles offline.

Also this is question for another repository maybe but is it also possible for your tile servers to serve zipped MVT tiles? Can also https://github.com/tilezen/tilepacks tool add zipped MVT tiles into mbtiles?

Thank you.

**Comment by nvkelso** [comment]
We support zoom 15 max tiles now, I recommend this for offline packs.

Like:

https://tile.mapzen.com/mapzen/vector/v1/{256,512}/all/{z}/{x}/{y}.mvt

**Comment by rwrx** [comment]
Thank you, but I am not sure if I understand correctly what do you mean by "zoom 15 max tiles". It means that when I replace that {z} parameter with 16 and higher zooms that it will still serve only tiles from 15 zoom level? 

Also I am not sure what that {256,512} parameter means? These are vector tiles, I understand why this is important for raster tiles, but for vector tiles it means that vector geometry will be less accurate when using 256?

Is that tile.mapzen.com endpoint able to zip that mvt tiles, or it should be done by client for example from inside of that Tile packs tool? Because if it is meant to zip that mvt tiles in Tile packs tool I think that it will be simple to add zipping functionality into it. I can do this also by myself and then maybe do pull request?

**Comment by matteblair** [comment]
Regarding zip-compressed MVT tiles in an MBTiles database: Tangram ES actually supports the proposed MBTiles 2.0 specification, which includes a key describing the compression of the database contents (https://github.com/pnorman/mbtiles-spec/blob/39d9b0b4c253649ec7ffd7f93f6adb9b325be4cd/2.0/spec.md#content). Therefore, if you compress your MVT tiles with zip and specify `deflate` for the `compression` key in the database, Tangram ES will be able to extract the tiles correctly. 

Does that answer your question?

**Comment by nvkelso** [comment]
_... Monday and a desktop computer will help clarify this ;)_

The Tangram JS [v0.13 release notes](https://github.com/tangrams/tangram/releases/tag/v0.13.0) have some more detail:

The URL pattern `{256,512}` indicates that either of those values is valid in the path, in your case you'd want to use `512`. 

Because of the way the larger 512px tiles are built on the server, a zoom 15 sized 512px tile has all the content the 4 children 256px tiles have – so for offline cases you only need to request a source `max_zoom` of 15 instead of the usual 16 to get all the content – which will substantially reduce the number of tiles and overall file size.

```
sources:
   mapzen:
      url: https://tile.mapzen.com/mapzen/vector/v1/512/all/{z}/{x}/{y}.mvt
      type: mvt
      tile_size: 512
      max_zoom: 15
```

I don't think https://github.com/tilezen/tilepacks doesn't currently internally ZIPs individual MVT tiles as they are added to the overall tile pack. I've added a tracking issue in https://github.com/tangrams/tangram-es/issues/1552#issuecomment-310866480 for this.

**Comment by rwrx** [comment]
Thank you a lot for your answers. I was able to modify Tile Packs code to deflate individual tiles and also Tangram ES was correctly inflating them and then rendering them.

Thank you also for explaining hat tile size, so I have used 512 and limited max zoom to 15 in style yaml file.

Also maybe I can do pull request to Tile Packs repository, but I have changed that builder.py code a bit also to download normal tiles.

I am closing this issue.

**Comment by nvkelso** [comment]
@rwrx Glad you got it working! Yes, please file a PR on Tile Packs repo, we can continue the discussion there :)

**Comment by Buthrakaur** [comment]
Hi @rwrx , could you post sample MBTiles file + scene file which works for you, please? I'm struggling with MBTiles offline usage on Android (https://github.com/tangrams/tangram-es/issues/1555) and didn't find any working example nor working combination of MBTiles + scene file.
