### ISSUE TITLE
Fallback to lower zoom levels

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#1553]
I was playing a little bit with mbtiles and one improved came into my mind. One of my testing scenarios was that I had mbtiles file with 0 - 6 zooms for whole world. When my app started zoomed to let's say 10 zoom level it won't show any tile until I zoom out to 6 zoom level. Then it is able to fetch 6 zoom level and when I zoom again to 10 zoom level it will still show that tile from 6 zoom level. 

As an user this seems to me as strange behavior. As developer I understand why is this happening, but for user this is strange I think. 

Is it possible to add fallback to fetch tiles from lower zoom levels when map is zoomed that much that mbtiles doesn't contain appropriate tiles? So it will serve tile from lower zoom level. From using of Google Maps it seems to me that they are doing fallback to tiles from lower zoom levels when tiles from higher zoom levels are not available.

**Comment by hjanetzek** [comment]
Hi @rwrx, you can set the maximal zoom that should be loaded by a tile source with `max_zoom` parameter. 

It's a good idea to try lower zoom-level tiles when a tile fails to load. This could be useful when mbtiles contains the whole world at low zoom and some small area at high zoom-level

**Comment by rwrx** [comment]
Thank you. Yes, I am aware of max_zoom parameter but it does not work in this scenario because I need to have max_zoom set at least to 15 but mbtiles file may contain only tiles for zoom 6 for example.

I can add code for trying lower zoom-level tiles and maybe create pull request. Or would rather somebody from Tangram ES team do this?

**Comment by rwrx** [comment]
@hjanetzek Firstly I have tried to add trying lower zoom-levels into `MBTilesDataSource::loadTileData()` method when `MBTilesDataSource::getTileData()` fails to load. But it is somehow needed to properly cut tile from lower zoom-level to fit this tile correctly. Is this possible? Also then I tried to add this fallback into `TileManager` class, but I am not sure how to do this correctly without much changing code. It seems to me that this couldn't be simply added due to code architecture. How this could be done? Thank you!

**Comment by rwrx** [comment]
I haven't tried to add fallback already, but now I have some time to do it. Is it possible to give me some advice how this could be done effectively? As I didn't digged deeply into tile rendering architecture in Tangram-ES but as I have looked into it previously it seemed to me that currently from architectural point of view this cannot be done without changing architecture a bit. Am I right?

**Comment by rwrx** [comment]
Will move discussion here: https://github.com/tangrams/tangram-es/pull/1626
