### ISSUE TITLE
Unable to display offline map from OSM extracts (MBTiles) on Android

### ISSUE THREAD

**Issue by Buthrakaur** [tangrams/tangram-es#1555]
- I'm trying to open offline map from MBTiles file downloaded from https://openmaptiles.org/downloads/#city
- I tried to understand what's the right approach to load the map and define scene file in https://github.com/tangrams/tangram-es/issues/1544 + https://github.com/tangrams/tangram-es/issues/1309 , but didn't succeeded
- I ensured the app has `READ_EXTERNAL_STORAGE` permission
- my scene file (used asset file):
```
global:
    sdk_mapzen_api_key: ''

sources:
    offline:
        type: MVT
        url: file:///storage/emulated/0/Download/new-york_new-york.mbtiles
        max_zoom: 14

layers:
    landcover:
        data: { source: offline }
    landuse:
        data: { source: offline }
    transportation:
        data: { source: offline }
```

**RESULT:**

Black screen:
![image](https://user-images.githubusercontent.com/126757/27585787-e692edda-5b3d-11e7-9599-8c8243059f48.png)

Log file doesn't show any error:
```
06-27 11:34:15.909 20352-20352/com.mapzen.tangram.android D/Tangram: TANGRAM tangram.cpp:187: Loading scene file: asset:///my.yaml
06-27 11:34:15.917 20352-20352/com.mapzen.tangram.android D/Tangram: TANGRAM mbtilesDataSource.cpp:251: SQLite database opened: /storage/emulated/0/Download/new-york_new-york.mbtiles
06-27 11:34:15.926 20352-20352/com.mapzen.tangram.android D/Tangram: NOTIFY tileManager.cpp:53: Remove source osm
06-27 11:34:15.929 20352-20352/com.mapzen.tangram.android D/Tangram: NOTIFY tileManager.cpp:72: add source offline
06-27 11:34:15.943 20352-20382/com.mapzen.tangram.android D/EGL_emulation: eglMakeCurrent: 0x9f7b0d60: ver 2 0 (tinfo 0xa141d5e0)
06-27 11:34:15.944 20352-20352/com.mapzen.tangram.android W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
06-27 11:34:15.945 20352-20352/com.mapzen.tangram.android W/IInputConnectionWrapper: requestCursorAnchorInfo on inactive InputConnection
06-27 11:34:15.946 20352-20352/com.mapzen.tangram.android W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
06-27 11:34:15.946 20352-20352/com.mapzen.tangram.android W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
06-27 11:34:15.947 20352-20352/com.mapzen.tangram.android W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
06-27 11:34:15.950 20352-20398/com.mapzen.tangram.android D/Tangram: TANGRAM tileWorker.cpp:51: Passed new TileBuilder to TileWorker
06-27 11:34:15.950 20352-20352/com.mapzen.tangram.android W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
06-27 11:34:15.954 20352-20352/com.mapzen.tangram.android W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
06-27 11:34:15.956 20352-20352/com.mapzen.tangram.android W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
06-27 11:34:15.957 20352-20389/com.mapzen.tangram.android D/Tangram: TANGRAM tileWorker.cpp:51: Passed new TileBuilder to TileWorker
06-27 11:34:15.982 20352-20715/com.mapzen.tangram.android D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 4823/6160/14/14, 159525
06-27 11:34:15.995 20352-20715/com.mapzen.tangram.android D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 4824/6160/14/14, 169355
06-27 11:34:16.016 20352-20715/com.mapzen.tangram.android D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 4823/6161/14/14, 39673
06-27 11:34:16.060 20352-20715/com.mapzen.tangram.android D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 4823/6159/14/14, 142265
06-27 11:34:16.082 20352-20715/com.mapzen.tangram.android D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 4824/6161/14/14, 375304
06-27 11:34:16.109 20352-20715/com.mapzen.tangram.android D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 4824/6159/14/14, 449546
06-27 11:34:16.246 20352-20352/com.mapzen.tangram.android D/Tangram: View complete
```

**EXPECTED RESULT:**

I expect map to render from local MBTiles file.

**ENVIRONMENT:**

- Android, `compile 'com.mapzen.tangram:tangram:0.7.1'`

**OTHER:**

I guess this could be caused by problem with my scene file, but how should the scene file look like for OSM extracts? I looked into the MBTiles DB file `metadata` and it contains `json` field with list of layers contained in the DB so I use this for my scene file, but I may be doing some dummy mistake, because I'm total mapzen noob :)

![image](https://user-images.githubusercontent.com/126757/27585908-568e5962-5b3e-11e7-9862-e318c3404ebb.png)

**Comment by Buthrakaur** [comment]
Another question is how do I recognize which format is stored in the MBTiles DB file - I looked into table `images.tile_data` and it contains some binary data so I guess it's MVT? Would there be plain text JSON in case of Topo/GeoJSON format instead of the binary data?

**Comment by nvkelso** [comment]
OpenMapTiles has a different layer name and feature property schema than
the Tilezen schema that Mapzen vector tiles (and Mapzen basemaps) and the
other source can’t be used interchangeably.

**Comment by Buthrakaur** [comment]
@nvkelso thanks for explanation. So do I understand it right it's entirely not possible to render maps using OSM Extracts MBTiles format (it's not MVT nor GeoJson nor TopoJson, but some other format)? Or is it just necessary to specify correct scene file to get it working?

**Comment by Buthrakaur** [comment]
I just tried to create GeoJSON MBTiles file (downloaded Metro Extract GeoJSON file with OSM layers and convert it to MBTiles DB using Mapbox Studio Classic) and display it using https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap-style-more-labels.yaml scene file, but still no success:
```
06-28 09:15:05.504 824-868/com.mapzen.tangram.android D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 807/473/10/10, 102318
06-28 09:15:05.504 824-866/com.mapzen.tangram.android D/Tangram: ERROR geoJson.cpp:173: Json parsing failed on tile [807/473/10/10]: Invalid value. (0)
```

Is there any recommended approach how to get MBTiles data files compatible with Tangram-ES renderer? I feel like reinventing the wheel :/

**Comment by Buthrakaur** [comment]
I tried to convert the Metro Extract GeoJSON data files using tippecanoe, but result is still the same.

```
06-28 09:39:26.051 22243-22264/com.mapzen.tangram.android D/Tangram: WARNING mbtilesDataSource.cpp:159: loaded tile: 808/473/10/10, 1279
06-28 09:39:26.052 22243-22263/com.mapzen.tangram.android D/Tangram: ERROR geoJson.cpp:173: Json parsing failed on tile [808/473/10/10]: Invalid value. (0)
```

**Comment by rwrx** [comment]
Hello, I get working MBTiles in Tangram ES. Firstly you need to modify yaml style sources like this for example:

sources:
    mapzen:
        type:  MVT
        url:  file:///storage/emulated/0/bratislava_center_z15.mbtiles
        tile_size: 512
        max_zoom: 15

Basically you need to set url to MBTiles file path on your device's external storage to which your App has READ permission (I am not sure about WRITE permission, I am using both). You need to use file:// schema and set correct path to your MBTiles file in external storage. I have also set tile_size to 512 and max_zoom to 15 as it was recommended to me here: https://github.com/tangrams/tangram-es/issues/1552#issuecomment-311106730 .

I can provide you one of MBTiles file which I created using this tool: https://github.com/tilezen/tilepacks . With this tool you can create MBTiles with proper schema for Tangram ES. You also need Mapzen API key to download tiles. But don't use it very extensively. Here you can download one of MBTiles which I created with this tool and which is working in Tangram ES: https://www.dropbox.com/s/je87awxhwoe3eyz/bratislava_center_z15.mbtiles?dl=0 .

**Comment by Buthrakaur** [comment]
@rwrx thanks a lot for help - it really works with your file. I guess you produced the file with modified tilepacks source code to get appropriate tiles for `tile_size: 512`? A question to the scene file - I used https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap-style-more-labels.yaml , but get error `style.cpp:428: Mesh built by style building-grid cannot be drawn` and little bit strange map image rendered:
![image](https://user-images.githubusercontent.com/126757/27677536-60520ff0-5cb2-11e7-84c0-0e1cba1fd73e.png)

Do you get simmilar experience or do you use a different scene file which works flawlessly?

**Comment by Buthrakaur** [comment]
I just tried cinnabar style (https://github.com/tangrams/cinnabar-style-more-labels) and it doesn't report any warning and the map looks much better so forget the last question :)

**Comment by klokan** [comment]
BTW - if you want to use OpenMapTiles tiles with Tangram - we have a very basic style under the tab "Tangram" at https://openmaptiles.org/viewers/ - to start with.

The style is stored on GitHub at:
https://github.com/openmaptiles/www.openmaptiles.org/blob/master/js/tangram-style.yaml
https://github.com/openmaptiles/www.openmaptiles.org/blob/master/js/viewers.js#L86

It would be great to improve the sample Tangram style for OpenMapTiles tiles... 
I would be glad to help anybody who want's to play with this...

**Comment by rwrx** [comment]
@Buthrakaur Yes, I have produced that MBTiles file with modified Tile packs. I have also created pull request with these modifications here: https://github.com/tilezen/tilepacks/pull/7 .  I have tried all Mapzen house styles and they were shown properly as I tested them. However I didn't look at logs.

**Comment by Buthrakaur** [comment]
@klokan thanks for the link - will try it. On the other hand I think the most usable feature at the moment would be to display offline map from MBTiles file generated from Mapzen Metro Extracts, because it even allows to produce custom area extracts, which is not possible to do in https://openmaptiles.org/downloads/. I wasn't able to get the GeoJson MBTiles working unfortunately (tried tippecanoe and Mapbox Studio Classic export) :(

**Comment by Buthrakaur** [comment]
Closing the issue as https://github.com/tangrams/tangram-es/issues/1555#issuecomment-311911442 answers the primary question.

**Comment by klokan** [comment]
You can make a vector tiles extract for a custom area here:
https://openmaptiles.com/extracts/

If you want to generate the OpenMapTiles vector tiles yourself with our open-source code - for example from the Mapzen Metro Extracts or Geofabrick extracts - follow the guide at:
https://openmaptiles.org/docs/ (section Generate Vector Tiles).
