### ISSUE TITLE
Smart Marker Zoom

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#1556]
Tangram-es should provide a "smart zoom" utility given an arbitrary set of markers (points, lines, polygons) that can compute the optimal map position and zoom level so all markers are visible in the viewport.

Currently this requires lots of math on behalf of the developer to calculate this using coordinates and screen size. See this example in Eraser Map in the method `MainActivity.zoomToShowRoute(...)` implemented by @matteblair using an `AxisAlignedBoundingBox`.

https://github.com/mapzen/eraser-map/blob/master/app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt#L801-L854

This is a feature we will want to implement in both Android and iOS so it may be a good candidate to be written in a way that can be used cross-platform

https://github.com/mapzen/android/issues/250

cc/ @msmollin

**Comment by matteblair** [comment]
This has been addressed with new interfaces for both iOS and Android. On Android we now have 
```java
public CameraPosition getEnclosingCameraPosition(@NonNull LngLat sw, @NonNull LngLat ne, @NonNull Rect padding)
```
https://github.com/tangrams/tangram-es/blob/master/platforms/android/tangram/src/main/java/com/mapzen/tangram/MapController.java#L574

And while the client application still has to calculate a bounding box of the target feature(s) I think this takes care of the hard parts of determining this kind of view. Closing this issue!
