### ISSUE TITLE
Feature: Display own data on map

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1565]
**User Story**
Imagine the following, probably very common, use case:
I have some geospatial data that I need to display on top of the normal tangram map. There are many maps like this on the web, they often show their data in clusters on lower zoom levels. For sake of example, let's say I want to display openstreetmap notes on the map.
Using `myLayer.addGeoJson` is not really eligible because the data can change - the user can add notes or resolve notes (and because there may be lots of data). The marker interface is also not suitable because there is lots of data.

Another method is necessary. However, I think with offline MBTiles support, you guys are very close to support this use case. With the following necessary changes / added features:

**Requirements**
- It must be possible to define MBTile data only for a few certain (or: one) zoom levels. The rendering engine should be able to handle this ("interleave tiles") and/or automatically cluster the data. But clustering aside, it would be easiest for the library user to simply put the openstreetmap notes into tiles for one zoom level, let's say 14, and beginning at this zoom level, the notes should always be visible
- It must be possible to add a MBTile data source programmatically by specifying a file handle directly, not a path. Reason: If a MBTile data source is going to be loaded from disk, the app would need file system read access
- It must be possible to invalidate the currently viewed map section when changes of the map data occured (the app modified the database)

**Comment by westnordost** [comment]
I just noticed for point 1, there is already a ticket: #1553

**Comment by westnordost** [comment]
I noticed point 2 is not necessary, since files can be put into the application's internal directory.

**Comment by rugk** [comment]
Any news here?

**Comment by placz** [comment]
I think all of this is already supported functionality:

For your first requirement, just use max_zoom: in the parameters (max zoom gives the maximum that the data source provides)
For the second requirement, you can change the path programmatically using a scene update (I posted a [blog post](https://medium.com/afield-trails/behind-our-maps-mapzen-tangram-7f2c17fc0154) about this a bit ago.. pretty straight-forward.)
For your last point, you'll have to reload the scene, but I think that's also pretty straight forward. A different approach you could take is use the addDataLayer functions. That would probably work more smoothly if your data is changing a lot.

**Comment by rugk** [comment]
Hmm… it has been more than a year since this had been opened and there is still no official statement on this.
And the lack of this feature causes a reoccuring issue in SC.

**Comment by westnordost** [comment]
Well it is kind of better possible now and there are some other PRs / Issues about it, so I am closing this.
