### ISSUE TITLE
Lines outline on one side 

### ISSUE THREAD

**Issue by kdebowski** [tangrams/tangram-es#1567]
Is it possible to draw line with outline only on one side (left/right or call it inside/outside)? I was looking for some solution/inspiration in docs but couldn't come up with anything valuable. I was also thinking about mixing lines and polygon inside, but as before, nothing came to my mind.

Example:

![outline](https://user-images.githubusercontent.com/2165223/28163190-5e86e9ac-67ca-11e7-9d5a-b7e357135786.png)

**Comment by matteblair** [comment]
Hi @kdebowski! Currently there is no mechanism to explicitly outline only one side of a polyline. This is mostly because it is difficult to know the orientation of polylines without manually inspecting the source data ("left" and "right" can only be determined from the ordering of the points in the polyline).

One case where this is less ambiguous is the polylines that comprise polygons - for those an "inside" and "outside" is clear just from visual inspection. For polygons, you can get the visual result you're describing by adding an outline to the polygon and then filling the polygon with the same color as the background.

Another option to achieve this effect would be to create a new style for your scene that uses custom GLSL to render these polylines. If you're interested in this option I can find sample code to show you.

**Comment by kdebowski** [comment]
@matteblair Thank you for your answer. I would be grateful if you could provide some examples using GLSL shaders.

**Comment by Guillaume227** [comment]
@kdebowski for your inspiration, the following snippet will be drawing a line only on one side (the right side). I hope this helps !

``` 
styles:
  half_side_line:
        base: lines
        texcoords: true
        draw:
           color: blue
           width: .6

        shaders:
          blocks:
            global: |
              float right_side(float x){
                  if (x>0.51) return 1.0;
                  return 0.0;
              }
            color: color.a *= right_side(v_texcoord.x);
 ```

**Comment by nvkelso** [comment]
We use this technique in the Walkabout bike map overlay to show which side of the street a bike lane is located:

- https://github.com/tangrams/walkabout-style/blob/gh-pages/layers/bike-interlay.yaml#L2233-L2249

See it in action:

- http://tangrams.github.io/walkabout-style/#17/37.77382/-122.43736

<img width="774" alt="screen shot 2017-07-17 at 09 29 50" src="https://user-images.githubusercontent.com/853051/28278613-8aebac0c-6ad2-11e7-8446-433630dc7b39.png">

**Comment by kdebowski** [comment]
@Guillaume227 @nvkelso thank you for your examples. They work great, but... There might be some issue with tangram generating lines. What I mean is: 

If you have geojson data saved as LineString (ie. [geojson.io](http://geojson.io/#data=data:application/json,%20{%22type%22:%20%22FeatureCollection%22,%22features%22:%20[{%22type%22:%20%22Feature%22,%22properties%22:%20{},%22geometry%22:%20{%22type%22:%20%22LineString%22,%22coordinates%22:%20[[11.633332999999993,52.543056],[11.708333333333343,52.45],[11.625,52.4125],[11.609722000000005,52.35],[11.538889000000012,52.277778],[11.461110999999988,52.277778],[11.422222000000005,52.3],[11.5,52.42916666666667],[11.466666666666669,52.520833333333336],[11.633332999999993,52.543056]]}}]}) ) your solutions work fine, There is only little problem with closing object (I've tried cap, join, miter_limit and other parameters but they didn't work for me). 

![geojson](https://user-images.githubusercontent.com/2165223/28313929-ec6f58ac-6bb8-11e7-8774-11d96e3943df.png)

But if you have data type set as 'Polygon' (ie. [geojson.io](http://geojson.io/#data=data:application/json,%7B%22type%22%3A%22FeatureCollection%22%2C%22features%22%3A%5B%7B%22type%22%3A%22Feature%22%2C%22properties%22%3A%7B%7D%2C%22geometry%22%3A%7B%22type%22%3A%22Polygon%22%2C%22coordinates%22%3A%5B%5B%5B11.633332999999993%2C52.543056%5D%2C%5B11.708333333333343%2C52.45%5D%2C%5B11.625%2C52.4125%5D%2C%5B11.609722000000005%2C52.35%5D%2C%5B11.538889000000012%2C52.277778%5D%2C%5B11.461110999999988%2C52.277778%5D%2C%5B11.422222000000005%2C52.3%5D%2C%5B11.5%2C52.42916666666667%5D%2C%5B11.466666666666669%2C52.520833333333336%5D%2C%5B11.633332999999993%2C52.543056%5D%5D%5D%7D%7D%5D%7D) ) and want to draw lines from polygonal data, it looks like that:

![geojson2](https://user-images.githubusercontent.com/2165223/28313938-f20f25f8-6bb8-11e7-8286-4b863bb73b62.png)

It looks like the lines are incorrectly generated from polygonal data - there are some duplicates. Some lines have triangular endings.

**Comment by nvkelso** [comment]
I think there is a Tangram bug with transparency, @meetar might know more.

In the meantime, try turning transparency off and picking an RGB color instead (of RGBA).

For the lines, you can also extend the cap to hide the bad corner join.

**Comment by tallytalwar** [comment]
I am closing this issue as the original issue is answered here and inactivity for further issue(s).

Kindly open a new issue if you are still experiencing the issue(s)
