### ISSUE TITLE
MarkerPickResult is always null in onMarkerPick on Android

### ISSUE THREAD

**Issue by Buthrakaur** [tangrams/tangram-es#1568]
I'm trying to add a listener for marker picked event, but I never get proper `MarkerPickResult` instance in the `onMarkerPick` callback. The instance is always null and X+Y position zero. I'm using 0.7.1 release and took inspiration from https://github.com/tangrams/tangram-es/blob/master/platforms/android/demo/src/main/java/com/mapzen/tangram/android/MainActivity.java . My code looks like this:

```
    public void onMapReady(MapController mapController) {
        map = mapController;
        map.setPickRadius(50);
        ...
        map.setMarkerPickListener(this);
        ...
            Marker marker = map.addMarker();
            marker.setStylingFromString("{ style: 'points', color: 'limegreen', size: [25px, 25px], order: 2001, collide: false }");
            marker.setPoint(sight.location);
        ...
   }

    @Override
    public boolean onSingleTapConfirmed(float x, float y) {
        LngLat tappedPoint = map.screenPositionToLngLat(new PointF(x, y));

        map.pickFeature(x, y);
        map.pickLabel(x, y);
        map.pickMarker(x, y);

        map.setPositionEased(tappedPoint, 1000);

        return true;
    }

    @Override
    public void onMarkerPick(MarkerPickResult markerPickResult, float positionX, float positionY) {
        if (markerPickResult == null) {
            Log.d(LOG_TAG, "Empty marker selection");
            return;
        }

        Log.d(LOG_TAG, "Picked marker: " + markerPickResult.getMarker().getMarkerId());
    }

```

The marker is being correctly rendered on the map, but doesn't respond to a click even though I'm clicking on emulator with mouse very precisely and I also tried to fiddle with the `setPickRadius` value. The only *pick callback correctly being called is `onLabelPick`. Am I doing anything wrong? I suspect the problem could be in the `onSingleTapConfirmed` method, but I actually copied the code from the demo.. Could this be a bug in the 0.7.1 release?

**Comment by karimnaaji** [comment]
Can you try adding the `interactive: true` in the style of this markers See reference documentation for this parameter here: https://mapzen.com/documentation/tangram/draw/#interactive.
