### ISSUE TITLE
Unauthorized mapzen API key

### ISSUE THREAD

**Issue by hymn4u** [tangrams/tangram-es#1579]
Hi, guys! Really sorry to ask a question, i just can't see the map! This is what I did.

1. I've pull the tangram-es code from github, and used "make xcode" command to build project  in my mac.

2. Get an mapzen key use github account, add it to the scene.yaml:
    global:
        feature_order: function () { return feature.sort_rank; }
        sdk_mapzen_api_key: 'mapzen-TvvXXXX'
Setup an environment variable:
launchctl setenv MAPZEN_API_KEY mapzen-TvvXXXX

3.Then i run the project, everything seems alright, but only the map doesn't appear~~ I mean the glfw window appear, but map does not.

I realized it is a problem from getting vector data, but I don't know why. This is the messages:

 - To produce the result hereTANGRAM map.cpp:208: Loading scene file (async): scene.yaml
WARNING sceneLoader.cpp:1025: Invalid url_params entry in source 'osm', entries should be strings.
WARNING sceneLoader.cpp:1788: Can't find data source touch for layer touch
WARNING styleParam.cpp:280: Invalid font-size '1.2em'.
TANGRAM map.cpp:861: setup GL
TANGRAM hardware.cpp:60: Driver supports map buffer: 0
TANGRAM hardware.cpp:61: Driver supports vaos: 1
TANGRAM hardware.cpp:62: Driver supports rgb8_rgba8: 0
TANGRAM hardware.cpp:63: Driver supports NPOT texture: 1
TANGRAM hardware.cpp:77: Hardware max texture size 16384
TANGRAM hardware.cpp:78: Hardware max combined texture units 16
TANGRAM map.cpp:324: resize: 2048 x 1536
NOTIFY tileManager.cpp:72: add source osm
ERROR osxPlatform.mm:137: Unsuccessful status code 401: "unauthorized" from: http://tile.mapzen.com/mapzen/vector/v1/all/16/19295/24642.mvt?
ERROR osxPlatform.mm:137: Unsuccessful status code 401: "unauthorized" from: http://tile.mapzen.com/mapzen/vector/v1/all/16/19295/24641.mvt?
ERROR osxPlatform.mm:137: Unsuccessful status code 401: "unauthorized" from: http://tile.mapzen.com/mapzen/vector/v1/all/16/19294/24641.mvt?
ERROR osxPlatform.mm:137: Unsuccessful status code 401: "unauthorized" from: http://tile.mapzen.com/mapzen/vector/v1/all/16/19294/24642.mvt?
ERROR osxPlatform.mm:137: Unsuccessful status code 401: "unauthorized" from: http://tile.mapzen.com/mapzen/vector/v1/all/16/19294/24643.mvt?
ERROR osxPlatform.mm:137: Unsuccessful status code 401: "unauthorized" from: http://tile.mapzen.com/mapzen/vector/v1/all/16/19295/24643.mvt?
ERROR osxPlatform.mm:137: Unsuccessful status code 401: "unauthorized" from: http://tile.mapzen.com/mapzen/vector/v1/all/16/19293/24641.mvt?

**RESULT:**

Just glfw windows appear, no map.

**EXPECTED RESULT:**

Show me a map, please.

**ENVIRONMENT:**

MacOS Sierra, 10.12.5

 - If you used a released version, what is the version number?
I used latest version in github, the last commit is 82831b8849ef98194c9650bdb22693342b55def1 by Matt Blair.

Any help is appreciate, thank you!

**Comment by nvkelso** [comment]
Once the API key is set, then make xcode again. I've found the order to matter.

**Comment by tallytalwar** [comment]
We recently (less than 12 hours back) changed this behavior to have a run
time check than a compile time check for api key for the desktop demo apps.
Will give this a look tomorrow morning and update what's happening.

**Comment by tallytalwar** [comment]
Hey @hymn4u 

Can you clarify 2 things here?
1. Are you running the latest `master` branch for this?
2. Do you see the following message in the logs:
```
WARNING glfwApp.cpp:77: No API key found!

Mapzen data sources require an API key. Sign up for a free key at http://mapzen.com/developers and then set it from the command line with: 

	export MAPZEN_API_KEY=YOUR_KEY_HERE

Or, if using an IDE on macOS, with: 

	launchctl setenv MAPZEN_API_KEY YOUR_API_KEY
```

Also can you try setting the environment variable first using `launchctl setenv MAPZEN_API_KEY mapzen-TvvXXXX` and then opening xcode from the same terminal window. You can also set the environment variable globally (refer the instructions [here](https://stackoverflow.com/a/26586170/4079488) for the same).

**Comment by hymn4u** [comment]
Sorry for late. @tallytalwar 
1. Yes, i'm using master.
2. I just saw these message in the logs.

**Comment by hymn4u** [comment]
@nvkelso 
thanks, that works!

@tallytalwar 
I used the way you mentioned, set enviroment variable and then open xcode from terminal window, map came out. Thanks a lot!
