### ISSUE TITLE
Mapbox Tile Schema/Style

### ISSUE THREAD

**Issue by ac87** [tangrams/tangram-es#1580]
Whilst the Mapzen sources and styles are excellent, my end goal will be to create an application that the end user is able to add their own mapping files to.

The easiest source I can find for offline MVT data is Osm2VectorTiles (now https://openmaptiles.org/) tiles whose schema is more like MapBox's than the Mapzen's. 

I've started to try to convert Mapbox's JSON styles to YAML, but does something already exist? This looks like it could be a major project just to get the rendering looking good.

Here is what I currently have:

**Bright-v9**

![device-2017-07-20-100404](https://user-images.githubusercontent.com/20557626/28420326-b3a74046-6d59-11e7-855c-8042d21a4000.png)
![device-2017-07-20-100457](https://user-images.githubusercontent.com/20557626/28420329-b65d8c64-6d59-11e7-9e76-a873ac6f2410.png)
![device-2017-07-20-100535](https://user-images.githubusercontent.com/20557626/28420332-b77f756c-6d59-11e7-9899-316d3335b377.png)

**Basic-v9**

![device-2017-07-20-100811](https://user-images.githubusercontent.com/20557626/28420333-b8bd0336-6d59-11e7-9afc-ea9908de9687.png)
![device-2017-07-20-100914](https://user-images.githubusercontent.com/20557626/28420334-b9961284-6d59-11e7-87a5-e580928e85b3.png)
![device-2017-07-20-100957](https://user-images.githubusercontent.com/20557626/28420335-ba8482b6-6d59-11e7-9d19-c6bc71ac95fe.png)

**Comment by nvkelso** [comment]
Nice work! Nothing like this exists so far, this will be a nice contribution.

**Comment by tallytalwar** [comment]
@ac87 nicely done.

No we currently do not have any conversion scripts between Mapbox themes and Tangram styles. A generic script will involve it to understand the inner workings of both the renderers. We can certainly give it a try though. In your conversion process so far have you come across any pattern or other things which can be automated?

**Comment by ac87** [comment]
I will persist with my converter then. The JSON to YAML conversion is straight forward. The way road 'casings' are done is pretty different so I think I've got 2 layers where it can probably be done with one. I've had to adjust a lot of layer ordering and to stop layers appearing at too higher zoom level in Tangram.

Current version of the Styles can be found [here](https://github.com/ac87/tangram_android/tree/master/app/src/main/assets/vector/mapbox)

In Tangram Play the labels go a bit wild, it seems like a label appears in each tile, I think that is a difference with MapBox's storage but Tangram-ES displays things correctly. Don't know if this is something I should report to them?

![tplay](https://user-images.githubusercontent.com/20557626/28464587-d6091fdc-6e1d-11e7-8330-69d3dfffdf34.png)

**Comment by nvkelso** [comment]
That's a "feature" of their buffered MVT version. Ours are clipped to help with how MapboxGL renders things. Tangram doesn't need the buffer. There may be way in Tangram to ignore buffer, but will need to follow-up about that..

**Comment by Alex237** [comment]
Hello @ac87 
 Is it possible to have your converter ? I would like to use it, or also port it if possible. Thank you

**Comment by ac87** [comment]
@Alex237 sure, sorry I've been away. I've uploaded it to https://github.com/ac87/jsontoyaml

Apologies there is no commented rationale for some of the changes like making roads appear _n_ zoom levels sooner or later than the Mapbox style.

I also started adding support for the OpenMapTiles styles as the mvt layers are different to Mapbox.

**Comment by Alex237** [comment]
Thank you @ac87  , i appreciate, il try to port it in my free time an also try to contribute. thanks a lot 👍 🥇

**Comment by lygstate** [comment]
Wonderfull, any update?

**Comment by matteblair** [comment]
Not sure what the current status is on @ac87 's project for this, but since it isn't strictly an issue with Tangram ES I'm gonna close this issue to clean up our backlog.
