### ISSUE TITLE
MapController screenPositionToLngLat returns invalid longitude when user scrolls around the world

### ISSUE THREAD

**Issue by ac87** [tangrams/tangram-es#1586]
Calling `mapController.screenPositionToLngLat(new PointF(x, y));` in `onSingleTapConfirmed` method.

If the user has scrolled passed 180 either way and is in an alternate world the resulting longitude value now has to be processed to get a valid longitude.

i.e.
lat 25.223555452423366
lon -3320.1739616806763

currently adding this in sorts things

```// swiping around adds or removes 360
    public static double sanitiseLng(double longitude) {
        if (longitude > 180)
            return ((longitude % 360) - 360);
        if (longitude < -180)
            return ((longitude % 360) + 360);
        return longitude;
    }
```
Intentional or a bug? Don't know if I've never done this before or if its new.

**Comment by matteblair** [comment]
I don't believe this feature has changed recently, as far as I know we've always been producing un-wrapped longitudes. 

Wrapping longitude to { -180, 180 } is probably more sensible, we can implement that change.

**Comment by ac87** [comment]
I'd personally say wrapped would be better but maybe there are cases for sketching across the date line where it would be less helpful.

Also just realised this is a duplicate of #1097.

**Comment by tallytalwar** [comment]
Thanks @ac87.

Yeah will incorporate this in next release tasks.
