### ISSUE TITLE
No mouse pointer visible using GL ES2 on Raspberry Pi 1

### ISSUE THREAD

**Issue by raspi-user** [tangrams/tangram-es#1591]
Built RPI master branch.

Mouse working but no mouse pointer visible.

Seems to be a lot of this code:
[https://github.com/tangrams/tangram-es/blob/aa362f0f9ef9e66b0af9673fd6bcf38b17fa241d/rpi/src/main.cpp](https://github.com/tangrams/tangram-es/blob/aa362f0f9ef9e66b0af9673fd6bcf38b17fa241d/rpi/src/main.cpp)
missing from current branch?

**Comment by matteblair** [comment]
Yep, seems like that's been lost for a while now. If mouse rendering is important to your application then feel free to add that code path again, you can propose it as a pull request as well.

For now I'm removing the mouse option from the documentation: https://github.com/tangrams/tangram-es/pull/1592
