### ISSUE TITLE
Handle markers picks iOS (objective-C)

### ISSUE THREAD

**Issue by nasmuris** [tangrams/tangram-es#1601]
Hello,
I'm following [demo for iOS](https://github.com/tangrams/tangram-es/tree/master/platforms/ios/demo), the map loads well, rotation and zooming works just fine, I'm able to add new markers etc. too. 
But I cannot figure out how to handle marker picks,  `- (void)mapView:(TGMapViewController *)mapView didSelectMarker:(TGMarkerPickResult *)markerPickResult atScreenPosition:(TGGeoPoint)position;` in `MapViewControllerDelegate ` never gets called, I have set marker interactive style as true of course and I'm running the demo in simulator (maybe that's the reason?).
Thank you in advance for any advice

**Comment by karimnaaji** [comment]
Hey, can you try uncommenting this line https://github.com/tangrams/tangram-es/blob/master/platforms/ios/demo/src/MapViewController.m#L158? This is what should trigger the selection of markers.

**Comment by nasmuris** [comment]
Unfortunately that doesn't help, the `- (void)mapView:(TGMapViewController *)view recognizer:(UIGestureRecognizer *)recognizer didRecognizeSingleTapGesture:(CGPoint)location` doesn't even get called. 

I'm creating marker like this in `viewWillAppear` after the `[super loadSceneFile:....]`
`TGMarker *markerPoint = [self markerAdd];
    markerPoint.stylingString = @"{ style: 'points', interactive : true, color: 'white', size: [25px, 25px], order:2000, collide: false }";
    [markerPoint setPoint:TGGeoPointMake(103.8571689, 13.423786)];`

**Comment by karimnaaji** [comment]
Hi, I just tried from latest mater and I get the right behavior from the simulator:

![screen shot 2017-08-07 at 12 25 50](https://user-images.githubusercontent.com/7061573/29036021-aef6d1b8-7b6b-11e7-8c9c-6fd5a3454b9f.png)

Are you using the synchronous or asynchronous version of scene file loading? Loading a new scene clears out any previously created markers since markers are scene dependent. It might be why you are having some issues. One solution would be to create the markers once the scene is created (for example in `didLoadSceneAsync` if you use asynchronous scene loading).

**Comment by nasmuris** [comment]
I have the same code as in the demo with synchronous file loading. The only change is in implementation of viewWillAppear of MapViewController




    - (void)viewWillAppear:(BOOL)animated {
        NSMutableArray<TGSceneUpdate *>* updates = [[NSMutableArray alloc]init];
        [updates addObject:[[TGSceneUpdate alloc]initWithPath:@"global.sdk_mapzen_api_key" value:@"mapzen-NhhVzar"]];
        [super loadSceneFile:@"https://tangrams.github.io/walkabout-style/walkabout-style.yaml" sceneUpdates:updates];
        self.position=TGGeoPointMake(103.8571689, 13.423786);
        self.zoom=15;
        TGMarker *markerPoint = [self markerAdd];
        markerPoint.stylingString = @"{ style: 'points', interactive : true, color: 'white', size: [25px, 25px], order:2000, collide: false }";
        [markerPoint setPoint:TGGeoPointMake(103.8571689, 13.423786)];
    }

I can also see the marker, I set breakpoints to every method of the delegates but won't run to any of them
![Marker on Tangram](https://i.imgur.com/xjzx0Ly.png)

**Comment by nasmuris** [comment]
I have tried both Tangram-es v. 7.2.0 and 0.8.0-beta2 from cocoapods but with no luck

**Comment by karimnaaji** [comment]
@nasmuris can you try the following:

- Set a breakpoint in `viewWillAppear`
- Inspect `self.gestureDelegate`

The demo app assigns the delegate from `viewDidLoad` and loads the scene from `viewWillAppear`, `viewDidLoad` comes before the `viewWillAppear` in the iOS app lifecycle so your delegate should have a value a this point. Also, you said that `didRecognizeSingleTapGesture` was not called; one reason I can see this would happen is with a `nil` delegate or gesture recognizers not set (which are ensured to be internally initialized by `TGMapViewController`).

**Comment by Buthrakaur** [comment]
Hello @karimnaaji ,
I just inspected `self.gestureDelegate` and `self.mapViewDelegate` in `viewWillAppear` and they're `nil` even though they're set in `viewDidLoad` exaclty same as in the demo. Tried to assign them in `viewWillAppear` instead of `viewDidLoad`, but it didn't help - they just disappear and get `nil` somehow. Any idea what should we try next, please?

The special thing is this is running from a React-Native application, so the `MapViewController` is initialized little bit specifically - there's no storyboard. Could this cause the problem?

**Comment by Buthrakaur** [comment]
Few code samples of the initialization:
```
@interface RCTMapView : UIView {
  id <RCTMapViewDelegate> _delegate;
}
...
```
```
@interface RCTMapViewController : TGMapViewController<LocationHandlerDelegate,RCTMapViewDelegate>{
  id <RCTMapViewDelegate> _rctdelegate;
}
...
```
```
@implementation RCTMapView

{
  
  /* Required to publish events */
  RCTMapViewController *_rctMapViewController;

}

- (instancetype)init
{
  
  if (self = [super initWithFrame:CGRectMake(0,
                                             0,
                                             [[UIScreen mainScreen] bounds].size.width,
                                             [[UIScreen mainScreen] bounds].size.height)]){
    self.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
    _rctMapViewController = [[RCTMapViewController alloc]init];
    _rctMapViewController.rctdelegate=self;
    [self addSubview:_rctMapViewController.view];
  }
  return self;
}
```
I suspect there's some wrong with the `init` and `addSubview` as the map component is practically nested inside `RCTMapView` component...

**Comment by karimnaaji** [comment]
Hey,

I haven't been able to reproduce locally yet, can you try this branch and let me know whether that fixes the problem: https://github.com/tangrams/tangram-es/tree/delegate-strong-property

**Comment by nasmuris** [comment]
Unfortunately setting delegate properties as strong doesn't help

**Comment by Buthrakaur** [comment]
Hi @karimnaaji ,
I just tried the demo with tangram 0.7.2 on iOS simulator (tried iOS versions 9.3 and 10.3) and behaves in the same manner as our React Native application. Could you provide us the xcode project of your test app you posted the screenshots above from?

![image](https://user-images.githubusercontent.com/126757/29276526-2b192504-810f-11e7-99b6-2f265b502491.png)

**Comment by karimnaaji** [comment]
@Buthrakaur did [this branch](https://github.com/tangrams/tangram-es/tree/delegate-strong-property) helped in regards to your issue? The warnings seem to reference that specific issue. What version of Xcode are you using?

For the project, I've only generated the default xcode project from the master branch running `make ios`.

**Comment by nasmuris** [comment]
@karimnaaji 
I've already solved this problem last week and forgot to write my solution here...
What helped me was 
`@interface MapViewController : TGMapViewController<TGMapViewDelegate,TGRecognizerDelegate>`
then in `ViewDidLoad`
`self.mapViewDelegate = self;
self.gestureDelegate=self;` and implement necessary delegates methods in `MapViewController`

**Comment by karimnaaji** [comment]
Yes I can see how this works since ARC will always retain `self` alive while using it as the delegate. It would still be safe to change those properties to retain the delegates with `strong` so I'll push a fix for that soon.
Thanks for posting your solution!
