### ISSUE TITLE
Suspend updates/add Markers in batches

### ISSUE THREAD

**Issue by ac87** [tangrams/tangram-es#1604]
Currently working on a prototype to render KML placemarks onto Tangram-ES only really looking at Placemarks (Points) for now.

Because technically Google Earth can specify one of many icons and completely recolor those icons, it would be limiting to do this using sprites/GeoJson

The performance with 1000 markers is very reasonable however adding them is slow, I imagine because the map constantly redraws when it could just redraw once when all markers are added.

Example - on an Galaxy S8 its not as noticeable but gives the idea.
![markers](https://user-images.githubusercontent.com/20557626/29120437-0bf67f3e-7d02-11e7-9918-76a9a2ab207d.gif)

Is there a way to achieve this currently? if not then I guess this is a feature request.

**Comment by hjanetzek** [comment]
Yes, it should be possible to suspend redraws while adding markers when you add them in a `synchronized(mapController)` block since all native calls are synchronized on the `MapController` instance.

**Comment by ac87** [comment]
Absolutely does, works a treat and speeds it up a lot. Thanks!
