### ISSUE TITLE
Can't load textures via file://path-to-texture.png

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1607]
### Reproduction
On Android, have a texture definition like this: 
```
textures:
    quests:
        url: file:///data/data/de.westnordost.streetcomplete/files/quests.png
```
(etc...)

### Result

Tangram-ES fails to load the file and logs even though the file exists at that place.
```
WARNING platform.cpp:29: Failed to read file at path: file:///data/data/de.westnordost.streetcomplete/files/quests.png
ERROR sceneLoader.cpp:646: Can't load texture resource at url 'file:///data/data/de.westnordost.streetcomplete/files/quests.png'
ERROR sceneLoader.cpp:699: Missing texture quests
```

### More information
These are the things I tried out to no avail:
- When leaving out the leading `file://` in the path, the path is automatically prefixed by `assets://` so the file is not found in the first place because it is not in the assets folder.
- chmod 777 on the file has no effect
- Initially, the file was generated programmatically and then set in a `SceneUpdate`, but it also doesn't work if the file is there from the beginning and no `SceneUpdate` is made (so it has nothing to do with that)

**Comment by matteblair** [comment]
This should be resolved in https://github.com/tangrams/tangram-es/pull/1465. I had hoped to get it merged much sooner but I've had a hard time integrating it with the code for loading scenes from zip files.

**Comment by westnordost** [comment]
Oho, cool. Hope you are able to merge it after such a long time.

**Comment by westnordost** [comment]
The use case for this is, by the way, to create a spritesheet for usage in tangram from a set of (vector) drawable icons used elsewhere in an Android app.

**Comment by westnordost** [comment]
Actually, this is very likely a duplicate of #1564
