### ISSUE TITLE
Synchronous scene loading functions don't update map until some other render event occurs

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1608]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
1. Load up the iOS framework using 0.8-beta2 in a sample app.
2. Load a scene file using an async function (cinnabar for example)
3. Load a different scene file using a *synchronous* function (walkabout for example)

**RESULT:**

Until you re-interact with the map, the map will remain in cinnabar display.

**EXPECTED RESULT:**

The map should switch immediately without additional "motivation".

**ENVIRONMENT:**

 - Environment: iOS 10.3.2 on an iPad Pro 12.9 (first gen).
 - Tangram-es Version:  0.8-beta2

**OTHER:**

Can be resolved by enabling continuous rendering, meaning there's probably a missing call in the sync function to request a render.

**Comment by matteblair** [comment]
I'm having trouble reproducing this in our demo app - can you point me to code that exhibits this issue?

**Comment by msmollin** [comment]
Sure!

The callsite is here: https://github.com/mapzen/ios/blob/issue-351/SampleApp/SampleMapViewController.swift#L50

Which calls this superclass function:
https://github.com/mapzen/ios/blob/issue-351/MapzenSDK/MZMapViewController.swift#L549

Which cascade through an objective-c-like series of functions (since we can't use nice overloading to maintain compatibility) down to here:
https://github.com/mapzen/ios/blob/issue-351/MapzenSDK/MZMapViewController.swift#L583

Which just extracts the URL path for the bundle and then calls into the TGMapViewController's function over here:
https://github.com/tangrams/tangram-es/blob/master/platforms/ios/src/TangramMap/TGMapViewController.mm#L157

which cascades a bunch again and ultimately winds up here:
https://github.com/tangrams/tangram-es/blob/master/platforms/ios/src/TangramMap/TGMapViewController.mm#L174

**Comment by matteblair** [comment]
@msmollin Thanks! Reproduced the issue in the sample app and confirmed that #1612 resolves it.
