### ISSUE TITLE
Log spam in iOS Framework 0.8-beta2

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1610]
When zooming in on an area, there's sometimes hundreds of lines of
`ERROR iosPlatform.mm:231: Response "(null)" with error "cancelled".`
flooding the debugger. It's not terribly useful as it seems to be from us canceling URL requests as we no longer need the tile for that area we zoom in. 

Can we remove it?

**Comment by matteblair** [comment]
That output comes from the HTTP request completion handler in `IOSPlatform`: https://github.com/tangrams/tangram-es/blob/master/platforms/ios/src/TangramMap/iosPlatform.mm#L229-L233

We log any `NSError` returned by the HTTP request. In general, errors seem like a good thing to have in logs - but it's true that the `"cancelled"` error can really bloat the logs. Cancelled requests aren't errors as far as our use is concerned, maybe we can specifically ignore those errors while still logging others.

**Comment by matteblair** [comment]
@msmollin Just created a PR addressing this; I made cancelled URLs print to debug output rather than error output.
