### ISSUE TITLE
possible typo in SpriteLabel::updateScreenTransform?

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#1620]
I am playing a little bit with custom markers in Tangram ES and I have found out that when I am setting offset in styling for these markers they are not being drawed when they are partially visible and are near left and top edge. They should be drawed in this case because they are still partially visible. 

After some searching in code which is responsible for this clipping I have found out that there may be typo here https://github.com/tangrams/tangram-es/blob/master/core/src/labels/spriteLabel.cpp#L165 and here https://github.com/tangrams/tangram-es/blob/master/core/src/labels/spriteLabel.cpp#L166 I think that `m_options.offset` shouldn't be there as on line https://github.com/tangrams/tangram-es/blob/master/core/src/labels/spriteLabel.cpp#L161 it is already added to `position` vector. I may be really wrong and this should be there maybe as I haven't digged deeply into what that projection is doing. 

I have also tested it and when I delete that `+ m_options.offset` from there, then clipping of markers works properly.

**Comment by hjanetzek** [comment]
Yes, you are right. The offset was added twice to bounding box when testing visibility. Thanks!

**Comment by tallytalwar** [comment]
Resolved vias #1623
