### ISSUE TITLE
setPosition() does not center map correctly

### ISSUE THREAD

**Issue by thmalm** [tangrams/tangram-es#1622]
Hello,

I'm having problems to correctly center the map using Tangram for Android on mobile device.

The map view only use part of the screen (approx. 2/3) and I'm using setPosition() to center map on a certain lng/lat. Problem is that the map is always offset 125 pixels on the Y axis.

I have verified that I use the correct lng/lat by placing a marker at the location provided with the call to setPosition().

What am I missing here? Guess I'm doing something in the wrong way... =)

Best regards // Thomas

**Comment by westnordost** [comment]
Could it be that your MapView spans the whole screen in your layout and is only being covered 1/3 by another view?

**Comment by thmalm** [comment]
I did suspect that was the case and tested to place a marker at the calculated center of map view (by height/width of MapView and using screenPositionToLngLat() to add the marker). That actually does center the marker on the visible map view.

**Comment by matteblair** [comment]
I also believe that this is likely caused by the layout of your map view. `setPosition` will put the specified location at the center of the entire view, not just the visible portion. In your case you probably want to adjust your activity layout to make the map view fill only the area where it will be visible.

**Comment by ac87** [comment]
What's your camera settings in the scene file? I had the same issue and it was down to copying and pasting a sample with `vanishing_point: [0, -500]` taking that out made the center actually be the center.

**Comment by thmalm** [comment]
Thank you very much! The camera settings was the actual problem and centering in map view now works as expected.
