### ISSUE TITLE
Memory runaway with raster-only sources.

### ISSUE THREAD

**Issue by cleeus** [tangrams/tangram-es#1631]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- create a scene with a single raster source and show it in a layer
- browse the map for a while

**RESULT:**

- tangram demo uses excessive amounts of memory 

**EXPECTED RESULT:**

- tangram demo should only use a limited/bounded amount of memory

**ENVIRONMENT:**

 - seen on OSX with master (roughly at 0.8.0).

**OTHER:**

Hello everyone,

I experience unbounded memory usage/growth when using only raster tile sources. Issuing Map::onMemoryWarning() calls does not reduce memory usage.

To trigger this, you need a simple scene with just a single raster source (no geometry) and browse the map for a while. What happens is, that tangram-core will continue to allocate more and more memory, I’ve seen something like 1.6GB (where I stopped to browse the map and started investigating).

I think I found the reason for it: `Tangram::TileCache.` If I understand correctly, the TileCache is supposed to only use a limited amount of RAM and keeps track of RAM usage by adding up the result of all `Tile::getMemoryUsage().` Now `Tile::getMemoryUsage()` only returns the amount of memory required for geometry - which is negligible for raster-only tiles. Accordingly basically all tiles `(std::shared_ptr<Tangram::Tile>)` are kept alive which also keeps alive the textures in the rasters via Tile::m_rasters. Now the textures themselves are only handles/references to GL textures - tangram does clean the pixel data after is has been copied over into GL (see `Texture::update(…)` ). So the Tangram::Texture object itself does not take up much memory, but it keeps the GL texture handle alive and GL has to store it somewhere where somewhere is either graphics card memory or main memory.

**Comment by hjanetzek** [comment]
Hi @cleeus - thanks for investigating this issue. Yes,`Tile::getMemoryUsage()` was missing to count  texture memory usage. https://github.com/tangrams/tangram-es/pull/1632

**Comment by tallytalwar** [comment]
Addressed by #1632.

**Comment by cleeus** [comment]
Thanks for fixing this :)
