### ISSUE TITLE
Cannot locate symbol on Samsung jfltexx

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1643]
Fun with Samsung devices: I got this error report from a user of StreetComplete with a samsung jfltexx device, Android 4.4.4, using tangram-es 0.7.2.

Stack trace:
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "" referenced by "libtangram.so"...
at java.lang.Runtime.loadLibrary(Runtime.java:364)
at java.lang.System.loadLibrary(System.java:526)
at com.mapzen.tangram.MapController.<clinit>(MapController.java:1097)
at com.mapzen.tangram.MapView.getMapInstance(MapView.java:107)
at com.mapzen.tangram.MapView.getMapAsync(MapView.java:77)
at com.mapzen.tangram.MapView.getMapAsync(MapView.java:61)
...
```

Line 1097 for tangram-es 0.7.2 is this:
```
1095  static {
1096    System.loadLibrary("c++_shared");
1097    System.loadLibrary("tangram");
1098  }
```

Not sure how helpful this stack trace is. What I read from that is that somewhere inside the C++ code, a symbol is not defined for the given device, but doesn't say which symbol.
Feel free to close this report if you can't act on it due to a missing test device. I notified the user via email that I opened this ticket, perhaps he can answer questions that you may have.

**Comment by tallytalwar** [comment]
Thanks @westnordost 

As you mentioned its a hard one to track because we can not get our hands on this rare (:D) device.

Closing for now, let us know if you hear more noise on this. Thanks
