### ISSUE TITLE
Loading scene errors (iOS - Swift)

### ISSUE THREAD

**Issue by Alex237** [tangrams/tangram-es#1650]
Hello Tangram-es Team 😄 

I have some trouble with Tangram 0.8.0

I have installed Tangram-es From cocoapods, then ! followed the tutos from this page (who seems to be outaded)
[https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/iOS-walkthrough.md](https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/iOS-walkthrough.md)

I am using Tangram on an iOS swift project

this code from doc do not work 

```swift
class ViewController: TGMapViewController {

    override func viewWillAppear(_ animated: Bool) {
        let sceneURL = "walkabout-style-more-labels.yaml"
        super.loadSceneFileAsync(sceneURL, sceneUpdates: [ TGSceneUpdate(path: "global.sdk_mapzen_api_key", value: <YOUR_API_KEY_HERE>) ])
        super.loadSceneAsync(from: Bundle.main.url(forResource: Tangram.scene, withExtension: "yaml")!)
    }

    [...]
}
```

so i changed it to (according Xcode Autocomplete.)

```swift
class ViewController: TGMapViewController {

    override func viewWillAppear(_ animated: Bool) {
        let sceneURL = "walkabout-style-more-labels.yaml"
        super.loadSceneFileAsync(fromYAML: sceneURL, , relativeTo:  Bundle.main.bundleURL, with: [ TGSceneUpdate(path: "global.sdk_mapzen_api_key", value: <MY_API_KEY_HERE>) ])
    }

    [...]
}
```

After that , i have this error  :
```
TANGRAM map.cpp:902: setup GL
TANGRAM hardware.cpp:60: Driver supports map buffer: 1
TANGRAM hardware.cpp:61: Driver supports vaos: 1
TANGRAM hardware.cpp:62: Driver supports rgb8_rgba8: 1
TANGRAM hardware.cpp:63: Driver supports NPOT texture: 0
TANGRAM hardware.cpp:77: Hardware max texture size 4096
TANGRAM hardware.cpp:78: Hardware max combined texture units 8
TANGRAM map.cpp:240: Loading scene string (async)
TANGRAM map.cpp:213: Loading scene file: <PATH_TO_SCENE_FILE>
libc++abi.dylib: terminating with uncaught exception of type YAML::BadSubscript: operator[] call on a scalar
```

But i Use this code : 

```swift
class ViewController: TGMapViewController {

    override func viewWillAppear(_ animated: Bool) {
        let sceneURL = Bundle.main.url(forResource: "walkabout-style-more-labels", withExtension: "yaml")!)
        super.loadSceneFileAsync(from: sceneURL, , relativeTo:  Bundle.main.bundleURL, with: [ TGSceneUpdate(path: "global.sdk_mapzen_api_key", value: <MY_API_KEY_HERE>) ])
    }

    [...]
}
```

it's work !.
any usage of : 
```swift
super.loadSceneFileAsync(fromYAML: [...]}

    [...]
}
```
or

```swift
super.loadSceneFile(fromYAML: [...]}

    [...]
}
```

always fail.

**Comment by msmollin** [comment]
Hi @Alex237. Thanks for the issue. We should probably clarify the docs for the new method. However, it is working as intended. The `fromYAML` methods are intended to take in raw YAML strings that perhaps you read off of disk in your app or maybe downloaded from the internet. If you want to load an entire style sheet from disk, like Walkabout in your example, you would use the `from: sceneURL` methods as you did already.

Make sense?

**Comment by matteblair** [comment]
As described above, this is working as intended. Check the documentation in https://github.com/tangrams/tangram-es/blob/master/platforms/ios/src/TangramMap/TGMapViewController.h#L492-L570
