### ISSUE TITLE
Markers are not redrawn when raster map wraps around

### ISSUE THREAD

**Issue by Jiangyi** [tangrams/tangram-es#1654]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
 - Use a raster world map
 - Create some markers scattered on the map (I created ones that use Android drawables, but I suspect the behaviour is the same otherwise)
 - Scroll either left or right until the map wraps around

**RESULT:**

The markers do not appear when the map wraps around.

**EXPECTED RESULT:**

The markers should be redrawn and appear when the map wraps around.

**ENVIRONMENT:**

 - Tested on a Motorola Z Play XT1635 on Android 7.1.1, using the release version of Tangram 0.8.0.

**OTHER:**

Hey guys, me again with another raster map issue 😅. The logs show the tiles getting loaded as the map wraps around, but nothing relevant regarding the markers. I can try to produce a recording if that helps!

Keep up the great work, I look forward to hearing back from you!

**Comment by matteblair** [comment]
Hey sorry for not responding to this issue in a timely fashion, but this issue has been fixed - check the latest releases!
