### ISSUE TITLE
Cannot build tests on macOS

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#1673]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

On the `master` branch, run: `make tests`

**RESULT:**

```
[ 90%] Linking CXX executable ../bin/unit/tileIDTests.out
Undefined symbols for architecture x86_64:
  "__objc_empty_cache", referenced from:
      _OBJC_METACLASS_$_FontConverter in libalfons.a(fontConverter.mm.o)
      _OBJC_CLASS_$_FontConverter in libalfons.a(fontConverter.mm.o)
  "_objc_msgSend_stret", referenced from:
      alfons::AppleFontFace::load() in libalfons.a(appleFontFace.mm.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [bin/unit/tileManagerTests.out] Error 1
make[2]: *** [tests/CMakeFiles/tileManagerTests.out.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 91%] Built target tileIDTests.out
make[1]: *** [all] Error 2
make: *** [unit-tests] Error 2
```

**EXPECTED RESULT:**

Successful build.

**ENVIRONMENT:**

macOS 10.12.6

**OTHER:**

The problem can be resolved by modifying the tests `CMakeLists.txt` to link with the required frameworks:
```
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index 2e94c47a..7dc588d6 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -5,6 +5,8 @@ add_library(platform_test
 target_link_libraries(platform_test
   PUBLIC
   platform_mock
+  "-framework Foundation"
+  "-framework CorGraphics"
   -lpthread)
 ```
But we would only want these frameworks to be linked when we build on macOS and not on Linux.

This problem seems to have started when Alfons began using CoreText for font loading on macOS. I would think the burden of linking necessary frameworks should be on Alfons, which is calling into those frameworks, and not from the application that is using Alfons.

**Comment by tallytalwar** [comment]
Ahaa... interesting and nice catch. Never built tests on osx during that work. Yeah does make sense for alfons to specify those frameworks in its own CMakeFile.

**Comment by matteblair** [comment]
Should be resolved by merging https://github.com/hjanetzek/alfons/pull/16 and then updating our submodule.
