### ISSUE TITLE
Provide convenience method to set map bounds

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#1678]
We've had several requests come in for an easy way to set the map bounds. Currently we have implemented a solution for this within the Places SDK (https://github.com/mapzen/android/blob/master/mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerActivity.java#L164-L184). The Android/iOS SDKs could each add this logic and expose individual APIs, however it would be preferable to have it in a centralized place within Tangram

**Comment by matteblair** [comment]
Agreed! We've had requests for this in Tangram ES as well.

**Comment by matteblair** [comment]
Doh! I just created an issue that duplicates this one - oops. Gonna consolidate over in https://github.com/tangrams/tangram-es/issues/2034
