### ISSUE TITLE
iOS How to block longitude range?

### ISSUE THREAD

**Issue by seubseub** [tangrams/tangram-es#1692]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
 I think this issue is related to #1431 
 We want to show just one map to user by restricting longitude.
 So as #1431 issue, We have limited to show just one map using the calculated logitude.
 but in previous #1431 issue, setLimitsY& setLimitsX will be exposed later release.
 Is there any method that block longitude? not calculating longitude.

**RESULT:**
calculated.. not naturally.

**EXPECTED RESULT:**
map restricted to show one map naturally

**ENVIRONMENT:**
 - iOS 10.x
 - Device iPhone 6s
 - Tangram Version 0.8.1

**OTHER:**
I really thank you for your library :).

**Comment by matteblair** [comment]
Superseded by #2034
