### ISSUE TITLE
Map rendering with 10000 points in mapdata layer

### ISSUE THREAD

**Issue by ac87** [tangrams/tangram-es#1694]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Might be I've hit a known limit here as opposed to a bug?

See last commit to my test repository 
https://github.com/ac87/tangram_android/commit/229c208868946ce14b7bd392f07de604a693ae33

It adds just over 10000 points to a GeoJson collection then passes this to Tangram via a MapData layer.

**RESULT:**

Map rendering becomes very slow, calculating the points also seems to block all other map loading i.e. if you zoom out extra map tiles are not loaded (although the android profiler shows the HTTP request is going out when expected) no noticeable spike in CPU although memory usage appears to climb slowly.

The transition in the filter for the layer between 'high' and 'low' draw rules is also noticeably slow.

Markers i.e. the MyLocation marker are rendered in a timely fashion.

**EXPECTED RESULT:**

Map rendering to be largely unaffected by these additional points.

**ENVIRONMENT:**

Tangram-ES 8.2-SNAPSHOT - but tried back to 8.0
Samsung Galaxy S8 - Android 7.0

**OTHER:**

In order to reduce the work ES has to do
- I've switched it to use a Raster layer rather than rendering any vectors, other than the MapData but this made no noticeable difference.
- Tried adding the points one by one via `addPoint` instead of `addGeojson`.

**Comment by matteblair** [comment]
The performance issues here should be addressed by the changes in #2043. Thanks for the report :+1:
