### ISSUE TITLE
Most recent scene yaml should be applied when all onSceneReady calls finish

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#1704]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

0. Get reference to `MapController` with `MapView#getMap(SceneLoadListener)`
1. Call `MapController#loadSceneYamlAsync` with bubble wrap yaml
2. After onSceneReady callback received
3. Call `MapController#updateSceneAsync` with path overlay scene updates
4. Call `MapController#loadSceneYaml` with cinnabar yaml
5. Receive `onSceneReady` `MapController#loadSceneYaml`
6. Receive `onSceneReady` `MapController#updateSceneAsync`

**RESULT:**

The map style displayed is bubble wrap

**EXPECTED RESULT:**

I expect cinnabar to be displayed because it was the most recent style yaml set on `MapController`

**ENVIRONMENT:**

Tangram 0.8.1
Android 7.0

**OTHER:**

Note that when I replace call 4. `MapController#loadSceneYaml` with the async `MapController#loadSceneYamlAsync` method, the callbacks to onSceneReady finish in the same order as they were called (and the style is set to cinnabar as expected). Also, if I add a delay before the call to 4. to allow the previous scene updates to finish, cinnabar is set properly.

This makes me wonder if we should add a way to cancel previously made asynchronous calls? If we did this, I'd imagine it would then be the developer's responsibility to cancel existing async calls before making any sync calls. Alternatively, we could enforce ordering within Tangram so that sync calls wouldn't happen until previously queued async ones finished. Or something else entirely?

Since its common to see methods to cancel async operations (https://developer.apple.com/documentation/foundation/nsoperationqueue/1417849-cancelalloperations?language=objc, https://developer.android.com/reference/android/os/Handler.html#removeCallbacks(java.lang.Runnable)), I prefer we add something like `MapController#cancelSceneLoad(sceneId)`. 

Note that the synchronous call in 4. was only made in the sample app to test how the Android SDK responded after I found a bug in the iOS SDK, we don't recommend devs use these methods. That said, if there is anything we should be doing differently in the Android SDK, let me know.

**Comment by sarahlensing** [comment]
I was thinking about this more and realize that the Android SDK is doing something that isn't kosher by loading the scene yaml in 4. before the scene update in 3. finishes. This should be fixed and narrows the scope of this issue to considering whether Tangram should provide a way to cancel async scene updates/scene loads? This API would be a "nice to have" and would allow clients to optimize the work done by Tangram.

**Comment by matteblair** [comment]
This should be resolved by #1722 

As you suggested, the problem arises when a synchronous load is started before a pending asynchronous load/update completes. This PR will cause a synchronous load to block until all asynchronous loads are completed, preventing loads from finishing out-of-order.

**Comment by tallytalwar** [comment]
Resolved by #1722
