### ISSUE TITLE
Latest build for Raspberry Pi fails. When fixed, default scene.yaml crashes with YAML::BadSubscript

### ISSUE THREAD

**Issue by raspi-user** [tangrams/tangram-es#1711]
Latest build (yesterday git) needs this update:

> UrlRequestHandle RpiPlatform::startUrlRequest(Url _url, UrlCallback _callback) {
    return m_urlClient.addRequest(_url.string(), _callback);
}

> void RpiPlatform::cancelUrlRequest(UrlRequestHandle _request) {
    m_urlClient.cancelRequest(_request);
}

Now will build.

But gives following error with default scene.yaml.

pi@raspberrypi:~/tangram-es/build/rpi/bin $ ./tangram

**RESULT:**

Starting an interactive map window. Use keys to navigate:
	'w' = Pan up
	'a' = Pan left
	's' = Pan down
	'd' = Pan right
	'=' = Zoom in
	'-' = Zoom out
	'esc'= Exit
Press 'enter' to continue.
Mouse [NONE]
TANGRAM map.cpp:213: Loading scene file: scene.yaml
terminate called after throwing an instance of 'YAML::BadSubscript'
  what():  operator[] call on a scalar
Aborted

**EXPECTED RESULT:**

Working map

**ENVIRONMENT:**

Raspberry Pi 1 GLES2

**Comment by matteblair** [comment]
Should be resolved by #1717, thanks for the report!
