### ISSUE TITLE
Marker Drawables not working in 0.8.2-SNAPSHOT

### ISSUE THREAD

**Issue by ac87** [tangrams/tangram-es#1712]
Might have caught a WIP here as its in SNAPSHOT but reporting in case.

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Using the code from https://github.com/ac87/tangram_android/blob/master/app/src/main/java/com/test/tangramandroid/MyLocationMarkerManager.java

or Westnordost's StreetComplete (just to check it wasn't something I'd done)

The marker is no longer showing the drawable and is only showing the 'points' defined style.

**RESULT:**

0.8.2-SNAPSHOT

![device-2017-10-27-134444](https://user-images.githubusercontent.com/20557626/32105159-68f63444-bb1f-11e7-8212-405a5d46b809.png)

![device-2017-10-27-135657](https://user-images.githubusercontent.com/20557626/32105209-94dd7b30-bb1f-11e7-9628-2a116e6e0399.png)

**EXPECTED RESULT:**

0.8.1

![device-2017-10-27-133743](https://user-images.githubusercontent.com/20557626/32105171-6dcc299c-bb1f-11e7-852d-1208b9255991.png)

![device-2017-10-27-135239](https://user-images.githubusercontent.com/20557626/32105205-8fb26c42-bb1f-11e7-9e0d-53fdf80721d9.png)

**Comment by matteblair** [comment]
I can reproduce a similar result on `master` - looking into this now.
