### ISSUE TITLE
[Question] Is there any way to  Marker point and  text style support angle and flat ?

### ISSUE THREAD

**Issue by saeedtabrizi** [tangrams/tangram-es#1713]
Hi .
In my case i want to set a `Marker` point that draw an icon from  **Font icons** (`FontAwesome`) .
So the marker draw an Icon with **text** option and it's **OK** ,  but i can't to rotate it by angle or using **flat** option for drawn text icon .
Is there any way to using teh `flat` and `angle` options in text from points style ?

If "yes" ,  so please make an style sample for me here  .
I'm confused when i reading the docs exactly . 

Thanks .

**Comment by saeedtabrizi** [comment]
Hi @matteblair .
Please help me about it .

**Comment by matteblair** [comment]
Hi @saeedtabrizi 

There is currently not a way to apply the `flat` or `angle` parameters to text labels. Tangram ES draws text in a very different way than image icons, so the options for them are not exactly the same. For your use case I would recommend creating an image from the font icon and using that with the Marker.
