### ISSUE TITLE
MapController#requestRender Not Working

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#1723]
```kotlin
class MainActivity : AppCompatActivity() {

  var controller: MapController? = null
  var routePinData: MapData? = null

  var points: MutableList<LngLat> = ArrayList()

  val tapResponder = object : TouchInput.TapResponder {
    override fun onSingleTapUp(x: Float, y: Float): Boolean {
      addRouteMarker(x, y)
      return false
    }

    override fun onSingleTapConfirmed(x: Float, y: Float): Boolean {
      return false
    }
  }

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)

    val sceneLoadListener = MapController.SceneLoadListener { sceneId, sceneError ->
      controller?.zoom = 16f
      controller?.position = LngLat(-122.394046, 37.789747)
      controller?.setTapResponder(tapResponder)
    }

    val map = findViewById<MapView>(R.id.mz_tangram_map)
    controller = map.getMap(sceneLoadListener)
    val sceneUpdates = mutableListOf(SceneUpdate("global.sdk_mapzen_api_key", "MY_API_KEY"))
    controller?.loadSceneFileAsync("https://mapzen.com/carto/bubble-wrap-style/bubble-wrap-style.zip", sceneUpdates)
  }

  private fun addRouteMarker(x: Float, y: Float) {
    val point = controller?.screenPositionToLngLat(PointF(x, y))
    point?.let { points.add(it) }

    if (points.size == 1) {
      if (routePinData == null) {
        routePinData = controller?.addDataLayer("mz_route_location")
      }
      val properties = HashMap<String, String>()
      properties.put("type", "point")
      routePinData?.addPoint(point, properties)
      controller?.requestRender()
    }
  }
}
```
activity_main.xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<com.mapzen.tangram.MapView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/mz_tangram_map"
    />
```

**RESULT:**

The first time the map is clicked the route marker does not show. It is only after the map is moved or clicked a second time does it show.

**EXPECTED RESULT:**

Because I am requesting the map render, I would expect the route marker to show after the first map click.

**ENVIRONMENT:**

Pixel 8.0.0
Tangram-es 0.8.1

**OTHER:**

![requestrender](https://user-images.githubusercontent.com/494323/32632717-e33887ce-c561-11e7-9695-af4a5cacc115.gif)

**Comment by westnordost** [comment]
I have had a similar problem, perhaps this is related or even the same: `controller.screenPositionToLngLat` will not return any reasonable value as long as the view has not been measured yet. Could it be that the marker is placed outside the screen viewport?
I solved it by adding things to the map only after 

```
private void postOnLayout(final Runnable runnable)
{
	ViewTreeObserver vto = getView().getViewTreeObserver();
	if(vto.isAlive())
	{
		vto.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener()
		{
			@Override public void onGlobalLayout()
			{
				getView().getViewTreeObserver().removeOnGlobalLayoutListener(this);
				runnable.run();
			}
		});
	}
}
```

Does this solve your problem?

If yes, it would be convenient anyway if tangramES would only called `onSceneReady` after the view itself also has been layout fully.

**Comment by sarahlensing** [comment]
Unfortunately that doesn't solve my problem

**Comment by matteblair** [comment]
Hey @sarahlensing thanks for the report. I don't see anything wrong with your example (glad that it's working with Kotlin!) - I would also expect the point to show up without any further interaction required.

Can you try putting `addRouteMarker` in a `Runnable` and passing that into `MapController$queueEvent()`? It shouldn't be necessary to do that, but the problem is probably with synchronization of the UI thread and the GL thread and this might help narrow it down.

**Comment by sarahlensing** [comment]
@matteblair That didn't resolve the issue. Is there anything else I should try to help debug/triage?

On a somewhat related note- I noticed that the implementation of a couple `MapView` [methods](https://github.com/tangrams/tangram-es/blob/master/platforms/android/tangram/src/main/java/com/mapzen/tangram/MapView.java#L81-L90) aren't calling corresponding `GLSurfaceView` [methods](https://developer.android.com/reference/android/opengl/GLSurfaceView.html#onResume()). I tried updating `MapView` to call through to `GLSurfaceView#onResume` & `GLSurfaceView#onPause` but this also didn't fix the issue though it is a change we should make
