### ISSUE TITLE
Support `size: %` draw rule

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#1746]
Following up on work for `density` parameter for scene sprite textures, we can implement the use of the % scaling of the sprites using the density information.

Docs: https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/draw.md#size-

**Comment by westnordost** [comment]
(From the linked documentation, I do not understand the application. % of what?)

**Comment by matteblair** [comment]
The `%` here is applied to the size of a sprite as defined in a texture description. So if a sprite is defined with a region of `[0, 0, 32, 32]` and drawn with a `size: 100%` then it will be displayed at a size of 32 logical pixels in x and y. If drawn with `size: 50%` it will be displayed at a size of 16 logical pixels in x and y, et cetera.

**Comment by tallytalwar** [comment]
Was implemented as part of https://github.com/tangrams/tangram-es/pull/1788
