### ISSUE TITLE
OpeenStreetMap default-like map style

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#1753]
Hi, I am not sure if this is a correct repo for this question, but are you planning creating similar map style for Tangram-ES to "default" Mapnik style for OpenStreetMap? Or is there some tool for converting CartoCSS style to Tangram-ES yaml style? If no is this even possible to be done manually? Thank you.

**Comment by rwrx** [comment]
I forgot to add link to map style which I mean: https://github.com/gravitystorm/openstreetmap-carto .

**Comment by tallytalwar** [comment]
I think @hjanetzek gave it a shot a couple of years back.

@hjanetzek you still have the osm style sheet around?

**Comment by matteblair** [comment]
This isn't really an issue for the map rendering engine itself. Gonna close this.
