### ISSUE TITLE
how strongly Mapzen shutdown will affect tangram-es

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/tangram-es#1758]
https://github.com/tangrams/tangram-es is under https://github.com/tangrams with

> An open-source project sponsored by Mapzen.

with website set to https://mapzen.com/tangram

Mapzen shutdowns within month ( https://mapzen.com/blog/shutdown/ ) but neither https://mapzen.com/blog/shutdown/ nor https://mapzen.com/blog/migration/ mentions tangram-es from what I see.

How it will affect tangram-es? Is it going to become abandoned as main purpose of this project was to make possible to easily use vector tiles made by Mapzen? Or is it going to continue to be maintained in some form?

**Comment by matteblair** [comment]
Hi @matkoniecz, the short answer is that Tangram ES will not be abandoned but development will be different.

 It's true that the main use of Tangram ES was for Mapzen's hosted tile services, but the library is intentionally designed to accommodate many different sources of data. It's entirely possible to use Mapbox tiles with Tangram ES if your scene file is designed for their data schema. The Mapzen tile services are all open-source as well, so if another individual or organization wanted to run their own version of it, Tangram ES would naturally work well with that too.

We maintainers will no longer be able to work full-time on developing new features and fixing bugs, but we expect to continue part-time support. Beyond that, community contributors can also drive forward new features and submit changes on their own.

**Comment by tehKaiN** [comment]
Thanks for not abandoning this project, because those maps rock! Also they're the only one which allows injecting custom opengl without much hassle.

What I'd reallly like to see is some small example of scene file which would use other map tile sources, I guess many people would have to get a solution which would make their app work just fine after shutdown.

**Comment by tehKaiN** [comment]
Okay, so right now we have Nextzen, but AFAIK it offers maps from December 2017. It's half a year past that point, maps will get more and more outdated. Are there any other free map sources compatible with tangram-es which are supporting yaml styling etc.?

**Comment by matteblair** [comment]
There are a number of vector tile providers serving map tiles in formats compatible with Tangram ES (including [Mapbox](https://www.mapbox.com/) and [OpenMapTiles](https://openmaptiles.org/)) but their tile data may use different schemas, so you'll need to update your scene files accordingly.

As for the future of Tangram ES, it was recently adopted as a Linux Foundation Project :) https://www.linuxfoundation.org/press-release/2019/01/mapzen-open-source-data-and-software-for-real-time-mapping-applications-to-become-a-linux-foundation-project/

I hope this question is answered well enough for now. Closing!
