### ISSUE TITLE
Corrupted marker bitmaps

### ISSUE THREAD

**Issue by m-sasha** [tangrams/tangram-es#1763]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Add a marker with a bitmap to the map.

**RESULT:**

The bitmap on the map has artifacts in the corner; sometimes it's corrupted completely:

![corrupt](https://user-images.githubusercontent.com/5230206/35279214-164285a6-0055-11e8-9b7d-149179124c7a.png)

**EXPECTED:**

![good](https://user-images.githubusercontent.com/5230206/35279215-1661b0d4-0055-11e8-902a-015b167d9c9e.png)

**ENVIRONMENT:**

Nexus 4

**OTHER:**

In jniExports.cpp Java_com_here_mobility_sdk_map_MapController_nativeMarkerSetBitmap the code is:
```
JNIEXPORT bool JNICALL Java_com_here_mobility_sdk_map_MapController_nativeMarkerSetBitmap(JNIEnv* jniEnv, jobject obj, jlong mapPtr, jlong markerID, jint width, jint height, jintArray data) {
    assert(mapPtr > 0);
    auto map = reinterpret_cast<Tangram::Map*>(mapPtr);
    jint* ptr = jniEnv->GetIntArrayElements(data, NULL);
    unsigned int* imgData = reinterpret_cast<unsigned int*>(ptr);
    jniEnv->ReleaseIntArrayElements(data, ptr, JNI_ABORT);
    auto result = map->markerSetBitmap(static_cast<unsigned int>(markerID), width, height, imgData);
    return result;
}
```
So it appears that the image data is released before it's actually used, allowing the JVM to overwrite it. If the two lines before the `return` are swapped, the issue seems to go away.

**Comment by matteblair** [comment]
Hmm yes this may be an oversight on our part. Your suggested solution makes sense, I'll try it out!

**Comment by matteblair** [comment]
The Marker Bitmap functionality on Android has been rewritten since this issue was reported - I believe the problem no longer exists. Please re-open if you continue to see this problem!
