### ISSUE TITLE
Marker with tilt and perspective camera

### ISSUE THREAD

**Issue by Alex237** [tangrams/tangram-es#1764]
Hello Tangram Team :)

here my issue on tangram android some of my drawable looks malformed

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

 - Load mapview
 - use `MapController`'s function "`addMarker()`" to create a marker
 - use `setStylingFromString` to set style with : `{ style: 'ux-location-gem-overlay', sprite: 'ux-current-location', size: [76px, 76px], color: 'white', collide: false, interactive: true, flat: true, angle: 0}` (notice the "flat: true")
 - use `setDrawable` with my drawable (png image)

**RESULT:**

The drawable seems to be malformed with the perspective view and tilt on the map.
<img width="241" alt="diformed" src="https://user-images.githubusercontent.com/3592127/35524894-3e72353a-0523-11e8-9629-41c497e77627.png">

**EXPECTED RESULT:**

I expected this : 

<img width="100" alt="curseur_navigation" src="https://user-images.githubusercontent.com/3592127/35524959-69ca16a8-0523-11e8-8d0b-6e46b0099404.png">

to be more like this with the perspective and the tilt

<img width="325" alt="correctp" src="https://user-images.githubusercontent.com/3592127/35525062-b98f9032-0523-11e8-95e9-de6bd72f3a25.png">

**ENVIRONMENT:**
 - Android (Emulator) With API 23
 - I am using the lastes release version

Thank you for your help

**Comment by matteblair** [comment]
How interesting! This looks like the texture is not being rendered with [perspective-correct sampling](https://en.wikipedia.org/wiki/Texture_mapping#Perspective_correctness). I'll need to look more closely at the code for this, but I believe the quad for markers like this may be transformed for "perspective" before the vertex transformation step in hardware - which would lead to this effect. If that is the case then this may be substantial work to fix, so I can't give a timeline on resolving this yet.

**Comment by Alex237** [comment]
thank you for your answer. Is it possible to apply a temporary fix ? i can apply myself for the moment ?

**Comment by karimnaaji** [comment]
I don't believe there is a temporary fix for this issue unfortunately. Usually this artifact is relatively small but the more coverage and distortion the sprite has on screen and the more this would be visible. In order to solve this we would need to rewrite part of the label system to have CPU occlusion and GPU transforms (in order to have perspective correct UVs interpolation), right now we have CPU occlusion/transforms so all the vertices have 2d positions before being sent to the hardware.

**Comment by hjanetzek** [comment]
Hey @karimnaaji :) We had it already - almost: https://github.com/tangrams/tangram-es/pull/1768

**Comment by Alex237** [comment]
so fast, so quick :D

**Comment by matteblair** [comment]
Fix has been merged - forgot to close this issue!
