### ISSUE TITLE
Ends of linear rings are not joined

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1765]
So while playing around with shaders (from tron), I came across this situation:

![circle2](https://user-images.githubusercontent.com/4661658/35630859-b36c0520-06a2-11e8-8fb5-2bf8ed5ac921.png)

Check this tangram play setup for a minimal demo:
[**>> Demo <<**](https://tangram.city/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fe4b6909facde8cb6cbff3f44625339b1%2Fraw%2Ffb5105eb015ee678248acab99d3e9b34dfbe0b9e%2Fscene.yaml#20.00000/53.55052/9.97208)

So, the problem is that the start/end of a linear ring is not joined, at least of a `boundary: true`. There is an open end like this, which is especially visible of course if the boundary is not a solid color:

![illust](https://user-images.githubusercontent.com/4661658/35630184-0680fdda-06a1-11e8-954b-f216059f5495.png)

The same issue occurs in [Tangram-JS](https://github.com/tangrams/tangram/issues/631).

**Comment by bcamper** [comment]
Replied in https://github.com/tangrams/tangram/issues/631#issuecomment-361968308
