### ISSUE TITLE
Extruded features: Visible walls at tile edges

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1766]
More fun with fancy stuff (tangram-es 0.9.0): Additive extruded buildings. Looking at this screenshot...

![screenshot](https://user-images.githubusercontent.com/4661658/35651805-456c2624-06e1-11e8-87c6-9361e1306c2c.png)

one can see, that apparently, the buildings are split for the renderer at the tile edges. (**Edit**: removed pointless dabble about how this bug may have originated)

Possibly related: #545

**Comment by westnordost** [comment]
Also, there are some more oddities in this picture, some of the walls of buildings directly neighbouring each other are drawn (additively), some are not. Take the two identical-looking buildings just above "Schopstraße" for example: 
- ✔ The back walls of the left building's is occluded
- ❌ One tiny portion of that left building's back wall (on the right) is not occluded by the building itself, but is by the building neighbouring to the right
- ✔ the left building's right wall is occluded by the building to the right of it
- ❌ but the right building's right wall is not occluded by the building right of it.

**Comment by matteblair** [comment]
Hmm yeah there's a lot goin on here.

Have you tried the `translucent` blending option for these buildings? That seems closer to the intent for this style, if I had to guess.

**Comment by westnordost** [comment]
Yes, I tried `translucent`, but I wanted to report this bug with `add` blend mode.

**Comment by hjanetzek** [comment]
One part of the solution https://github.com/tangrams/tangram-es/pull/1769.

The other is to remove 'walls' on tile edges analog to polygon outlines - TBD.

**Comment by westnordost** [comment]
I think this is fixed with  #1820?

**Comment by matteblair** [comment]
I believe this is behaving as expected for `blend: add`, the way to prevent this "overdraw" is with `blend: translucent`.
