### ISSUE TITLE
Additive drawing: Sometimes flickers

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1767]
On my device, there is something flickering with additive drawing. See this video:

[![Screen Record](http://img.youtube.com/vi/52cIU-P62cc/0.jpg)](http://www.youtube.com/watch?v=52cIU-P62cc "Screen Record")

Device: Sony Xperia Z1 Compact
Android: 5.1
Tangram-ES: 0.9.0
Map style used: [streetcomplete-dark-style](https://github.com/ENT8R/streetcomplete-mapstyle/blob/master/streetcomplete-dark-style.yaml)

**Comment by matteblair** [comment]
My hypothesis for the flickering here is that it's a z-fighting effect caused by building features from multiple tiles overlapping. At some points when Tangram ES is loading tiles, a placeholder tile from another zoom level will be drawn to cover the area of a tile that's not yet loaded. The placeholder can also overlap with tiles that are currently loaded and draw simultaneously with them. This state is temporary and usually not too noticeable, but in this particular instance it's quite visible. 

I'd suggest trying the `translucent` blending option instead of `add`. The `translucent` option should provide better resolution of polygons by depth.

**Comment by westnordost** [comment]
> This state is temporary

Tested a bit more.
* The state is not temporary, but occurs for those buildings with zero height only in certain zoom ranges. Probably, within these ranges, the same buildings are rendered twice(?)
* does *not* occur for normal simple buildings with a height
* does *always* occur for buildings that are made up of different building part sections. I guess the z-fighting occurs here because the outside wall of buildings is on the same plane than that of the building parts

With `translucent`, this problem does not occur of course, but I meant to report a bug with `add` blend mode. It is a different effect, i.e. `translucent` is not additive.
Perhaps if there are problems with `add` that cannot likely be solved, the implementation of it could be switched out to be the same as `translucent`, only additive.

**Comment by westnordost** [comment]
One more test:
* For flat buildings, it is **only** reproducable if the view is tilted
* Actually, the general problem is not limited to additive drawing. See video (only reproducable in tilted view, as said):

[![Screen Record](http://img.youtube.com/vi/he28svR7Q0A/0.jpg)](http://www.youtube.com/watch?v=he28svR7Q0A "Screen Record")

**Comment by hjanetzek** [comment]
Hey @westnordost - I've started a branch to handle the walls and depth-buffer/add blend mode issue:
https://github.com/tangrams/tangram-es/pull/1770

If you start to show 3d buildings at source max_zoom (i.e. set source max_zoom to 16) flickering from proxy should also be gone. -- and disable `animate` unless you need a hand warmer ;)

For the roads: make sure that the layers have a different draw order. Though there is certainly some more z-fighting to fight :)

**Comment by westnordost** [comment]
I'll close this based on the fact that the issue is very old, with a very old version of tangram and the screen records I posted are not available anymore, so I am not sure if this issue still persists. Also, the WIP branch that worked on this issue was deleted.
