### ISSUE TITLE
Loading cached tile data is blocked while bad reception

### ISSUE THREAD

**Issue by RubenKelevra** [tangrams/tangram-es#1777]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

 - Open the StreetComplete app while having bad receptions, so ping time might be above 10 seconds.
 - Map appears (partly) blank
 - No new tiles are shown from the cache, while panning/zooming

**RESULT:**

The initial map view is sometimes loaded from cache and sometimes stuck directly after start. But most of the time the map start to get stuck after some tiles are already loaded. None new tiles are shown from the cache, after a long(!) while the problem disappears and maybe the reception got a bit better or there's a timeout which is reached and the connection is considered to be dead.

**EXPECTED RESULT:**

Tiles from cache should always be loaded regardless of the connection quality. If some tiles are outdated or missing, those fetches should be scheduled for a background task.

**ENVIRONMENT:**

 - What operating system and device did you produce this issue on?
Android 8.0 / ONEPLUS A5010 (OnePlus 5T)
 - If you used a released version, what is the version number?
I've been using tangram-es in 0.9.0 which is built into StreetComplete 4.0.

This ticket has been already submitted to the StreetComplete bug tracker under the number https://github.com/westnordost/StreetComplete/issues/846.

**Comment by matteblair** [comment]
Hmm it's hard to know exactly what's going on here without a reproducible test case. I have a hunch that this could be related to the timeouts used for our HTTP layer on Android (see https://github.com/tangrams/tangram-es/blob/master/platforms/android/tangram/src/main/java/com/mapzen/tangram/HttpHandler.java#L129-L131). You should try to shorten those timeout values in `HttpHandler` or create a subclass that instantiates a `OkHttpClient` with different timeouts, then see if that improves the behavior in this case. We didn't put a lot of effort into finding good values for these, so I wouldn't be surprised if they can be improved!

**Comment by RubenKelevra** [comment]
Well, I'm not a java developer, just a user. But the developer insist that this should be a bug in tangram-es not his code. So there we are.

The timeout and http stuff isn't really the problem here, I suspect.

It just seems that loading an item from cache is blocked by an operation on the network side
 So maybe one missing tile is blocking other tiles from beeing loaded or loading tiles from cache do a network operation like asking the server if they could be refreshed for example. But currently the app nearly all the time shows few or no tiles if opend on bad reception, but I know I've looked at that area just one or two days ago. After a while this bug seems to resolve itself, refreshing all tiles from cache in no time. This lead me to my assumption that there's a timeout running for an operation which then is discarded or retried, lifting the lock for other operations to happen.

**Comment by goldfndr** [comment]
A possible factor is that each of the StreetComplete tiles has a .0 file with the following line:

`Cache-Control: max-age=86400`

Is this something that the cache algorithm checks or that the tile provider has control over?

**Comment by matteblair** [comment]
The StreetComplete client can accept stale cached responses with a change on the client side, I've explained more on the original StreetComplete issue. I think this is the appropriate solution for this behavior.
