### ISSUE TITLE
iOS CocoaPods dependecy stopped working

### ISSUE THREAD

**Issue by Buthrakaur** [tangrams/tangram-es#1787]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

 - open any project with CocoaPods dependency on tangram-es (https://cocoapods.org/pods/Tangram-es)
 - clean the Pod caches `pod cache clean --all`
 - `pod install`

**RESULT:**

CocoaPods fail to install tangram-es dependency, because the server http://ios.mapzen.com is down.

```
Installing Tangram-es (0.7.2)

[!] Error installing Tangram-es
[!] /usr/bin/curl -f -L -o /var/folders/t2/07vccr413_v6dhp03zx538fr0000gn/T/d20180409-1708-vemgf4/file.zip http://ios.mapzen.com/tangram-releases/tangram-release-0.7.2.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403 Forbidden
```

**EXPECTED RESULT:**

tangram-es dependency should be installed. I understand the website is down, but CocoaPods should just stay working. Why aren't binary packages included in this github repository in releases and linked from the podspec file?

**Comment by tallytalwar** [comment]
The latest 0.9.2 release of tangram (hosted off bintray) is now available through cocoapods. https://cocoapods.org/pods/Tangram-es

Kindly let us know if this is not working for you.
Thanks
