### ISSUE TITLE
Performance issue: tangram-es seems to swap buffers a lot

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1800]
(Disclaimer: I am not proficient in OpenGL, I can only report my observation here. My deduction might be wrong)

StreetComplete v5.0 uses tangram-es 0.8.1. In the app, there seems to be a performance problem (or rather, battery usage problem) that may be caused by "something" in tangram-es.
Whenever the map is shown, on my smartphone I can reproduce a continuous CPU usage of 8-12%. When it is not shown, it's at about 0%. Most of that percentage is used by a GL thread of which I deduce that it must be the GL thread of tangram-es.

![profiler](https://user-images.githubusercontent.com/4661658/39478800-b4129ec8-4d63-11e8-86bb-958f23fd6e53.png)

Remarkably, the CPU usage does not really differ between erratically zooming and rotating the map and leaving it be.
Also, the Android profiler tells me that most of the time on that GL thread is spent in `EGLImpl.eglSwapBuffers`.

Do you have any ideas where this might come from? Or is this normal and not a bug (on either side)?

**Comment by matteblair** [comment]
Hey @westnordost, this is pretty interesting - it's not the performance profile I would expect! When the map is not moving or loading the GL thread should be asleep, the map only renders on-demand. 

This might happen if the map has an "animated" style or if the map is being modified frequently. Otherwise it could be a bug in Tangram ES. 

Is this the Android Studio profiler that you've screenshotted?

**Comment by westnordost** [comment]
Yes, it is.

I tried removing the shader code from the used map style, but this doesn't change anything.

**Comment by matteblair** [comment]
Can you try removing this line? https://github.com/westnordost/StreetComplete/blob/master/app/src/main/assets/map_theme/global.yaml#L41

**Comment by westnordost** [comment]
Ah yes, if I do that and make the compass not update anymore, the GL thread is almost silent.

The animation of rotating of the compass also triggers a complete(?) redraw, it seems.

**Comment by matteblair** [comment]
How is the compass implemented? If it's an element in the Tangram map then the only way to redraw it is to redraw the entire map. I don't think a compass really belongs _in_ the map, it should probably be in a separate view on top of the map.

**Comment by westnordost** [comment]
It is this blue triangle, like in Google Maps.

![device-2018-05-01-200519](https://user-images.githubusercontent.com/4661658/39486047-1f7d0038-4d7b-11e8-8033-f09a9dd265ee.png)

Implemented as a marker on which the following method is called on each rotation change.

```
directionMarker.setStylingFromString(
	"{ style: 'points', color: '#cc536dfe', size: [" +
	TextUtils.join(",", directionMarkerSize) +
	"], order: 2000, collide: false, flat: true, angle: " + r + " }");
```

I guess there is nothing tangram-es could do to make this more performant. 

Thinking more deeply into this, what would make it more performant if there would be a concept of completely separate layers in tangram-es, so that the map does not need to be redrawn if something on the overlay (such as a location + direction marker, or the quest pins in StreetComplete) changes. But I guess this ship has sailed.
