### ISSUE TITLE
pbfParser.cpp: In function ‘void PbfParser::extractFeature

### ISSUE THREAD

**Issue by mjjw2003** [tangrams/tangram-es#1802]
- Steps used
sudo apt-get update
sudo apt-get install cmake libcurl4-openssl-dev g++-4.9
cd ~
git clone https://github.com/tangrams/PI-GPS.git
cd PI-GPS
git submodule update --init --recursive
mkdir build
export CXX=/usr/bin/g++-4.9
cd build
cmake ..
make

**RESULT:**
pi@raspberrypi:~ $ git clone https://github.com/tangrams/PI-GPS.git
Cloning into 'PI-GPS'...
remote: Counting objects: 142, done.
remote: Total 142 (delta 0), reused 0 (delta 0), pack-reused 142
Receiving objects: 100% (142/142), 30.66 MiB | 86.00 KiB/s, done.
Resolving deltas: 100% (69/69), done.
pi@raspberrypi:~ $ cd PI-GPS
pi@raspberrypi:~/PI-GPS $ git submodule update --init --recursive
Submodule 'tangram-es' (https://github.com/tangrams/tangram-es.git) registered for path 'tangram-es'
Cloning into '/home/pi/PI-GPS/tangram-es'...
Submodule path 'tangram-es': checked out 'e58852c08068a598f5d90fa32601804cc75453aa'
Submodule 'core/include/libtess2/libtess2' (https://github.com/memononen/libtess2.git) registered for path 'tangram-es/core/dependencies/tess2/libtess2'
Submodule 'core/dependencies/yaml-cpp' (https://github.com/blair1618/yaml-cpp.git) registered for path 'tangram-es/core/dependencies/yaml-cpp'
Submodule 'core/include/fontstash-es' (https://github.com/tangrams/fontstash-es.git) registered for path 'tangram-es/core/include/fontstash-es'
Submodule 'core/include/glm' (https://github.com/g-truc/glm.git) registered for path 'tangram-es/core/include/glm'
Submodule 'core/include/isect2d' (https://github.com/tangrams/isect2d.git) registered for path 'tangram-es/core/include/isect2d'
Cloning into '/home/pi/PI-GPS/tangram-es/core/dependencies/tess2/libtess2'...
Cloning into '/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp'...
Cloning into '/home/pi/PI-GPS/tangram-es/core/include/fontstash-es'...
Cloning into '/home/pi/PI-GPS/tangram-es/core/include/glm'...
Cloning into '/home/pi/PI-GPS/tangram-es/core/include/isect2d'...
Submodule path 'tangram-es/core/dependencies/tess2/libtess2': checked out '24e4bdd4158909e9720422208ab0a0aca788e700'
Submodule path 'tangram-es/core/dependencies/yaml-cpp': checked out '2703ef784ddc0a5e488d77a7ed8dd8831b64b868'
Submodule path 'tangram-es/core/include/fontstash-es': checked out 'de034e4f4b5328f03b002ca4365353f6d08a83fe'
Submodule path 'tangram-es/core/include/glm': checked out '8b09606c7bc51b8d8ac24a2f6773cc173c4437af'
Submodule path 'tangram-es/core/include/isect2d': checked out '3ff1a433e2a344c2c76015db9baf37754587a59f'
pi@raspberrypi:~/PI-GPS $ mkdir build
pi@raspberrypi:~/PI-GPS $ cd build
pi@raspberrypi:~/PI-GPS/build $ cd ..
pi@raspberrypi:~/PI-GPS $ export CXX=/usr/bin/g++-4.9
pi@raspberrypi:~/PI-GPS $ cd build
pi@raspberrypi:~/PI-GPS/build $ cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-4.9
-- Check for working CXX compiler: /usr/bin/g++-4.9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test FLAG_WEXTRA
-- Performing Test FLAG_WEXTRA - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/PI-GPS/build
pi@raspberrypi:~/PI-GPS/build $ make
Scanning dependencies of target yaml-cpp
[  1%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o
[  2%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o
[  3%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/directives.cpp.o
[  4%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emit.cpp.o
[  5%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitfromevents.cpp.o
[  6%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitter.cpp.o
In file included from /home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/emitterstate.h:11:0,
                 from /home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/emitterutils.h:12,
                 from /home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/emitter.cpp:3:
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h: In member function ‘std::auto_ptr<YAML::SettingChangeBase> YAML::Setting<T>::set(const T&)’:
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h:53:43: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.9/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
   std::auto_ptr<SettingChangeBase> pChange(new SettingChange<T>(this));
                                           ^
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h: At global scope:
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h:78:60: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.9/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
   void push(std::auto_ptr<SettingChangeBase> pSettingChange) {
                                                            ^
[  7%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterstate.cpp.o
In file included from /home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/emitterstate.h:11:0,
                 from /home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/emitterstate.cpp:3:
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h: In member function ‘std::auto_ptr<YAML::SettingChangeBase> YAML::Setting<T>::set(const T&)’:
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h:53:43: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.9/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
   std::auto_ptr<SettingChangeBase> pChange(new SettingChange<T>(this));
                                           ^
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h: At global scope:
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h:78:60: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.9/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
   void push(std::auto_ptr<SettingChangeBase> pSettingChange) {
                                                            ^
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/emitterstate.cpp: In member function ‘void YAML::EmitterState::EndedGroup(YAML::GroupType::value)’:
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/emitterstate.cpp:152:26: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.9/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
     std::auto_ptr<Group> pFinishedGroup = m_groups.pop();
                          ^
[  8%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterutils.cpp.o
In file included from /home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/emitterstate.h:11:0,
                 from /home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/emitterutils.h:12,
                 from /home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/emitterutils.cpp:4:
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h: In member function ‘std::auto_ptr<YAML::SettingChangeBase> YAML::Setting<T>::set(const T&)’:
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h:53:43: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.9/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
   std::auto_ptr<SettingChangeBase> pChange(new SettingChange<T>(this));
                                           ^
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h: At global scope:
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/setting.h:78:60: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.9/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
   void push(std::auto_ptr<SettingChangeBase> pSettingChange) {
                                                            ^
[ 10%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/exp.cpp.o
[ 11%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/memory.cpp.o
[ 12%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node.cpp.o
[ 13%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node_data.cpp.o
[ 14%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodebuilder.cpp.o
[ 15%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodeevents.cpp.o
[ 16%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/null.cpp.o
[ 17%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/ostream_wrapper.cpp.o
[ 19%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parse.cpp.o
[ 20%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parser.cpp.o
[ 21%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/regex_yaml.cpp.o
[ 22%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanner.cpp.o
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/scanner.cpp: In member function ‘YAML::Scanner::IndentMarker* YAML::Scanner::PushIndentTo(int, YAML::Scanner::IndentMarker::INDENT_TYPE)’:
/home/pi/PI-GPS/tangram-es/core/dependencies/yaml-cpp/src/scanner.cpp:284:38: warning: ‘auto_ptr’ is deprecated (declared at /usr/include/c++/4.9/backward/auto_ptr.h:87) [-Wdeprecated-declarations]
   std::auto_ptr<IndentMarker> pIndent(new IndentMarker(column, type));
                                      ^
[ 23%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanscalar.cpp.o
[ 24%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantag.cpp.o
[ 25%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantoken.cpp.o
[ 26%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/simplekey.cpp.o
[ 28%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/singledocparser.cpp.o
[ 29%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/stream.cpp.o
[ 30%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o
[ 31%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
[ 32%] Building CXX object tangram-es/core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o
[ 33%] Linking CXX static library ../../../../lib/libyaml-cpp.a
[ 33%] Built target yaml-cpp
Scanning dependencies of target libtess2
[ 34%] Building C object tangram-es/core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/bucketalloc.c.o
[ 35%] Building C object tangram-es/core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/dict.c.o
[ 37%] Building C object tangram-es/core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/geom.c.o
[ 38%] Building C object tangram-es/core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/mesh.c.o
[ 39%] Building C object tangram-es/core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/priorityq.c.o
[ 40%] Building C object tangram-es/core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/sweep.c.o
[ 41%] Building C object tangram-es/core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/tess.c.o
[ 42%] Linking C static library ../../../../lib/liblibtess2.a
[ 42%] Built target libtess2
Scanning dependencies of target core
[ 43%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/data/dataSource.cpp.o
[ 44%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/data/geoJsonSource.cpp.o
[ 46%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/data/mvtSource.cpp.o
[ 47%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/scene/ambientLight.cpp.o
[ 48%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/scene/directionalLight.cpp.o
[ 49%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/scene/light.cpp.o
[ 50%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/scene/pointLight.cpp.o
[ 51%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/scene/scene.cpp.o
[ 52%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/scene/sceneLoader.cpp.o
[ 53%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/scene/spotLight.cpp.o
[ 55%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/style/debugStyle.cpp.o
[ 56%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/style/debugTextStyle.cpp.o
[ 57%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/style/material.cpp.o
[ 58%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/style/polygonStyle.cpp.o
[ 59%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/style/polylineStyle.cpp.o
[ 60%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/style/spriteStyle.cpp.o
[ 61%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/style/style.cpp.o
[ 62%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/style/textStyle.cpp.o
/home/pi/PI-GPS/tangram-es/core/src/style/textStyle.cpp: In member function ‘virtual void TextStyle::buildLine(Line&, StyleParams&, Properties&, VboMesh&) const’:
/home/pi/PI-GPS/tangram-es/core/src/style/textStyle.cpp:95:9: warning: unused variable ‘skipOffset’ [-Wunused-variable]
     int skipOffset = floor(lineLength / 2);
         ^
/home/pi/PI-GPS/tangram-es/core/src/style/textStyle.cpp:96:11: warning: unused variable ‘minLength’ [-Wunused-variable]
     float minLength = 0.15; // default, probably need some more thoughts
           ^
[ 64%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/tangram.cpp.o
[ 65%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/text/fontContext.cpp.o
[ 66%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/text/textBuffer.cpp.o
[ 67%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/tile/labels/label.cpp.o
[ 68%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/tile/labels/labelContainer.cpp.o
/home/pi/PI-GPS/tangram-es/core/src/tile/labels/labelContainer.cpp: In member function ‘void LabelContainer::updateOcclusions()’:
/home/pi/PI-GPS/tangram-es/core/src/tile/labels/labelContainer.cpp:57:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < m_labelUnits.size(); i++) {
                      ^
/home/pi/PI-GPS/tangram-es/core/src/tile/labels/labelContainer.cpp:110:22: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i = 0; i < m_labelUnits.size(); i++) {
                      ^
[ 69%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/tile/mapTile.cpp.o
[ 70%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/tile/tileManager.cpp.o
[ 71%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/tile/tileWorker.cpp.o
[ 73%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/util/builders.cpp.o
[ 74%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/util/error.cpp.o
[ 75%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/util/geoJson.cpp.o
[ 76%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/util/geom.cpp.o
[ 77%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/util/mapProjection.cpp.o
[ 78%] Building CXX object tangram-es/core/CMakeFiles/core.dir/src/util/pbfParser.cpp.o
/home/pi/PI-GPS/tangram-es/core/src/util/pbfParser.cpp: In function ‘void PbfParser::extractFeature(protobuf::message&, Feature&, const MapTile&, std::vector<std::basic_string<char> >&, std::vector<float>&, std::vector<std::basic_string<char> >&, int)’:
/home/pi/PI-GPS/tangram-es/core/src/util/pbfParser.cpp:105:37: error: ‘isnan’ was not declared in this scope
                     if(!isnan(numVal)) {
                                     ^
/home/pi/PI-GPS/tangram-es/core/src/util/pbfParser.cpp:105:37: note: suggested alternatives:
In file included from /home/pi/PI-GPS/tangram-es/core/include/glm/glm/detail/_fixes.hpp:33:0,
                 from /home/pi/PI-GPS/tangram-es/core/include/glm/glm/glm.hpp:81,
                 from /home/pi/PI-GPS/tangram-es/core/src/tile/labels/label.h:3,
                 from /home/pi/PI-GPS/tangram-es/core/src/tile/mapTile.h:9,
                 from /home/pi/PI-GPS/tangram-es/core/src/util/pbfParser.h:9,
                 from /home/pi/PI-GPS/tangram-es/core/src/util/pbfParser.cpp:1:
/usr/include/c++/4.9/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
/usr/include/c++/4.9/cmath:626:3: note:   ‘std::isnan’
   isnan(float __x)
   ^
tangram-es/core/CMakeFiles/core.dir/build.make:806: recipe for target 'tangram-es/core/CMakeFiles/core.dir/src/util/pbfParser.cpp.o' failed
make[2]: *** [tangram-es/core/CMakeFiles/core.dir/src/util/pbfParser.cpp.o] Error 1
CMakeFiles/Makefile2:130: recipe for target 'tangram-es/core/CMakeFiles/core.dir/all' failed
make[1]: *** [tangram-es/core/CMakeFiles/core.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
I have tried different ways of installing but had no luck. Using this method got me the furthest.

Currently running the latest raspbian stretch and using a Raspberry pi 3B

Any type of suggestion would help, Im new at this :)

Thanks

**Comment by matteblair** [comment]
Hi @mjjw2003 

It looks like you're trying to build this project: https://github.com/tangrams/PI-GPS.git which is separate from Tangram ES. The PI-GPS has not been maintained for a while, but you can try to contact @patriciogonzalezvivo for help with it. 

If you're trying to work with Tangram ES itself, please try a recent version of the code and report any problems as new issues. Thanks!
