### ISSUE TITLE
iOS issues with tilt (shove) gesture recognizer

### ISSUE THREAD

**Issue by placz** [tangrams/tangram-es#1803]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Try to disable tilting gestures by implementing (swift 4) in the GestureRecognizerDelegate

```
    func mapView(_ view: TGMapViewController, recognizer: UIGestureRecognizer,
                 shouldRecognizeShoveGesture displacement: CGPoint) -> Bool {
        return false
    }
```

**RESULT:**

This method is never called and the map can be tilted (willy-nilly :) )

**EXPECTED RESULT:**

No tilting!

**ENVIRONMENT:**

iOS 11, tangram version 0.9.2

**OTHER:**

This is just a simple typo in respondToShoveGesture; the selectors are named wrong.
```
-    if (self.gestureDelegate && [self.gestureDelegate respondsToSelector:@selector(recognizer:shouldRecognizeShoveGesture:)]) {
+    if (self.gestureDelegate && [self.gestureDelegate respondsToSelector:@selector(mapView:recognizer:shouldRecognizeShoveGesture:)]) {

-        if (self.gestureDelegate && [self.gestureDelegate respondsToSelector:@selector(recognizer:didRecognizeShoveGesture:)]) {
+        if (self.gestureDelegate && [self.gestureDelegate respondsToSelector:@selector(mapView:recognizer:didRecognizeShoveGesture:)]) {
```

I'm happy to send a pull request with the change, but haven't built/tested myself yet.
I also noticed that the _shoveGestureRecognizer.delegate is not set to self, but in gestureRecognizer:shouldRecognizeSimultaneouslyWithGestureRecognizer: there's a comment about trying to control its behavior. Should it's delegate be set to self?

**Comment by placz** [comment]
For anyone interested, there's a work-around:

In a subclass of `TGMapViewController`, you can re-assign the shoveGestureRecognizer:

```
    override func viewDidLoad() {
        super.viewDidLoad()

        // Replace the buggy shoveGestureRecognizer in the super class.
        let newShoveGestureRecognizer = UIPanGestureRecognizer(target: self, action: #selector(ignoreShoveGesture))
        newShoveGestureRecognizer.minimumNumberOfTouches = 2
        newShoveGestureRecognizer.delegate = self
        self.shoveGestureRecognizer = newShoveGestureRecognizer
    }
    
    @objc func ignoreShoveGesture(_ sender: Any) {
        // Do nothing; tilting is not allowed.
    }
```

You could do something more interesting in the selector it's calling by delegating to the original `respondtoShoveGestureAction` selector.

**Comment by matteblair** [comment]
Good catch! Fix is here: https://github.com/tangrams/tangram-es/pull/1804
