### ISSUE TITLE
Setting 2D position doesn't always make target position visible

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#181]
When the position of the map view is set to a 2D location, the location of the virtual camera is placed directly above that position on the ground. If the camera is tilted off of the z-axis, the point in the center of the screen isn't the position that was set (and often the targeted position won't even be visible). 

The simplest fix for this is to add a function that sets the "view focus" instead of just the position and let the library calculate the appropriate position for the camera. 

@ecgreb Would this be useful?

**Comment by ecgreb** [comment]
Useful yes but not a must have at this time. We typically reset zoom/tilt/rotation when setting the map position anyway.

**Comment by blair1618** [comment]
Resolved: https://github.com/tangrams/tangram-es/pull/289
