### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [tangrams/tangram-es#1850]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [destroy](https://github.com/tangrams/tangram-es/blob/868fe92cb315b390046d7d31e44c8f4fcb2b50f3/platforms/common/glfwApp.cpp#L202 "destroy function")
- [main](https://github.com/tangrams/tangram-es/blob/79e9498fd379cc06f310c62680ae1dbdd4791c7e/platforms/rpi/src/main.cpp#L179 "main function")
- [MeshBase](https://github.com/JakobEngel/dso/blob/f6e43e277a8e6f606265c1d90fd7549e475e6ea6/src/OptimizationBackend/AccumulatedSCHessian.h#L54 "Destructor for MeshBase")

**Comment by matteblair** [comment]
@elfring Are you a bot?

**Comment by cleeus** [comment]
I think he is -- looking at his profile, all totally pointless issues, some of them nonesense.
I admire the cleverness of the bot author, though.
