### ISSUE TITLE
Flickering on zooming out with controller.setZoomEased

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1867]
While zooming out via `controller.setZoomEased` on Android 5.1 with tangram-es 0.9.6 but possibly since always, the map shows nothing for a **few** frames at certain zoom levels. When zooming in and out a lot via this method (\*cough* StreetComplete), this can become quite disruptive.

A video shows more than thousand words: https://www.westnordost.de/misc/zoom-in-zoom-out.mp4
If you skip through here frame-by-frame, you will notice that at certain frames, the map is suddenly empty and in the next frame, everything is as normal again.

I cannot reproduce the issue when I zoom in and out manually (using the zoom gesture with my fingers), even if I do this very fast.

![screenshot](https://user-images.githubusercontent.com/4661658/45184436-30620900-b227-11e8-90e6-531ccf4ca511.png)
![screenshot](https://user-images.githubusercontent.com/4661658/45184496-58516c80-b227-11e8-885c-03a82e426642.png)

**Comment by westnordost** [comment]
Also, not sure if this is separate bug, if so, say so: If you skip through the video frame-by-frame, you will notice that there is also **one frame at the very start of the zoom-into-to animation where the final frame of the animation is visible**.

![screenshot](https://user-images.githubusercontent.com/4661658/45184306-e4af5f80-b226-11e8-9c1b-d42b81157cc0.png)

**Comment by matteblair** [comment]
🤔 
I suspect that the tile flickering and the single-frame-zoom-jump are different issues, but both are weird and I'll try to reproduce them.

**Comment by tallytalwar** [comment]
We might have already addressed these with the newer camera animation interface work in 0.9.7-SNAPSHOT.

**Comment by matteblair** [comment]
To try out the snapshot versions first add the jfrog snapshot repo to your Gradle dependency config:
```gradle
dependencies {
  repositories {
    maven {
      url "https://oss.jfrog.org/libs-snapshot/"
    }
  }
}
```
And then use the snapshot version in your module dependencies:
```gradle
dependencies {
  implementation 'com.mapzen.tangram:tangram:0.9.7-SNAPSHOT'
}
```
Be warned however that this snapshot represents a fairly big version change and there are some **major** API changes between this version and the last published version.

**Comment by westnordost** [comment]
Ah, well, it cannot be that much, I will try out the new version and report back.

**Comment by tallytalwar** [comment]
Thanks, while you are at it, will also welcome some feedback :D.

**Comment by westnordost** [comment]
Hmm, a bit of feedback on the new api changes regarding the camera:

- Not sure if it is a good idea to create an object for every update. Couldn't it be that updates are happening every frame? (For example a frantic compass sensor that rotates the map, or `flyTo` is using CameraUpdate under the hood as well perhaps?)
- I do not see any reason why the CameraUpdate must be a factory. This seems unnecessarily verbose and also _limiting_, because I cannot easily (or not at all?) get a CameraUpdate object that both zooms and rotates. CameraUpdate could just have public getters and setters. And if it should be immutable or for convenience, I suggest the builder pattern: I.e. `CameraUpdate upd = new CameraUpdate.Builder().rotateBy(30).tilt(10).zoom(15).moveTo(lng,lat).create()`
- the relation between CameraUpdate and CameraPosition is a bit unclear (to me)
- analogous to Android animation framework(s), wouldn't it make sense to store the information about animation-to duration (and interpolator?, etc) also in the CameraUpdate object?

**Comment by westnordost** [comment]
- If I want to just change the current rotation, before it was `controller.setRotation(...)`, now it is 		`CameraPosition p = controller.getCameraPosition();` p.rotation = ...; controller.updateCameraPosition(CameraUpdateFactory.newCameraPosition(p));`. That seems to be needlessly verbose. Why not at least `controller.getCameraPosition().setRotation(...)` for the simple things that do not involve animations or several changes at once? (And even for several changes at once, if no animation, animation callback etc. is involved, an interface like `controller.getCamera().setRotation(...); controller.getCamera().setTilt(...)` would be very convenient.)

**Comment by matteblair** [comment]
Hey thanks for the feedback! Some of those bullet points have good answers and others might be reasons to change things:
- It probably isn't a good idea to create new objects every frame - I expected camera updates to be relatively infrequent! We can probably make things better for frequent updates, but if your compass is making changes at 60Hz then maybe tell it to chill out :)
- We made a factory for camera updates because in general updates are not compose-able. Some updates make sense to combine, but if you combine a `newLatLngBounds` update with a `zoomBy` update then the result depends on the order they are applied. For the most general case you can just create an arbitrary camera position (though yeah - it's more verbose than before).
- Camera update and position are probably a little confusing: a camera update effectively transforms one camera position to a new camera position
- Android animation frameworks aren't really suitable for our renderer because they animate on the UI thread and we render on a separate GL thread
 - If you want to just change the current rotation, it's an easy one-liner:
```
controller.updateCameraPosition(CameraUpdateFactory.setRotation(radians));
```

**Comment by westnordost** [comment]
> If you want to just change the current rotation, it's an easy one-liner:
> controller.updateCameraPosition(CameraUpdateFactory.setRotation(radians));

Hmm but that is still much longer than before. The inner workings may have changed, but shouldn't the interface be as concise as possible? If updates are not composable, I do not get the reason to move from a concise interface to a, well, verboser one.

**Comment by westnordost** [comment]
Anyway, `</feedback>`, back to the topic:

**I tried it out and the flickering as described in this ticket definitely exists in 0.9.7-SNAPSHOT as well.** 

Regarding the first frame being already at the zoom target (mentioned in first reply), this seems to be gone in 0.9.7-SNAPSHOT.

**Comment by matteblair** [comment]
🙏 Thank you for all the feedback and testing! Seriously, it's high-quality feedback.

That flickering is probably a bug in the proxy tile logic - the tiles at the lower zoom level are clearly loaded already, so there should be no visible gap in coverage.

**Comment by westnordost** [comment]
I haven't been able to reproduce #1772 so far on my smartphone with debuggable libtangram.so, but I noticed that the flickering-problem is much worse then. So, the slower the device, the more apparent this issue.
This hints to that perhaps there is no real bug as such but the way zooming is implemented isn't able to keep up when the zoom level changes very fast. 
What happens when the thread doing rendering and/or loading the tiles can't keep up? Are the render results per tile and zoom cached as bitmaps?

**Comment by westnordost** [comment]
Sadly, still same behavior in 0.11.2.

However I further analyzed this behavior and found out what triggers it. I opened a new ticket with better information here: #2131
