### ISSUE TITLE
Marker.setBitmap seems to be very slow

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1896]
So I have been looking into the cold start performance of my app with the Android profiler and noticed that a big portion seems to be due to Tangram-ES:

![performance](https://user-images.githubusercontent.com/4661658/46744235-04fd8e80-ccab-11e8-8c6a-8ffe0985f6e8.png)
**How to read this chart?** It's a timeline, the first row is the seconds that passed, the Y-axis drills down on which method was on the call stack at that time. Of course, measuring the performance this way somewhat slows down the app, so it wouldn't really be 5.5 seconds just to set two marker bitmaps.

**What bitmap is set?**
direction marker (96x96 dp): https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/drawable-xxhdpi/location_direction.png
accuracy marker (256x256 dp): https://github.com/westnordost/StreetComplete/blob/master/app/src/main/res/drawable/accuracy_circle.xml

**How to measure start-up performance?** Set a breakpoint on the first line of the `onCreate` method of your application class, start the app in debug, wait for the breakproint to trigger, go to Android Studio's Profiler tab, click on CPU, click on Record, go back to the Debug tab and continue. Then, in the record, you can move and zoom in/out on what method executed when and how long.

**Device**: Sony Xperia Z1 Compact
**Android Version**: 5.1.1
**Tangram Version**: 0.9.6

**Comment by westnordost** [comment]
Also, according to the profiling record, note that the time tangram-ES spends off the main thread to asynchronously initialize the map (`getMapAsync`) seems to be smaller than the time `getMapAsync` needs on the main thread.

**Comment by westnordost** [comment]
I am not sure if the Android profiler also shows functions in native code, my guess is not. However, already the Java code could be improved. For a 256x256 dp bitmap, I see already around 589824 unnecessary divisions and 589824 unnecessary modulo operations for a screen with a high screen density (xxhdpi = x3).

**Comment by matteblair** [comment]
We could just move these Bitmap calculations into native code - should be noticeably faster in c++ where we can skip array bounds checks and such.

Or we could just use `GLUtils.texImage2D` directly on the Bitmap https://developer.android.com/reference/android/opengl/GLUtils.html#texImage2D(int,%20int,%20android.graphics.Bitmap,%20int)

**Comment by westnordost** [comment]
I ran some tests and it looks like less than half of the time spent in `Marker.setBitmap` is due to the for-loop mentioned in #1897. 

Also, I have the impression that the Android profiler slows down at least the mentioned for-loop somewhat more than other things. E.g. to iterate through this for-loop on my phone for a 396x396 bitmap takes 100ms, but 2000ms when the profiler is recording. In other words, the chart posted in the initial post might skew things somewhat.

**Comment by westnordost** [comment]
So, maybe you could close this issue as my claim that `Marker.setBitmap` is exceptionally slow is not well proven. Though, my pull request is a small performance improvement nonetheless.
