### ISSUE TITLE
iOS (maybe android?) Feature Request: Callback to indicate rendering completed

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#1911]
Right now, the only indication we have entered a "completed" state from Tangram-es on iOS is `mapViewDidCompleteLoading` from the delegate callback here:https://github.com/tangrams/tangram-es/blob/master/platforms/ios/framework/src/TGMapViewDelegate.h#L114

While this works well, the documentation states that it's ` Called after the view completes loading all content in the current view.` is not 100% accurate as it's called as soon as the map is moved, and every time a tile load completes, which can be hundreds of calls if the map is actively panning / zooming.

This is actually fine behavior as it's good to have indication of when individual tile requests complete, but it would be nice to have a "steady state" or "fully rendered" state of a map viewport callback fired that is called less often and might be a good place for doing heavy lifting tasks developers don't want to do while say the map is animating between two places and tiles haven't finished loading yet.

Also, we should probably update the documentation to indicate `mapViewDidCompleteLoading` is called more frequently than the header docs might indicate :)

**Comment by matteblair** [comment]
Well the docs don't say that `mapViewDidCompleteLoading` is called _once_ after the view completes loading :P but I can see how this could be misconstrued.

We could change the implementation to trigger only on the "rising edge" of this state, like you describe. Or maybe instead we should just have a `mapViewIsLoading` property that you could query - would that be more useful?

**Comment by msmollin** [comment]
I think it's more useful to indicate that a steady state has been reached. Not sure I follow the rising edge thought as I'm not 100% familiar with the internal workings that this callback is an indicator of. I need to compare how some other implementations do this, but being notified via callback and reacting to that is much easier to deal with on iOS and is more what developers tend to expect. 

Like I said I think it's useful to also have the current behavior, although I think it could be better named like `mapViewDidLoadTileForViewport` or something similar.

**Comment by matteblair** [comment]
Resolved by https://github.com/tangrams/tangram-es/pull/1937 - now the "view complete" event is triggered only when the map goes from "loading" to "complete".
