### ISSUE TITLE
Marker.setDrawable does not handle screen density.

### ISSUE THREAD

**Issue by polar** [tangrams/tangram-es#1925]
1. Have a phone with a screen density of 3.374 (Motorola Moto4)
2. Create a Bitmap Drawable with a bitmap at the same target density (540Dpi).
    Say bitmap is 540x540 pixels. 
3. Marker.setDrawable(bitmap).

Expected Result:

Marker should be about an inch high and wide.

Actual Result:

Marker is significantly larger than the screen.

This is an issue especially for Text drawing functions. Scaling the drawn bitmap down to an acceptable size is ugly. I want to be able to draw a bitmap at the current screen resolution and get it displayed at that resolution.

I find this a problem with that `nativeSetMarkerBitmap()` does not take into account a density parameter, which would eventually be handed off to the `Texture` constructor. 

I solved this problem by adding a `float density` parameter to the following calls:

    JNIEXPORT jboolean JNICALL Java_com_mapzen_tangram_MapController_nativeMarkerSetBitmap(JNIEnv* jniEnv, jobject obj, jlong mapPtr, jlong markerID, jobject jbitmap, jfloat density)
    ---\calls/----
    bool Map::markerSetBitmap(MarkerID _marker, int _width, int _height, const unsigned int* _data, float _density)
    ---\calls/----
    bool MarkerManager::setBitmap(MarkerID markerID, int width, int height, const unsigned int* bitmapData, float density) {
         ...\calls/...
          auto texture = std::make_unique<Texture>(width, height, options, false, density)
         ...
    }
  
It is invoked by `Marker.java` using:

    public boolean setDrawable(final int drawableId) {
        DisplayMetrics metrics = context.getResources().getDisplayMetrics();
        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inTargetDensity = metrics.densityDpi;
        Bitmap bitmap = BitmapFactory.decodeResource(context.getResources(), drawableId, options);
        return setBitmap(bitmap, metrics.density);
    }
    public boolean setDrawable(@NonNull final Drawable drawable) {
        DisplayMetrics metrics = context.getResources().getDisplayMetrics();

        float screenDensity = metrics.density;
        int density = context.getResources().getDisplayMetrics().densityDpi;
        BitmapDrawable bitmapDrawable = (BitmapDrawable) drawable;
        bitmapDrawable.setTargetDensity(density);
        Bitmap bitmap = bitmapDrawable.getBitmap();
        bitmap.setDensity(density);
        return setBitmap(bitmap, screenDensity);
    }

I'd submit a pull request for this issue, but first I wanted to check if there are any ramifications concerning this setting of a drawable, or do we need a special function to handle such cases? Also, how would it affect iOS?

**Comment by matteblair** [comment]
Good catch - thanks for tracking down the cause of this. I think this is just an oversight, probably not enough testing of different Drawables when this was implemented. A PR for this would be welcome!

**Comment by polar** [comment]
Will do.
