### ISSUE TITLE
Init in .mm not in .h

### ISSUE THREAD

**Issue by brianLeeson** [tangrams/tangram-es#1933]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

 - Look at [TGMapView.h](https://github.com/tangrams/tangram-es/blob/master/platforms/ios/framework/src/TGMapView.h)
 - Look at [TGMapView.mm](https://github.com/tangrams/tangram-es/blob/master/platforms/ios/framework/src/TGMapView.mm)
 - See that `initWithCoder` is only defined in the .mm and not the header

**RESULT:**

Everything works fine. 

**EXPECTED RESULT:**

Everything works fine. 

**ENVIRONMENT:**

Not Applicable

**OTHER:**

I'm wondering if leaving `initWithCoder` out of the header and internal header was an oversight. I'm still able to refer to that init in my swift code, so no problems here. If `initWithCoder` is intentionally left out of the headers, why? I am willing to try and make a PR to fix it if this is an omission.

**Comment by matteblair** [comment]
The declaration of `initWithCoder` is inherited from `UIView`, so there shouldn't be any problems using it. I think it was left out of the header because there isn't any reason for user code to call it.

**Comment by brianLeeson** [comment]
Thank you for the explanation! As this was intentional and not a mistake, I am closing this issue.
