### ISSUE TITLE
0.10: Bugs with getEnclosingCameraPosition (Android)

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#1961]
I am trying to use the new method `MapController.getEnclosingCameraPosition`, unfortunately, it is not always working as expected. 

I observed the following issues with this method:
1. it sets the tilt always to 0
2. it sets the rotation always to 0
3. it (tries to set) the zoom to something above the previously set maximumZoomLevel. Not sure if this is intended or not
4. **it often does not position the center correctly**. See this video as an example: https://www.westnordost.de/misc/getEnclosingCameraPosition.mp4

Regarding 4, I have not been able to find out any regularity for when the function works correctly and when not. The method I use in my code is this (shortened for easier read):
```java
	private void zoomAndMoveToContain(ElementGeometry geometry)
	{
		BoundingBox objectBounds = geometry.getBounds();
		LngLat sw= TangramConst.toLngLat(objectBounds.getMin());
		LngLat ne= TangramConst.toLngLat(objectBounds.getMax());
		CameraPosition position = controller.getEnclosingCameraPosition(sw, ne, padding);
		controller.updateCameraPosition(CameraUpdateFactory.newCameraPosition(position), 500);
	}
```
`padding` is a Rect with `top=0, left=0, bottom=600, right=0` (in portrait mode)

One thing I can definitely say is that the given padding is ignored when getting the enclosing camera position for point features (`sw==nw`). Perhaps the bug has something to do with point 3? (On zoom level ∞, the lnglat center position would need to be offsetted only by <img src="https://wikimedia.org/api/rest_v1/media/math/render/svg/f096e2ddf75824f09c6b8c85b00c41b3d40a698e"/> degrees to meet the padding.)

**Comment by westnordost** [comment]
If you want to have a quick look at the code, I [pushed the migration on a branch](https://github.com/westnordost/StreetComplete/tree/tangram-0.10/app/src/main/java/de/westnordost/streetcomplete/tangram) (see `QuestsMapFragment.java` and its parent class `MapFragment.java`). The current head of the branch also runs out of the box.

**Comment by matteblair** [comment]
Hmmmm it could be that something implicitly assumes that `sw != ne`. I'll check this out.

**Comment by westnordost** [comment]
Thanks for the fix!

Point 1 and 2 is not fixed though. Did you overlook that our is this intended?

**Comment by matteblair** [comment]
Oh sorry I forgot to address those points. That behavior is known and intentional. You can modify the `tilt` and `rotation` fields of the `CameraPosition` that is returned from `getEnclosingCameraPosition` to change the final view. The caveat is that if the `tilt` or `rotation` is modified, the final view might not actually enclose the original bounding box. Finding a view with an arbitrary orientation that encloses a bounding box is beyond the scope of this method - though we may add a method to support this in the future.

**Comment by westnordost** [comment]
Exactly. Rotating and tilting afterwards will make the element not actually contained anymore.

The use case is that the user oriented the map in a random rotation and tilt (for example in a navi-like view, rotating map according to view direction or simply rotated so with  the figure gesture) and then wants to zoom to a certain map feature.
It would appear very disrupting if the map would then suddenly rotate 180 degrees in the worst case. The user expects that the map stays as it is, only the view flies to enclose the given bbox.
(This is my use case)

Am 12. Dezember 2018 00:10:29 MEZ schrieb Matt Blair <notifications@github.com>:
>Oh sorry I forgot to address those points. That behavior is known and
>intentional. You can modify the `tilt` and `rotation` fields of the
>`CameraPosition` that is returned from `getEnclosingCameraPosition` to
>change the final view. The caveat is that if the `tilt` or `rotation`
>is modified, the final view might not actually enclose the original
>bounding box. Finding a view with an arbitrary orientation that
>encloses a bounding box is beyond the scope of this method - though we
>may add a method to support this in the future.

**Comment by matteblair** [comment]
I think I understand the problem you want to solve. This is a complicated and pretty specific operation. To my knowledge, no major map API has built-in support for this. Tangram may support this in the future, but that isn't the intended goal of this method.

**Comment by westnordost** [comment]
What is the intended goal for this method?

Currently I do solve this problem by myself in StreetComplete, woth a caveat. It's not THAT complex when you assume that increasing zoom level by one will result in an object being displayed 4 times the size and the other way round. 


Am 12. Dezember 2018 01:20:11 MEZ schrieb Matt Blair <notifications@github.com>:
>I think I understand the problem you want to solve. This is a
>complicated and pretty specific operation. To my knowledge, no major
>map API has built-in support for this. Tangram may support this in the
>future, but that isn't the intended goal of this method.
