### ISSUE TITLE
Crash in Map::OnMemoryWarning

### ISSUE THREAD

**Issue by Developers-Here-Mobility** [tangrams/tangram-es#1968]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

this crash can be easily reproduced in iOS/XCode by using
1.  "Simulate Memory Warnings" option in Simulator
2. An application that uses TGMapView
3. add observer for : UIApplicationDidReceiveMemoryWarningNotification in TGMapView.
3. Invoke "Simulate Memory Warnings" in transition to Map view controller (that uses TGMapView).

**RESULT:**
Runtime crash:
Crashed: com.apple.main-thread
0  HereSDKMapKit                  0x1051d50f4 Tangram::FontContext::releaseFonts() + 28
1  CoreFoundation                 0x21858e928 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
2  CoreFoundation                 0x21858e8f4 ___CFXRegistrationPost_block_invoke + 64
3  CoreFoundation                 0x21858dde4 _CFXRegistrationPost + 392
4  CoreFoundation                 0x21858da90 ___CFXNotificationPost_block_invoke + 96
5  CoreFoundation                 0x218505d70 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1404
6  CoreFoundation                 0x21858d51c _CFXNotificationPost + 696
7  Foundation                     0x218f9dc10 -[NSNotificationCenter postNotificationName:object:userInfo:] 

**EXPECTED RESULT:**
Memory should be released without any stability issues

**ENVIRONMENT:**
- XCode 9.4
- Simulator : IPhone 8
- Used iOS Demo + adding memorywarning observer in TGMapView

#1967

**Comment by matteblair** [comment]
Hey @Developers-Here-Mobility thanks for the high-quality issue report, we really appreciate it!
