### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Lecrapouille** [tangrams/tangram-es#1980]
Just a small error (I'm using Debian 64bits):

```
tangram-es/platforms/common/linuxSystemFontHelper.cpp:46:36: error: ‘FC_COLOR’ was not declared in this scope
         if (FcPatternGetBool(font, FC_COLOR, 0, &w) != FcResultMatch ||
```
I just commeted this line and compilation finished with sucess

**Comment by matteblair** [comment]
Thanks for the heads up! Seems like the `FC_COLOR` constant doesn't exist in all versions of FontConfig, we should be able to conditionally remove it with an `#ifdef`.

**Comment by Lecrapouille** [comment]
ok this is compiling fine now !
