### ISSUE TITLE
Out of date documentation.

### ISSUE THREAD

**Issue by brianLeeson** [tangrams/tangram-es#1995]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Go to TGSceneUpdate.h for iOS
https://github.com/tangrams/tangram-es/blob/master/platforms/ios/framework/src/TGSceneUpdate.h

Lines 30 and 31

**RESULT:**

Find functions that don't exist anymore.
Either `queueSceneUpdates` and `applySceneUpdates` aren't methods of TGMapView anymore or they are really good hiders, cause I can't find them.

**EXPECTED RESULT:**

Up to date swift example. Probably with a `loadScene`

**ENVIRONMENT:**

The iOS platform

**OTHER:**

Please correct me if I am misunderstanding something!

**OTHER UPDATES NEEDED:**
1. [flyToCameraPosition](https://github.com/tangrams/tangram-es/blob/6a8333b859f68ebb6e2286132d4436cbf157265c/platforms/ios/framework/src/TGMapView.h#L233) is missing a @param for duration. I can guess at what that variable does though. :P

2. `TGGestureDelegate` should be `TGRecognizerDelegate` [here](https://github.com/tangrams/tangram-es/blob/master/platforms/ios/framework/src/TGRecognizerDelegate.h#L14) and [here](https://github.com/tangrams/tangram-es/blob/master/platforms/ios/framework/src/TGRecognizerDelegate.h#L212)

3. I think [this](https://github.com/tangrams/tangram-es/blob/master/platforms/ios/framework/src/TGMarker.h#L89) should be `maker.stylingString` as marker does not have a `styling` member

**Comment by matteblair** [comment]
You're right - that example code is outdated! The function to use for that now is `updateSceneAsync` (https://github.com/tangrams/tangram-es/blob/master/platforms/ios/framework/src/TGMapView.h#L164). Thanks for the heads up, I'll make sure this gets fixed in the next release.

**Comment by brianLeeson** [comment]
I found another line of documentation that could be updated. I could find more in the future. I don't think they all deserve their own issue. I will add them to this issue until this issue is closed as some future date. Does that seem reasonable?

**Comment by matteblair** [comment]
Yep sounds good. Thanks!

**Comment by matteblair** [comment]
Resolved by https://github.com/tangrams/tangram-es/commit/9f511231ba5d4fb2cb4710e765033a47e46b605f
