### ISSUE TITLE
Add zoom_offset data source parameter for down-sampling data

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-es#2019]
Tangram ES sister issue to the new Tangram JS functionality in https://github.com/tangrams/tangram/pull/685.

From the JS release notes:

- In some circumstances, the default tiles for a source may be either too large (in file size) or too detailed (in feature density or coordinate precision) than needed for the current application. The new `zoom_offset` data source parameter allows the user to request lower zooms for each zoom level, reducing tile size and visual detail.
- For example, a `zoom_offset: 1` will down-sample the tile data (for both vector and raster sources) by one level, e.g. at zoom 12, zoom 11 tiles will be loaded instead.
- Note: sources with `tile_size: 512` already do this implicitly, loading one level lower than the typical Web Mercator "view" zoom level; any `zoom_offset` for these data source is applied in addition to the tile size adjustment, e.g. `zoom_offset: 1` with `tile_size: 512` will request tiles from two zoom levels earlier (but the 512px tiles will have been designed to not show any loss in visual detail from the first zoom subtraction).
- An example showing Mapzen terrain normal tiles with `zoom_offset: 1` (as compared to full detail), automatically generalizing the terrain while also lowering network bandwidth:

![image](https://user-images.githubusercontent.com/16733/51883976-53669400-2353-11e9-9241-9de27eea6f6d.gif)

**Comment by tallytalwar** [comment]
Addressed by #2026
