### ISSUE TITLE
Android | set 'blend: overlay' with Marker.setStylingFromString()

### ISSUE THREAD

**Issue by marcamorin** [tangrams/tangram-es#2029]
I'm trying to put blend=overlay to polygon using "Marker.setStylingFromString":

code:

String json = {"width":"0px","interactive":true,"style":"polygons","blend":"overlay","collide":false,"color":"hsla(180,100%,25%, 10%)","order":997,"visible":true}
this.marker.setStylingFromString(json);

result: 

D/Tangram: WARNING styleParam.cpp:130: Unknown StyleParam draw:blend:overlay

What I'm doing wrong? Thanks in advance

**Comment by polar** [comment]
Unfortunately, I've discovered the same thing. You have to create a style, such as 
`styles:
   overlay_polygons:
       base: polygons
       blend: overlay`

You can modify your scene files, adding this style, or by using UpdateScene.

**Comment by marcamorin** [comment]
Thanks @polar !

**Comment by tallytalwar** [comment]
Yeah `blend` is not a draw rule but a style property, hence you will have to define a new style with the required `blend` value.

Good community engagement here, thanks @polar :D
