### ISSUE TITLE
loadScene does not generate error on auth failure.

### ISSUE THREAD

**Issue by brianLeeson** [tangrams/tangram-es#2031]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

 - Download the most recent tangram-es
 - Put in a valid API key, build/run the demo. Verify that the demo app and map work.
 - Put in an invalid API key. The app should not load a map.
 - Add a break point at the start of `mapViewDelegate.didLoadScene:withError`
 - Be confused when `sceneError` is nil, when it should be -1 as the scene didn't load.

**RESULT:**

`mapViewDelegate.didLoadScene:withError` did not catch an authentication error while loading a scene with bad apikey

**EXPECTED RESULT:**

I expected `sceneError` to be -1 as the scene file could not be loaded due to my deliberately incorrect API key.

**ENVIRONMENT:**

 - Mac 10.14, xcode 10, simulated iphone XR

**OTHER:**
Is failing auth not an error that tangram is attempting to catch?

xcode output
https://hastebin.com/raw/vasisajejo

**Comment by matteblair** [comment]
Hey @brianLeeson thanks for the A+ issue report!

Short answer: `sceneError` is behaving as intended in this case.

Long answer: Tangram is designed to be agnostic to platforms and services like those that you would provide an API key for. From the engine's perspective the API key is just a parameter to add to tile URLs. So in your example, the scene is loaded successfully and no `sceneError` is reported. Then when Tangram tries to retrieve map tiles with the API key in the scene, the tile endpoint returns an authentication error. In general there could be many reasons for such an error, we can't say for sure that it's an invalid API key. 

For an iOS project you may be able to intercept these sorts of errors yourself by providing a custom `TGURLHandler` that checks for authentication errors on responses and reacts appropriately. Does this make sense to you?

**Comment by brianLeeson** [comment]
Hey thank you! I try to make the reports comprehensible! Glad it worked.

I think I understand what you're say. So if I want to go about handling that auth failure error (or any other tile retrieval error) I would be able to see that an error occurred by checking `error` in a `TGDownloadCompletionHandler`? Thanks! I'll runs some tests and give it a shot!

**Comment by brianLeeson** [comment]
Actually I don't think I'm understanding what you mean here. Looking in [TGURLHandler](https://github.com/tangrams/tangram-es/blob/master/platforms/ios/framework/src/TGURLHandler.h#L34). I understand that we should make a something that implements this protocol, but how would we define the `completionHandler` argument when the map view is calling `downloadRequestAsync` automatically? Wont the map view then be defining what the `completionHandler` looks like? Or should I be the one calling `downloadRequestAsync` before loading a scene?

**Comment by matteblair** [comment]
What I meant is that you can create an implementation of `TGURLHandler` that performs some other logic in response to network errors. For example:
```objective-c
@interface CustomURLHandler : TGDefaultURLHandler
@end

@implementation CustomURLHandler
- (NSUInteger)downloadRequestAsync:(NSURL *)url completionHandler:(TGDownloadCompletionHandler)completionHandler
{
    TGDownloadCompletionHandler wrapper = ^void (NSData* data, NSURLResponse* response, NSError* error) {
        if (error) {
            // TODO: Respond to the error!
        }
        completionHandler(data, response, error);
    };

    return [super downloadRequestAsync:url completionHandler:wrapper];
}
@end
```

Then pass this in as the `urlHandler` when you initialize your `TGMapView`

**Comment by brianLeeson** [comment]
Thank you! This is very helpful! As far as I can tell I've got the wrapper function being called when different error occur.

For future humans, I've translated the objective-c into what I believe to be its swift equivalent (I'm in swift).

```Swift
public class CustomURLHandler: TGDefaultURLHandler {

    public override func downloadRequestAsync(_ url: URL, completionHandler: @escaping TGDownloadCompletionHandler) -> UInt {

        let wrapper: TGDownloadCompletionHandler = {
            data, urlResponse, error in
            if error != nil {
                // TODO: Respond to the error!
            }
            completionHandler(data, response, error)
        }
        return super.downloadRequestAsync(url, completionHandler: wrapper)
    }
}
```
