### ISSUE TITLE
Android | Line render error

### ISSUE THREAD

**Issue by marcamorin** [tangrams/tangram-es#2038]
I've problems with Lines when I create Line using Map.addMarker(). 

Large line:
If line is large and I do zoom in the lines disappear.

Small line
if line is small and I do zoom in the line modifies the width on map.

Code for reproduce it:

On Android demo (MainActivity) replace:

            Map<String, String> props = new HashMap<>();
            props.put("type", "line");
            props.put("color", "#D2655F");

            List<LngLat> line = new ArrayList<>();
            line.add(lastTappedPoint);
            line.add(tappedPoint);
            markers.addPolyline(line, props);

for this

            String style = "{\"width\":\"3px\",\"color\":\"red\",\"order\":500,\"style\":\"lines\",\"visible\":true}";

            List<LngLat> line = new ArrayList<>();
            line.add(lastTappedPoint);
            line.add(tappedPoint);
            Marker lineMarker = map.addMarker();
            lineMarker.setPolyline(new Polyline(line, new HashMap<String, String>()));
            lineMarker.setStylingFromString(style);

screenshots:
![device-2019-02-15-094647](https://user-images.githubusercontent.com/46893633/52845940-a2a91480-3108-11e9-867b-64359e41a310.png)

![device-2019-02-15-094711](https://user-images.githubusercontent.com/46893633/52845953-ab99e600-3108-11e9-9247-9b7bca3fcccc.png)

![device-2019-02-15-094725](https://user-images.githubusercontent.com/46893633/52845965-afc60380-3108-11e9-9050-8abb14f8ff7d.png)

vidio:

[record.zip](https://github.com/tangrams/tangram-es/files/2868537/record.zip)

Thanks!

**Comment by vilinet** [comment]
Its happening on my side as well, really irritating.
This should be a 5px wide line, but its totally huge!

  String lineStyle = "{ style: 'lines', color: '#06a6d4', width: '5px', order: 2000 }";
   lineMarker.setPolyline(new Polyline(taps, null));

![Untitled (1)](https://user-images.githubusercontent.com/13279531/54449139-540d8b00-4745-11e9-81cd-739f8017c445.png)

**Comment by vilinet** [comment]
As i see its happening at least since Release 0.10.0, i couldnt built the older releases.

**Comment by vilinet** [comment]
Here is the fix: https://pastebin.com/TEk68XVb
I dont know why is modelScale added or why, but with the old marker->extent() it just works well.

**Comment by matteblair** [comment]
Hey @vilinet thanks for checking this out. I believe there was a reason we didn't use `extent()` in these cases (it might have broken some other use case) but I will find out why.

**Comment by vilinet** [comment]
Would be nice to find out. This error shows up when the zoom level is kinda high. As closer you go down, the line getting enormously wider.

**Comment by mee-marcin** [comment]
Hi @matteblair, are there any updates for that? I am facing the same problem as @vilinet and would be happy to get the real fix or at least some reasoning for why you stopped using the extent() in favour of modelScale(). Thanks!

**Comment by tallytalwar** [comment]
Hi @vilinet 

Thanks for debugging this and suggesting a fix. It seems like we had the markers use the `extent` to begin with, but @cleeus found some interesting polygon vertex wrapping issues (#1639) which lead to a fix (#1776) for that specific problem. 

Clearly, there is a regression here, as it popped up this issue you and others are running into. 

I think the solution might involve a different approach which should address #1639 along with this issue. I will investigate this more and see if I can come up with a good solution.

Thanks

**Comment by wcrestfield** [comment]
Hi @tallytalwar 
I'm not sure that we need a different approach, so much as better follow through with using `modelScale()` instead of `extent()` in polylineStyle.cpp.

**Comment by tallytalwar** [comment]
In order for us to cut a new release and avoid a regression, I am going to revert the changes from #1776 (sorry @cleeus) and open another issue that describes the behavior we have discovered here. 

@wcrestfield Maybe the solution here is to refactor polylineStyle, but currently adding the 3rd-dimensional complexity to already not so trivial marker system (something what #1776 was doing) might not be the right approach, plus I do not think we ever thought marker system will be used in the way it's being used right now :D. We have been meaning to refactor the annotation system and with that the marker API for some time now, and cutting a major release will get us started on the same.

Thanks to everyone here for being patient, tangram-es project currently is in parttime dev mode, hence the noticed slowness!

**Comment by wcrestfield** [comment]
@tallytalwar I don't think polylineStyle needs a refactor.  The regression stemmed from using `extent()` in some places instead of `modelScale()`.  I haven't verified extrusion, but https://pastebin.com/SKEJFmNK resolves the line width issue.

**Comment by tallytalwar** [comment]
@wcrestfield Thanks, I can give this a try later. Also extrusion examples are specifically related to Polygon styles, so I am not sure. Again I need to verify and collect more thoughts here before I can concretely answer on the correct solution.
