### ISSUE TITLE
Ensure that Android apps using Tangram comply with Play Store 64-bit requirement

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#2044]
> Starting August 1, 2019, your apps published on Google Play will need to support 64-bit architectures.

https://developer.android.com/distribute/best-practices/develop/64-bit

Published Tangram AARs currently include libraries for the `armeabi-v7a` ,`arm64-v8a`, and `x86` ABIs. `x86_64` has been omitted because there are exceedingly few Android devices using this ABI and including it adds substantially to the size of the AAR. However, this might mean that apps using current published Tangram AARs do not meet the upcoming 64-bit requirement for the Play Store. 

I can see 2 ways to ensure that apps using Tangram meet the new requirement:

1. __Add x86_64 libraries to the published AAR.__ This will definitely comply with the new requirement but at the cost of a larger AAR, leading to larger APK sizes for developers who don't split their APK per ABI. The new [App Bundle](https://developer.android.com/platform/technology/app-bundle/) distribution format will mitigate this size increase for apps, but may not be suitable for all projects. There's also [APK splits](https://developer.android.com/studio/build/configure-apk-splits), which has been around longer. We can offer guidance for developers to use these methods to mitigate app size.

2. __Remove x86 libraries from the published AAR.__ The documentation page linked above says: _It is not required to support every 64-bit architecture, but for each native 32-bit architecture you support you must include the corresponding 64-bit architecture._  Therefore we should be in compliance if we only include `armeabi-v7a` and `arm64-v8a` libraries in our AAR. We currently include an `x86` library to support emulators, which typically use `x86` for better performance on PC hardware.

I'm currently in favor of option 1 (it just seems safer to me) but the first step should be trying a build with all four ABIs included to see how much of a difference it makes.

**Comment by matteblair** [comment]
AAR sizes for ABI combinations:
- `armeabi-v7a`, `arm64_v8a`, `x86`, `x86_64` (option 1): 10.6MB
- `armeabi-v7a`, `arm64_v8a`, `x86` (current configuration): 7.6MB
- `armeabi-v7a`, `arm64_v8a` (option 2): 4.7MB

**Comment by westnordost** [comment]
Does any release contain this already? As of today, I am getting a warning that starting February 2020, it will not any more be possible to update an existing app that does not both provide `arm64_v8a` and `x86_64`.

https://developer.android.com/distribute/best-practices/develop/64-bit

**Comment by tallytalwar** [comment]
Ahh none at the moment, we wanted to cut a release but our ci was failing,
Matt fixed it last week and we should be cutting a new release soonish.

**Comment by westnordost** [comment]
The deadline of February 2020 is moving closer. Any plans yet when the next release will come out?

**Comment by tallytalwar** [comment]
Soo...onish :D @westnordost
