### ISSUE TITLE
Local reference table overflow when more than 512 tiles were tried to be loaded, WITH FIX ATTACHED

### ISSUE THREAD

**Issue by vilinet** [tangrams/tangram-es#2050]
I am just tried to use the latest map, browsing tiles, and the errors just pops out
Issue came with this commit: https://github.com/tangrams/tangram-es/commit/795347c713c7f349b3cb466af3b86e529034813a?diff=split

Solution:
in androidPlatform.Cpp:308, 
jniEnv->DeleteLocalRef(jUrl) is missing to remove the local reference.

Locally i tested it and works perfectly after this line addition.

**Comment by vilinet** [comment]
Here is the patch file for latest master, as i dont have write to create branch: 
https://pastebin.com/S8J5SpNZ

**Comment by nvkelso** [comment]
Fix in https://github.com/tangrams/tangram-es/pull/2051.
