### ISSUE TITLE
Tangram::LngLat::operator == (...) must be const.

### ISSUE THREAD

**Issue by Hsilgos** [tangrams/tangram-es#2061]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

1. Create two const objects of type LngLat
2. Compare them

const LngLat lngLat1, lngLat2;
assert(lngLat1 == lngLat2);

**RESULT:**

Compilation error, attempt to call non-const method on const object.

**EXPECTED RESULT:**

Compilation success.

**ENVIRONMENT:**

Any OS and device.
Version of Tangram from master.

**OTHER:**

https://github.com/tangrams/tangram-es/blob/c323375f6249a655ddb3684d5f09770a1f58aeee/core/include/tangram/util/types.h#L27

**Comment by matteblair** [comment]
@Hsilgos good catch! Fix should be merged shortly.
