### ISSUE TITLE
Android demo app crashing

### ISSUE THREAD

**Issue by mkandulavm** [tangrams/tangram-es#2062]
[tangram-es-android.log](https://github.com/tangrams/tangram-es/files/3194919/tangram-es-android.log)
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
- install android studio 3.4
- Follow android setup instructions to run demo app

**RESULT:**
- app crashes with following error
2019-05-19 13:57:02.603 32373-32448/com.mapzen.tangram.android E/Tangram: Error in font.xml parsing: END_TAG expected (position:START_TAG (empty) <axis tag='wdth' stylevalue='100.0'>@351:51 in java.io.InputStreamReader@d000c7e) 
2019-05-19 14:09:29.073 3209-3305/com.mapzen.tangram.android A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7428706d616c63 in tid 3305 (RenderThread), pid 3209 (tangram.android)

**EXPECTED RESULT:**

demo app should run without crashes

**ENVIRONMENT:**

android studio 3.4
android compileSdkVersion 28
Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
[tangram-es-android.log](https://github.com/tangrams/tangram-es/files/3194903/tangram-es-android.log)
[tangram-es-android.log](https://github.com/tangrams/tangram-es/files/3194920/tangram-es-android.log)

**OTHER:**
log output is attached.

**Comment by matteblair** [comment]
Ah damn. This is an error in the Android Font XML file parsing, and it is not altogether surprising. The XML files where Android devices store their lists of available font faces do not have a stable format. Parsing these files in an application is not recommended, but it was the best solution we found to loading font files from the device. This must be a device with a new format that we don't support in our parsing code :\

The best solution would be to find a new way to list the font files available on a device, but I don't think that's going to be easy.

In the short term we should at least catch any errors like this and try to proceed as best we can without a list of font files. I'll see if I can fix that quickly.

**Comment by matteblair** [comment]
@mkandulavm What device(s) produced these crash logs?

**Comment by mkandulavm** [comment]
@matteblair Thanks for the quick reply !! :)

I found this issue in samsung note 8 running android version 9. I have not tried it in other devices.
However, I got same error by running emulator with android 9 , API Q.

**Comment by mkandulavm** [comment]
@matteblair Can you let me know if there is way ?
I am also not able to generate a crash dump in android to analyze the trace. Could you help me on that ?

**Comment by mkandulavm** [comment]
Bug not related to SDK. Was unable to detect easily an exit(1) in native code  :(

**Comment by matteblair** [comment]
Thanks for your investigation! :+1:

**Comment by marcamorin** [comment]
@mkandulavm @matteblair I found the same bug on v0.12.0.

How can I solve it?

Thanks!

**Comment by matteblair** [comment]
@marcamorin The crash reported here was found to be unrelated to the Tangram SDK, so you probably have a different problem. 

Can you please open a new issue and share any logs you are able to collect as attachments? Thanks!
