### ISSUE TITLE
Crash an Android during scene loading.

### ISSUE THREAD

**Issue by Hsilgos** [tangrams/tangram-es#2064]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

My Android application is built with tangram and i have a lot of automated tests.
All files with styles are hardcoded built in to apk. Access to Tangram::map is synchronized.

**RESULT:**

**Sometimes** I have following crash during my tests:

********** Crash dump: **********
Build fingerprint: 'google/sdk_gphone_x86_64/generic_x86_64:9/PSR1.180720.093/5456446:userdebug/dev-keys'
#00 0x0000000004a52eeb /data/app/com.test.myapp -Y_QSPnLFHS_UW5JU7HIq2g==/lib/x86_64/lib---.so
YAML::detail::node* YAML::detail::node_data::get<YAML::detail::string_view, 1>(YAML::detail::string_view const&, YAML::detail::ref_holder<YAML::detail::memory_ref, true>&) const
---/tangram-es/core/deps/yaml-cpp/include/yaml-cpp/node/detail/impl.h:101:14
#01 0x0000000004a520af /data/app/com.test.myapp-Y_QSPnLFHS_UW5JU7HIq2g==/lib/x86_64/lib---.so
YAML::detail::node* YAML::detail::node::get<YAML::detail::string_view>(YAML::detail::string_view const&, YAML::detail::ref_holder<YAML::detail::memory_ref, true>&) const
---/tangram-es/core/deps/yaml-cpp/include/yaml-cpp/node/detail/node.h:114:51
#02 0x0000000004a51dc0 /data/app/com.test.myapp-Y_QSPnLFHS_UW5JU7HIq2g==/lib/x86_64/lib---.so
YAML::Node::get(YAML::detail::string_view const&) const
---/tangram-es/core/deps/yaml-cpp/src/node.cpp:26:68
#03 0x000000000241bb9c /data/app/com.test.myapp-Y_QSPnLFHS_UW5JU7HIq2g==/lib/x86_64/lib---so
YAML::Node const YAML::Node::operator[]<char [7]>(char const (&) [7]) const
---/tangram-es/core/deps/yaml-cpp/include/yaml-cpp/node/impl.h:422:10
#04 0x0000000002502fc1 /data/app/com.test.myapp-Y_QSPnLFHS_UW5JU7HIq2g==/lib/x86_64/lib---.so
Tangram::StyleContext::initFunctions(Tangram::Scene const&)
---/tangram-es/core/src/scene/styleContext.cpp:103:21
#05 0x0000000002a681f2 /data/app/com.test.myapp-Y_QSPnLFHS_UW5JU7HIq2g==/lib/x86_64/lib---.so
Tangram::TileBuilder::init()
---/tangram-es/core/src/tile/tileBuilder.cpp:28:21
#06 0x000000000270913e /data/app/com.test.myapp-Y_QSPnLFHS_UW5JU7HIq2g==/lib/x86_64/lib---.so
Tangram::TileWorker::run(Tangram::TileWorker::Worker*)
---/tangram-es/core/src/tile/tileWorker.cpp:53:26
#07 0x000000000270e890 /data/app/com.test.myapp-Y_QSPnLFHS_UW5JU7HIq2g==/lib/x86_64/lib---so
decltype(*(std::__ndk1::forward<Tangram::TileWorker*>(fp0)).*fp(std::__ndk1::forward<Tangram::TileWorker::Worker*>(fp1))) std::__ndk1::__invoke<void (Tangram::TileWorker::*)(Tangram::TileWorker::Worker*), Tangram::TileWorker*, Tangram::TileWorker::Worker*, void>(void (Tangram::TileWorker::*&&)(Tangram::TileWorker::Worker*), Tangram::TileWorker*&&, Tangram::TileWorker::Worker*&&)
/Users/---/Projects/dependencies/AndroidSDK/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/type_traits:4291:1
#08 0x000000000270e699 /data/app/com.test.myapp-Y_QSPnLFHS_UW5JU7HIq2g==/lib/x86_64/lib---.so
void std::__ndk1::__thread_execute<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (Tangram::TileWorker::*)(Tangram::TileWorker::Worker*), Tangram::TileWorker*, Tangram::TileWorker::Worker*, 2ul, 3ul>(std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (Tangram::TileWorker::*)(Tangram::TileWorker::Worker*), Tangram::TileWorker*, Tangram::TileWorker::Worker*>&, std::__ndk1::__tuple_indices<2ul, 3ul>)
/Users/---/Projects/dependencies/AndroidSDK/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/thread:342:5
#09 0x000000000270dfb4 /data/app/com.test.myapp-Y_QSPnLFHS_UW5JU7HIq2g==/lib/x86_64/lib---.so
void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (Tangram::TileWorker::*)(Tangram::TileWorker::Worker*), Tangram::TileWorker*, Tangram::TileWorker::Worker*> >(void*)
/Users/---/Projects/dependencies/AndroidSDK/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/thread:352:5
#10 0x0000000000092bab /system/lib64/libc.so (__pthread_start(void*)+27)
#11 0x000000000002af2d /system/lib64/libc.so (__start_thread+61)

**EXPECTED RESULT:**

No crash

**ENVIRONMENT:**
 - Tangram: master
 - NDK: 20.0.5392854-beta2
 - Android emulator, info:

Name: TESTING_API_28
CPU/ABI: Google APIs Intel Atom (x86_64)
Path: /Users/***/.android/avd/TESTING_API_28.avd
Target: google_apis [Google APIs] (API level 28)
Skin: pixel_2_xl
SD Card: 10G
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: pixel_2_xl
hw.lcd.width: 1440
hw.initialOrientation: Portrait
image.androidVersion.api: 28
tag.id: google_apis
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: TESTING_API_28
hw.gpu.mode: auto
hw.ramSize: 1024
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 2880
vm.heapSize: 384
skin.dynamic: yes
hw.device.manufacturer: Google
hw.gps: yes
hw.audioInput: yes
image.sysdir.1: system-images/android-28/google_apis/x86_64/
showDeviceFrame: yes
hw.camera.back: virtualscene
AvdId: TESTING_API_28
hw.lcd.density: 560
hw.arc: false
hw.device.hash2: MD5:ce72d6c2506218ad8c9cc1cfa7e13357
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
disk.dataPartition.size: 10G
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes

**OTHER:**

UPD: My fix with memory fences didn't help

**Comment by Hsilgos** [comment]
Hey, seems that fix which I proposed earlier fixes this issue also: https://github.com/tangrams/tangram-es/issues/2071
At least it never produced after it

**Comment by matteblair** [comment]
I believe this has been fixed by #2073
