### ISSUE TITLE
fatal error: curl/curl.h: No such file or directory

### ISSUE THREAD

**Issue by Lecrapouille** [tangrams/tangram-es#2069]
This is more a remark, than a real bug, but is CMake not supposed to check if `curl` is present on the system? Because I did not install it and got this error `fatal error: curl/curl.h: No such file or directory`

The fix is only `apt-get install  libcurl4-openssl-dev` but I think CMake is made for checking against missing libs.

**Comment by matteblair** [comment]
Good point! We're just adding `curl` as a link dependency for the Linux target but it would be better practice to use `find_package` so that the missing dependency is detected at configuration time.
