### ISSUE TITLE
xcode's sanitiser caught "stack-use-after-scope" issue while loading scene

### ISSUE THREAD

**Issue by Hsilgos** [tangrams/tangram-es#2071]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

1. Build tangram for ios with sanitizer enabled:
    How to enable sanitizer: Product->Scheme->Edit Scheme->Run
    Enable "Address Sanitizer" and "Detect use of stack after return" there

2. Load scene

**RESULT:**

Sanitizer stops app with error:

> ==84528==ERROR: AddressSanitizer: stack-use-after-scope on address 0x70000c1415c0 at pc 0x00010e74e99e bp 0x70000c141090 sp 0x70000c141088
> READ of size 8 at 0x70000c1415c0 thread T15

 and shows callstack:

>     #0 0x10e74e99d in YAML::detail::ref_holder<YAML::detail::memory_ref, true>::operator!=(YAML::detail::ref_holder<YAML::detail::memory_ref, true> const&) const ptr.h:60
>     #1 0x10e74ef6b in YAML::Node::isValid() const node.h:144
>     #2 0x10e74ed98 in YAML::Node::IsDefined() const impl.h:81
>     #3 0x10e731bc4 in YAML::Node::operator!() const node.h:58
>     #4 0x10e787be4 in YAML::Node::operator void (*)(YAML::detail::unspecified_bool::NOT_ALLOWED*)() const node.h:57
>     #5 0x10e798ab8 in Tangram::SceneLoader::loadTexture(std::__1::pair<YAML::Node, YAML::Node> const&, Tangram::SceneTextures&) sceneLoader.cpp:499
>     #6 0x10e797910 in Tangram::SceneLoader::applyTextures(YAML::Node const&, Tangram::SceneTextures&) sceneLoader.cpp:451
>     #7 0x10e72f30a in Tangram::Scene::load() scene.cpp:152
>     #8 0x10e62934a in Tangram::Map::Impl::loadSceneAsync(Tangram::SceneOptions&&)::$_1::operator()() const map.cpp:175
>     #9 0x10e6292cc in decltype(std::__1::forward<Tangram::Map::Impl::loadSceneAsync(Tangram::SceneOptions&&)::$_1&>(fp)()) std::__1::__invoke<Tangram::Map::Impl::loadSceneAsync(Tangram::SceneOptions&&)::$_1&>(Tangram::Map::Impl::loadSceneAsync(Tangram::SceneOptions&&)::$_1&&&) type_traits:4339
>     #10 0x10e62927c in void std::__1::__invoke_void_return_wrapper<void>::__call<Tangram::Map::Impl::loadSceneAsync(Tangram::SceneOptions&&)::$_1&>(Tangram::Map::Impl::loadSceneAsync(Tangram::SceneOptions&&)::$_1&&&) __functional_base:349
>     #11 0x10e625c90 in std::__1::__function::__func<Tangram::Map::Impl::loadSceneAsync(Tangram::SceneOptions&&)::$_1, std::__1::allocator<Tangram::Map::Impl::loadSceneAsync(Tangram::SceneOptions&&)::$_1>, void ()>::operator()() functional:1562
>     #12 0x10d31422d in std::__1::function<void ()>::operator()() const functional:1913
>     #13 0x10e6041be in Tangram::AsyncWorker::run() asyncWorker.h:59
>     #14 0x10e607e3b in decltype(*(std::__1::forward<Tangram::AsyncWorker*>(fp0)).*fp()) std::__1::__invoke<void (Tangram::AsyncWorker::*)(), Tangram::AsyncWorker*, void>(void (Tangram::AsyncWorker::*&&)(), Tangram::AsyncWorker*&&) type_traits:4280
>     #15 0x10e607c7d in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (Tangram::AsyncWorker::*)(), Tangram::AsyncWorker*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (Tangram::AsyncWorker::*)(), Tangram::AsyncWorker*>&, std::__1::__tuple_indices<2ul>) thread:342
>     #16 0x10e606c78 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (Tangram::AsyncWorker::*)(), Tangram::AsyncWorker*> >(void*) thread:352
>     #17 0x12216e2ea in _pthread_body (libsystem_pthread.dylib:x86_64+0x32ea)
>     #18 0x122171248 in _pthread_start (libsystem_pthread.dylib:x86_64+0x6248)
>     #19 0x12216d40c in thread_start (libsystem_pthread.dylib:x86_64+0x240c)

**EXPECTED RESULT:**

No any issues

**ENVIRONMENT:**

 - iOS 12, xcode
 - Tangram version: latest master

**OTHER:**

The problem is this line:
https://github.com/tangrams/tangram-es/blob/931a12e2262bb064c92e0c1da371456b5a556b50/core/src/scene/sceneLoader.cpp#L496

yaml iterator operator-> returns proxy object which keeps copy of Node and looks like this:
> struct proxy {
>     explicit proxy(const V& x) : m_ref(x) {}
>     V* operator->() { return std::addressof(m_ref); }
>     operator V*() { return std::addressof(m_ref); }
> 
>     V m_ref;
>   };

proxy has "V* operator->"  which returns pointer to internal value, so when you call "it->second" it returns pointer to object which is deleted right after this line, you shouldn't keep reference to it.

So fix is trivial, save it to value:
const Node sprite = it->second;

**Comment by matteblair** [comment]
Aha! It's very easy to see the problem now. I'll get this fixed shortly.

Thank you for the excellent issue report :)
