### ISSUE TITLE
builds are failing according to the readme badges

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/tangram-es#2078]
See https://github.com/tangrams/tangram-es#platform-targets

**Comment by matkoniecz** [comment]
Seems to be at least partially fixed by #2076

**Comment by matteblair** [comment]
Yeah this is a real annoyance. The builds are able to complete successfully, but something about one of the Ruby tools we use to build the iOS docs has broken in our CI environment.

**Comment by matteblair** [comment]
Resolved by #2076
