### ISSUE TITLE
Raspberry Pi platform is not updated.

### ISSUE THREAD

**Issue by RochiGH** [tangrams/tangram-es#2096]
config.make is not ok , I had to patch it with : 
1 - commenting # add_subdirectory(platforms/common/duktape)
2 - I had to change add_resources(tangram "${PROJECT_SOURCE_DIR}/scenes" "res")

in building , I got some platform compatibilty issues : 
[ 98%] Building CXX object CMakeFiles/tangram.dir/platforms/rpi/src/main.cpp.o
In file included from /home/pi/tangram-es/platforms/rpi/src/main.cpp:4:0:
/home/pi/tangram-es/platforms/rpi/src/rpiPlatform.h:19:22: error: 'Tangram::UrlRequestHandle Tangram::RpiPlatform::startUrlRequest(Tangram::Url, Tangram::UrlCallback)' marked 'override', but does not override
     UrlRequestHandle startUrlRequest(Url _url, UrlCallback _callback) override;
                      ^~~~~~~~~~~~~~~
/home/pi/tangram-es/platforms/rpi/src/rpiPlatform.h:20:10: error: 'void Tangram::RpiPlatform::cancelUrlRequest(Tangram::UrlRequestHandle)' marked 'override', but does not override
     void cancelUrlRequest(UrlRequestHandle _url) override;
          ^~~~~~~~~~~~~~~~
/home/pi/tangram-es/platforms/rpi/src/main.cpp: In function 'int main(int, char**)':
/home/pi/tangram-es/platforms/rpi/src/main.cpp:122:22: error: 'struct Tangram::UrlClient::Options' has no member named 'numberOfThreads'
     urlClientOptions.numberOfThreads = 4;
                      ^~~~~~~~~~~~~~~
/home/pi/tangram-es/platforms/rpi/src/main.cpp:153:27: error: no matching function for call to 'Tangram::Map::Map(std::shared_ptr<Tangram::RpiPlatform>&)'
     map = new Map(platform);

/usr/include/c++/6/ext/new_allocator.h:120:4: error: invalid new-expression of abstract class type 'Tangram::RpiPlatform'
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }

**Comment by wegherfe** [comment]
Hello RochiGH. I have the same issue. I am using Raspberry PI 3.

My feeling is that rpi platform is not maintained up-to-date and aligned with platform and core code. Too many cmake/make errors are due to changes in function/method signatures.

**Comment by matteblair** [comment]
Hey! Thanks for documenting the current breakage on Raspberry Pi. I admit that it's not as well maintained as the other platforms. The big problem with it is the difficulty in running automated builds and tests on the RPi - if we had that then we would know immediately when something breaks and be able to fix it right away.

Do either of you know of a good solution for automated Raspberry Pi builds? Just yesterday I discovered that we might be able to run builds using Docker images like this one: https://hub.docker.com/r/raspbian/jessie but I haven't tested it out yet.

**Comment by wegherfe** [comment]
Hello.

In order to cross-compile using Docker, I followed this [guide](https://hub.docker.com/r/mitchallen/pi-cross-compile/), which provides a Docker image with RaspPI toolchain.
Since Tangram needs cmake, I had to create my own image, like in this Dockerfile:

```
FROM mitchallen/pi-cross-compile

RUN apt-get update && apt-get install -y vim cmake pkg-config
```

Then I built it and ran it like this:

```bash
docker build -t rpi .
docker run -it -v /work/tmp/tangram-es/tangram-es:/build rpi bash
```

From the console, I started the build:

```bash
root@ce3b6dd6b9df:/build# mkdir -p mybuild
root@ce3b6dd6b9df:/build# cd mybuild/
root@ce3b6dd6b9df:/build/mybuild# cmake -DTANGRAM_PLATFORM=rpi ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type configuration: 
-- Including platform CMake config file: platforms/rpi/config.cmake
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'fontconfig'
--   No package 'fontconfig' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
  platforms/rpi/config.cmake:14 (pkg_check_modules)
  CMakeLists.txt:68 (include)


-- Configuring incomplete, errors occurred!
See also "/build/mybuild/CMakeFiles/CMakeOutput.log".
```

As you see, it stops because fontconfig is not detected. The Docker image has no RaspPI SDK inside. The only solution is to add fontconfig, and any other dependency, to the tangram-es project and build it.

If you bypass the problem, my commenting line `platforms/rpi/config.cmake:14`and run cmake again, you will get the same errors reported by RochiGH:

```
root@ce3b6dd6b9df:/build/mybuild# cmake -DTANGRAM_PLATFORM=rpi ..
-- Build type configuration: 
-- Including platform CMake config file: platforms/rpi/config.cmake
CMake Error at platforms/rpi/config.cmake:16 (add_subdirectory):
  add_subdirectory given source "platforms/common/duktape" which is not an
  existing directory.
Call Stack (most recent call first):
  CMakeLists.txt:68 (include)


CMake Error at platforms/rpi/config.cmake:58 (add_resources):
  add_resources Macro invoked with incorrect arguments for macro named:
  add_resources
Call Stack (most recent call first):
  CMakeLists.txt:68 (include)


-- Performing Test FLAG_WEXTRA
-- Performing Test FLAG_WEXTRA - Success
-- Creating directory /build/mybuild/core/deps/harfbuzz-icu-freetype/freetype/include/freetype/config
-- Creating file /build/mybuild/core/deps/harfbuzz-icu-freetype/freetype/include/freetype/config/ftconfig.h
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Creating file /build/mybuild/core/deps/harfbuzz-icu-freetype/freetype/include/freetype/config/ftoption.h
-- harfbuzzfreetypeicucommon
-- Looking for GLM
-- GLM include /build/core/deps/glm
-- CMake version: 3.5.1
-- CMAKE_CXX_COMPILER '/usr/bin/c++' 'GNU' '5.4.0'
-- CMAKE_CXX_FLAGS                ''
-- CMAKE_CXX_FLAGS_RELEASE        '-O3 -DNDEBUG'
-- SQLITECPP_RUN_CPPLINT OFF
-- SQLITECPP_RUN_CPPCHECK OFF
-- SQLITECPP_RUN_DOXYGEN OFF
-- SQLITECPP_BUILD_EXAMPLES OFF
-- SQLITECPP_BUILD_TESTS OFF
-- Configuring incomplete, errors occurred!
See also "/build/mybuild/CMakeFiles/CMakeOutput.log".
```

I think having a working Docker image to cross-compile tangram is worth, independently on the issue for which this post was created.

Hope this helps.

**Comment by matteblair** [comment]
@rwrx I recently got that error about the `fontconfig` package too. I think the problem is that we need the `dev` package, not just the binaries. I fixed it by installing `libfontconfig1-dev`. If that works for you too then I'll add it to the build dependencies in the README.
