### ISSUE TITLE
Polyline not going through anti-meridian

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#2102]
Hello, when I draw polyline with these two coordinates:

(202.0798142905279, 21.32412098661676), (140.3857509038345, 35.77296590017364)

and also:

(-158.0798142905279, 21.32412098661676), (140.3857509038345, 35.77296590017364)

Tangram is drawing it in opposite way, not through Pacific ocean but, throught Atlantic ocean. In Google Maps library this is working properly, maybe they are using algorithm when drawing polyline around earth to use the shortest distance line. Could this be fixed in Tangram? Or I can do it by myself if you give me some hints where I can find code for this. Thank you.

**Comment by matteblair** [comment]
Just to clarify, are you creating a polyline marker with these coordinates or is this in GeoJSON data?

**Comment by rwrx** [comment]
Hi @matteblair I am creating creating it using MapController.addDataLayer().

**Comment by matteblair** [comment]
I'm not able to reproduce the issue as described. In the Android demo app, I added a test polyline:
```
        mapData = map.addDataLayer("touch");

        List<LngLat> testLinePoints = Arrays.asList(
                new LngLat(202.0798142905279, 21.32412098661676),
                new LngLat(140.3857509038345, 35.77296590017364)
        );

        Map<String, String> testLineProps = new HashMap<>();
        testLineProps.put("type", "line");
        testLineProps.put("color", "#D2655F");

        Polyline polyline = new Polyline(testLinePoints, testLineProps);

        mapData.setFeatures(Collections.singletonList((Geometry)polyline));
```
And saw the line rendered across the antimeridian as expected:
![Screenshot_20191117-122855](https://user-images.githubusercontent.com/3371850/69013596-ccb98c80-094f-11ea-86de-3bc6d21e4714.png)

When polylines are created this way, we transform them into a set of tiled geometry using geojson-vt-cpp, which has logic to split and duplicate features over the antimeridian (thanks Mapbox!). 

It's possible that Tangram ES used to include an older version of geojson-vt-cpp that did not use this logic. What version of Tangram ES produced this issue for you?

**Comment by rwrx** [comment]
Hi @matteblair I am sorry, there was a problem somewhere else, my app is also using Google LatLng class which is wrapping longitude values and does not allow a values larger than 180 and smaller than -180, so it converted that longitude 202.0798142905279 to -158.0798142905279 which caused Tangram to not properly show this line. I am sorry for this, I must fix it another way.

**Comment by rwrx** [comment]
I still have a question for this. In my app I basically need for coordinates:

List<LngLat> testLinePoints = Arrays.asList(
        new LngLat(-158.0798142905279 , 21.32412098661676),
        new LngLat(140.3857509038345, 35.77296590017364)
);

to go through anti-meridian. So I want to modify code for Tangram-ES polyline rendering in my fork so it will compute the shortest distance to next point and it won't go all around the globe as it is now. In Google Maps API for Android they have solved this somehow - I think that they are computing the shortest distance. Could I ask you for a hints where this polyline rendering code is so I can modify it in this way in my fork of Tangram-ES? Thank you a lot.

**Comment by matteblair** [comment]
It does seem like the GMaps API determines polyline segment "wrapping" based on the direction of shortest longitude change. I don't agree with this design decision, as it arbitrarily forbids you from creating a polyline segment with a longitude span of 180+ degrees. BUT if you really need to imitate this behavior here's what I'd do:

Before sending your sequence of coordinates to a Tangram polyline, adjust them like this.
```
if (current.longitude - previous.longitude > 180) {
  current.longitude -= 360;
} else if (current.longitude - previous.longitude < -180) {
  current.longitude += 360;
}
```
No need to modify any code inside Tangram, you can implement this in your own application code.

**Comment by rwrx** [comment]
@matteblair thank you a lot.
