### ISSUE TITLE
Alternative to MapController.updateSceneAsync

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#2107]
I have noticed that `MapController.updateSceneAsync` is missing for a quite some time in MapController. Is there an alternative way to do scene updates? Thank you.

**Comment by matteblair** [comment]
Use `MapController$loadSceneFileAsync(sceneFilePath, sceneUpdateList)`.
(https://github.com/tangrams/tangram-es/blob/master/platforms/android/tangram/src/main/java/com/mapzen/tangram/MapController.java#L319)

"Updating" a scene is the same as re-loading a scene with a new set of updates. `updateSceneAsync` was implemented this way, so we just made the operation more explicit.
