### ISSUE TITLE
AndroidX annotations

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#2109]
Is planned to change library for Android annotations to AndroidX library https://developer.android.com/jetpack/androidx/releases/annotation? It is only needed to change library in gradle dependencies and also change imports. I can do this and make a pull request if you want.

**Comment by matteblair** [comment]
Seems updating to use AndroidX would be a good practice, I just haven't gotten around to it yet. A PR for this would be welcome!

**Comment by rwrx** [comment]
Closing via #2110
