### ISSUE TITLE
Animated scenes no longer works

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#2114]
I have tried to show Tron style in latest version of Tangram-ES and unfortunately animations does not work. In scene styling it is set `animated: true` but the scene is animated only when camera is moving. Could I ask you to verify this?

**Comment by matteblair** [comment]
I just tried out the `tron` style on macOS and animation was working as expected. Did you observe this on a specific platform target?

**Comment by rwrx** [comment]
Thank you. I am sorry, it was my bad. I was testing it on Android and Linux. Recently I have updated to Tangram ES 0.11.1 and noticed that Tron style is not animated (I have a fork). Before update of Tangram ES animations were working. Now I have noticed that there were some updates to Tron style which are not in my fork, so I have updated Tron style and now it is working. I did not expected that there could be a problem in Tron style as I have updated Tangram ES and before updating it it worked.

**Comment by matteblair** [comment]
Oh good, thanks for figuring that out.

I'm also curious why animation would have stopped working - were there errors from Tangram in the log?

**Comment by bcamper** [comment]
It's a result of https://github.com/tangrams/tron-style/pull/160, and tightening up the animation logic such that we only animate the current view when needed (when animated styles are in view).

**Comment by tallytalwar** [comment]
I remember this. Thanks @rwrx for doing the legwork of finding this.
