### ISSUE TITLE
Problem with long in AndroidMap::pickMarker on armv7 devices

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#2115]
I have two devices NVIDIA SHIELD Tablet K1 - https://www.gsmarena.com/nvidia_shield_k1-7832.php and Huawei Y360-U61 - https://www.gsmarena.com/huawei_y360-7077.php which are armv7 devices (by CPU-Z app). But on these devices callback to java method `MapController.markerPickCallback` from C++ method `AndroidMap::pickMarker` corrupts long value in Java and the Java method `MapController.markerPickCallback` has wrong value of `markerId` parameter. When I rewrite data type for `markerID` variable in `AndroidMap::pickMarker` and also static casting to `long long` it is working properly. I am not sure what is doing "behind scene" and I am not sure if this is a proper fix. I think that you will know what is causing this issue. I have also tested it on other devices: Google Pixel, Nexus 5X, Nexus 5 and Honor 8X and it is working properly on these devices.

**Comment by matteblair** [comment]
Aha, thank you for this report! With the clue about `AndroidMap::pickMarker` and 32-bit CPUs I was able to track down a couple bugs.

**Comment by rwrx** [comment]
Thank you a lot. Your changes does solve it. So this issue could be closed.
