### ISSUE TITLE
ClientDataSources removed after sceneupdate

### ISSUE THREAD

**Issue by sheikh-iffi** [tangrams/tangram-es#2117]
Hi all

I am currently facing issue regarding scene update. Whenever I add a clientsource and call loadSceneAsync to update a color, clientsource gets removed. I think this is due to the fact that loadSceneAsync makes a new scene and removes older tiles. Can you tell me what should I do to retain these clientsources.

**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
Add any clientsource (In my case I have drawn a line)
Call scene update through loadSceneAsync 

**RESULT:**

Clientsource gets removed

**EXPECTED RESULT:**

Clientsource should not be removed no matter how many times I update the scene

**Comment by matteblair** [comment]
Hey @sheikh-iffi thanks for the report. I've confirmed this behavior, and it's not intended. Tracking down the cause now.
