### ISSUE TITLE
Support GlobalGeodetic 4326 tile

### ISSUE THREAD

**Issue by ccxxbb** [tangrams/tangram-es#2121]
have any plan for support GlobalGeodetic EPSG:4326 tile?

**Comment by matteblair** [comment]
Hello! Can you clarify what you mean by "EPSG:4326 tile"?

As I understand it, EPSG:4326 is another name for the WGS 84 coordinate system. The GeoJSON format uses WGS 84 coordinates (https://tools.ietf.org/html/rfc7946#section-4) and Tangram ES supports GeoJSON tiles. Does this help?

**Comment by ccxxbb** [comment]
Such tiles are compatible with Google Earth

**Comment by matteblair** [comment]
I would need a little more detail than that. Can you link to a document that describes this?

**Comment by ccxxbb** [comment]
https://github.com/CjS77/gdal2tiles/blob/master/gdal2tiles.py ,there is a describtion about GlobalMercator tile and  GlobalGeodetic tile .

**Comment by matteblair** [comment]
Copying the relevant comments from the link above for easier reference:
```
    TMS Global Geodetic Profile
    ---------------------------
    Functions necessary for generation of global tiles in Plate Carre projection,
    EPSG:4326, "unprojected profile".

    Such tiles are compatible with Google Earth (as any other EPSG:4326 rasters)
    and you can overlay the tiles on top of OpenLayers base map.

    Pixel and tile coordinates are in TMS notation (origin [0,0] in bottom-left).

    What coordinate conversions do we need for TMS Global Geodetic tiles?

      Global Geodetic tiles are using geodetic coordinates (latitude,longitude)
      directly as planar coordinates XY (it is also called Unprojected or Plate
      Carre). We need only scaling to pixel pyramid and cutting to tiles.
      Pyramid has on top level two tiles, so it is not square but rectangle.
      Area [-180,-90,180,90] is scaled to 512x256 pixels.
      TMS has coordinate origin (for pixels and tiles) in bottom-left corner.
      Rasters are in EPSG:4326 and therefore are compatible with Google Earth.

         LatLon      <->      Pixels      <->     Tiles     
     WGS84 coordinates   Pixels in pyramid  Tiles in pyramid
         lat/lon         XY pixels Z zoom      XYZ from TMS 
        EPSG:4326                                           
         .----.                ----                         
        /      \     <->    /--------/    <->      TMS      
        \      /         /--------------/                   
         -----        /--------------------/                
       WMS, KML    Web Clients, Google Earth  TileMapService
```

**Comment by matteblair** [comment]
I think I understand your question now. You want to be able to input EPSG:4326 "unprojected" tiles into Tangram ES and render them directly as planar coordinates.

Tangram ES does not currently support this and there are no plans for adding this feature at this point. However if you or another contributor were to implement it I would definitely be open to merging your changes.

Let me know if I can answer any further questions about this!
