### ISSUE TITLE
Question: DataLayer (MapData) invalidated on MapController.loadSceneFile?

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2126]
I understand that markers are invalidated on a call to `MapController.loadSceneFile` (#1756), so all previously added markers need to be reinitialized after loading of the new scene succeeded.

Question: Does this behavior apply to `MapData` added with `MapController.addDataLayer` as well?

**Comment by matteblair** [comment]
`MapData` instances are preserved through scene changes until you explicitly call `remove()` (if you observe something different that is probably a bug!).

**Comment by westnordost** [comment]
Nice, thanks!
