### ISSUE TITLE
Edges of icon in spritesheet bleed into neighbouring icon

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2130]
**Tangram Version**: 0.11.2
**Android Version**: Lollipop
**Device**: Sony Xperia Z1 Compact

Not reproducible with Android 28 emulator.

I have a spritesheet with 128x128px icons and display them as point features on the map.

I noticed that the edge of the neighbouring icons bleed into the currently displayed one. It is not quite one pixel but flickers somewhere between 0 and 1 pixels. (It is the barely visible white stripe on the left side of the icon):
![device-2020-01-18-173241](https://user-images.githubusercontent.com/4661658/72667395-e3499600-3a1b-11ea-8434-ffdaac989f0a.png)

Looking closer, it is clear that the white stripe is the rightmost outer part of the neighbouring icon:

![device-2020-01-18-173241_1](https://user-images.githubusercontent.com/4661658/72667404-feb4a100-3a1b-11ea-9b49-61f32196c641.png)

Perhaps related: On the right side, this is the actual asset used for the spritesheet. You can see that the icon as it appears on the map looks as if it has been scaled up (or down). Though, I can confirm that the icon in the spritesheet is exactly 128px, the same size it appears on the map.

Tangram log:
```
Loading native library took 28ms
Loading native library took 0ms
MapController creation took 4ms
MapController init took 6ms
TANGRAM map.cpp:874: setup GL
TANGRAM hardware.cpp:60: Driver supports map buffer: 0
TANGRAM hardware.cpp:61: Driver supports vaos: 1
TANGRAM hardware.cpp:62: Driver supports rgb8_rgba8: 1
TANGRAM hardware.cpp:63: Driver supports NPOT texture: 0
TANGRAM hardware.cpp:77: Hardware max texture size 4096
TANGRAM hardware.cpp:78: Hardware max combined texture units 32
TANGRAM map.cpp:207: resize: 720 x 1025
NOTIFY importer.cpp:264: Merging different node types: 
    'rgb(204,214,238)'
    <--
    '[0.16, 0.36, 0.36, 0.75]'
NOTIFY importer.cpp:264: Merging different node types: 
    'rgb(185,195,217)'
    <--
    '[0.12, 0.32, 0.32, 0.75]'
WARNING sceneLoader.cpp:687: Can't find data source streetcomplete_quests for layer streetcomplete_quests
WARNING sceneLoader.cpp:687: Can't find data source streetcomplete_geometry for layer streetcomplete_geometry
WARNING tileManager.cpp:204: add source mapzen
TANGRAM scene.cpp:312: Prefetch tiles for View: 720.000000x1025.000000 / zoom:18.999456 lon:9.943832 lat:53.580477
FontConfig init took 20ms
TANGRAM scene.cpp:481: Fetch font asset:///map_theme/fonts/Montserrat-Bold.woff
TANGRAM scene.cpp:485: Received font: asset:///map_theme/fonts/Montserrat-Bold.woff
TANGRAM scene.cpp:481: Fetch font asset:///map_theme/fonts/Montserrat-Medium.woff
TANGRAM scene.cpp:481: Fetch font asset:///map_theme/fonts/Montserrat-Regular.woff
TANGRAM scene.cpp:427: Fetch texture asset:///map_theme/images/oneway_arrow@2x.png
TANGRAM scene.cpp:427: Fetch texture asset:///map_theme/images/quest_dot@2x.png
TANGRAM scene.cpp:485: Received font: asset:///map_theme/fonts/Montserrat-Medium.woff
TANGRAM scene.cpp:427: Fetch texture file:///data/data/de.westnordost.streetcomplete.debug/files/quests.png
TANGRAM scene.cpp:485: Received font: asset:///map_theme/fonts/Montserrat-Regular.woff
TANGRAM scene.cpp:432: Received texture asset:///map_theme/images/oneway_arrow@2x.png
WARNING texture.cpp:172: OpenGL ES doesn't support texture repeat wrapping for NPOT textures nor mipmap textures
WARNING texture.cpp:173: Falling back to LINEAR Filtering
TANGRAM scene.cpp:432: Received texture asset:///map_theme/images/quest_dot@2x.png
TANGRAM scene.cpp:432: Received texture file:///data/data/de.westnordost.streetcomplete.debug/files/quests.png
WARNING texture.cpp:172: OpenGL ES doesn't support texture repeat wrapping for NPOT textures nor mipmap textures
WARNING texture.cpp:173: Falling back to LINEAR Filtering
TANGRAM scene.cpp:312: Prefetch tiles for View: 720.000000x1025.000000 / zoom:18.999456 lon:9.943832 lat:53.580477
TANGRAM map.cpp:186: ASYNC DISPOSE OF OLD SCENE - 1
```

**Comment by westnordost** [comment]
To workaround this is obviously trivial, so if you think this is a quirk iin the OpenGL implementation of the device I was testing it with, feel free to close it. I just wanted to let you know.

**Comment by matteblair** [comment]
Yeah this looks to me like the texture filtering is pulling a little bit of the adjacent icon into your sprite. If you're going to use linear or mipmap filtering on sprites in a packed texture you'll probably want to leave 1 or 2 pixels of padding between sprites in the texture. I don't know that there's a better way to handle this with the way that OpenGL samples textures.

As for the scaling: Tangram calculates the size of a rendered icon using "logical pixels", which is the pixel size specified in the scene file multiplied by a scale factor to account for the screen density. The screen density is a value we get from the device, and on many Android devices it's not a whole number (1.5 is a pretty common value). So even though the icon size in the scene matches the icon size in the texture, we still have to scale it sometimes to keep the UI consistently sized :\

**Comment by westnordost** [comment]
Actually I create the spritesheet dynamically. The icons in my scene have a size of 64x64 "logical pixels". For devices with x1.5 densitiy, the spritesheet is created from assets of 96x96px. For devices with x2 density, with 128x128px etc.

My device has a screen density of x2, so the icons are displayed at 128x128px and the spritesheet also contains sprites of 128x128. There *should* be no scaling happening. Could this be a bug?

**Comment by westnordost** [comment]
I am closing this because
1. the question about the edges of an icon in a spritesheet bleeding into each other has been answered: Yes, this can happen and the maintainer knows no way to cirvumvent it, so it is recommended to leave at least 1px of space empty between the icons
2. I don't see the scaling issue raised with my new smartphone anymore. It could very well be that the issue still persists, but I don't have the device to reproduce this anymore plus this issue ticket was about something else, so if someone else still finds this issue, it'd be better to create a new issue for that.
