### ISSUE TITLE
Architectural issue of DefaultHttpHandler + Kotlin

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2145]
I want to notify you of a compatibility issue with the architecture of `DefaultHttpHandler` and Kotlin

Let's take for example this subclass of `DefaultHttpHandler`:

```kotlin
class CachingHttpHandler(
    private val cacheDirectory: File?,
    private val maxCacheSizeInBytes: Long = 16 * 1024 * 1024
) : DefaultHttpHandler() {

    override fun configureClient(builder: OkHttpClient.Builder) {
        if (cacheDirectory?.exists() == true) {
            builder.cache(Cache(cacheDirectory, maxCacheSizeInBytes))
        }
    }
}

```

Believe it or not, `cacheDirectory` is always null and even `maxCacheSizeInBytes` is always 0 in `configureClient`, no matter what was passed as constructor parameter. Why is this the case? Because in Kotlin, first always the constructor of the parent class is executed, after that the constructor of the child class. In the constructor of the child class implicitly the passed parameters are put into the private fields.
Since the parent class calls `configureClient` in its own constructor, this call happens before these values are initialized.
This is a problematic language design of Kotlin at this point, but you can solve this issue for Kotlin users by not calling `configureClient` in the constructor but lazily just before the first request is made.

**Comment by matteblair** [comment]
🤦‍♂ I did not realize that Kotlin does not allow subclasses to control when the super constructor gets invoked. That is unfortunate. 

Instantiating the OkHttpClient lazily would seem to solve this. I'll try that out and think about any other possible solutions.
