### ISSUE TITLE
Shader compatibility between ES and JS

### ISSUE THREAD

**Issue by warpedgeoid** [tangrams/tangram-es#2153]
It appears that the core shaders used by the two flavors of Tangram are sufficiently different as to make it difficult to share shader code between web and mobile applications. For example, many variable names, such as `v_aa_offset` and `v_aa_factor` are not shared between flavors of Tangram.

Perhaps these aren't meant to be used by custom shaders, and if they aren't, I welcome recommendations for alternatives.

In the meantime, I propose that you implement defines so that shaders can act differently depending on platform. Something like `TANGRAM_IS_ES` and `TANGRAM_IS_JS` would be fine. I looked in the shader code for Tangram ES and didn't see anything like this defined, so please let me know if I missed it.

Thanks!

**Comment by matteblair** [comment]
Good idea! Injecting a define for the engine version would be pretty easy and won't break any existing shader code. We don't intend for all the variables to be "available" to user code because there are sometimes differences between the JS and ES shader implementations, and we don't want to prevent ourselves from improving the implementation in the future either.

**Comment by matteblair** [comment]
Does `GL_ES` get defined in WebGL? If not you could try using that to detect that you're in Tangram ES.

**Comment by matteblair** [comment]
Hmm scratch that, `GL_ES` is defined in WebGL too (https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#Shaders_Programs_and_GLSL)

**Comment by warpedgeoid** [comment]
Thanks! I was dropping by to tell you that I would check for `GL_ES` today and report back, but it looks like you're well ahead of me!

**Comment by bcamper** [comment]
We did intend to leave leeway for implementation differences between JS and ES as @matteblair said. So the intended "safe" public API for shaders is as defined with these [built-ins](https://tangrams.readthedocs.io/en/latest/Syntax-Reference/shaders/#built-ins-defaults-and-presets), along with additional occasional context-specific functions like [raster samplers](https://tangrams.readthedocs.io/en/latest/Syntax-Reference/styles/#raster).

That said, I was also surprised we don't have a a JS/ES define, as I know we've thought about it before, and it makes sense to add. As long as you are OK accepting the risks of possible changing API (without release documentation), you *can* use those other varyings, uniforms, etc. you find in the source... but I would caution that they do change from time to time (in fact, I've sometimes added block scoping to Tangram JS shaders to prevent leakage of some variables where possible).

And, if there are specific cases you see in JS or ES and would be interested in having them available for official use across platforms, please feel free to file issues for those individually. Thanks!

**Comment by bcamper** [comment]
Added issues in JS and ES repos to add the shader define.
