### ISSUE TITLE
Is there any tool for create custom nextzen terrain tile?

### ISSUE THREAD

**Issue by ccxxbb** [tangrams/tangram-es#2155]

**Comment by nvkelso** [comment]
Can you provide a little more background, please?

**Comment by ccxxbb** [comment]
I want to create  custom nextzen terrain tile from  dem  file,   such as  geotif file

**Comment by matteblair** [comment]
I believe https://github.com/tilezen/joerd is the set of tools used to create the hosted Nextzen tiles, you may be able to use it for your own purpose.

**Comment by nvkelso** [comment]
[Marblecutter](https://github.com/mojodna/marblecutter) was used for v2 terrain tiles
(Joerd was used for v1 terrain tiles)
