### ISSUE TITLE
Why not use   libcurl  on  android platform  ,Some useful classes have been included in the code，such as  UrlWorker...

### ISSUE THREAD

**Issue by ccxxbb** [tangrams/tangram-es#2156]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

 - List the steps you used
 - To produce the result here
 - Don't leave any out

**RESULT:**

Describe the result here.

**EXPECTED RESULT:**

Describe what you expected to see here.

**ENVIRONMENT:**

 - What operating system and device did you produce this issue on?
 - If you used a released version, what is the version number?

**OTHER:**

Any additional notes, comments, tips, tricks, gifs, suggestions, poetry, recipes, jokes

If you are able to record the log output from tangram-es, please attach it as a text file or share it using a site like https://hastebin.com/

**Comment by matteblair** [comment]
Fair question. Tangram ES _could_ use libCURL for URL transfer on Android (and on all of our target platforms, actually) but there are a few advantages to using OkHTTP in Java:
- Local response caching, which is especially important on mobile devices
- Configuration options accessible from Java
- Option to completely override the HTTP engine with a different implementation (users have needed this in some cases).

All of these things would be possible, but more difficult with libCURL.
