### ISSUE TITLE
Layer's visible property is not working propertly with function

### ISSUE THREAD

**Issue by vilinet** [tangrams/tangram-es#2161]
Feature is not hided/shown properly based on a function that returns a feature's true/false property

REPRODUCE: 
Have a scene with a layer that relis on the feature json. With any geometry.
...
visible: function() { feature.isVisible; }
Source of the issue likely at DrawRuleMergeSet::evaluateRuleForContext. it checks the visible at the top, then it evalutes the function. Does not seem tobe the correct logic.

Also it does strange things with true/false in the json, it does not identify them as bool, but numbers.
See at StyleContext::evalStyle.

**RESULT:**
Once the feature is shown its not gonna be hidden.

**EXPECTED RESULT:**
Features should be hidden and shown based on the feature.isVisible's value

**Comment by matteblair** [comment]
The `visible` property in draw groups and the `enabled` property in layers (which used to be called `visible`) both expect boolean values, not functions. This is the documented behavior: https://tangrams.readthedocs.io/en/latest/Syntax-Reference/draw/#visible, https://tangrams.readthedocs.io/en/latest/Syntax-Reference/layers/#enabled. 

To get more granular control over feature visibility you should use a `filter`, which does allow functions of feature properties.

**Comment by vilinet** [comment]
@matteblair Then the documentation is not so perfect...
https://tangrams.readthedocs.io/en/latest/Syntax-Reference/yaml/#function

"Strings starting with function will be passed to the style builder as JavaScript in certain contexts, including: color, width, order, interactive, **visible**, filter, size, fill, and stroke. These functions will be evaluated at runtime, and the returned value will be passed to the parameter."

**Comment by bcamper** [comment]
We should probably update the docs to just indicate which fields take a
function within each field definition, rather than maintaining this list,
and/or just a few "core" style fields here like the first 3.
