### ISSUE TITLE
Incorrect icon marker channels on iOS

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#2167]
I have tried to add an icon to a marker in Tangram Swift Sample project - https://github.com/tangrams/tangram-swift-sample. Running it on iPhone 8, I got this result:

![screenshot](https://user-images.githubusercontent.com/2378743/84544052-cda37880-acfc-11ea-9eba-47eed9f3a0af.jpg)

The icon seems to have channels changed. I have found out that it is due to this for loop: https://github.com/tangrams/tangram-es/blob/514e9528b5936658527f111fada3273abcea779e/platforms/ios/framework/src/TGMarker.mm#L188

When I commented out this for loop, the icon seems to have correct channels.

This is the icon:

![location_icon](https://user-images.githubusercontent.com/2378743/84544661-009a3c00-acfe-11ea-9811-e04af189dccb.png)

and the Swift code I have added into Tangram Swift Sample into `ViewController.swift` file:

```
let newYork = CLLocationCoordinate2DMake(40.70532700869127, -74.00976419448854)
let marker = mapView.markerAdd()
marker.stylingString = "{ style: 'ux-location-gem-overlay', color: 'white', size: [35px, 35px], order: 10000, priority: 1, collide: false }"
marker.icon = UIImage(named: "location_icon")!
marker.point = newYork
```

**Comment by matteblair** [comment]
That's very odd! This loop is for converting pixel formats in a way that was clearly intentional - I wonder if something changed in iOS? Can you tell me what version of iOS you are using?

**Comment by rwrx** [comment]
I only have one device - iPhone 8, so unfortunately I cannot test it on other devices. It has iOS version 13.5.1. It should be the latest version.

**Comment by matteblair** [comment]
I've reproduced the behavior you described. I'm still puzzled as to why the code worked this way in the first place! I'll see if I can dig up info in the repo history, but in the meantime I've drafted the fix here: https://github.com/tangrams/tangram-es/pull/2168

**Comment by rwrx** [comment]
@matteblair thank you a lot for addressing this. So I can close this issue. Could I also ask you to have a look at https://github.com/tangrams/tangram-swift-sample/issues/3 when you will have some time?
