### ISSUE TITLE
Rarely MapController.getCameraPosition().longitude returns NaN

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2169]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Call `MapController.getCameraPosition().longitude`. Very rarely, it returns `NaN`.
Reproduction is unknown, I got a few crash reports because the app expects valid lat/lon pairs.

It happened once roughly when the map was displayed near latitude 48.864143, longitude 16.469961, quite an innocent position.

**ENVIRONMENT:**

at least Android 10, tangram-es 0.12.0

**OTHER:**

I am in contact with the person for which this happened several times. Should I ask him anything specific?

**Comment by tallytalwar** [comment]
Thanks @westnordost 

Yeah maybe what action is the person performing and in what orientation of the map (tilted, rotated, etc). Its very odd that current map positions returns a NaN. My immediate guess is because of the orientation and constraining of lat/lon there might be an some error, but can not pin point to anything specific right now.

**Comment by westnordost** [comment]
He answered that he cannot remember exactly but that he'd say that the display wasn't rotated or tilted.

**Comment by matteblair** [comment]
Well this is pretty odd. I can't think of any reason this would happen and a quick look over the code doesn't give me any leads. 

Does this _only_ happen with longitude, and not latitude?

**Comment by westnordost** [comment]
So far, yes

Am 19. Juni 2020 07:12:52 MESZ schrieb Matt Blair <notifications@github.com>:
>Well this is pretty odd. I can't think of any reason this would happen
>and a quick look over the code doesn't give me any leads. 
>
>Does this _only_ happen with longitude, and not latitude?

**Comment by westnordost** [comment]
Got another report, also just longitude, latitude is fine:
`java.lang.IllegalArgumentException: Latitude -85.05103089299783, Longitude NaN is not a valid position.`

The value of the latitude seems to be suspicious though, this is almost the south pole.

**Comment by westnordost** [comment]
java.lang.IllegalArgumentException: Latitude -62.19512403058969, Longitude NaN is not a valid position.

**Comment by westnordost** [comment]
another one:
`java.lang.IllegalArgumentException: Latitude -57.99715861574568,
Longitude NaN is not a valid position.`

### Here is the summary of findings so far:
- it only concerns the **longitude**
- it happens independently of the Android version or device
- it happens during the callback made to `MapChangeListener::onRegionIsChanging`: When querying `MapController::getCameraPosition().longitude` in that callback, sometimes the longitude is `NaN`

**Comment by westnordost** [comment]
Is there any more information you could need from me? Otherwise I'd perhaps just wrap it in a try-catch or specifically add a check for that. Thoug, this would mean that there won't be any more (crash) reports for this issue from my side.

**Comment by tallytalwar** [comment]
Thanks @westnordost. I think above should be good given the circumstances as I do not think we can get any more info from the crash logs.

**Comment by matteblair** [comment]
Is there just one piece of code that's receiving invalid coordinates? Can you link to it?

**Comment by tallytalwar** [comment]
Hmm my very initial hunch when I saw this issue come up was, possible long/lat values are uninitialized somewhere. But looking at how these get reported it does not seem like the case. [This](https://github.com/tangrams/tangram-es/blob/893eb73904a7fe6d3afce2537065f8044892bb16/core/src/util/mapProjection.cpp#L14) is where long values get computed So its not possible for for reported long to be uninitiated or NaN unless `View::m_pos` is a NaN. In which case it might help to also log `View::getPosition()` (which is then used to get longitude value).

I do not see that we expose `View::getPosition()` API, maybe we should? Will it help in other usages for a client to know camera position in projection units?

However another thing which can be logged from the app or from the stack trace, is what is the state being set in `setMapRegionState` which is triggering the `onRegionIsChanging` callback (It has to be Animating, or Jumping). This can give us hints on what action user is doing to result in this.

**Comment by westnordost** [comment]
> long/lat values are uninitialized somewhere

In Java, `double` variables are initialized with 0.0

> However another thing which can be logged from the app or from the stack trace, is what is the state being set in setMapRegionState

hmm, the `MapRegionChangeState currentState` isn't public either.

---

The full stacktrace is this:

> at de.westnordost.osmapi.map.data.LatLons.checkValidity(LatLons.java:21)
at de.westnordost.osmapi.map.data.OsmLatLon.<init>(OsmLatLon.java:23)
**at de.westnordost.streetcomplete.map.tangram.CameraPosition.<init>([CameraManager.kt:223](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/map/tangram/CameraManager.kt#L215-L224))** <- 3
at de.westnordost.streetcomplete.map.tangram.CameraManager.getCamera(CameraManager.kt:60)
at de.westnordost.streetcomplete.map.tangram.KtMapController.getCameraPosition(KtMapController.kt:152)
at de.westnordost.streetcomplete.map.MapFragment.getCameraPosition(MapFragment.kt:369)
**at de.westnordost.streetcomplete.map.MapFragment$registerResponders$1.onMapIsChanging([MapFragment.kt:202](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/map/MapFragment.kt#L199))** <- 2
**at de.westnordost.streetcomplete.map.tangram.KtMapController$6$onRegionIsChanging$1.run([KtMapController.kt:112](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/map/tangram/KtMapController.kt#L110)) <- 1**
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)


1. The app gets the `onRegionIsChanging` callback from the tangram `MapController`, relays that call to ...
2. the `MapFragment` which eventually calls [`MapController.getCameraPosition(_tangramCamera)` (not in stack trace)](https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/map/tangram/CameraManager.kt#L165) in order to fill the `_tangramCamera` variable with the data from tangram
3. and then creates a new object from the `_tangramCamera` object, at which the check whether the data in that variable is valid is made

So, the error happens at point 2, where the `_tangramCamera` variable is apparently not filled with a valid value for the longitude

**Comment by westnordost** [comment]
Oh, but I can say with certainty that the `MapRegionChangeState` can't be `MapRegionChangeState.ANIMATING` and thus must be `MapRegionChangeState.JUMPING`:

Neither `MapController::flyToCameraPosition` nor `MapController::updateCameraPosition` with a `duration > 0` is called anywhere in the app. (The app handles animations itself)

**Comment by matteblair** [comment]
The only theory I have at this point is that somehow the application code is sending a longitude of NaN in a `CameraUpdate`. I've checked and confirmed that a NaN would in fact be propagated all the way through from `updateCameraPosition` to `getCameraPosition`. Do you perform `LatLons.checkValidity` on coordinates before they are used in a `CameraUpdate`? If not it may be worth trying. I really haven't found any other way that a NaN could be introduced.

**Comment by westnordost** [comment]
I'll check, thanks for the hint!

**Comment by westnordost** [comment]
Hm, I checked. The validity is checked. I can be sure of it because
1. the only point from where `MapController::updateCameraPosition` is called is from the `CameraManager` class which on its interface only accepts the `LatLon` interface for position. `LatLon` is then translated to tangram's `LngLat` internally in that class.
2. The only implementation of `LatLon` that is used in the app is the class `OsmLatLon` which does the `LatLons.checkValidity` check in its constructor. So, it is not possible to pass an invalid position to the `CameraManager`

One uncertainty that is missing is that it may be possible that the Android animation system fucks up and somehow reaches `NaN` for latitude during animation 🤷 . So what I'll do is to fail early and throw an Exception when trying to call `MapController::updateCameraPosition` with a `NaN`. Then, I'll notify you what crash reports I get in the future.

**Comment by westnordost** [comment]
> One uncertainty that is missing is that it may be possible that the Android animation system fucks up and somehow reaches NaN for latitude during animation 🤷 . So what I'll do is to fail early and throw an Exception when trying to call MapController::updateCameraPosition with a NaN. Then, I'll notify you what crash reports I get in the future.

Since tangram 0.14.1, it seems as if the issue happens more often now (~4 times as often).

I also fail early and throw an exception if the latitude and longitude is invalid whenever I push a position to Tangram-ES. That exception is not thrown however, so it doesn't look like my app is supplying tangram-es with invalid latitude/longitude.

**Comment by westnordost** [comment]
**Finally, there seems to be a surefire way to reproduce this!**

See https://github.com/streetcomplete/StreetComplete/issues/2601

Quoting @mkotzjan
> I'm able to crash the app by zooming in and out quickly using only one finger. I know that this is rather unusual behavior, i just discovered this by accident. See also the attached video
> 
> How to Reproduce
> 
>    - Open StreetComplete
>    - Double tap the map and hold on the second tap
>    - move finger up or down for zooming in or out with just one finger
>    - move finger quickly up and down to crash app

Several users could confirm that they could reproduce this.

**Comment by matteblair** [comment]
That's a really good tip, I was able to finally reproduce this crash! In the exception I saw, both longitude and latitude were NaN. Have to do a bit more diagnosis, but I bet there's a line that's dividing by a zero delta time or taking the log of a zero delta zoom.

**Comment by tallytalwar** [comment]
Will also look at this, could be related to flinging code also, since that is all tangram internal.
