### ISSUE TITLE
gcc error for Raspberry pi

### ISSUE THREAD

**Issue by ric96** [tangrams/tangram-es#217]
pi@raspberrypi ~/tangram-es $ export CXX=/usr/bin/g++-4.9
pi@raspberrypi ~/tangram-es $ make -j4 rpi
-- Platform chosen : RASPBERRYPI
-- Including raspberrypi dependent cmake file : /home/pi/tangram-es/toolchains/raspberrypi.cmake
CMake Error at toolchains/raspberrypi.cmake:14 (message):
  Please install g++ version 4.8 or greater
Call Stack (most recent call first):
  CMakeLists.txt:56 (include)

-- Configuring incomplete, errors occurred!
Makefile:172: recipe for target 'cmake-rpi' failed
make: *** [cmake-rpi] Error 1
pi@raspberrypi ~/tangram-es $ export CXX=/usr/bin/g++-4.8
pi@raspberrypi ~/tangram-es $ make rpi
-- Platform chosen : RASPBERRYPI
-- Including raspberrypi dependent cmake file : /home/pi/tangram-es/toolchains/raspberrypi.cmake
CMake Error at toolchains/raspberrypi.cmake:14 (message):
  Please install g++ version 4.8 or greater
Call Stack (most recent call first):
  CMakeLists.txt:56 (include)

-- Configuring incomplete, errors occurred!
Makefile:172: recipe for target 'cmake-rpi' failed
make: *** [cmake-rpi] Error 1
pi@raspberrypi ~/tangram-es $

**Comment by tallytalwar** [comment]
Hey Sahaj

We moved to g++4.9 for our builds. g++4.9 has better support for c++11 and
will also help when we move to c++14 (which is soon).

Please refer to the error message and the Readme, for how you can install
g++4.9 on raspbian.

And again thanks for trying tangram :). Much appreciated.

**Comment by tallytalwar** [comment]
We should also update our error message to say "g++4.9 or above". Will fix that.

**Comment by ric96** [comment]
I do have g++-4.9 installed

**Comment by blair1618** [comment]
export CXX=/usr/bin/g++-4.9
should do the trick. 

The error message has been fixed, thanks for the heads up!

**Comment by hjanetzek** [comment]
@blair1618, it's pretty much what @ric96 did according to the first line of the logs :)

**Comment by ric96** [comment]
Not Helping :(
pi@raspberrypi ~/tangram-es $ ls /usr/bin/g++*
/usr/bin/g++      /usr/bin/g++-4.7  /usr/bin/g++-4.9
/usr/bin/g++-4.6  /usr/bin/g++-4.8
pi@raspberrypi ~/tangram-es $ export CXX=/usr/bin/g++-4.9
pi@raspberrypi ~/tangram-es $ make -j4 rpi
-- Platform chosen : RASPBERRYPI
-- Including raspberrypi dependent cmake file : /home/pi/tangram-es/toolchains/raspberrypi.cmake
CMake Error at toolchains/raspberrypi.cmake:14 (message):
  Please install g++ version 4.9 or greater
Call Stack (most recent call first):
  CMakeLists.txt:56 (include)


-- Configuring incomplete, errors occurred!
Makefile:172: recipe for target 'cmake-rpi' failed
make: *** [cmake-rpi] Error 1
pi@raspberrypi ~/tangram-es $

**Comment by ric96** [comment]
Its working on a fresh install of raspbian, idk what happened with my original install. If someone else could confirm that it works then we can close this issue.

**Comment by blair1618** [comment]
Just got our raspberry pi 2 to build, doesn't seem to be an issue with gcc-4.9 installed so I'll go ahead and close this one
