### ISSUE TITLE
Feature request: maximum tilt

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2170]
It would be very helpful if it was possible to set a maximum tilt, analogous to the maximum zoom.

It looks like it is not trivial to implement such a thing "on top" of tangram-es in Java.

This came up in https://github.com/westnordost/StreetComplete/issues/1932 (_Scrolling "the sky" on maximum tilt makes map jump tens of kilometers_)

**Comment by matteblair** [comment]
There is a `max_tilt` property in the `camera` section of the scene file. Have you tried this? https://tangrams.readthedocs.io/en/latest/Syntax-Reference/cameras/#max_tilt

**Comment by westnordost** [comment]
No, I haven't, thanks for the hint!

**Comment by westnordost** [comment]
Works well, I withdraw this feature request, thank you!
