### ISSUE TITLE
raspberry pi build error

### ISSUE THREAD

**Issue by ric96** [tangrams/tangram-es#218]
pi@raspberrypi ~/tangram-es $ make rpi
-- Platform chosen : RASPBERRYPI
-- Including raspberrypi dependent cmake file : /home/pi/tangram-es/toolchains/raspberrypi.cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/tangram-es/build/rpi
make[1]: Entering directory '/home/pi/tangram-es/build/rpi'
make[2]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[ 33%] Built target yaml-cpp
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[ 41%] Built target libtess2
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[ 42%] Built target libcsscolorparser
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[ 95%] Built target core
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
[ 96%] Building CXX object CMakeFiles/tangram.dir/rpi/src/main.cpp.o
/home/pi/tangram-es/rpi/src/main.cpp: In function ‘void onKeyPress(int)’:
/home/pi/tangram-es/rpi/src/main.cpp:98:52: error: too few arguments to function ‘void Tangram::handlePinchGesture(float, float, float, float)’
             Tangram::handlePinchGesture(0.0,0.0,0.5);
                                                    ^
In file included from /home/pi/tangram-es/rpi/src/main.cpp:15:0:
/home/pi/tangram-es/core/src/tangram.h:67:6: note: declared here
 void handlePinchGesture(float _posX, float _posY, float _scale, float _velocity);
      ^
/home/pi/tangram-es/rpi/src/main.cpp:101:52: error: too few arguments to function ‘void Tangram::handlePinchGesture(float, float, float, float)’
             Tangram::handlePinchGesture(0.0,0.0,2.0);
                                                    ^
In file included from /home/pi/tangram-es/rpi/src/main.cpp:15:0:
/home/pi/tangram-es/core/src/tangram.h:67:6: note: declared here
 void handlePinchGesture(float _posX, float _posY, float _scale, float _velocity);
      ^
CMakeFiles/tangram.dir/build.make:100: recipe for target 'CMakeFiles/tangram.dir/rpi/src/main.cpp.o' failed
make[3]: *** [CMakeFiles/tangram.dir/rpi/src/main.cpp.o] Error 1
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/tangram.dir/all' failed
make[2]: *** [CMakeFiles/tangram.dir/all] Error 2
make[2]: Leaving directory '/home/pi/tangram-es/build/rpi'
Makefile:113: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/tangram-es/build/rpi'
Makefile:168: recipe for target 'rpi' failed
make: *** [rpi] Error 2
pi@raspberrypi ~/tangram-es $

**Comment by tallytalwar** [comment]
Hey

Can you give this a try again? 3a6496079bc11017404c431892ac03320d952dfa should fix this issue.

**Comment by ric96** [comment]
Nope, didn't help


pi@raspberrypi ~/tangram-es $ make -j4 rpi
-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-4.9
-- Check for working CXX compiler: /usr/bin/g++-4.9 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Platform chosen : RASPBERRYPI
-- Including raspberrypi dependent cmake file : /home/pi/tangram-es/toolchains/raspberrypi.cmake
-- Performing Test FLAG_WEXTRA
-- Performing Test FLAG_WEXTRA - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/tangram-es/build/rpi
make[1]: Entering directory '/home/pi/tangram-es/build/rpi'
make[2]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
Scanning dependencies of target libcsscolorparser
Scanning dependencies of target libtess2
Scanning dependencies of target yaml-cpp
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[  1%] make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
Building CXX object core/dependencies/cssColorParser/CMakeFiles/libcsscolorparser.dir/csscolorparser.cpp.o
[  2%] [  3%] cc1plus: warning: /home/pi/tangram-es/core/dependencies/cssColorParser/csscolorparser.hpp: not a directory
Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/bucketalloc.c.o
Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/sweep.c.o
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
[  5%] [  5%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node.cpp.o
Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/memory.cpp.o
[  6%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/mesh.c.o
[  8%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/priorityq.c.o
[  9%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/dict.c.o
[ 10%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/geom.c.o
[ 11%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/tess.c.o
Linking C static library ../../../lib/liblibtess2.a
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[ 12%] [ 12%] Built target libtess2
Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodeevents.cpp.o
[ 13%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/simplekey.cpp.o
Linking CXX static library ../../../lib/liblibcsscolorparser.a
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[ 13%] Built target libcsscolorparser
[ 14%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanner.cpp.o
[ 16%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parser.cpp.o
[ 17%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/stream.cpp.o
[ 18%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/nodebuilder.cpp.o
[ 19%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scanscalar.cpp.o
[ 20%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/binary.cpp.o
[ 21%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/ostream_wrapper.cpp.o
[ 22%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emit.cpp.o
[ 24%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/null.cpp.o
[ 25%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/regex_yaml.cpp.o
[ 26%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterutils.cpp.o
[ 27%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitterstate.cpp.o
[ 28%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/tag.cpp.o
[ 29%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/directives.cpp.o
[ 31%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/exp.cpp.o
[ 32%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/node_data.cpp.o
[ 33%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/convert.cpp.o
[ 34%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/singledocparser.cpp.o
[ 35%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantoken.cpp.o
[ 36%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitfromevents.cpp.o
[ 37%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/parse.cpp.o
[ 39%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/scantag.cpp.o
[ 40%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/emitter.cpp.o
[ 41%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
[ 42%] Building CXX object core/dependencies/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilderadapter.cpp.o
Linking CXX static library ../../../lib/libyaml-cpp.a
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[ 42%] Built target yaml-cpp
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
Scanning dependencies of target core
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
[ 43%] [ 45%] [ 45%] [ 47%] Building CXX object core/CMakeFiles/core.dir/src/scene/light.cpp.o
Building CXX object core/CMakeFiles/core.dir/src/scene/sceneLayer.cpp.o
Building CXX object core/CMakeFiles/core.dir/src/scene/scene.cpp.o
Building CXX object core/CMakeFiles/core.dir/src/scene/skybox.cpp.o
[ 48%] Building CXX object core/CMakeFiles/core.dir/src/scene/spotLight.cpp.o
[ 49%] Building CXX object core/CMakeFiles/core.dir/src/scene/ambientLight.cpp.o
[ 50%] Building CXX object core/CMakeFiles/core.dir/src/scene/sceneLoader.cpp.o
[ 51%] Building CXX object core/CMakeFiles/core.dir/src/scene/directionalLight.cpp.o
[ 52%] Building CXX object core/CMakeFiles/core.dir/src/scene/pointLight.cpp.o
[ 54%] Building CXX object core/CMakeFiles/core.dir/src/view/view.cpp.o
[ 55%] Building CXX object core/CMakeFiles/core.dir/src/gl/error.cpp.o
[ 56%] Building CXX object core/CMakeFiles/core.dir/src/gl/vertexLayout.cpp.o
[ 57%] Building CXX object core/CMakeFiles/core.dir/src/gl/vboMesh.cpp.o
[ 58%] Building CXX object core/CMakeFiles/core.dir/src/gl/primitives.cpp.o
[ 59%] Building CXX object core/CMakeFiles/core.dir/src/gl/textureCube.cpp.o
[ 60%] Building CXX object core/CMakeFiles/core.dir/src/gl/texture.cpp.o
[ 62%] Building CXX object core/CMakeFiles/core.dir/src/gl/shaderProgram.cpp.o
[ 63%] Building CXX object core/CMakeFiles/core.dir/src/gl/renderState.cpp.o
[ 64%] Building CXX object core/CMakeFiles/core.dir/src/text/textBuffer.cpp.o
[ 65%] Building CXX object core/CMakeFiles/core.dir/src/text/fontContext.cpp.o
[ 66%] Building CXX object core/CMakeFiles/core.dir/src/tile/tile.cpp.o
[ 67%] Building CXX object core/CMakeFiles/core.dir/src/tile/tileWorker.cpp.o
[ 68%] Building CXX object core/CMakeFiles/core.dir/src/tile/tileManager.cpp.o
[ 70%] Building CXX object core/CMakeFiles/core.dir/src/labels/textLabel.cpp.o
[ 71%] Building CXX object core/CMakeFiles/core.dir/src/labels/spriteLabel.cpp.o
[ 72%] Building CXX object core/CMakeFiles/core.dir/src/labels/label.cpp.o
[ 73%] Building CXX object core/CMakeFiles/core.dir/src/labels/spriteAtlas.cpp.o
[ 74%] Building CXX object core/CMakeFiles/core.dir/src/labels/labels.cpp.o
[ 75%] Building CXX object core/CMakeFiles/core.dir/src/util/builders.cpp.o
[ 77%] Building CXX object core/CMakeFiles/core.dir/src/util/mapProjection.cpp.o
[ 78%] Building CXX object core/CMakeFiles/core.dir/src/util/geom.cpp.o
[ 79%] Building CXX object core/CMakeFiles/core.dir/src/util/pbfParser.cpp.o
[ 80%] Building CXX object core/CMakeFiles/core.dir/src/util/geoJson.cpp.o
[ 81%] Building CXX object core/CMakeFiles/core.dir/src/util/inputHandler.cpp.o
[ 82%] Building CXX object core/CMakeFiles/core.dir/src/data/mvtSource.cpp.o
[ 83%] Building CXX object core/CMakeFiles/core.dir/src/data/dataSource.cpp.o
[ 85%] Building CXX object core/CMakeFiles/core.dir/src/data/geoJsonSource.cpp.o
[ 86%] Building CXX object core/CMakeFiles/core.dir/src/style/polylineStyle.cpp.o
[ 87%] Building CXX object core/CMakeFiles/core.dir/src/style/textStyle.cpp.o
[ 88%] Building CXX object core/CMakeFiles/core.dir/src/style/spriteStyle.cpp.o
[ 89%] Building CXX object core/CMakeFiles/core.dir/src/style/material.cpp.o
[ 90%] Building CXX object core/CMakeFiles/core.dir/src/style/debugStyle.cpp.o
[ 91%] Building CXX object core/CMakeFiles/core.dir/src/style/polygonStyle.cpp.o
[ 93%] Building CXX object core/CMakeFiles/core.dir/src/style/style.cpp.o
[ 94%] Building CXX object core/CMakeFiles/core.dir/src/style/debugTextStyle.cpp.o
[ 95%] Building CXX object core/CMakeFiles/core.dir/src/tangram.cpp.o
Linking CXX static library ../lib/libcore.a
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[ 95%] Built target core
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
Scanning dependencies of target tangram
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
[ 97%] [ 97%] [ 98%] [100%] Building CXX object CMakeFiles/tangram.dir/rpi/src/platform_rpi.cpp.o
Building CXX object CMakeFiles/tangram.dir/rpi/src/context.cpp.o
Building CXX object CMakeFiles/tangram.dir/rpi/src/main.cpp.o
Building CXX object CMakeFiles/tangram.dir/linux/src/urlWorker.cpp.o
Linking CXX executable bin/tangram
lib/libcore.a(tileManager.cpp.o): In function `std::atomic<double>::store(double, std::memory_order)':
/usr/include/c++/4.9/atomic:199: undefined reference to `__sync_val_compare_and_swap_8'
lib/libcore.a(tileWorker.cpp.o): In function `std::atomic<double>::load(std::memory_order) const':
/usr/include/c++/4.9/atomic:209: undefined reference to `__sync_val_compare_and_swap_8'
collect2: error: ld returned 1 exit status
CMakeFiles/tangram.dir/build.make:164: recipe for target 'bin/tangram' failed
make[3]: *** [bin/tangram] Error 1
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
CMakeFiles/Makefile2:63: recipe for target 'CMakeFiles/tangram.dir/all' failed
make[2]: *** [CMakeFiles/tangram.dir/all] Error 2
make[2]: Leaving directory '/home/pi/tangram-es/build/rpi'
Makefile:117: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/tangram-es/build/rpi'
Makefile:168: recipe for target 'rpi' failed
make: *** [rpi] Error 2
pi@raspberrypi ~/tangram-es $

**Comment by hjanetzek** [comment]
Look closely: this is a different problem than before

**Comment by hjanetzek** [comment]
There are some google results for 'rpi undefined reference to__sync_val_compare_and_swap_8'. 

I guess we could change the Tile m_priority to use float instead of double to workaround this..

**Comment by ric96** [comment]
Hmmm... Tru, that changing wheezy to jessie back and fourth could have messed up my raspbian installation. Might as well give it a try on a fresh install. I doubt that will have any effect.

**Comment by ric96** [comment]
even a fresh install gives me the same error.

**Comment by hjanetzek** [comment]
could you try if it help to change that atomic to float?

    sed -i 's/double/float/g' core/src/tile/tile.h

**Comment by ric96** [comment]
That worked !!!!
@hjanetzek  Can u create a pull request??

**Comment by ric96** [comment]
wait, it did compile but the program is completly broken, all the "3d" stuff is missing...!!!!

![img_20150727_022132836](https://cloud.githubusercontent.com/assets/5900740/8895870/9581c0fc-3406-11e5-8830-ca7a78fd1274.jpg)

**Comment by hjanetzek** [comment]
Awesome. Does the console scroll in the background?

... but seriously, better wait for a Tangram dev with a Pi handy.

**Comment by ric96** [comment]
Yup it does scroll.
Its as if there is see thru holes...

**Comment by blair1618** [comment]
tangram draws to the same buffer as the console so yes, the console will be visible where the map isn't drawn :)

I'm able to reproduce the linking error so we can work on a fix for that. 

While I'm at it, I'll look into the missing building geometry as well.

**Comment by ric96** [comment]
New build issues 
http://paste.ubuntu.com/13628522/

**Comment by tallytalwar** [comment]
Hi Sahaj

Its very likely rpi builds are failing. We have been focusing on an internal release for the time being and have not gotten to test/catchup with raspberry pi builds of tangram-es.

That being said, your build issue could be just related to submodule `init`, `sync` and `update`. See if doing the following fixes it:

* `make clean`
* `git submodule init`
* `git submodule sync`
* `git submdoule update`
* make rpi

**Comment by ric96** [comment]
submodule is fine i did recheck that.
Its fine. just let us know when it works again.
also make clean might be broken as it start building for android 
and if i do make clean rpi it again builds for android and make rpi clean starts building for rpi.

**Comment by blair1618** [comment]
The build process for Raspberry Pi should be fixed with this PR: https://github.com/tangrams/tangram-es/pull/416 It was broken in a few places, so thanks for letting us know. 

`make clean` runs a clean for all the target platforms in sequence. Android is first in this sequence and cleaning the Android build involves a Gradle clean, which is probably what you saw running. 

`make clean-rpi` will clean just the RPi build files.

**Comment by ric96** [comment]
works well, thnx.
