### ISSUE TITLE
Build error with iOS static lib target in Xcode 12

### ISSUE THREAD

**Issue by AceDong0803** [tangrams/tangram-es#2193]
run : make ios-static-lib-universal 

 Build ios static lib show error in xcode12，but success in xcode 11 xcode 10

**Comment by matteblair** [comment]
Can you include the error log or screenshots from Xcode? I don't have Xcode 12 on my main computer.

**Comment by AceDong0803** [comment]
> Can you include the error log or screenshots from Xcode? I don't have Xcode 12 on my main computer.

![image](https://user-images.githubusercontent.com/17538276/95973064-c83e7200-0e45-11eb-8e97-524570f8d5c1.png)
the error screenshot

**Comment by AceDong0803** [comment]
make ios-static-lib
cmake -H. -Bbuild/ios -DTANGRAM_PLATFORM=ios -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_XCODE_GENERATE_SCHEME=0 -G Xcode
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type configuration:
-- Including platform CMake config file: platforms/ios/config.cmake
-- LOCAL_XCCONFIG: /Users/liuchuandong/tangram-esnew/platforms/ios/demo/Local.xcconfig
-- LOCAL_XCCONFIG: /Users/liuchuandong/tangram-esnew/platforms/ios/swift/Local.xcconfig
-- Performing Test FLAG_WEXTRA
-- Performing Test FLAG_WEXTRA - Success
CMake Deprecation Warning at core/deps/harfbuzz-icu-freetype/freetype/CMakeLists.txt:78 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Creating directory /Users/liuchuandong/tangram-esnew/build/ios/core/deps/harfbuzz-icu-freetype/freetype/include/freetype/config
-- Creating file /Users/liuchuandong/tangram-esnew/build/ios/core/deps/harfbuzz-icu-freetype/freetype/include/freetype/config/ftconfig.h
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for fcntl.h
-- Looking for fcntl.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Creating file /Users/liuchuandong/tangram-esnew/build/ios/core/deps/harfbuzz-icu-freetype/freetype/include/freetype/config/ftoption.h
-- harfbuzzfreetypeicucommon
-- Looking for GLM
-- GLM include /Users/liuchuandong/tangram-esnew/core/deps/glm
-- ALFONS_APPLE_LIBRARIES: -framework CoreGraphics-framework Foundation
-- CMake version: 3.19.0-rc1
-- CMAKE_CXX_COMPILER '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++' 'Clang' '12.0.0.12000032'
-- CMAKE_CXX_FLAGS                ' -fvisibility=hidden -fvisibility-inlines-hidden'
-- CMAKE_CXX_FLAGS_RELEASE        '-O3 -DNDEBUG'
-- SQLITECPP_RUN_CPPLINT OFF
-- SQLITECPP_RUN_CPPCHECK OFF
-- SQLITECPP_RUN_DOXYGEN OFF
-- SQLITECPP_BUILD_EXAMPLES OFF
-- SQLITECPP_BUILD_TESTS OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/liuchuandong/tangram-esnew/build/ios
xcodebuild -workspace platforms/ios/Tangram.xcworkspace -scheme tangram-static -configuration Release -sdk iphoneos | xcpretty && exit ${PIPESTATUS[0]}
▸ Running script 'Generate CMakeFiles/ZERO_CHECK'
▸ Running script 'Generate ../../core/generated/ambientLight_glsl.h'

**Comment by AceDong0803** [comment]
> Can you include the error log or screenshots from Xcode? I don't have Xcode 12 on my main computer.

the error screenshot 
![截屏2020-10-14 17 52 40](https://user-images.githubusercontent.com/17538276/95973379-25d2be80-0e46-11eb-9ccd-06aba9820116.png)

**Comment by matteblair** [comment]
Are you able to build for the iOS simulator with `make ios-static-sim`?

I tested Xcode 12.0.1 on CircleCI and the simulator build succeeded (https://app.circleci.com/pipelines/github/tangrams/tangram-es/117/workflows/de0fe1c3-f6d5-4619-9a84-16c0f60c61d5/jobs/8450).

**Comment by matteblair** [comment]
Aha, but `make ios-static-lib` fails the same way as in the screenshot (https://app.circleci.com/pipelines/github/tangrams/tangram-es/119/workflows/269c95f6-7df7-4e22-81e0-7b4de0baa14e/jobs/8458). Since this seems to be reproducible I'll look into it using CircleCI.

**Comment by matteblair** [comment]
I've determined that this only affects the `ios-static` targets, the `ios-framework` targets work as expected. Xcode 12.0.1 and Xcode 12.2.0 beta both seem to exhibit the same problem.

It seems like Xcode 12 is somehow failing to build the `tangram-core` library target before the `tangram-static` target, which depends on `tangram-core`. This could be a bug in Xcode 12, or in CMake's Xcode generator. Xcode introduced a "new" build system in Xcode 10 and as of Xcode 12 CMake is starting to use it by default, rather than the "legacy" system that CMake had used before.

As a workaround, it's possible to build `tangram-core` directly before building `tangram-static`: https://github.com/tangrams/tangram-es/pull/2194/commits/64f8bb9c3deda92d36c28feebe886e001b8ea04c With this change, `make ios-static-lib` succeeds in Xcode 12.

If I can't find any other fix I may just merge in this work-around.

**Comment by warpedgeoid** [comment]
@matteblair I'm seeing this pop up again with Xcode 12.4 and TangramES 0.14.1. Both on my local machine (Big Sur) and a CI agent running Catalina.
