### ISSUE TITLE
Compilation error with newest branch master

### ISSUE THREAD

**Issue by whitespeed** [tangrams/tangram-es#2202]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
Android compile error

**RESULT:**

![image](https://user-images.githubusercontent.com/5187837/97835959-43dd6180-1d16-11eb-9cb6-b335cfe49aea.png)

**ENVIRONMENT:**

newest master branch.  lost native methods.

**Comment by matteblair** [comment]
This isn't actually a compilation error, if it were then our automated builds would have failed. 

However, this _will_ cause errors at runtime if these methods are invoked. It seems like these native implementations got lost in the recent refactor (https://github.com/tangrams/tangram-es/pull/2187), that's my bad. It won't take long to fix though, I can do this today.
