### ISSUE TITLE
Zooming out with tap+drag gesture is too fast

### ISSUE THREAD

**Issue by kuba-orlik** [tangrams/tangram-es#2207]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

 - Use [StreetComplete](https://github.com/westnordost/StreetComplete)'s app, v26.2
 - Zoom out using the tap + drag gesture

**RESULT:**

The map zooms out super fast, goes from street level to world level in a fraction of a second. 

See the result here:

https://vimeo.com/480702185

**EXPECTED RESULT:**

The zoom out happens more gradually, allowing for fine control of the zoom level

**ENVIRONMENT:**

 - Nexus 5X, Android 8.1.0

**OTHER:**

The bug happens on StreetComplete, but to my understanding the authors of the app did not change the behavior of the tap+drag gesture in any way

**Comment by westnordost** [comment]
tangram 0.13.0

**Comment by matteblair** [comment]
Thanks for the report and the video - that does seem way too fast. I'll check this out.

**Comment by westnordost** [comment]
I am not sure if this behavior is overrideable at all? Can you tell which touch input responder this would be?

**Comment by matteblair** [comment]
The pinch scaling and the tap-swipe scaling behaviors are handled by a `ScaleResponder` (https://github.com/tangrams/tangram-es/blob/master/platforms/android/tangram/src/main/java/com/mapzen/tangram/TouchInput.java#L151-L173). Both of these gestures are detected by Android's built-in [ScaleGestureDetector](https://developer.android.com/reference/android/view/ScaleGestureDetector).

**Comment by matteblair** [comment]
I was able to reproduce an issue with the quick-scale gesture that seems similar to this. The changes in https://github.com/tangrams/tangram-es/pull/2208 resolved the problem that I was seeing. 

In your app, can you try setting the `MapController` to continuous rendering mode with `mapController.setRenderMode(1)`? If that change fixes this behavior on your end then it's very likely that you are having the same problem that I saw.

**Comment by westnordost** [comment]
Wait, in which timezone are you? I thought you were in the US? 

Anyway, I tried it out with setting `mapController.setRenderMode(1)` and I can confirm that it workarounds the behavior.

**Comment by matteblair** [comment]
Cool! Changing the render mode might be ok as a temporary workaround, but be aware that it will increase power consumption.

I am in the US but have very late hours 🙃

**Comment by westnordost** [comment]
Okay, me too ;-)

I rather choose not to do the temporary workaround if it is going to shorten the battery life.

**Comment by matteblair** [comment]
I believe this is resolved by https://github.com/tangrams/tangram-es/pull/2208, which has been released in version 0.14.0. Please re-open if you encounter this again after upgrading!
