### ISSUE TITLE
Compilation fails with gcc-7.5

### ISSUE THREAD

**Issue by saai63** [tangrams/tangram-es#2209]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
make linux

**RESULT:**
Build fails
---------
/home/.../work/tangram-es/tangram-es/core/deps/glm/glm/detail/type_vec4_simd.inl:156:11: error: ‘struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));
           ^~~~
/home/.../work/tangram-es/tangram-es/core/deps/glm/glm/detail/type_vec4_simd.inl:156:31: error: ‘const struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));
                               ^~~~
/home/.../work/tangram-es/tangram-es/core/deps/glm/glm/detail/type_vec4_simd.inl:156:50: error: ‘const struct glm::tvec4<float, (glm::precision)5>’ has no member named ‘data’
    Result.data = _mm_mul_ps(a.data, _mm_rcp_ps(b.data));
                                                  ^~~~
/home/.../work/tangram-es/tangram-es/core/deps/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(T) [with T = float; glm::precision P = (glm::precision)5]’:
/home/ksp3kor/work/tangram-es/tangram-es/core/deps/glm/glm/detail/type_vec4_simd.inl:367:3: error: class ‘glm::tvec4<float, (glm::precision)5>’ does not have any field named ‘data’
   data(_mm_set1_ps(s))
   ^~~~
/home/.../work/tangram-es/tangram-es/core/deps/glm/glm/detail/type_vec4_simd.inl: In constructor ‘glm::tvec4<T, P>::tvec4(T) [with T = float; glm::precision P = (glm::precision)4]’:
/home/.../work/tangram-es/tangram-es/core/deps/glm/glm/detail/type_vec4_simd.inl:372:3: error: class ‘glm::tvec4<float, (glm::precision)4>’ does not have any field named ‘data’
   data(_mm_set1_ps(s))
   ^~~~

---------

**EXPECTED RESULT:**

Build should be successful

**ENVIRONMENT:**

Ubuntu 18.04
4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

**OTHER:**

Any additional notes, comments, tips, tricks, gifs, suggestions, poetry, recipes, jokes

If you are able to record the log output from tangram-es, please attach it as a text file or share it using a site like https://hastebin.com/

**Comment by matteblair** [comment]
Thanks for the report! I'm able to reproduce this error in an Ubuntu 18.04 container with GCC 7.5. The automated builds also use Ubuntu 18.04, but with GCC 7.3 instead - so they do not encounter this error.

The solution to this is probably to update the version of [GLM](https://github.com/g-truc/glm/releases) that we include in our [dependencies](https://github.com/tangrams/tangram-es/tree/master/core/deps/glm). I will have to verify that a new version doesn't break anything (it has happened before, specifically with GLM) so this may take a few days.

**Comment by saai63** [comment]
Hello @matteblair 

Thank you!
The build was successful after adding the below lines of code to 'core/deps/glm/glm/simd/platform.h'
`#	elif (__GNUC__ == 7) && (__GNUC_MINOR__ == 5)
#		define GLM_COMPILER (GLM_COMPILER_GCC72)`
