### ISSUE TITLE
Showing blank screen in Android 10 device.

### ISSUE THREAD

**Issue by android-team-stack** [tangrams/tangram-es#2210]
Not loading tiles in android 10 device. The tiles present in our server. And I am using the tile server link as source in scene.yaml file and added layers according to data. But it is working fine below android 10 device. Please check the Log file for this issue.
[Log.txt](https://github.com/tangrams/tangram-es/files/5578050/Log.txt)

**Comment by matteblair** [comment]
Hi, thanks for the report. Are you saying your scene file and tiles are working correctly on some Android devices, but not on Android 10? If you're able to share your scene file that might help to figure this out.

**Comment by android-team-stack** [comment]
Yes, you are correct. I am using the scene file which is present inside tangram-android-demos project only by changing the sources and layers. Please check the scene file.
[scene.txt](https://github.com/tangrams/tangram-es/files/5578676/scene.txt)

**Comment by android-team-stack** [comment]
Ok I got the solution. Thank you.

**Comment by matteblair** [comment]
@android-team-stack Can you share what your solution was, in case it helps other users?

**Comment by android-team-stack** [comment]
Reason: If the source url starts with "http" then in android 10 devices the map is showing as blank screen as it can't call any network request to fetch the map tile. Because in android 10 device if the network request starts with http then OkHttp throws an IOException that's why the response goes to onFailure() method. 

Solution : Need to add `android:usesCleartextTraffic="true"` inside AndroidManifest.xml under application tag.

Suggestion to Tangram ES : If Tangram ES android SDK print the log statement inside onRespose() and onFailure() method in MapController.java then it will be easy to find out the error for developer.
