### ISSUE TITLE
Filled circle on Android

### ISSUE THREAD

**Issue by FunnyDevs** [tangrams/tangram-es#2227]
Hi! Is there some api to draw a filled circle (even with borders) like Google Maps Api? I haven't found an example to do that.

Thanks

**Comment by matteblair** [comment]
Hello! Can you share a specific example of what you're trying to replicate from the Google Maps API (method calls or screenshots)?

**Comment by FunnyDevs** [comment]
https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/model/Circle

this is the link of the official documentation with a code example

**Comment by matteblair** [comment]
Thanks for the clarification - there's no built-in API for rendering a circle in Tangram ES right now. You would need to generate a set of coordinates to represent the circle using your own code.

**Comment by FunnyDevs** [comment]
ok, thank you. So, if i use a set of coordinates to represent the border of the circle, then am i able fill it like this example?

https://play.tangram.city/?scene=https://tangrams.github.io/tangram-docs/tutorials/editing-basemaps/editing-basemaps1.yaml&lines=1#5/38.720/-79.717

**Comment by matteblair** [comment]
Yes, exactly. In your scene you can add a styling layer like the one called `_blob` in this example and then add your coordinates via the Tangram Android SDK using a `MapData` with the same name as the data source (`_mine`, in this example).

**Comment by FunnyDevs** [comment]
ok, i've tried and it works! Thank you!
