### ISSUE TITLE
C # extended library

### ISSUE THREAD

**Issue by jinyuttt** [tangrams/tangram-es#2230]
Is it available?WPF?

**Comment by matteblair** [comment]
Hi @jinyuttt, can you be more specific about what you are looking for?

**Comment by warpedgeoid** [comment]
I'm assuming that @jinyuttt wants C# bindings for Tangram-ES for use in a WPF app. Since this would first require Tangram-ES to support Windows platform, I doubt this is doable right now.

**Comment by jinyuttt** [comment]
@warpedgeoid yes,net core

**Comment by warpedgeoid** [comment]
@matteblair wasn’t there an effort to make a Windows port awhile back?

**Comment by matteblair** [comment]
Yes, there is a PR for a MinGW port that I have neglected to follow up on: https://github.com/tangrams/tangram-es/pull/2035 I have made other attempts at a "native" Windows port using MSVC as well, but that's a more involved problem. There seems to be persistent interest in a Windows port of some form, so I will endeavor to finally merge that.

However I don't think a Windows port of our C++ library will fulfill the request for a .NET API. @jinyuttt Do you have experience creating .NET bindings for C++ libraries?

**Comment by charlenni** [comment]
Is there any documentation, what is needed for a new platform? And could the core part build as library without any platform?
