### ISSUE TITLE
iOS scene files as bundles does not work properly

### ISSUE THREAD

**Issue by rwrx** [tangrams/tangram-es#2233]
I have noticed that after this commit https://github.com/tangrams/tangram-es/commit/4114aeccbda6f9272d2f891ae04822a061203f57 when scene files are added into iOS project as bundles - zipped files (I am using them in this way so that they are included in the project) textures inside scene are not loaded or something wrong is happening. I have not digged into code change more, but it is broken. I have noticed that it is working when these scene files are added by internet url to zip it is working, but I need to use them as bundles which are contained inside application.

**Comment by rwrx** [comment]
@matteblair maybe for you it is a quick fix, so I do not wanted to dig into it yet.

**Comment by matteblair** [comment]
Hi, I've just tested out a scene file in a bundle on iOS and the textures seem to be loading correctly. Can you describe in more detail the problem you're seeing? Or, better yet, do you have an example of a scene bundle that isn't working for you?

**Comment by rwrx** [comment]
Thank you a lot for looking into it. For example Walkabout style: https://cloud.vecturagames.com/index.php/s/ZmeesYiBiXPEo6E . But you need to uncomment sources, because they are commented out.

**Comment by matteblair** [comment]
Thanks for the example - I've reproduced the issue and will report back when I find a fix.

**Comment by tallytalwar** [comment]
@matteblair could you put some logs or your initial findings here, maybe I can recollect the logic of code around this and help direct indirectly. Thanks
