### ISSUE TITLE
Release artifacts need to move off of Bintray

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#2234]
JFrog is ending service for Bintray and JCenter, which is where we currently host our release artifacts for Android and iOS.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter

We need to move these artifacts onto a different service before May 1, 2021.

**Comment by westnordost** [comment]
In Bird culture, this is considered a dick move.

Anyway, as I also have to migrate some libraries away from Dicktray, I read a bit into this, here is some useful info about it from [gradle.org](https://blog.gradle.org/jcenter-shutdown):

> Impact to packages publishing to Bintray
> 
> If you are publishing your builds to Bintray using the [com.jfrog.bintray](https://github.com/bintray/gradle-bintray-plugin) plugin, you’ll need to find another repository to host your package. You may be able to publish using the [built-in maven-publish](https://docs.gradle.org/current/userguide/publishing_setup.html#header).
> 
> If you’re migrating to Maven Central, the [io.github.gradle-nexus.publish-plugin](https://github.com/gradle-nexus/publish-plugin) plugin automates publishing to Nexus and Maven Central.

Also important for anyone **using** JCenter to date to get dependencies is this security consideration:

> As we have seen in recent years, dependency confusion and namespace collisions can be serious dangers for supply chain attacks. Each of these vulnerabilities relied on untrusted artifacts being used in place of trusted ones.
> 
> When you change the list of repositories you use to resolve dependencies, you may inadvertently expose yourself to these kinds of attacks.

Gradle offers a mechanism to defend against this, [described in their user guide](https://docs.gradle.org/current/userguide/dependency_verification.html#sub:enabling-verification). In a nutshell:

Execute `gradle --write-verification-metadata sha256 help` to bootstrap checksum verification of dependencies, then after that you can change the repository to fetch dependencies from and gradle will throw an error if the checksum of a dependency now located somewhere else is different.
