### ISSUE TITLE
Translucent background 

### ISSUE THREAD

**Issue by soheilarmin** [tangrams/tangram-es#2235]
Currently, background opacity is ignored. Is there anyway we can have a background with alpha channel, or optionally entirely remove the background?

**Comment by matteblair** [comment]
Hello! There currently is not a way to change the opacity of the map background, but it may be possible to add this as a feature. 

Can you tell me which platform(s) you are targeting and describe your use case in more detail?

**Comment by soheilarmin** [comment]
Hi,
I'm using Tangram-es on Android. From my understanding, I need to change the color depth to 8,8,8,8. I'm not sure about all other changes that should take place. It would be nice if you can help. There are many many good features (like shaders) that Mapbox lacks of, so I'm deciding to use Tangram over Mapbox but this single feature about translucent background is really needed for my use case. 
I need to blend the map in several applications (like a media player). Those application have very simple backgrounds and map objects should be drawn over those background images. So, I will need to remove the current solid background color. As far as I know, I cannot apply a fragment shader on the background.
