### ISSUE TITLE
How to compile and see the sample applications using the library on Ubuntu

### ISSUE THREAD

**Issue by WilliamWangPeng** [tangrams/tangram-es#2242]
Dear experts
    My question is how to compile and see the sample applications using the library on Ubuntu.

Thank you
Best Regards
William

**Comment by matteblair** [comment]
Hello! The linux platform README has exactly what you're looking for: https://github.com/tangrams/tangram-es/blob/main/platforms/linux/README.md

Feel free to open another issue if you have problems following these steps.
