### ISSUE TITLE
how to implement a fill cicle  and sprite(icon) mix show？

### ISSUE THREAD

**Issue by ccxxbb** [tangrams/tangram-es#2251]
I wang to implement a fill cicle and sprite(icon) mix show  on a single point

**Comment by warpedgeoid** [comment]
You should be able to easily accomplish this by using two different styles in the same draw group. See the documentation on draw groups ([link](https://tangrams.readthedocs.io/en/master/Syntax-Reference/draw/#draw)) for details.

**Comment by warpedgeoid** [comment]
@ccxxbb was this able to resolve your issue? Also, I might recommend that you check out the tangram-chat gitter as another place for support.

https://gitter.im/tangrams/tangram-chat

**Comment by ccxxbb** [comment]
This  is effective，thank you .  I'll follow tangram-chat gitter later
