### ISSUE TITLE
Black background shown for all dashed line styles

### ISSUE THREAD

**Issue by warpedgeoid** [tangrams/tangram-es#2256]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

Apply a dashed style to any line or polygon features.

**RESULT:**

<img width="418" alt="image" src="https://user-images.githubusercontent.com/7670504/112771893-09919b00-8ffc-11eb-8c56-e3bd55301f53.png">

**EXPECTED RESULT:**

The default dashed line background color should be transparent. This was the case until recently. I wasn't paying attention, so I'm not sure exactly when this started occurring, but I can state confidently that it used to work just fine.

**ENVIRONMENT:**

 - Tangram ES on iOS

As far as I know, our styles haven't changed. However, I can confirm that all of the dashed lines are now showing this black background by default.

**Comment by matteblair** [comment]
Ooh yikes, that's a regression all right. I can confirm it on macOS as well so it may not be a platform-specific bug.

**Comment by warpedgeoid** [comment]
Whew, glad it wasn't just me. The app from the screenshot is using Tangram ES 0.14.1.
