### ISSUE TITLE
Added a boundary that returns the current Zoom Level

### ISSUE THREAD

**Issue by fail572872916** [tangrams/tangram-es#2266]
Actually I want to do a marker aggregation effect on Android, I need to know the current Zoom level boundary, or do you have any other better scheme

**Comment by matteblair** [comment]
Sorry, but I don't understand what you are asking. What do you mean by boundary?

**Comment by fail572872916** [comment]
> Sorry, but I don't understand what you are asking. What do you mean by boundary?
The four vertex coordinates of the current screen will change as the screen is scaled

**Comment by matteblair** [comment]
I think what you are asking is: How can I find the boundary of the current map view?

You can call `MapController.screenPositionToLngLat()` for each of the four corners of the view. If your view has width _w_ and height _h_ then the corners would be (0, 0), (_w_, 0), (_w_, _h_), (0, _h_). That will give you the four `LngLat` coordinates that define the boundary of the current map view.

**Comment by fail572872916** [comment]
> 我想你要问的是：如何找到当前地图视图的边界？
> 
> 您可以调用视图的四个角中的每一个。如果您的视图具有宽度_w_和高度_h，_则角为 （0，0）、（w ， 0）、（w， _h）、（0、h）。_ 这将为您提供定义当前地图视图边界的四个坐标。`MapController.screenPositionToLngLat()``LngLat`

Yes, what I need to know is the four vertex coordinates of the current world zoom level, can I get them based on the current width and height of my MapView space?

**Comment by fail572872916** [comment]
Thank you. My problem is solved
