### ISSUE TITLE
[Feature Request] Rotate around non-center point

### ISSUE THREAD

**Issue by smichel17** [tangrams/tangram-es#2284]
- Downstream issue: https://github.com/streetcomplete/StreetComplete/issues/3101

   In StreetComplete, when a quest form or "add note" form is open, the map is partially obscured, so the visible center is not the same as the screen center. In this case, operations should take place around this offset center, not the screen center. StreetComplete has some workarounds to enable this, but rotating the map to face north (when the user presses the compass button) was not easily possible:

- https://github.com/streetcomplete/StreetComplete/pull/3122

   It would be great if there were a way to set a different center for rotation (or movement!) events. I imagine this would be added to the `CameraUpdate`, but I'm not familiar enough with Tangram to say for sure.

**Comment by westnordost** [comment]
So, basically the feature request ist to be able to define a pivot-point around which the camera update is rotated (and zoomed)

**Comment by warpedgeoid** [comment]
This would be very helpful for my application, too. Actually, it would be helpful if a margin could be defined that would shift the map to avoid the region at the current center from being obstructed by UI elements that might move or expand.

**Comment by matteblair** [comment]
This is in-progress. The basic idea is to add a method on the map view of the form:
```
setPadding(int left, int top, int right, int bottom)
```
The "padding" values will determine the relative position of the map's center position in the view.

This functionality is working in the desktop app in my current branch, and I hope to get this into the mobile SDKs in the next few days.

**Comment by warpedgeoid** [comment]
Thanks, @matteblair! Amazing work, as always!

**Comment by matteblair** [comment]
Resolved by https://github.com/tangrams/tangram-es/pull/2294
