### ISSUE TITLE
Windows platform compilation error

### ISSUE THREAD

**Issue by whitespeed** [tangrams/tangram-es#2285]
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**
Windows platform complie error
initializer list support error
**RESULT:**
![image](https://user-images.githubusercontent.com/5187837/128679757-28d4ed2e-72fb-40e4-9bed-b104c3343808.png)

**ENVIRONMENT:**
Microsoft Visual Studio 2019
Version 16.9.4

**Comment by matteblair** [comment]
Hi, thanks for the report. Can you provide the CMake log from your build as well as the full text of the first compilation error that you are seeing?

**Comment by whitespeed** [comment]
------------------------------------------CMake Log-----------------------------------------------------------
1> CMake generation started for configuration: 'x64-Debug'.
1> Found and using vcpkg toolchain file (E:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake).
1> Command line: "cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "D:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="E:\projects\tangram-es\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="D:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="D:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="D:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="E:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake" "E:\projects\tangram-es" 2>&1"
1> Working directory: E:\projects\tangram-es\build\x64-Debug
1> [CMake] -- Running vcpkg install
1> [CMake] Detecting compiler hash for triplet x64-windows...
1> [CMake] All requested packages are currently installed.
1> [CMake] 
1> [CMake] Total elapsed time: 4.1 us
1> [CMake] 
1> [CMake] The package benchmark:x64-windows provides CMake targets:
1> [CMake] 
1> [CMake]     find_package(benchmark CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE benchmark::benchmark benchmark::benchmark_main)
1> [CMake] 
1> [CMake] The package zlib is compatible with built-in CMake targets:
1> [CMake] 
1> [CMake] 
1> [CMake] 
1> [CMake]     find_package(ZLIB REQUIRED)
1> [CMake] 
1> [CMake]     target_link_libraries(main PRIVATE ZLIB::ZLIB)
1> [CMake] 
1> [CMake] 
1> [CMake] The package curl:x64-windows provides CMake targets:
1> [CMake] 
1> [CMake]     find_package(CURL CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE CURL::libcurl)
1> [CMake] 
1> [CMake] The package glad:x64-windows provides CMake targets:
1> [CMake] 
1> [CMake]     find_package(glad CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE glad::glad)
1> [CMake] 
1> [CMake] The package glfw3:x64-windows provides CMake targets:
1> [CMake] 
1> [CMake]     find_package(glfw3 CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE glfw)
1> [CMake] 
1> [CMake] The package harfbuzz:x64-windows provides CMake targets:
1> [CMake] 
1> [CMake]     find_package(harfbuzz CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE harfbuzz harfbuzz::harfbuzz)
1> [CMake] 
1> [CMake] The package imgui:x64-windows provides CMake targets:
1> [CMake] 
1> [CMake]     find_package(imgui CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE imgui::imgui)
1> [CMake] 
1> [CMake] The package yaml-cpp:x64-windows provides CMake targets:
1> [CMake] 
1> [CMake]     find_package(yaml-cpp CONFIG REQUIRED)
1> [CMake]     target_link_libraries(main PRIVATE yaml-cpp)
1> [CMake] 
1> [CMake] -- Running vcpkg install - done
1> [CMake] -- Build type configuration: Debug
1> [CMake] -- Including platform CMake config file: platforms/windows/config.cmake
1> [CMake] CMake Warning (dev) at build/x64-Debug/vcpkg_installed/x64-windows/share/zlib/vcpkg-cmake-wrapper.cmake:13 (_find_package):
1> [CMake]   Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
1> [CMake]   Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
1> [CMake]   command to set the policy and suppress this warning.
1> [CMake] 
1> [CMake]   CMake variable ZLIB_ROOT is set to:
1> [CMake] 
1> [CMake]     E:/projects/tangram-es/build/x64-Debug/vcpkg_installed/x64-windows
1> [CMake] 
1> [CMake]   For compatibility, CMake is ignoring the variable.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   E:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:736 (include)
1> [CMake]   D:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
1> [CMake]   build/x64-Debug/vcpkg_installed/x64-windows/share/curl/CURLConfig.cmake:53 (find_dependency)
1> [CMake]   build/x64-Debug/vcpkg_installed/x64-windows/share/curl/vcpkg-cmake-wrapper.cmake:7 (_find_package)
1> [CMake]   E:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:736 (include)
1> [CMake]   platforms/windows/config.cmake:10 (find_package)
1> [CMake]   CMakeLists.txt:64 (include)
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
1> [CMake] -- Found ZLIB: optimized;E:/projects/tangram-es/build/x64-Debug/vcpkg_installed/x64-windows/lib/zlib.lib;debug;E:/projects/tangram-es/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/zlibd.lib (found suitable version "1.2.11", minimum required is "1") 
1> [CMake] CMake Deprecation Warning at platforms/common/glfw/CMakeLists.txt:10 (cmake_policy):
1> [CMake]   The OLD behavior for policy CMP0042 will be removed from a future version
1> [CMake]   of CMake.
1> [CMake] 
1> [CMake]   The cmake-policies(7) manual explains that the OLD behaviors of all
1> [CMake]   policies are deprecated and that a policy should be set to OLD only under
1> [CMake]   specific short-term circumstances.  Projects should be ported to the NEW
1> [CMake]   behavior and not rely on setting a policy to OLD.
1> [CMake] 
1> [CMake] 
1> [CMake] -- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
1> [CMake] -- Using Win32 for window creation
1> [CMake] CMake Warning (dev) at build/x64-Debug/vcpkg_installed/x64-windows/share/zlib/vcpkg-cmake-wrapper.cmake:13 (_find_package):
1> [CMake]   Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
1> [CMake]   Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
1> [CMake]   command to set the policy and suppress this warning.
1> [CMake] 
1> [CMake]   CMake variable ZLIB_ROOT is set to:
1> [CMake] 
1> [CMake]     E:/projects/tangram-es/build/x64-Debug/vcpkg_installed/x64-windows
1> [CMake] 
1> [CMake]   For compatibility, CMake is ignoring the variable.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   E:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:736 (include)
1> [CMake]   core/CMakeLists.txt:4 (find_package)
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
1> [CMake] -- Found ZLIB: optimized;E:/projects/tangram-es/build/x64-Debug/vcpkg_installed/x64-windows/lib/zlib.lib;debug;E:/projects/tangram-es/build/x64-Debug/vcpkg_installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.11") 
1> [CMake] CMake Warning (dev) at build/x64-Debug/vcpkg_installed/x64-windows/share/zlib/vcpkg-cmake-wrapper.cmake:13 (_find_package):
1> [CMake]   Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
1> [CMake]   Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
1> [CMake]   command to set the policy and suppress this warning.
1> [CMake] 
1> [CMake]   CMake variable ZLIB_ROOT is set to:
1> [CMake] 
1> [CMake]     E:/projects/tangram-es/build/x64-Debug/vcpkg_installed/x64-windows
1> [CMake] 
1> [CMake]   For compatibility, CMake is ignoring the variable.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   E:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:736 (include)
1> [CMake]   D:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
1> [CMake]   build/x64-Debug/vcpkg_installed/x64-windows/share/freetype/freetype-config.cmake:2 (find_dependency)
1> [CMake]   E:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package)
1> [CMake]   build/x64-Debug/vcpkg_installed/x64-windows/share/harfbuzz/harfbuzzConfig.cmake:25 (find_package)
1> [CMake]   E:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake:782 (_find_package)
1> [CMake]   core/deps/CMakeLists.txt:55 (find_package)
1> [CMake] This warning is for project developers.  Use -Wno-dev to suppress it.
1> [CMake] -- Found the following ICU libraries:
1> [CMake] --   uc (required)
1> [CMake] --   data (required)
1> [CMake] -- Looking for GLM
1> [CMake] -- GLM include E:/projects/tangram-es/core/deps/glm
1> [CMake] -- Using c++ standard c++17
1> [CMake] -- CMake version: 3.19.20122902-MSVC_2
1> [CMake] -- Project version: 3.1.1
1> [CMake] -- CMAKE_CXX_COMPILER 'D:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe' 'MSVC' '19.28.29914.0'
1> [CMake] -- CMAKE_CXX_FLAGS                '/DWIN32 /D_WINDOWS /W3 /GR /EHsc'
1> [CMake] -- CMAKE_CXX_FLAGS_DEBUG          '/MDd /Zi /Ob0 /Od /RTC1'
1> [CMake] -- CMAKE_CXX_FLAGS_RELEASE        '/MD /O2 /Ob2 /DNDEBUG'
1> [CMake] -- CMAKE_CXX_FLAGS_RELWITHDEBINFO '/MD /Zi /O2 /Ob1 /DNDEBUG'
1> [CMake] -- CMAKE_CXX_FLAGS_MINSIZEREL     '/MD /O1 /Ob1 /DNDEBUG'
1> [CMake] -- Compile sqlite3 from source in subdirectory
1> [CMake] -- SQLITECPP_RUN_CPPLINT OFF
1> [CMake] -- SQLITECPP_RUN_CPPCHECK OFF
1> [CMake] -- SQLITECPP_RUN_DOXYGEN OFF
1> [CMake] -- SQLITECPP_BUILD_EXAMPLES OFF
1> [CMake] -- SQLITECPP_BUILD_TESTS OFF
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: E:/projects/tangram-es/build/x64-Debug
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted includes paths.
1> CMake generation finished.

**Comment by whitespeed** [comment]
Severity	Code	Description	File	Line	Source	Suppression State
Error	C2664	'void std::vector<mapbox::geometry::feature<T>,std::allocator<mapbox::geometry::feature<T>>>::push_back(const _Ty &)': cannot convert argument 1 from 'initializer list' to 'const _Ty &'	E:\projects\tangram-es\core\deps\geojson-vt-cpp\include\mapbox\geojsonvt\tile.hpp	99

**Comment by whitespeed** [comment]
First error has been resolved, just left these.
![image](https://user-images.githubusercontent.com/5187837/128863995-391a6641-0b76-4e1a-b84c-7cd70f4218f5.png)

**Comment by matteblair** [comment]
I am not able to reproduce these errors on my Windows machine, and the automated Windows builds don't encounter these errors either (https://github.com/tangrams/tangram-es/runs/3297135316?check_suite_focus=true). Have you checked that your repository is up-to-date on the main branch and that your submodules are updated?
