### ISSUE TITLE
Excessive Storage Utilisation - Tiles are cached at duplicate locations, never get pruned

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#2298]
Spawned from https://github.com/streetcomplete/StreetComplete/issues/3417 .

## In a nutshell
It looks like the map tiles are cached both at the location the user of this library specified and at another location at the same time. The issues are:
- that the tiles get cached at that other location at all, this duplicates the cache space requirement
- that the tiles in that other location seemingly never get pruned

## My cache configuration

```kotlin
// = sdcard/Android/data/de.westnordost.streetcomplete/cache/tile_cache
val cacheDir = File(context.externalCacheDir, "tile_cache")

val cache = Cache(cacheDir , 50 * 1000L * 1000L) // prune after reaching 50 MB

val cacheControl = CacheControl.Builder()
    .maxAge(12, TimeUnit.HOURS) // do not re-download tiles younger than 12 hours
    .maxStale(14, TimeUnit.DAYS) // prune tiles older than 14 days
    .build()

val httpHandler = object : DefaultHttpHandler(OkHttpClient.Builder().cache(cache)) {
    override fun configureRequest(url: HttpUrl, builder: Request.Builder) {
        builder.cacheControl(cacheControl)
    }
}

tangramMapView.initMap(httpHandler )
```

The OkHttpCache actually prunes tiles in `sdcard/Android/data/de.westnordost.streetcomplete/cache/tile_cache` correctly when this directory exceeds a size of 50MB. I tested this.

## What is wrong? Observations

1. Reported cache size:
![image](https://user-images.githubusercontent.com/4661658/139259739-4e8d8693-b4d7-4b72-9aab-c7bbf286e21c.png) 

2. Actual size of external cache directory:
![image](https://user-images.githubusercontent.com/4661658/139262567-2a9d746a-d7a1-40be-ab8c-8594a9bbf9af.png)

3. There are no other cache files in neither of
    - `/sdcard/Android/data/de.westnordost.streetcomplete/cache/`
    - `/data/data/de.westnordost.streetcomplete/cache/`

4. When panning the map and thus downloading new tiles, the reported cache size grows at pretty much at 2x the rate as the size of the external cache directory 

5. When comparing the total free storage space on the phone before and after clearing the cache for the app, it is clear that the reported cache size by Android is **not** a display error: In this case, indeed 57 MB storage space has been freed. 
However, the size of the directories mentioned in point 3 were reduced by only 22MB.

Thus, I conclude that there must be a third directory **somewhere** where the tiles are cached and that is never pruned that is outside of the directories mentioned in point 3 and used by tangram-es to store duplicates of the downloaded tiles.
Android is able to attribute this directory to the app and able to clear it but I have not found where on the sdcard it is supposed to be.

## Used versions
- tangram-es 0.16.2
- Android (different versions, different devices)

**Comment by matteblair** [comment]
Good information to know! This makes me think that it would be possible to implement a more space-efficient cache by combining tile responses into a single file - like a sqlite database. I don't expect to do this in Tangram ES but it might be possible for a client application.

**Comment by Joxit** [comment]
Hi there, yes file system is not adapted to tile storing, you should use SQLite based on the [MBTiles specification](https://github.com/mapbox/mbtiles-spec)

**Comment by matteblair** [comment]
@Joxit indeed MBTiles is what I had in mind when I mentioned an sqlite database. It's a tempting idea, but I think it would be pretty complicated for a couple reasons:
1. In addition to storing tile data, we also need to respect cache control headers in the client request and in the server response. Currently this is handled by OkHTTP. Implementing this again would be non-trivial work and would probably not be as good as OkHTTP's implementation!
2. Tangram ES doesn't just request tiles, it can also request scene files, scene bundles, or image resources over HTTP. These other resources don't fit in the MBTiles schema, so we would need multiple caches for different types of resources.

This doesn't mean it can't be done! Tangram ES allows a client application to replace the entire HTTP implementation, so you could certainly create a tile cache based on MBTiles if you wanted to.

**Comment by westnordost** [comment]
Hmm...
1. To create a tile cache based on MBTiles just so to store the cache more efficiently seems something no user of a map render library would do. So it seems this is something that should be done by the render library.
2. However, for web-maps (tangram, maplibre-gl-js), the render library obviously does not manage the cache by itself but the browser does that. So why should the library on native manage the cache itself and on the web, not?

I am not sure if browsers put all the cached files in some kind of giant indexed table so they don't have this problem. I'd also be curious how MapLibre handles this.

**Comment by smichel17** [comment]
Seems like the ideal setup would be an independent library which handles this. That way it could be shared between renderers, and only included when needed.

**Comment by tallytalwar** [comment]
Last I remember we did add some code to do offline Rendering via mbtiles. If needed we should be able to use that tile source class generically for all tile source cache?

**Comment by matteblair** [comment]
Yep, there is code in Tangram ES currently for caching vector tile sources in a local mbtiles database. However in its current form it isn't a substitute for HTTP caching. The existing mbtiles cache will naively store all tiles forever, regardless of the `cache-control` headers that accompanied the tile response. 

I looked into maplibre to see what approach is used there. It does seem to use a local sqlite database for tile caching, complete with parsing and logic for response headers. The maplibre caching code is in the shared native library, for reuse across platforms. 

A similar approach would make sense for Tangram ES. Tile caching could be implemented in the shared core library using sqlite, with options like the maximum cache size exposed to the client SDKs. I would support this approach, I think it could lead to a better user experience for Tangram ES. But the scope of this work is beyond my current availability (for the time being, at least).

It would be nice if the caching code from maplibre could be shared in an independent library, but unfortunately it seems very tightly coupled with the internals of their renderer.
