### ISSUE TITLE
Loading Resource bug

### ISSUE THREAD

**Issue by hoss291069** [tangrams/tangram-es#2310]
Hi.
some times tangram doesn't load map, and crash in loading resources.
I found bug that cause this problem. in urlClient.cpp the following two lines must be  moved.
m_curlWorker = std::make_unique<std::thread>(&UrlClient::curlLoop, this);
m_curlRunning = true;
When we set thread running flag after thread creation, it's possible thread don't run.

**Comment by matteblair** [comment]
Hi! Thanks for the report. I have never encountered this issue in my testing, but I think you are correct that depending on thread scheduling it is possible for the worker thread to start before the `m_curlRunning` flag is set, which would lead it to immediately exit! I have just created a PR for the fix.
