### ISSUE TITLE
 Two independent maps on screen

### ISSUE THREAD

**Issue by ccxxbb** [tangrams/tangram-es#2325]
I want to display two independent maps on the top and bottom of one  screen, but after looking at the code, I find that there are global variables in the namespace primitives, which should be a problem. I would like to ask if there is any good solution to this problem

**Comment by matteblair** [comment]
There should be no problem with running two or more Map instances at the same time. The 'primitives' namespace is a debugging utility that isn't intended for production use. If you try to use multiple Map instances and encounter a problems, please file an issue for that specific case.
