### ISSUE TITLE
[Solved] How set Marker (as bitmap) over textlayer ?

### ISSUE THREAD

**Issue by swa00** [tangrams/tangram-es#2329]
i'm trying to add a bitmap based marker programmaticaly.

How to set this Marker as overlay on top of any layer that was defined in scene file ?
Its  working with all layers ( lines / polygons), but not on text layers.

Here my Source:

`  Marker p = map.addMarker();
       p.setStylingFromString("{ style: 'overlay_points', color: 'white', size: ["+width/3+"px, "+height/3+"px], order: 500, flat: false, collide: false}");
       p.setDrawable(bb);
       LngLat startPoint = new LngLat(lon, lat);
       p.setPoint(startPoint);`

Style  define of "overlay_points"
`styles:
      overlay_points:
        base: points
        blend: overlay
`

 
Here the result:
![image](https://user-images.githubusercontent.com/21235108/178564919-d4cdc3db-c01a-421e-964f-7f4cfff5f573.png)

Thx a lot

**Comment by swa00** [comment]
Solution: 
Add "blend_order: 1" to style

` overlay_points:
        base: points
        blend: overlay
        blend_order: 1`

Result 👍 
![image](https://user-images.githubusercontent.com/21235108/178567168-ff003a30-8274-4881-80aa-944346a2730b.png)

**Comment by matteblair** [comment]
Thanks for posting your solution! Glad you were able to figure it out.
