### ISSUE TITLE
Check why android x86 doesn't build

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#251]
Its been long since we build android for x86 arch.

@karimnaaji tried to build x86 so that he can play with the intel gl debugger tool using genymotion, however x86 fails with the following:

```
CMake Error at toolchains/android.toolchain.cmake:639 (message):
  Specified ANDROID_ABI = "x86" is not supported by this cmake toolchain or
  your NDK/toolchain.

     Supported values are: "armeabi-v7a", "armeabi", "armeabi-v7a with NEON", "armeabi-v7a with VFPV3", "armeabi-v6 with VFP"
```

**Comment by blair1618** [comment]
It isn't super clear from the makefile, but you also need to change the line that specifies the toolchain name (https://github.com/tangrams/tangram-es/blob/master/Makefile#L68), in this case to `x86-clang3.5`

**Comment by karimnaaji** [comment]
Fixed by https://github.com/tangrams/tangram-es/commit/57a7eccc06eae5e3c0ace631ac8f776a7e2ddee9
