### ISSUE TITLE
Random crash on FontContext::lock() on app exit.

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#252]
Note: Noticed on deviceFonts-android and text-color branch. Try to repro this on master.

Both the feature branches are modifying any of the code path responsible to call FontContext::lock.

Also, if reproduced update with the stacktrace.

**Comment by hjanetzek** [comment]
On a first look it seems the order of destructor calls for TileManager and FontContext is implicitly given by the order they appear in tangram.cpp - So the global FontContext could be destroyed while TileManager is still waiting for it's workers to shut down.

 http://stackoverflow.com/questions/469597/destruction-order-of-static-objects-in-c

**Comment by tallytalwar** [comment]
I just removed m_ftContext in deviceFonts-android feature branch, because now its not needed there. I have not been able to recreate it, but its random :|.

**Comment by karimnaaji** [comment]
Any related crashes since the merge on this issue?

**Comment by tallytalwar** [comment]
Nothing I am aware of. We can mark it resolved for the time being.

**Comment by karimnaaji** [comment]
Ok, there is other issues but it doesn't seem to be related to this specific one.
