### ISSUE TITLE
Offline map data

### ISSUE THREAD

**Issue by andreynovikov** [tangrams/tangram-es#265]
May be this is a little bit early to ask, but still: I am authoring an open source Android map application and want to add true vector maps in it. But what I need is ability to work with offline map data. Are there any plans on this? I am eager to help with this but I am not familiar with C/C++.

**Comment by blair1618** [comment]
Hello @andreynovikov! This may be too late to help with your project, but offline map data is something we are interested in for tangram-es. The project isn't quite to the point where I'd recommend using it in a production app - right now we're working on one client application in particular to get our feature set somewhat complete and make sure our API is usable and flexible. 

Offline data isn't too far from reality - it's not at the top of our priority list right now but I would guess we'll get around to that within a couple months.

**Comment by nicklasaven** [comment]
Hello
This is also something I have been thinking about. 
When I have been working on the twkb-format, which now is released in PostGIS, I have thought about those things. I also think Tangram could be the right place to test.

What I would like to test is reading twkb-geometries from a sqlite database. The data base only knows it as blobs, but with a small decoder of should be a fast way of handling geometries. 

As a start I think it is easiest to simulate a tile grid by giving each geometry a tile id. Then the decoder gets the right rows from an ordinary id-index when tangram asks for a tile.

Then it is also possible to use sqlite r-tree as a spatial index. But that makes it harder to keep track of the internal cache.

I am about to look at this, but right now I am stuck at compiling tangram-es on a fresh ubuntu install :-(

**Comment by blair1618** [comment]
Interesting project!

One good thing to know about Tangram is that on Linux, the data retrieval
is all done by cURL, and cURL is perfectly happy to read from local file
URLs. If you're able to create a tile URL template that maps your data into
files (or maybe even file aliases) then it should be no problem for Tangram
to retrieve and assemble them into a map.

Another approach would be to write a small HTTP server that runs locally
and maps tile URL requests into the appropriate retrieval command from your
database.

Or of course you're free to hack on Tangram yourself ;)

If compiling continues to be a problem then I can help with that too, just
create a new github issue with the details of your problem and we'll go
from there. (You might first check that you have submodules up-to-date, I
often forget that)

**Comment by nicklasaven** [comment]
I have been doing some digging in the code to find out the path , how to do it.
Your hints is valuable. 

What I have is a C decoder as a start.
https://github.com/nicklasaven/twkbC
There is also a sqlite-branch that is reading from a local sqlite db. 
(All is ugly and just to make things run so far.)
 But I have found that the decoding will be very much simplier in Tangram. twkbC uses a temporary internal format to get to geoJSON. 

For Tangram only a very small part of that code is needed, just parsing it directly to std::vector.
It seemd like you have a simple and great approach for that so it seems very great.

My biggest problem is that I am not used to read C++. When writning PostGIS code it is just plain C. But I am learning, and i think an alternative to vector tiles can be a good thing. And twkb is very fast to get directly from PostGIS too.

**Comment by nvkelso** [comment]
+1

**Comment by andreynovikov** [comment]
Speaking about offline data the question is not only to save tiles in a file(s) but also to illuminate duplication of data, so tiles from different zooms handle the same data if possible. This not only minimizes the file size but also makes it possible to efficiently search for objects in the map.

**Comment by nicklasaven** [comment]
Yes, that is one thing with Vector tiles that I think can be better handled with twkb in sqlite. Then each geometry can be assigned a tile  id. The purpose of that tile id is just to make the internal cache know that is new and what is cached. Handling single geometries in that way will be too clumsy. But to reuse one geoemtry over several zoom-levels it just have to be addressed in some attribute what levels it shall be rendered on. Then that will be a part of the sqlite sql-query. When it is lower zoom levels it is probably also wise to simplify the geoemtry. 

That can be done in run time, or it can be done by assigning a value of "effective area" in the m-coordinate, if the data comes from PostGIS (see ST_SetEffectiveArea) Then the simplification can be done on parsing by just filtering on the effective area value.

**Comment by tallytalwar** [comment]
Closing in favor of this collective issue: https://github.com/tangrams/tangram-es/issues/931
