### ISSUE TITLE
No labels drawn on Galaxy Nexus

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#385]
Samsung Galaxy Nexus running 4.2.2 fails to draw any text labels or icons and produces no error messages. 
![2015-11-05 11 19 02](https://cloud.githubusercontent.com/assets/3371850/10974378/d4c46442-83af-11e5-9a3f-12533078a9bb.png)

**Comment by karimnaaji** [comment]
Now under #744 . Closing this.
