### ISSUE TITLE
Ensure disposal of GL resources is done on render thread

### ISSUE THREAD

**Issue by hjanetzek** [tangrams/tangram-es#389]
It is currently possible that the Scene may be disposed on a worker thread when a new scene is loaded while the previous is still held by a worker thread during processing. 
In my opinion the best solution would be to use a custom deleter for unique_ and shared_ptrs for a classes that hold GL resources, where the deleter enqueues them for disposal on the render thread.

This (or another solution) will be necessary for scene reloading on Android

**Comment by blair1618** [comment]
Good call. Custom deleters would work, but is that any less complicated than just customizing the destructors of those classes? Would we want to make all classes with GL resources inherit from an abstract "GLObject" class or something?

Having a global queue of tasks to be executed on the render thread isn't a bad idea in general; it could useful for more than just these resources.

**Comment by karimnaaji** [comment]
We can also remove gl calls from `~` and put it in a `destroy` method that main thread have to call explicitly.

**Comment by hjanetzek** [comment]
A queue to put tasks on the render thread is probably the way to go. Since the deletion of GL resources on other threads is rather a rare case I think it would make sense to use have a fine-grained per gl-resource handling. Tile and Scene are basically the root containers, so it may be sufficient to move their resources to a 'disposer' task when their destructor is called and the thread-id is not the render-thread-id.

**Comment by hjanetzek** [comment]
Done by moving Scenes to the task queue running on the main thread for disposal
