### ISSUE TITLE
Crash with bad TileID

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#394]
Steps to Reproduce:

* Launch `tangram`
* Rotate upside down
* zoom out
* try to move across tile dayline
* WIll notice a crash (and if you look closely, it will be in MVT datasource trying to parse an illegal tile ID).

In the case I tried, the illegal tileID was: `x: 3, y: 1, z: 1`.

Highly likely there is a bug in this code: https://github.com/tangrams/tangram-es/blob/master/core/src/view/view.cpp#L498-L504

**Comment by blair1618** [comment]
Can't reproduce. Are you running on a specific branch? A specific device?

**Comment by karimnaaji** [comment]
No we were running this on master branch on desktop os x.

**Comment by blair1618** [comment]
Me too, still can't reproduce. Seems to work fine on my phone too.

**Comment by tallytalwar** [comment]
I can get to this in some time, need some other things to take care of first.

I think @karimnaaji meant "No", we can :D. He only showed me this :D.

**Comment by karimnaaji** [comment]
Oh yeah sorry @blair1618 ! I meant no, it's not a specific branch :)

**Comment by blair1618** [comment]
I see. Can this be consistently reproduced on more than one machine? (My laptop with ubuntu doesn't produce this crash either)

**Comment by tallytalwar** [comment]
We have been able to reproduce this every single time.

@blair1618 check the fix here: https://github.com/tangrams/tangram-es/pull/395.

**Comment by blair1618** [comment]
The view has to be *tilted* to reproduce this, not upside-down. #395 does indeed correct the problem, will merge.

**Comment by tallytalwar** [comment]
We were able to reproduce it with upside down or rather any kind of rotation. But yes, its confusing how that fix in #395 fixes the rotation case also.

2 people here were able to repro it. :D.

Anyhow, #395 is a step in the right direction.
