### ISSUE TITLE
Compilation of dependency geojson-vt-cpp fails on Windows

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#401]
I am trying to get the demo of tangram-es running on an Android using my development environment on Windows. To compile on Windows (for Android), I use the following commandline, using CMake 3.4.0, MinGW with g++ 4.8.1, Android NDK r10e (64-bit):
```
    > cmake . -G"MinGW Makefiles" -DPLATFORM_TARGET=android -DMAKE_BUILD_TOOL=%ANDROID_HOME%/ndk-bundle/prebuilt/windows-x86_64/bin/make
    > cmake . --build
```

When the compiler reaches the compilation of geojson-vt-cpp, I get this error (and a couple of follow-ups):
```
In file included from tangram-es\external\geojson-vt-cpp\src\geojsonvt.cpp:1:0:
tangram-es/external/geojson-vt-cpp/include/mapbox/geojsonvt/geojsonvt.hpp:74:5: error: 'mutex' in namespace 'std' does not name a type
     std::mutex mtx;
     ^
```
It looks like g++ is not instructed to use -std=c++11 or higher.

Sadly, my knowledge of CMake is very superficial, so I was unable to find the problem. In external/CMakeLists.txt, I found this,
```
  if (GCC_VERSION VERSION_GREATER 5.1)
    add_definitions("-D_GLIBCXX_USE_CXX11_ABI=1")
  endif()
```
but changing 5.1 to 4.8 (g++ 4.8 and higher understands the option -std=c++11) does not change the error for me.

**Comment by blair1618** [comment]
Hi @westnordost thanks for the report. There isn't "official" Windows build support for tangram-es yet, but I bet we can get your Android build working :)

We typically run our android build through the `Makefile` in the root directory, which sets up parameters and then calls CMake to do the rest of the work. The Android toolchain depends on correct configuration from this file, so I would recommend changing [this line](https://github.com/tangrams/tangram-es/blob/master/Makefile#L81) to say `windows-x86_64` where it now says `darwin-x86_64` and then building with `make android`. The toolchain will then be configured to use Clang 3.6 from the NDK with `-std=c++1y`. 

Let me know if that helps, if not we can try to figure something out on a Windows machine here!

**Comment by westnordost** [comment]
Thank you for your reply, @blair1618.

Oh right, I wondered about the `android.toolchain.cmake` before as it was referenced nowhere in the `CMakeLists.txt` and not even in `android.cmake` where would have I expected it. I executed Cmake now in the same way as it is specified in the makefile:
```
tangram-es\build\android> cmake ../.. \
-DPLATFORM_TARGET=android \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_TOOLCHAIN_FILE=toolchains/android.toolchain.cmake \
-DMAKE_BUILD_TOOL=%ANDROID_NDK%/prebuilt/windows-x86_64/bin/make \
-DANDROID_ABI=armeabi-v7a -DANDROID_STL=c++_shared \
-DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-clang3.5 \
-DANDROID_NATIVE_API_LEVEL=android-15 \
-DLIBRARY_OUTPUT_PATH_ROOT=../../android/tangram
tangram-es\build\android> cmake ../.. --build
```
however, with the same result. I found out that the android toolchains file comes from [here](https://github.com/taka-no-me/android-cmake) but did not find `c++_shared` amongst the documented possible values for the `ANDROID_STL` parameter. I have no clue though if this is connected with the build problem though.
Also, the options `ANDROID_ABI, ANDROID_NATIVE_API_LEVEL, ANDROID_TOOLCHAIN_NAME` are documented as optional as the toolchain finds the default values itself. Is it imperative for the build process to succeed that these are predefined when calling make?

Also, wondering about how the build process would need to be adapted to "officially" support Windows, it strikes me as odd that CMake overwrites the Makefile every time I run it. Is this setup (make calls cmake, cmake overwrites makefile) standard?

**Comment by blair1618** [comment]
Sorry for neglecting this issue for so long! 

Out of curiosity, did you manage to get your build working on Windows? Supporting Windows as a development and deployment target is one of our eventual goals but we've had a lot of other things take priority with the project.

**Comment by westnordost** [comment]
No, unfortunately I haven't be able to.

**Comment by tallytalwar** [comment]
Work done here: https://github.com/tangrams/tangram-es/pull/836 resolved this.
