### ISSUE TITLE
Crash when updating client data source

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#404]
The crash results from a particular timing of multi-threaded activity and is therefore difficult to reproduce. 

The suspected cause is that the "store" of data for a geojsonvt data source is cleared while a worker thread is parsing data from that source, leading the worker to access freed memory.

**Comment by hjanetzek** [comment]
Yes, it looks like the assignment to m_store needs to be synchronized with m_store->getTile

**Comment by tallytalwar** [comment]
Yup. That's what I found yesterday evening.
