### ISSUE TITLE
Road labels should be centered on geom (like WebGL)

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-es#412]
Tangram ES should match the WebGL implementation and center road labels on the line geometry.

![img_7730-2](https://cloud.githubusercontent.com/assets/853051/11494801/c484ad8e-97ba-11e5-9c1b-1f2eb7121494.PNG)
![screenshot_2015-11-29-19-04-17](https://cloud.githubusercontent.com/assets/853051/11494802/c4a1cc48-97ba-11e5-9101-7ef927b4f7a5.png)

**Comment by karimnaaji** [comment]
After a quick look it seems that it's a bounding box issue (being bigger than they should be) and not a centering issue.
![screen shot 2015-12-01 at 11 40 50 am](https://cloud.githubusercontent.com/assets/7061573/11507096/70a8e6ec-9820-11e5-8a39-f6513230b028.png)
Fixing the bouding boxes should fix that.
