### ISSUE TITLE
"make ios" fails to compile due to attempting to codesign a universal binary

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#448]
Tangram's build system probably shouldn't be going through the hoops of running compilation for iOS devices; much of that needs to be configured inside of Xcode beforehand, and certificate chains need to be in place, etc. Is there a reason it is going through this step? 

Log output:

```
=== BUILD TARGET tangram OF PROJECT tangram WITH THE DEFAULT CONFIGURATION (Debug) ===

Check dependencies
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 9.2'

** BUILD FAILED **
```

**Comment by tallytalwar** [comment]
Agreed, `make ios` should not be doing compilation using `xcodebuild`. We however need to do it for `ios-sim` targets for travis purposes. Refer: https://github.com/tangrams/tangram-es/blob/master/Makefile#L239-L240 and https://github.com/tangrams/tangram-es/blob/master/travis/script_build.sh#L18-L22

With respect to ios target, mainly our workflow have been to build a xcode project by running `make cmake-ios`. Once done all code signing, and building happens inside xcode.

**Comment by msmollin** [comment]
Interesting. Looking at `cmake-ios` definition - That's pretty much what I would expect from an iOS dev perspective: Have it spit out a project file and do actual compilation and code signing within Xcode.

It may make sense to just have `make ios` command a proxy to `make cmake-ios`.

As for simulator builds, there's a few different ways we could configure travis to have it do that. Regardless though, simulator builds do not require code signature to install, so that's not an issue.

**Comment by karimnaaji** [comment]
In that case `make ios` is misleading and should be removed, but this is not the suggested way to build for device (https://github.com/tangrams/tangram-es#ios-devices). Is there any way we could codesign with xcodebuild?

**Comment by msmollin** [comment]
@karimnaaji hah I didn't read down that far. I was looking in the Makefile and saw the make ios phony and figured it would just work :D That's a "my bad" then.

As for code signing, no not easily. Code signing requires 3 basic things as of Xcode 7:
1) Project team set to a team that the developer is part of
2) App bundle identifier set to a matching provisioning profile (normally a reverse DNS style like com.something.somewhere)
3) An unexpired provisioning profile, which has the subsequent requirements of a valid certificate chain behind it.

All of this is normally done automatically by Xcode when you click the "Fix Issues" button in the build configuration. However at the command line, none of that is exposed.

**Comment by tallytalwar** [comment]
Ohh, that `fix issue` button is magic. We always thought we have to do something more in our ios cmake toolchain that we never see that `fix issue` button. But looks like its the norm :D.

**Comment by msmollin** [comment]
Fix issue is super magical - Xcode Build Server will handle it for you *i think* but that requires having a Mac Mini or something doing your builds.

I think we're kind of stuck in the cmake land. The recommended steps for doing code-signing when you're using something like travis is to have a separate, private github repository with all your private keys and credential information stored alongside a Cocoapod defintion, and have travis grab the pod and go through the steps of installing all the keychain stuff. 

https://ios.james.ooo/automated-ios-app-beta-distribution-30855d77931a#.6xuw80xwc is a decent walkthrough of what is needed to get code signing to work inside of travis (and other command line builds honestly), and that's assuming you already have the project configured to match the provisioning profile and build identifier is good.

**Comment by karimnaaji** [comment]
There seem to be some ways to codesign through xcodebuild. (Refer https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/xcodebuild.1.html `exportSigningIdentity`)
What about https://github.com/phonegap/ios-deploy?

**Comment by msmollin** [comment]
Yes, there is a command to codesign in `xcodebuild` (although normally I use `xcrun` for it). However if you look at the pre-reqs for phonegap, you need to have the certificate installed in order for it to work, and that's actually not the entire story either. There's provisioning profiles as well that need to be setup, and that profile needs to match the app you're trying to install.

That said, we could put a pre-req that you need to have a working wildcard provisioning profile so you don't have to exactly match the bundle identifier, but we're just layering pre-requisites here on something that we should be trying to make easy.

**Comment by msmollin** [comment]
Is there a particular use case for having cmake do the code signing process? It just feels like something that's trying to be forced when it's not even the recommended install path :)

**Comment by tallytalwar** [comment]
No I don't think so we need to do code signing from command line here. We should have `make ios` do what `make cmake-ios` is doing for us. But we do need to have `make ios-sim` do command line build for travis.

**Comment by msmollin** [comment]
That's fine, and works well enough currently.

**Comment by karimnaaji** [comment]
Closing this, if there is any other issues relative to iOS integration we should track them here https://github.com/tangrams/tangram-es/issues/741.
