### ISSUE TITLE
Text halo collisions for POI labels

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-es#460]
Noticed this in Eureka, California but present just about everywhere.

Looks like each character's text halo is being calculated sequentially instead of all drawing at once before the text fill pass.

`yXyXyX` where `X` is fill, `y` is halo and the halo draws first, then the fill. Instead it' usually `yyy` then `XXX`.

It's not as bad for **not bold** text, letter spacing of bold text seems off, which is compounding this?

![screenshot_2016-01-11-12-49-02](https://cloud.githubusercontent.com/assets/853051/12246287/9517bf78-b862-11e5-9192-12fb3f854594.png)
![screenshot_2016-01-11-12-49-17](https://cloud.githubusercontent.com/assets/853051/12246289/95393248-b862-11e5-9ce5-a35c51a20424.png)
![screenshot_2016-01-11-12-49-34](https://cloud.githubusercontent.com/assets/853051/12246288/95342a64-b862-11e5-9aab-f8ec35b3f9f0.png)

**Comment by blair1618** [comment]
Resolved: https://github.com/tangrams/tangram-es/pull/463
