### ISSUE TITLE
"make linux" fails to compile 

### ISSUE THREAD

**Issue by ggi2003** [tangrams/tangram-es#462]
ubuntu version: 15.10
gcc version: 5.2

err:
core/src/data/clientGeoJsonSource.cpp:77:98: error: no matching function for call to 'std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >::map(<brace-enclosed initializer list>)'

thanks

**Comment by tallytalwar** [comment]
Hey @ggi2003 

I tried it on ubuntu 15.10, with gcc 5.2, but was not able to reproduce the build failure.

Can you reply with the whole log, please?

Thanks

**Comment by ggi2003** [comment]
Thank you, I have found the problem, reason is that the code is not complete.

**Comment by tallytalwar** [comment]
Ohh! Was it related to not updating submodules or are we missing something on our side?

Thanks for taking care of this though.
