### ISSUE TITLE
Loading large scene files should be faster

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#486]
There are two major contributors to scene load time:

**YAML parsing**
In some instances this cost is unavoidable, such as when evaluating a modified stylesheet. In production use, however, the scene file will be the same nearly every time the app starts up so there's no need to parse it all over again: instead we can serialize the parsed structure as a protocol buffer or a flat buffer and then on the next launch, if the scene file timestamp is unchanged, deserialize from the buffer instead of the YAML file. 

**Scene initialization**
This part is should be more straightforward to optimize; somehow `SceneLoader::loadStyle` is taking _substantially more time_ than the entire YAML parsing process, multiple seconds for the eraser-map style on a phone. In particular, `SceneLoader::mixStyles` and `SceneLoader::getMixins` are far more time-consuming than they have any reason to be.

**Comment by hjanetzek** [comment]
Yea, the yaml processing time is amazing indeed :D  I was also looking into this yesterday as while profiling with heaptrack. I have no clue yet why mixStyles/mergeBlocks does such an amount of allocations.. ~80MB of small nodes for the eraser-map Styles.  But also 50MB for just loading.
I think we should rewrite the merging without using yaml-cpp nodes. I.e. transferring the nodes to
 appropriate structs for Style properties and apply the merging on that.  

![shot-2016-01-21_18-14-36](https://cloud.githubusercontent.com/assets/1747/12488314/40f04170-c06b-11e5-8d06-884c3f52c1a2.jpg)

**Comment by blair1618** [comment]
I'm going to see what I can do about the time and memory performance of `SceneLoader::loadStyle` first - should be some low-hanging fruit.

**Comment by blair1618** [comment]
https://github.com/tangrams/tangram-es/pull/555 addresses part of this issue. Parsing large YAML files can still take an unacceptably long time on some devices, so a caching scheme for the parsed structure could still make sense.
