### ISSUE TITLE
Reverse VBO order for line and outline, so that outline is drawn before line.

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#502]

**Comment by hjanetzek** [comment]
Why not increase the depth offset between line and outline? It thought we didn't go for painters algorithm

**Comment by hjanetzek** [comment]
@tallytalwar putting all outlines at first in the VBO is easy to do on top of the changes from style-builder branch ;)

**Comment by bcamper** [comment]
@hjanetzek for lines rendered with depth testing on (`opaque` blend mode), the order works as intended (outline is placed 0.5 below the order of the line fill), but this case is for other blend modes like `overlay` where painter's algorithm matters and the outline must be drawn first. It's better than current behavior but there are still artifacts with this approach, as really *all* outlines in the style should be consolidated underneath *all* line fills, and instead we still get outlines that can render over intersecting line fills.

**Comment by tallytalwar** [comment]
@hjanetzek depth offset will not matter, if `line` and `outline` are drawn with blending mode set to `overlay`. As an example we plan to add `outline` to the route line in eraser-map. And because of `overlay` blending and outline vertices being added after line vertices, outline would always be drawn above the line geometry.

With respect to putting tis change on top of style-builder branch, I agree, however, to introduce this change to eraser-map asap, I feel this can go before we get to style-builder branch. 
Is this a hard one to rebase with style-builder?

**Comment by hjanetzek** [comment]
@bcamper, @tallytalwar thanks. I didn't thought of the blend modes.

No problem to add this change when needed in eraser-map now. Just merging or rebasing with style-builder won't work,  so we need to re-apply this change on top of it anyway.
