### ISSUE TITLE
Style "animated" property should enable continuous rendering

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#538]
https://github.com/tangrams/tangram-es/blob/master/core/src/scene/sceneLoader.cpp#L435

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/styles.md#animated

**Comment by karimnaaji** [comment]
This is implemented already, https://github.com/tangrams/tangram-es/search?utf8=%E2%9C%93&q=animated, continuous rendering is enabled [here](https://github.com/tangrams/tangram-es/blob/c13bfd8fd8dd9a4fa3bbf3f528b2cdc46b2e1d50/core/src/tangram.cpp#L199L_L208), property is parsed [here](https://github.com/tangrams/tangram-es/blob/82ca718a0fa0bbbae7ec83e74c9d4baa27807134/core/src/scene/sceneLoader.cpp#L457_L466).
