### ISSUE TITLE
Camera "vanishing_point" property should set the vanishing point for perspective cameras

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#541]
It's in the docs, but I'm honestly kind of unsure what effect this is supposed to have on cameras with arbitrary orientation.

https://github.com/tangrams/tangram-es/blob/master/core/src/scene/sceneLoader.cpp#L969

https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/cameras.md#vanishing_point

**Comment by bcamper** [comment]
I'm not entirely sure either, but we could try applying the same matrix modifications as Tangram JS and see what happens :)  It simply modifies the Z column of the X and Y rows from a standard perspective matrix, e.g. causes the Z component to skew the XY:

https://github.com/tangrams/tangram/blob/master/src/camera.js#L171-L176

I'd be curious to see what it does and then we can decide whether it makes sense in ES-land or not.

**Comment by blair1618** [comment]
Well it doesn't do anything catastrophic, mostly it just makes me lean to one side. 

![screen shot 2016-03-29 at 11 43 05 am](https://cloud.githubusercontent.com/assets/3371850/14114019/73f9acf6-f5a3-11e5-84e0-473e06427819.png)
*Vanishing point of (1000, 0), tilted*
