### ISSUE TITLE
On-screen debug info should include tilt angle

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#547]

**Comment by nvkelso** [comment]
I have a build with this working, yeah! 

But the navigation UI completely obscure this info debug once I start a nav session :(

**Comment by blair1618** [comment]
Haha nooo I didn't test it with the routing UI! I guess I'll just rearrange
the lines so that it's visible. Feels kinda sloppy but this stuff has no
other purpose than convenience.

I have a build with this working, yeah!

But the navigation UI completely obscure this info debug once I start a nav
session :(

—
Reply to this email directly or view it on GitHub
<https://github.com/tangrams/tangram-es/issues/547#issuecomment-184942085>.

**Comment by nvkelso** [comment]
Should the nav UI be slightly transparent, anyhow?

**Comment by blair1618** [comment]
Hmm transparency might feel inconsistent with the rest of the app chrome,
but that sounds like a question for a UI designer :)

I rearranged the debug text in tangram-es so subsequent eraser-map builds
should have the tilt angle visible.
