### ISSUE TITLE
Chinese text fonsTextDrawable check failed

### ISSUE THREAD

**Issue by softlxf** [tangrams/tangram-es#553]
Chinese text cannot display in new code, console print [Can't draw text 大唐西市](https://github.com/tangrams/tangram-es/blob/master/core/src/text/fontContext.cpp#L154), [fonsTextDrawable](https://github.com/tangrams/fontstash-es/blob/d027b921e03910193105c68691a42ae44ca7bd0a/fontstash/fontstash.h#L1676)

Sample Chinese text: "\u751f\u6001\u5e7f\u573a"

**Comment by hjanetzek** [comment]
We work on a new text-rendering implementation in wip-alfons branch PR #506 . Feedback on this would be welcome, especially how CJK fonts work.

**Comment by bcamper** [comment]
@softlxf thanks, as @hjanetzek indicates, we are in the process of working on this, and we do intend to support as broad a range of Unicode as possible, falling back on system fonts where user-supplied fonts do not support the requested characters.

**Comment by karimnaaji** [comment]
Fixed by #561
