### ISSUE TITLE
Support vertical text layout

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-es#556]
User request for vertical text layout, example given of Chinese text laid out vertically for vertical lines (would they switch back to horizontal when the line rotated as well?).

See https://github.com/tangrams/tangram-es/pull/506#issuecomment-187082328:

> It would be nice to have a feature called 'Vertical text', which is a very common in CJK displays.
> This is used to show the label of vertical line.
> 
> It looks like ('Vertical text' in Chinese '竖排文字')
> |竖
> |排
> |文
> |字

**Comment by TKJohn** [comment]
@bcamper 
would they switch back to horizontal when the line rotated as well?

> Yes, it is.
This kind of vertical text is just showed at certain angle range(like ±30° around Vertical line of screen), while out of that range, text is showed the same way as English does.

**Comment by matteblair** [comment]
Closing this issue. I don't think this feature adds enough value to justify the added complexity in the text layout system.
