### ISSUE TITLE
Font rendering should support text shaping

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#564]
Arabic, Thai, and other scripts require "text shaping" for correct presentation. The new alfons text rendering backend supports shaping, with the help of harfbuzz. 

(This issue is to track the current work on integrating alfons)

**Comment by karimnaaji** [comment]
Current state of #561 that would hopefully help to understand the changes, also a sum-up of the discussions we had with @hjanetzek  :

Some of the main changes relative to the flow:
- TextStyle uploads the vertex buffer on each frame [`onBeginDrawFrame`](https://github.com/tangrams/tangram-es/blob/rb-alfons/core/src/style/textStyle.cpp#L91). There is one vertex buffer per glyph atlas per style; a wip has been done to use one vertex buffer per style using multi texturing, but as @hjanetzek mentionned, the number of texture atlases can quickly increase so this could be considered as a later optimization.
- Drawing happens in two passes (once per style per texture atlas) as previously done (to prevent text outlines artifact); for each of the texture atlases from [`onEndDrawFrame`](https://github.com/tangrams/tangram-es/blob/rb-alfons/core/src/style/textStyle.cpp#L56).
    - First pass is [here](https://github.com/tangrams/tangram-es/blob/rb-alfons/core/src/style/textStyle.cpp#L63), only if SDF is used.
    - Second pass is [here](https://github.com/tangrams/tangram-es/blob/rb-alfons/core/src/style/textStyle.cpp#L72)
- FontContext uploads the texture atlases for each of the text batches (which are built from the workers) [here](https://github.com/tangrams/tangram-es/blob/rb-alfons/core/src/text/fontContext.cpp#L140); this happens at the same time as the vertex buffer upload at [each frame](https://github.com/tangrams/tangram-es/blob/rb-alfons/core/src/style/textStyle.cpp#L87)
- Shaping and line wrapping starts from [here](https://github.com/tangrams/tangram-es/blob/rb-alfons/core/src/style/textStyleBuilder.cpp#L192_L197). Those triggers two callbacks, one for the [mesh](https://github.com/tangrams/tangram-es/blob/rb-alfons/core/src/style/textStyleBuilder.cpp#L347_L357), one for the [texture](https://github.com/tangrams/tangram-es/blob/rb-alfons/core/src/text/fontContext.cpp#L77_L109). I would personally prefer not dealing with callbacks and dequeue the mesh data, texture data from alfons once drawing is done for clarify (and decouple those tasks, through several API calls), but this could be further work.

An optimization @hjanetzek found out was to upload meshes/textures at the end of `Tangram::update()` which was a nice improvement to upload the buffer before the next frame starts, though not having any GL related call outside of `Tangram::render()` would help us manage more easily RenderState invalidation if Tangram was coupled with another rendering engine; see discussion [here](https://github.com/tangrams/tangram-es/commit/b3ee907a6b5a9e15e120cbc465eb8aa5b363dc88#commitcomment-16062963).

Fallback fonts get added as in https://github.com/tangrams/tangram-es/pull/515, and resolved internally within Alfons, @blair1618 we would like to have your thoughts on that if possible.

Fonts get rasterized at different fixed sizes (not to rasterize for every font size used, saving some atlas space), the step size is a predefined parameter, and then a texture scaling is applied to the SDF texture, https://github.com/tangrams/tangram-es/blob/rb-alfons/core/src/text/fontContext.cpp#L36_L38, @hjanetzek can explain more on that.

**Comment by karimnaaji** [comment]
@tallytalwar , you can check on this issue for the main description of how alfons implementation has been done. I put it here so it's easier to follow since several PRs have been done for this work.
