### ISSUE TITLE
png24 icon transparent edges dirty

### ISSUE THREAD

**Issue by nvkelso** [tangrams/tangram-es#570]
When I use png8 icon with transparency have nice edges, but going to png24 ([example](https://github.com/tangrams/eraser-map/blob/gh-pages/images/poi_icons_18%402x.png)) they get dirty edges. I need to use png24 because my assets have both exterior transparency and internal transparency, to support Eraser Map app design. 

Opening the source asset up in Photoshop shows no artifacts, so I suspect this is a Tangram issue. This happens with all UI assets, and one map icon (traffic signals visible at max zoom only, look near the SF Mapzen office), which is used during routing to provide contrast with the blue route line.

![screenshot_2016-02-24-11-25-38](https://cloud.githubusercontent.com/assets/853051/13305281/094737f6-db0f-11e5-9c43-2fc93e09181c.png)

**Comment by nvkelso** [comment]
(Green map pin over the light blue water edges have grey funk.)

**Comment by blair1618** [comment]
I see the "dirtiness" you're talking about - it seems to be showing at edges where a true-color PNG would have partial transparency. I would guess that there's something undesirable happening in the interpolation between opaque and transparent pixels in the texture, I'll need to look a look at our shaders and blending.

**Comment by hjanetzek** [comment]
The darker fringe could come from mixing in the black background pixels:
http://www.realtimerendering.com/blog/gpus-prefer-premultiplication/

**Comment by hjanetzek** [comment]
Was looking if stb_image had a routing for applying premultiplication during loading. Not quite it but related: If we move the image loading to platform we could avoid back and forth premultiplication of *iphone-formatted PNGs*
https://github.com/nothings/stb/blob/master/stb_image.h#L388

**Comment by blair1618** [comment]
Yeah, iOS at least has GLKit to make texture loading very convenient, including an option to premultiply alpha: https://developer.apple.com/library/ios/documentation/GLkit/Reference/GLKTextureLoader_ClassRef/index.html

**Comment by matteblair** [comment]
I believe this has been resolved for a while now. If texture transparency still isn't behaving as expected then please open this or a new issue.
