### ISSUE TITLE
Vertex lighting with world origin for isometric projection in tilted view is wrong

### ISSUE THREAD

**Issue by hjanetzek** [tangrams/tangram-es#578]
Flat areas change their lighting relative to tilt angle

**Comment by blair1618** [comment]
Confirmed - looks like a bug. 

Seems like the factor that causes this isn't actually the isometric projection - it's the "oblique axis" value. An isometric camera with `axis: [0, 0]` results in correct lighting.

**Comment by blair1618** [comment]
This chunk seems suspect to me now: https://github.com/tangrams/tangram-es/blob/master/core/src/view/view.cpp#L340-L343

I think that comment used to be true, but probably isn't in every case now.
