### ISSUE TITLE
Namespaces should use snake_case

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#583]
`namespace Tangram` should be `namespace tangram`, etc.

The rationale is to be able to easily distinguish between class names and namespace names.

**Comment by msmollin** [comment]
Not to start a style argument, but coming from learning C++ on Windows, that's not the standard there - https://msdn.microsoft.com/en-us/library/5cb46ksf.aspx

snake_case is only used for `inline` namespaces which came in C++11.

Not saying we need to follow Microsoft's example here or anything - it just may seem weird to a rather large set of C++ devs. Probably would be good to have a style document.

**Comment by matteblair** [comment]
I don't think this adds enough value to justify the code churn. Closing.
