### ISSUE TITLE
Depth test function should use GL_LESS

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#592]
Testing with `GL_LESS` instead of `GL_LEQUAL` should result in many fewer fragments being processed with no change in visual quality. 

The only cases where this could change visual results would be overlapping geometries set to the same `order`, but this case is effectively a user error and those geometries will have visual artifacts from z-fighting anyway.

**Comment by blair1618** [comment]
Hey @karimnaaji can you try this out? We'll want to survey the results with a few stylesheets to make sure there aren't any unforeseen consequences.

**Comment by karimnaaji** [comment]
Yep

**Comment by blair1618** [comment]
Resolved by #656
