### ISSUE TITLE
Repeated points in linestrings should not impact line tessellation

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#603]
Some vector tile data can contain linestrings with consecutive identical points. This causes a normal vector calculation to fail in the polyline tessellator and results in incorrect vertex locations:

<img width="912" alt="screen shot 2016-03-04 at 6 54 16 pm" src="https://cloud.githubusercontent.com/assets/3371850/13543686/8b92bb30-e23b-11e5-9edc-ac6861ef5e56.png">

This doesn't occur for MVT tiles due to a de-duplication step during geometry decoding.

**Comment by blair1618** [comment]
This seems to be a much less common occurrence in our latest set of tiles (yay), which means that we'll have to conjure up some test data to make sure we fix this (boo).

**Comment by nvkelso** [comment]
Slap a /osm/v0.7/ in the source on prod and you'll have the older data.

**Comment by blair1618** [comment]
Resolved by #640
