### ISSUE TITLE
Default stylesheet

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#610]
We should have a more consistent default stylesheet covering most if not all of the features we claim to cover in tangram-es. This would make visual testing more accurate and parsing error less surprising while testing on other stylesheet than the one we develop on.

**Comment by karimnaaji** [comment]
Closing this as remote scene file URL makes it much simpler to test remote stylesheets.

**Comment by bcamper** [comment]
I think it would still be good to bundle with a more complete scene file. I keep the Tangram JS one pretty up to date with features! :)

**Comment by tallytalwar** [comment]
ES style sheet matches more closely with JS one now. https://github.com/tangrams/tangram-es/pull/1208
