### ISSUE TITLE
Building tangram-es with Qt, for android.

### ISSUE THREAD

**Issue by Ian-H** [tangrams/tangram-es#616]
Hello all, and sorry in advance if this question is a bit naive.

I'm attempting to build an application for android and ios which will leverage tangram-es (hopefully)! I'm using Ubuntu for development, after trying and failing to build on Windows, and so far I have the linux and android builds working.

However, at this point I'm not really sure how to proceed - my current goal is just to do essentially what the demo .apk does, by linking the tangram-es libraries and incorporating tangram-es into my own application.

Since there's virtually no documentation for this project, that is proving difficult. I assume I need to link everything in the build/android/lib folder, but I'm not sure where the headers I should include live, if that's even applicable. Were I able to get a build going, would I be able to look at the tangram docs in order to work with tangram-es?

Any suggestions? Thank you so much!

**Comment by Ian-H** [comment]
OK, sorry, I think I know what my strategy will be. I'll be including tangram.h in tangram-es/core/src, linking everything in build/linux/lib, and then looking at the big-brother original tangram project for API reference. In theory, the linux build is just using c++ code, which Qt will compile for Android using the NDK, so I can pretend I'm developing for that build.

If I were to do development for linux, does the above sound about right? Anything I'm missing? Do I need to be including anything in the linux/src folder?

**Comment by hjanetzek** [comment]
Hi! I think it will be best to get started with developing a Qt widget on the desktop: copy the 'linux' folder to 'qt' and replace the the use use of GLFW with QGLView (or similar) for GL context and input handling. (Or work in the linux directory to not have to modify Makefile and adapt toolchains/linux.toolchain.cmake).
Note that the c++ api will likely change quite a bit in the coming months. We are currently focusing on the android sdk and its java api.

I haven't used Qt on Android or iOS - there are probably tutorials out there how to set it up and include external libraries.

**Comment by blair1618** [comment]
@Ian-H Did you have any luck? If there's nothing else you need help with, feel free to close this issue.

**Comment by foobar671** [comment]
Hey, sorry! I let this slide, but it's not fair keeping it an open issue. If I try and fail I'll re-open then. Thanks guys.

**Comment by Ian-H** [comment]
Closing for now.

**Comment by ortogonal** [comment]
I have a fairly working implementation of running Tangram together with Qt. Currently it's based on QtWidgets but my goal is to have it running under Qt/QML.

If there are any interests in it or suggestions on how to integrated with Qt just send a message!

**Comment by Ian-H** [comment]
Yeah, I'm definitely interested in that. Are you able to build for android?

**Comment by ortogonal** [comment]
Currently not, to run it on Android it first has to be ported to QtQuick so it can be used in QML. My first goal is to get it up and running on QtQuick and when that is done it should be a simple task to get it running on Android.

**Comment by ortogonal** [comment]
You can check it out here, https://github.com/ortogonal/tangram-es. Make sure to use the qt branch.

**Comment by Ian-H** [comment]
Alright, I'll check it out when I have time!

**Comment by ortogonal** [comment]
First demo of Tangram-ES running under QtQuick with QML. Still some work left before optimal implementation. I also had to make some minor changes in Tangram-ES to get this to work.

https://www.youtube.com/watch?v=1s7JAP7VjLo

**Comment by bcamper** [comment]
Very nice! We'd be interested in officially supporting Qt more directly in the future, and would love to collaborate or take a PR if it makes sense (but I'll let the rest of the ES dev team speak for that :)

**Comment by ortogonal** [comment]
It would be really nice to have some sort of collaboration around this. I (and we at Combitech) thinks this is a important project and would love to help get it running on Qt.

There are still things to fix before a pull-request makes any sense. Maybe we can find a better way to communicate the using issues to determine what is needed and if you have any goals with the port.

**Comment by paoletto** [comment]
Hi, is there still interest in Qt/QML - tangram/valhalla integration? :)
