### ISSUE TITLE
"scene.animated" should set whether the scene renders continuously

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#617]
https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/scene.md#animated

**Comment by blair1618** [comment]
@bcamper does this always override the `animated` property of styles? i.e. If `scene.animated` is `false` and a style has `animated: true`, does the scene animate?

**Comment by bcamper** [comment]
Yes, it's a scene-level override. If `scene.animated` is present, it's
value is used. If it's not, then the scene is animated if *one or more*
styles has `animated: true`.

**Comment by tallytalwar** [comment]
Fixed by #629
