### ISSUE TITLE
All documented built-in uniforms should be available in shaders

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#622]
The documentation for shaders list built-in uniforms that are meant to be available in GLSL blocks:

 - https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/Shaders-Overview.md#defines-and-uniforms
 - https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/shaders.md#built-in-uniforms

Currently, tangram-es diverges in behavior for some uniforms:

 - `u_model` has different semantics than in tangram-js, because reasons
 - `u_modelView` is not currently provided (but could be, with the same semantics as in js)

**Comment by bcamper** [comment]
Do you think we should revisit the list?

**Comment by blair1618** [comment]
Yeah we could probably replace `u_model`, `u_modelView`, and `u_normalMatrix` with functions that perform the related transforms, which we've started to do with `worldNormal()` and `worldPosition()`. That would give us more flexibility in implementation.

**Comment by bcamper** [comment]
I am in favor of limiting the # of uniforms (and other variables) we expose publicly. I have updated the docs to remove the matrices (along with other corrections/clarifications): https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/shaders.md#built-in-uniforms

**Comment by blair1618** [comment]
Sounds good!

The docs here say that `u_map_position` and `u_tile_origin` are relative to "Null Island", but I thought they were relative to the top-left corner of Mercator space?

**Comment by bcamper** [comment]
@blair1618 you are right, that's misleading in the docs. Will update.
