### ISSUE TITLE
How to achieve Caching/Offline mode in case of no internet?

### ISSUE THREAD

**Issue by nomizodiac** [tangrams/tangram-es#623]
In demo project, there is chunk of code to cache tiles

```
    try {
        File httpCache = new File(getExternalCacheDir().getAbsolutePath() + "/tile_cache");
        handler.setCache(httpCache, 30 * 1024 * 1024);
    } catch (Exception e) {
        e.printStackTrace();
    }
```

Can we save/cache some of the GesoJson response coming from server and then use later on in case of no internet connection like offline map? Is there any method to load the GeoJson directly instead of server response? It is not implemented in [beta build](http://android.mapzen.com/erasermap/).

**Comment by blair1618** [comment]
In theory, this is very achievable! 

Tangram-es is just using a thin layer on top of [OkHTTP](https://square.github.io/okhttp/) for network operations on Android. As you've noted, response caching is demonstrated in the example application, but cached tiles won't always be used when network isn't available. HTTP responses (from Mapzen's tile servers, for example), will often have information attached which says when they will be "stale". If a cache entry is older than its "stale" date, then OkHTTP will not use the cached response automatically. 

The good news is that OkHTTP has ways to customize this behavior! I haven't tried to do this myself yet, but it seems like others have had success with modifying the Request object: http://stackoverflow.com/questions/23429046/can-retrofit-with-okhttp-use-cache-data-when-offline

Let me know how this works out, if it works well we could add this as a convenience function to tangram-es.

**Comment by nomizodiac** [comment]
Thanks for the link i have added an overloaded constructor in HttpHandler for customizing okhttp request. 

```
public HttpHandler(final Context context) {
        okRequestBuilder = new Request.Builder();
        okClient = new OkHttpClient();
        okClient.interceptors().add(
                new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                        Request originalRequest = chain.request();
                        String cacheHeaderValue = isNetworkAvailable(context)
                                ? "public, max-age=2419200"
                                : "public, only-if-cached, max-stale=2419200" ;
                        Request request = originalRequest.newBuilder().build();
                        Response response = chain.proceed(request);
                        return response.newBuilder()
                                .removeHeader("Pragma")
                                .removeHeader("Cache-Control")
                                .header("Cache-Control", cacheHeaderValue)
                                .build();
                    }
                }
        );
        okClient.networkInterceptors().add(
                new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                        Request originalRequest = chain.request();
                        String cacheHeaderValue = isNetworkAvailable(context)
                                ? "public, max-age=2419200"
                                : "public, only-if-cached, max-stale=2419200" ;
                        Request request = originalRequest.newBuilder().build();
                        Response response = chain.proceed(request);
                        return response.newBuilder()
                                .removeHeader("Pragma")
                                .removeHeader("Cache-Control")
                                .header("Cache-Control", cacheHeaderValue)
                                .build();
                    }
                }
        );
    } 
```
It is working fine and caching/loading tiles when offline. But please guide me if there is more efficient or optimal way. Update if you add any method for offline caching later on. Thanks

**Comment by blair1618** [comment]
Nice work! I'll check this code and update this thread when we start work on this as a built-in feature. 

Feel free to close this issue if your original problem has been resolved.

**Comment by nomizodiac** [comment]
@blair1618 Hi, i am getting an issue while loading tiles from cache using above code. I have added Interceptors to change response headers. Now it cache all tiles from server successfully i can see them in external storage. But when i go offline (no internet connection) it loads first 2-3 tiles and then stop. Now if i zoom out or pan map it wont load any tiles from cache even though tiles are saved in local storage. After sometimes another tile will appear. Is there any issue in max-age or max stale values or tangram handles it differently at backend? Can you please specify the correct way to achieve offline caching, i also thought about setting response headers at server end but can you specify what Cache-Controls header values should be set at server end to achieve caching right? Thanks

**Comment by nomizodiac** [comment]
@blair1618 i have also tested new Eraser Map 0.12.0. First i cached some tiles and then turn off wifi/internet. Now it only load one tile and then stop. If i zoom out or pan then it occasionally load other random tile. Here is screenshot

![screenshot_20160822-173450](https://cloud.githubusercontent.com/assets/3611309/17854975/7287e7fc-688f-11e6-8f93-e4ae6af1c2f6.png)

**Comment by blair1618** [comment]
Ah, sorry to hear that this stopped working. Did this happen after upgrading to a new release of tangram-es? Do you know the latest version which has not had this problem?

**Comment by nomizodiac** [comment]
Thanks for reply. I am not sure from which release it stopped working, i think it was not working perfectly even in previous releases. I googled a little on okhttp caching mechanism and tried to set response headers at server end. As it is suggested at many places not to use Interceptors so now i am doing only two things to achieve caching. First I have following response header at server end.

> Cache-Control: public, max-age=2419200

And second i have enabled cache in code as follow:

```
try {
        File httpCache = new File(getExternalCacheDir().getAbsolutePath() + "/tile_cache");
        handler.setCache(httpCache, 30 * 1024 * 1024);
    } catch (Exception e) {
        e.printStackTrace();
    }
```
Now when i run app with internet enabled it cache all tiles in storage at specified path perfectly. But i go offline it do not load tiles from cache. If i continue to pan and zoom map it randomly load some tiles but not as expected. Do you it is the right way or is there any issue with usage of okhttp in tangram? Thanks

**Comment by blair1618** [comment]
Ok. Are you working with the latest release of tangram-es for Android?

I'm not an expert on HTTP, but it sounds to me like your approach should work. tangram-es caches some tiles in memory, separately from the file system cache used by OkHTTP, so that may explain why some tiles are able to reload. 

If you're working with tangram-es from source, you could try upgrading OkHTTP to the newest available version and seeing if the behavior changes. OkHTTP in tangram-es is behind the latest and there may be some syntax changes needed to upgrade.

**Comment by nomizodiac** [comment]
I am using tangram version 0.4 and i have added build dependency. I wont be able to change okhttp version

**Comment by nomizodiac** [comment]
I have updated okhttp version to okhttp3 3.4.1 and also changed its updated methods in MapController and HttpHandler class. But i am still getting the same issue. It stores/cache all the tiles in local storage perfectly. But when i restart app with Wifi disabled, it do not load tiles data from cache/local storage. It loads 2-3 initial tiles but then i start getting error in on failure callback 
```
@Override
            public void onFailure(Call call, IOException e) {
                nativeOnUrlFailure(callbackPtr);
                Log.i("MapController", "Called: onFailure " + e.toString());
            }
```
Which says failed to connect to url. And  if i zoom in or out too quickly, it do not even send request to get tiles from cache and following lines wont get called in that case 

```
Request request = okRequestBuilder.tag(url).url(url).build();
        okClient.newCall(request).enqueue(cb);
```

 Any suggestion?

**Comment by karimnaaji** [comment]
Some more advanced work on offline tile caching has been done here by @hallahan https://github.com/tangrams/tangram-es/pull/982.

**Comment by karimnaaji** [comment]
Closing this issue as main work as been merged in master branch in https://github.com/tangrams/tangram-es/pull/1015.

**Comment by matteblair** [comment]
HTTP caching with custom cache policies is demonstrated here: https://github.com/tangrams/tangram-es/blob/master/platforms/android/demo/src/main/java/com/mapzen/tangram/android/MainActivity.java#L174-L190

Offline tile data can be pre-loaded as an MBTiles database and loaded through the scene file as a data source, see the docs: https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/sources.md#mbtiles
