### ISSUE TITLE
Move android toolchain to use r11

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#625]
Android ndk got upgraded to r11. Tangram-es is currently using r10e.

Update to use r11.
http://developer.android.com/ndk/downloads/index.html

**Comment by tallytalwar** [comment]
So they changed the entire directory structure in r11(a/b/c), plus moved `clang` toolchains from `{NDK_ROOT}/toolchains` to `{NDK_ROOT}/build/core/toolchains`. They also got rid of old clang toolchains. Apparently, all of these changes mean we can not directly (or with minimal change/work) use our present `android.toolchain.cmake`. A lot of work will be required to bring `android.toolchain.cmake` to work with ndk-r11* releases.

On the other hand, we should definitely find more robust way of bypassing this `android.toolchain.cmake`.

I am going to park this issue for the time being, or until we have a pressing reason to move to a newer ndk release.

Refer: https://github.com/taka-no-me/android-cmake/issues/81, (this also have some hacky way of getting the toolchain to work, but I do not think we should adopt this approach).

**Comment by blair1618** [comment]
Fascinating! Makes sense to put this on standby. 

Part of me would like to use the `ndk-build` script that comes with the NDK, then we could be sure that future versions of the NDK would continue to work. The trick would just be figuring out how to interface with the weird makefile-like inputs to `ndk-build`. 

Or we could move everything to [Bazel](http://bazel.io/)! ;)

**Comment by karimnaaji** [comment]
Doing some research over that, it seems that this project seems to have an updated version using r11 in their cmake toolchain https://github.com/urho3d/Urho3D. It would be worth trying this before investing more work towards moving to a different build system for android.

**Comment by blair1618** [comment]
Android Studio 2.2 supports CMake integration out of the box, we should wait until it's released and use that for our build toolchain instead: http://tools.android.com/recent/androidstudio22preview3available

**Comment by tallytalwar** [comment]
Our android build system is through new android studio and using gradle native builds, which will make sure we are upto date with NDK versions.
