### ISSUE TITLE
CMake error 'windows not in supported targets'

### ISSUE THREAD

**Issue by nomizodiac** [tangrams/tangram-es#632]
I am trying to build the tangram-es project at windows platform. I am using Cmake 3.5.0 and also did modified the NDK build tools path in Makefile to use windows-x86_64 instead of darwin-x86_64 as it was mentioned [here](https://github.com/tangrams/tangram-es/issues/608) to build it on windows. Now when i build project it throw me this error.
```
CMake Error at CMakeLists.txt:40 (message):
  windows not in supported targets: darwin;ios;android;raspberrypi;linux
```
What am i doing wrong here? Please guide me if i am not following the right steps or some tools that i am missing. Following are my platform details
Windows 7 64bit, Visual Studio 12 2013, CMake 3.5.0
I provide the tangram-es folder root path to CMake and Visual Studio 12 2013 to build. Thanks

**Comment by hjanetzek** [comment]
Hi! To build the android library call 'make android'. Using ```make``` is not strictly necessary though, it's more for convenience especially for the android build. See ```Makefile```  ANDROID_CMAKE_PARAMS for the options to pass to cmake.

**Comment by nomizodiac** [comment]
Thanks for quick response! But haven't got your point right. From where to call 'make android' as i am using CMake 3.5.0 gui version and i can only specify the Source code path, generated build libraries path and also some configurations regarding compiler etc. Apologies for being so naive

**Comment by karimnaaji** [comment]
No apologies :) There has been some related discussion here https://github.com/tangrams/tangram-es/issues/401. It has been some time I haven't use the CMake GUI but are be able to see [those parameters](https://github.com/tangrams/tangram-es/blob/master/Makefile#L107_L118) after setting the source path?
