### ISSUE TITLE
Textshaping performance

### ISSUE THREAD

**Issue by hjanetzek** [tangrams/tangram-es#633]
Collecting ideas to improve shaping speed. 
- hb 'fallback shaping' for simple scripts?
- cache shaping per word
- enable mmap'd freetype fonts (tested: very little impact on desktop)

https://www.chromium.org/blink/layout-team/eliminating-simple-text

Other options:
- Estimate minimal label size for line-labels and only run the shaping when there is a chance that the label fits on a line-segment

**Comment by karimnaaji** [comment]
Harfbuzz can now be built with `HB_NDEBUG` to disable debug code overhead, something to consider when addressing those.

**Comment by matteblair** [comment]
Closing this issue - it's pretty old now and I'm not sure how relevant these problems or solutions still are.
