### ISSUE TITLE
clientGeoJsonSource

### ISSUE THREAD

**Issue by haidershahzad** [tangrams/tangram-es#635]
Hi, Anybody will please guide me, how to fix the error below.

The following build commands failed:
CompileC build/xcode/core/tangram.build/Debug/core.build/Objects-normal/x86_64/clientGeoJsonSource.o core/src/data/clientGeoJsonSource.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
make: *** [xcode] Error 65
I have attach the full terminal response.

cmake version 3.4.0
xcode version 7.2.1

![screen shot 2016-03-21 at 5 48 47 pm](https://cloud.githubusercontent.com/assets/119604/13919089/3690c294-ef8d-11e5-8798-19df374d0a2d.png)

**Comment by karimnaaji** [comment]
Hi @haidershahzad,
Can you provide the exact command you executed to compile the project?
Thanks

**Comment by haidershahzad** [comment]
Make xcode from the documentation

On Monday, March 21, 2016, Karim Naaji <notifications@github.com> wrote:

> Hi @haidershahzad <https://github.com/haidershahzad>,
> Can you provide the exact command you executed to compile the project?
> Thanks
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/tangrams/tangram-es/issues/635#issuecomment-199323615>
>


-- 

*Developer*

**Comment by karimnaaji** [comment]
It's always hard to tell what cmake put into its own cache, especially if you switch branches.
I would first try this:
```
git submodule update --init --recursive
make clean-xcode
make xcode
```

If you're still having issues you can try the following set of commands (to set up a clean environment):

```
git clone git@github.com:tangrams/tangram-es.git
cd tangram-es
git submodule update --init --recursive
make xcode
```

**Comment by haidershahzad** [comment]
Thanks its came to work now.
