### ISSUE TITLE
IOS font not appearing

### ISSUE THREAD

**Issue by haidershahzad** [tangrams/tangram-es#643]
Hello, Im trying to display vector data from url  which is loading properly like buildings and poi but the labels are not appearing below i have pasted the console log please guide what is the issue, im using xcode 7.2.1. and cmake version 3.4.0

TANGRAM tileManager.cpp:67: add source local
TANGRAM tangram.cpp:99: finish initialize
TANGRAM tangram.cpp:577: setup GL
TANGRAM hardware.cpp:56: Driver supports map buffer: 1
TANGRAM hardware.cpp:57: Driver supports vaos: 1
TANGRAM hardware.cpp:71: Hardware max texture size 4096
TANGRAM hardware.cpp:72: Hardware max combined texture units 8
TANGRAM tangram.cpp:132: resize: 1242 x 2208
TANGRAM tileWorker.cpp:70: Passed new TileBuilder to TileWorker
Failed to read file at path: /var/mobile/Containers/Bundle/Application/40249C13-C398-4624-9D27-D6A170598A5E/tangram.app/fonts/default-400normal.ttf
Failed to read file at path: /var/mobile/Containers/Bundle/Application/40249C13-C398-4624-9D27-D6A170598A5E/tangram.app/fonts/default-400normal.ttf
Failed to read file at path: 
ERROR fontContext.cpp:263: Could not load font file default_400_normal
TANGRAM tileWorker.cpp:70: Passed new TileBuilder to TileWorker
Missing font: error: 1 NotoSans-Regular.ttf
Missing font: error: 1 NotoNaskh-Regular.ttf
Missing font: error: 1 NotoSansHebrew-Regular.ttf
Missing font: error: 1 DroidSansJapanese.ttf
Missing font: error: 1 DroidSansFallback.ttf
Missing font: error: 1 NotoSans-Regular.ttf
Missing font: error: 1 NotoNaskh-Regular.ttf
Missing font: error: 1 NotoSansHebrew-Regular.ttf

**Comment by tallytalwar** [comment]
Hi @haidershahzad 

Yes, I am able to reproduce this. We will look into this.

Thanks

**Comment by haidershahzad** [comment]
What will be the eta of documention ios.

**Comment by tallytalwar** [comment]
Hey Haider.

Currently we have not spent much time exposing a lot of functionality for iOS SDK. Our focus has been for Android, but soon we will be shifting gears and working on iOS SDK and documentation.

Tangram-es is a work in progress project, and we appreciate your desire of using it.
