### ISSUE TITLE
MapData

### ISSUE THREAD

**Issue by haidershahzad** [tangrams/tangram-es#646]
Hello guys, I need to know the MapData class alternate in ios or please guide me on how can i draw polygon and polyline on map.

**Comment by blair1618** [comment]
Hey @haidershahzad, our core team is focusing on an Android SDK right now, a matching iOS SDK will come later in the year. For now, here's what I recommend:

The `MapData` Java class on Android is mostly a wrapper around the `ClientGeoJsonSource` C++ class (https://github.com/tangrams/tangram-es/blob/master/core/src/data/clientGeoJsonSource.h). On iOS, you can directly use this C++ class with Objective-C code if you compile it as Objective-C++ (using a .mm extension). With this class you can add point, line, polygon, and raw GeoJSON data to your map. The demo application for OS X shows an example of using the `ClientGeoJsonSource` with the Tangram-ES API (https://github.com/tangrams/tangram-es/blob/master/osx/src/main.cpp). 

Let me know if this helps!

**Comment by haidershahzad** [comment]
Hi @blair1618 thank you for you response, i have check the osx example and prepare a sample code to run on ios, im trying to draw line between to coordinates buts its get crashed on addline method from the class ClientGeoJsonSource. Im attching the images of the crash and console description.

And this is how i declared the datasource like in the osx application.
using namespace Tangram;
std::shared_ptr<ClientGeoJsonSource> data_source;

![1](https://cloud.githubusercontent.com/assets/119604/14104389/67707a76-f5be-11e5-928a-5da2d438bbaf.png)
![2](https://cloud.githubusercontent.com/assets/119604/14104390/68f841c6-f5be-11e5-81f1-39d3d3659211.png)
![3](https://cloud.githubusercontent.com/assets/119604/14104392/6a50caac-f5be-11e5-86ff-6766999da5f1.png)
![description](https://cloud.githubusercontent.com/assets/119604/14104394/6c81cb3c-f5be-11e5-9f23-c5f70adefd65.png)

Thank you.

**Comment by blair1618** [comment]
@haidershahzad From your last screenshot, it looks like your `data_source` variable is holding a null pointer. A `shared_ptr` object must be initialized with an object to point to before it can be used (this is done here in the OS X demo: https://github.com/tangrams/tangram-es/blob/master/osx/src/main.cpp#L287).

**Comment by haidershahzad** [comment]
Thanks alot guys, keep doing the great work.
HAPPY CODING
