### ISSUE TITLE
Client applications should be able to modify the scene configuration through an API

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#650]
Something along the lines of
```cpp
Tangram::setSceneElement("cameras.main.type", "isometric");
Tangram::applySceneUpdates();
```

**Comment by bcamper** [comment]
I have a preference for using `.` dot notation for nested structures, because it better matches JS syntax, and that of other languages (including C++ :). Using `:` is fin with me for internal structures (and for the recently discussed case of flattening global properties, it would actually be more confusing in JS to have the property name include a dot, could lead to some easy mistakes on the console).

**Comment by blair1618** [comment]
I see! I wrote it out with colons to mimic the YAML itself. Dot notation works too, provided that node names do not include a `.` (YAML does allow that in general).

**Comment by bcamper** [comment]
YAML supports `:` in keys if you try hard enough...

`'a:b': c`

**Comment by blair1618** [comment]
This is also true, the specification is most generous :)

I had hoped to keep delimiters consistent throughout, but given that the global properties have introduced dot notation for nested structures, I suppose we had better stay consistent with that. I'll update the description.

**Comment by bcamper** [comment]
This should be added to Android SDK milestone, yeah?

**Comment by blair1618** [comment]
Yes, added!

**Comment by karimnaaji** [comment]
Should we also support more complex yaml tree updates like:

```c++
Tangram::setSceneComponent("textures.pois.sprites", "plane: [0, 0, 32, 32]\n museum:[0, 32, 32, 32]");
Tangram::applySceneUpdates();                                                       
```

cc @bcamper

**Comment by blair1618** [comment]
I don't think appending to current mappings is within the scope we intended for this feature. I would expect, however, that I could update the entire sprites mapping with:
```c++
Tangram::setSceneComponent("textures.pois.sprites", "{ plane: [0, 0, 32, 32], museum:[0, 32, 32, 32] }");
Tangram::applySceneUpdates();    
```

**Comment by tallytalwar** [comment]
Yup, exactly what we discussed right now @karimnaaji

**Comment by karimnaaji** [comment]
Yeah I wasn't speaking of appending, simple update replacement.
