### ISSUE TITLE
Android SDK should provide a mechanism to manipulate individual features as 'Markers'

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#653]
The `MapData` class provides a means to manage collections of features, with methods to add features one by one and to remove the entire collection at once. This does not provide the level of granularity that's desirable for common mapping applications. Manipulating individual features/annotations has become a de facto standard among popular mapping libraries; it will be expected of tangram-es as well. 

Hypothetical behavior:

``` java
// Creates a new point marker for the data source "touch" with a feature property;
// these methods would apply similarly to polyline and polygon features.
Marker m = map.addMarker("touch")
        .set("property", "value")
        .setPosition(aLngLat);
// Update the position of the marker.
m.setPosition(bLngLat);
// Update the rotation of the marker.
m.setRotation(degrees);
// Set the visibility of the marker.
m.setVisible(false);
// Remove the marker from the map.
m.remove();
```

Additionally we should enable touch/click callbacks for all markers (we are currently only able to provide callbacks for label features). Syntax for this is undecided.

**Comment by nomizodiac** [comment]
Can you please notify when implementing this behavior. Because many of issues are related to this like [issue](https://github.com/tangrams/tangram-es/issues/691). Desperately need this feature, waiting for it to release.  Also [this issue](https://github.com/tangrams/tangram-es/issues/698) something like `m.rotate(float rotation)`. Thanks

**Comment by yuridiniz** [comment]
You could also add something like `m.setFlat(boolean  #value)`?

I described the problem in this issue: #799

**Comment by blair1618** [comment]
Yes, we'll have a way to specify whether markers are oriented in *world space* or in *screen space*, but the syntax for that hasn't been decided yet.

**Comment by matteblair** [comment]
This exists now! https://github.com/tangrams/tangram-es/blob/master/platforms/android/tangram/src/main/java/com/mapzen/tangram/Marker.java
