### ISSUE TITLE
Investigate camera interface compatibility with Google Maps

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#654]
We may be able to make our Android interface for update camera parameters identical (or nearly identical) to that in the Google Maps API: https://developers.google.com/maps/documentation/android-api/views

There are some advantages to moving our interface in this direction:
- Building and then executing an update object eliminates some timing problems we have previously encountered when updates to different parameters were applied sequentially.
- An update object provides a convenient way to create more abstract transitions like moving to view a specific set of LngLat bounds. 
- Sharing the interface with a widely-adopted library could make our API more familiar and easier to learn.

There are a number of superficial differences that would mostly just involve syntax changes, but some differences are more substantial:
- The `GoogleMap.animateCamera` method accepts callbacks to execute when the animation is completed or cancelled. This would require additional logic in the core tangram library. 
- Tangram ES provides several interpolation types for camera animation, whereas `GoogleMap` has no such options. It would be unfortunate to artificially reduce the options available to our users.

**Comment by bcamper** [comment]
+1 to event callbacks, we're going to want those anyway

-1 to losing interpolation (or other) options, let's try to find a way to provide a (near-)compatible API with a superset of features

**Comment by blair1618** [comment]
cc @ecgreb @sarahlensing 

I have a partial implementation of the camera update interface used in Google Maps here: https://github.com/tangrams/tangram-es/commit/6cf24c25612a09c2a78ffd4752ff7451fdb1d307

There's a good amount of work left just to cover the options in [CameraUpdateFactory](https://developers.google.com/android/reference/com/google/android/gms/maps/CameraUpdateFactory). I'd estimate another 2 or 3 days to get this all working well. This interface would certainly make some tasks simpler (even if it's using a bafflingly unnecessary factory pattern) but I don't want to pull the floor out from under the development of the Mapzen SDK with the schedule we're on right now. This also won't be an exact copy of the gmaps interface, so it might be best to use the methods we have right now for the upcoming release. Thoughts?

**Comment by ecgreb** [comment]
We're planning to close the SDK to new changes tomorrow to give us time to test the preview version. What is your timeline for the next Tangram release?

That said, an update to the camera API could be included or not. On one hand I don't think its going to be a high demand feature for the first version. On the other hand the SDK does not have any camera-specific functionality yet so the ripple effect from these changes would likely be small (if any).

**Comment by matteblair** [comment]
Our Camera interface has evolved in this direction substantially - I think this issue has served its purpose!
