### ISSUE TITLE
Investigate gesture interface compatibility with Google Maps

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#655]
We may be able to make our gesture handling interface more similar to that of the Google Maps API: https://developers.google.com/maps/documentation/android-api/events

This may make our interface more familiar or easier to learn, but compared to our current gesture interface it would provide less detailed information and options to the client application. For example, Google Maps allows you to detect when a user taps on the map with the simple [OnMapClickListener](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnMapClickListener), whereas Tangram ES has [responders](https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/TouchInput.java) for a tap, a confirmed single tap, and a double tap.

**Comment by bcamper** [comment]
Would it be possible for us to somehow have a superset so we don't lose functionality?

**Comment by matteblair** [comment]
I believe this is no longer an issue for our Android gesture interface. Closing.
