### ISSUE TITLE
StyleParamKey::offset and StyleParamKey::size do not have JSFunction handling

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#665]
Currently `duk_is_array` check is only done for `extrude`, `color`, `outline_color`, `font_fill` and `font_stroke_color` style param keys.

Refer:
https://github.com/tangrams/tangram-es/blob/master/core/src/scene/styleContext.cpp#L236-L296

**Comment by blair1618** [comment]
As documented, these functions do not support JS function values: 
 - https://mapzen.com/documentation/tangram/draw/#size
 - https://mapzen.com/documentation/tangram/draw/#offset
