### ISSUE TITLE
live traffic ios

### ISSUE THREAD

**Issue by MajidBashir** [tangrams/tangram-es#669]
hi everyone
I need to implement live taffic  in iOS application. like this.. or any other

https://tangrams.github.io/carousel/?tron#15/40.7076/-74.0094
how can i perform this functionality ?
secondly , what type do i add to assign 
`    void addPoly(const Properties& _tags, const std::vector<Coordinates>& _poly);
`
I have `MKPolygon` type data which I am not able to assign it..
thanks

**Comment by tallytalwar** [comment]
Hi

1. "Live traffic" - we do not have any means of doing live traffic. The example you quoted are some shader tricks, and is actually not "live traffic". Refer the style sheet having all the shader magic which gives that perspective: https://github.com/tangrams/tangram-sandbox/blob/gh-pages/styles/tron.yaml

2. We do not provide any means to directly use MapKip Polygons (MKPolygon). You will have to convert these manually to vector of LonLat(s) and pass it to `addPoly`.

Hope this helps.

**Comment by MajidBashir** [comment]
Thanks for such  a rapid response...
how can i create such a pointer or  data_source type of that vector type.
I am not able to assign that vector type variable or pointer..

**Comment by MajidBashir** [comment]
Hi again. 
followed your instructions, and have parsed data according to its data type of vector<Coordinates>
from positions of lines and boxes,
I am able to zoom to specific point, but nothing is visible here...


my YAML is here
![screen shot 2016-04-11 at 4 06 27 pm](https://cloud.githubusercontent.com/assets/8158049/14425278/6942e870-ffff-11e5-84b1-56f6f7e48722.png)

i have tried it with polygon as well
but nothing is working..

**Comment by hjanetzek** [comment]
```filter: { type: line }``` requires that Properties contains type=line. It may be the old tangram-js way to match geometry types, now {$geometry : line} should be used. 

Have you tried without the filter?

**Comment by MajidBashir** [comment]
I did give it try. but nothing is working..

**Comment by blair1618** [comment]
The discussion here seems to be a different issue than the initial topic. If you're still having difficulty with using the scene file, please open a new issue with a description of the new problem. Thanks!
