### ISSUE TITLE
Deprecate setCameraType for dynamic scene update

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#677]
Set camera type should be deprecated and scene update should be used instead (https://github.com/tangrams/tangram-es/issues/650)

- [MapController API](https://github.com/tangrams/tangram-es/blob/717c5093a2a8d4c615e46ca0af2f1ce5bce5e99b/android/tangram/src/com/mapzen/tangram/MapController.java#L289)
- [Tangram API](https://github.com/tangrams/tangram-es/blob/master/core/src/tangram.h#L81_L82)

**Comment by tallytalwar** [comment]
Closed by #679

**Comment by tallytalwar** [comment]
EraserMap code will also have to make this change.
cc. @ecgreb @sarahlensing
