### ISSUE TITLE
Tangram should provide a mechanism to notify clients when a view is "complete"

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#683]
The motivation for this is mostly to support capturing screenshots of the current map view after the view is finished loading and rendering. The interface could be something very simple, like:

C++
```c++
void setViewCompleteCallback(std::function<void()> _onViewComplete);
```

Java
```java
public void setOnViewCompleteListener(OnViewCompleteListener listener);
```
The callback should be executed after all visible tiles have been loaded and made renderable. Some potential edge cases and how I feel they should be handled:

 - If there are any eases in progress, the view should not be considered "complete".
 - If labels collisions or transitions are still in progress, the view should not be considered "complete". 
 - Scene animation should be disregarded when determining whether the view is "complete".

**Comment by hjanetzek** [comment]
I came across a problem with using this callback to take a screenshot: one does not know whether the view is already complete when doing the screenshot render-request. So one would need to call onViewComplete after each render() with a complete view. I would suggest to have a

```OnRenderDoneCallback(bool complete, bool animating)```

with 'complete' meaning all tiles loaded and no label animations

**Comment by blair1618** [comment]
Resolved by https://github.com/tangrams/tangram-es/commit/90d259cee29c436540277ec9177f71221fbb1629. `Tangram::update(dt)` now returns a boolean representing whether the view is "complete".
