### ISSUE TITLE
Android properties.clear() method not working

### ISSUE THREAD

**Issue by nomizodiac** [tangrams/tangram-es#691]
I have added a layer in yaml file and then make a mapdata object
```
mapData = new MapData("routelayer");
Tangram.addDataSource(mapData);
```
Then i add multiple segments/lines/properties like following:

```
Properties properties = new Properties();
properties.set("type", "line");
segmentsPropertiesList.add(properties);
mapData.addLine(properties, lngLats);
mMapView.invalidate();
```
Now route/line is showing on map properly. But i want to change attributes of some of the properties  or segment that i have added. For that i also add properties in seperate ArrayList 'segmentsPropertiesList' so that i can access them later. Now when i get it and clear it does not make any change.

```
for (Properties properties : segmentsPropertiesList)
       properties.clear();
```
It simply stays on the map. Also i have tried to change some other atribute like color of the line
`       properties.set("color", "#ff0987")
`
It also does not change. But strange thing is that i am following the same approach in another class to add markers and then i get them from arraylist that i maintain for them and .clear() works. The difference here is that i am using .addLine() instead of .addPoint(). Please guide if i am following the right approach or if there is any other method to achieve this functionality?

**Comment by blair1618** [comment]
In the current version, features (and their properties) can't be updated after they are added to a `MapData`. Instead, you would need to remove the old features and add new ones with the updated properties and geometry. 

We're aiming to improve this interface in upcoming versions.

**Comment by nomizodiac** [comment]
> you would need to remove the old features and add new ones with the updated properties and geometry.
Exactly thats what i want to achieve  "remove the old features" like i have added a feature/property in mapdata as follow:
```
Properties properties = new Properties();
properties.set("type", "line");
mapData.addLine(properties, lngLats);
```
Then i simply want to clear a specific property from mapdata by 
`properties.clear();`
If we cant change or clear any property that is added to mapdata then what is the purpose of properties.clear() method?

**Comment by nomizodiac** [comment]
Any update on how its going to work? I have added new Classes now by using this build dependency `compile 'com.mapzen.tangram:tangram:0.2'` I am adding a complete route (with multiple segments) on the map with red color as:

```
public void setRouteAndDisplay(ESRIRoute route) {
        removeAllSegmentsFromLayer();
        mRoute = route;
        for (int i = 0; i < mRoute.getListRouteDirections().size(); i++) {
            addSegmentToMap(mRoute.getListRouteDirections().get(i), colorNonSelectedRoute);
        }
    } 

public void addSegmentToMap(ESRIRouteDirection routeDirection, String color) {

        List<GeoPoint> geoPoints = routeDirection.getGeomPolyline().getPoints();
        List<LngLat> lngLats = getLatLngListFromGeoPoints(geoPoints);
        Map<String, String> properties = new HashMap<>();
        properties.put("type", "line");
        properties.put("color", color);
        routeLayer.addPolyline(lngLats, properties);
        mMapView.invalidate();
    }
``` 

Route is drawing on map successfully with redcolor. Now when user enters to next segment I want to set color of selected/next segment to green and previous segment color to red. To do that i am adding another segment/polyline again to same points with different color

```
private void updateSegmentOverlayStyle(int indexOfMapOverlay, String color) {

        ESRIRouteDirection newSegment = mRoute.getListRouteDirections().get(indexOfMapOverlay);
        List<GeoPoint> geoPoints = newSegment.getGeomPolyline().getPoints();
        List<LngLat> lngLats = getLatLngListFromGeoPoints(geoPoints);
        Map<String, String> properties = new HashMap<>();
        properties.put("type", "line");
        properties.put("color", color);
        //segmentsPropertiesList.add(properties);
        routeLayer.addPolyline(lngLats, properties);
        mMapView.invalidate();
    }
```

But it do not add new polyline with different color on top of a polyline which is already drawn on the map.

**Comment by blair1618** [comment]
To wrap up this issue: features added to a `MapData` cannot be modified after they are created. To create features with different properties, you would need to remove the old feature and add a new one with the updated properties. 

This will probably change in future iterations of this interface. It's pretty clear that there is desire for more flexible and dynamic map annotations, so we're designing a totally new approach to this.
