### ISSUE TITLE
Android rotate marker at runtime

### ISSUE THREAD

**Issue by nomizodiac** [tangrams/tangram-es#698]
I have added location marker on map using mapdata class by adding a Property. Now i want to rotate that marker with respect to user direction or using device sensor like in Google maps marker rotates with device direction. How can i achieve this functionality with Tangram maps?

**Comment by blair1618** [comment]
There is currently no built-in mechanism to rotate features on the map. 

A new interface for working with dynamic map features will be coming in Q2 of this year.

**Comment by nvkelso** [comment]
+1

**Comment by blair1618** [comment]
This is tracked in #653, closing.
