### ISSUE TITLE
zoom, tilt, rotate keymaps behaving unexpectedly on Linux

### ISSUE THREAD

**Issue by sevko** [tangrams/tangram-es#70]
The keymap/scroll combinations to zoom, tilt, and rotate the view are behaving weirdly on Linux. When I launch tangram, scrolling will zoom. Pressing `shift` once, releasing, and then scrolling will rotate, while doing the same thing but with `ctrl` will cause tilting. After that, I have to press `ctrl` and `shift` to alternate between tilting/rotating, and need to *hold* `ctrl`/`shift` and scroll to zoom.

**Comment by blair1618** [comment]
Should be fixed in 63fddfc, give it a try to make sure

**Comment by sevko** [comment]
Awesome, working as expected.
