### ISSUE TITLE
API Document for C/C++

### ISSUE THREAD

**Issue by mgarcia01752** [tangrams/tangram-es#701]
This is not an issue question, but I don't know where else to look.  Where can I obtain a C/C++ API if one exists. I building a Senior Capstone project  Thank you.

**Comment by blair1618** [comment]
Thanks for your interest! The C++ interface to the core rendering library is in [tangram.h](https://github.com/tangrams/tangram-es/blob/master/core/src/tangram.h). You can look at the [OS X demo](https://github.com/tangrams/tangram-es/blob/master/osx/src/main.cpp) for sample usage. 

We are certainly looking into making the C++ interface more easily usable, right now it is mainly used for us to build mobile SDKs on top of it. Feedback is welcome!

**Comment by blair1618** [comment]
If there are specific problems you would like to see resolved with the C++ interface or documentation we'll help you out with those in separate, targeted issues. For now I'll close this issue. Thanks for your interest!
