### ISSUE TITLE
The display of polygon is not correct

### ISSUE THREAD

**Issue by kitcheng** [tangrams/tangram-es#703]
**scene.yaml**

    global:
        default_order: function() { return feature.sort_key || 0; }
    
    scene:
        background:
            color: '#eeede5'

    cameras:
        perspective-camera:
            position: [113.50074827671051, 22.83201674559789, 16]
            type: perspective
            fov: 45
            active: true

    lights:
        light1:
            type: directional
            origin: world
            direction: [0, 1, -.5]
            diffuse: [.3, .3, .3, 1.]
            ambient: [0.7, 0.7, 0.7, 1.]

    sources:
        local:
            type: GeoJSON
            url:  test.json

    layers:
        test:
            data: { source: local }
            filter: { kind: [shop] }
            draw:
                polygons:
                    order: global.default_order
                    extrude: [80, 120]
                    color: function() { return feature.fill || 0; }
                lines:
                    color: white
                    width: 1px
                    order: 50
                    extrude: [80, 120]

    test2:
        data: { source: local }
        filter: { kind: [block] }
        draw:
            polygons:
                order: global.default_order
                extrude: [0, 40]
                color: function() { return feature.fill || 0; }

**test.json**

{
    "type": "FeatureCollection",
    "features": [
    {
      "type": "Feature",
      "properties": {
        "kind": "block",
        "stroke": "#555555",
        "stroke-width": 2,
        "stroke-opacity": 1,
        "fill": "#f9f7f4",
        "fill-opacity": 0.5
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              113.49973171949387,
              22.832812742872964
            ],
            [
              113.499755859375,
              22.831257824605608
            ],
            [
              113.50189089775085,
              22.831270184916253
            ],
            [
              113.50186139345169,
              22.832444409308916
            ],
            [
              113.50089579820633,
              22.83243699318665
            ],
            [
              113.50089848041534,
              22.832812742872964
            ],
            [
              113.49973171949387,
              22.832812742872964
            ]
          ]
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {
        "stroke": "#555555",
        "stroke-width": 2,
        "stroke-opacity": 1,
        "fill": "#00f900",
        "fill-opacity": 0.5,
        "kind": "shop",
        "name": "unique",
        "height": "20"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              113.50026547908782,
              22.83262981223422
            ],
            [
              113.49987119436264,
              22.832612507971888
            ],
            [
              113.4998470544815,
              22.83204641017614
            ],
            [
              113.50033521652222,
              22.832038994032185
            ],
            [
              113.50026547908782,
              22.83262981223422
            ]
          ]
        ]
      }
    }
  ]
}

**Result**

![device-2016-04-25-101442](https://cloud.githubusercontent.com/assets/326181/14772500/c3a8a8fe-0ad1-11e6-94f1-5671dff76ac5.png)

This happen not only in tangram-es, but also tangram. Thanks.

**Comment by blair1618** [comment]
Hi @kitcheng! Thanks for your interest, I'm curious what sort of application you're working on. 

This may be an issue with one of the 3rd party libraries we use in tangram-es. For now you can fix the rendering of your polygons by reversing the order of coordinates in the geojson. We'll look into updating the code for this so that you can input coordinates in either "clockwise" or "counter-clockwise" order in the future.

**Comment by bcamper** [comment]
@kitcheng I also found that your polygons render properly in Tangram JS, which may indicate a different in polygon "winding order" handling between Tangram JS and ES, which we will look into further in the future:

https://mapzen.com/tangram/play/?scene=https://gist.githubusercontent.com/anonymous/68830cf3f5e7217787dc85599917ee7b/raw/4377f3b1fb951efbc5b7d5afb26a665776e8d48e/scene.yaml#16/22.8320/113.5007

**Comment by kitcheng** [comment]
@blair1618 @bcamper Thank you for your help! I reversed the order of coordinates in the geojson and it worked. And I'm trying to use tangram-es to develop an indoor map application.
