### ISSUE TITLE
Are there any helping Java classes for zoom to bouding box for markers/routes?

### ISSUE THREAD

**Issue by nomizodiac** [tangrams/tangram-es#710]
Is there any built in class to show/zoom to fit all marker/route on the screen like zoomToBoundingBox. Or else is there any suitable way to get projection or map dimensions fro MapController class so that we can calculate zoom level from it? Thanks

**Comment by tallytalwar** [comment]
Hey @nomizodiac 

Sorry for being late on this.
We do not as of now, we however do plan to support this API.

As an example you can probably mimic the code we have on our privacy focused mapping app: https://github.com/mapzen/eraser-map/blob/f61b29dd421220d181e6cac072d71f3387952530/app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt#L860

Let me know if you need more info on this.

Thanks

**Comment by nomizodiac** [comment]
Thanks for response. I'll try that. 
Also can you please notify when you add it in API

Thanks

**Comment by tallytalwar** [comment]
Sure will update this ticket when we have this functionality in.
Thanks
