### ISSUE TITLE
run applySceneUpdates on bg thread

### ISSUE THREAD

**Issue by sarahlensing** [tangrams/tangram-es#723]
I'm trying to migrate EM to use 0.2.2 and need to apply scene updates to change the camera when the user starts navigation mode (https://github.com/mapzen/eraser-map/blob/tangram-2.2/app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt#L1129). When `applySceneUpdates` is called, we are also changing the tilt/zoom, etc. Currently, applying the scene updates breaks the animation of these properties.

**Comment by hjanetzek** [comment]
It would be nice if we load all cameras and have an API to switch between them directly.

Bonus Points for smooth perspective interpolation :D
http://answers.unity3d.com/questions/583316/fluent-animation-from-orthographic-to-perspective.html
http://answers.unity3d.com/storage/attachments/18735-cameraprojectionchangedeux.txt

**Comment by hjanetzek** [comment]
@tallytalwar could it be the problem that applySceneUpdates blocks rendering longer than the animation is supposed to run? (blocked due to synchronized methods in MapController)

**Comment by tallytalwar** [comment]
@hjanetzek That was also my initial thought.

One small thing which can be done on the EM side is to make sure the sceneUpdate is called first and animations are performed later?

**Comment by tallytalwar** [comment]
I also agree it will be nice to have all cameras in the scene and set camera using an explicit API call to activate a specific camera, instead of using sceneUpdate on it.

**Comment by bcamper** [comment]
We will add back a more direct camera API but are waiting to decide on the exact interface, especially as regards to how much similarity we want to GMaps. @blair1618 is working on this. Using the lower level scene update is the generic way to do it for now.

**Comment by tallytalwar** [comment]
@hjanetzek has control over this now. Already has some experimentation going on in a test branch.

We should however discuss more on the ideas put in this issue on cameras for a refactor later on.

**Comment by hjanetzek** [comment]
Hey @sarahlensing, I've tested scene updates with view animations (started before and after applyUpdates) and it works properly here: https://github.com/tangrams/tangram-android-demos/commit/fa933ef1df3d2f055a0f759af41d8a1a9c6800c4

Allowing to apply Scene updates on a background thread seems to be a quite large task - for which I would also wait for @blair1618 to discuss as he worked on this recently.

**Comment by sarahlensing** [comment]
@hjanetzek Thanks for the update, in the meantime I'll take another look at the EraserMap code and see if sceneUpdates are called before other animations as @tallytalwar suggests doing.

**Comment by blair1618** [comment]
Loading new scenes and updating scenes should indeed be performed on a background thread, ideally. There's nothing technically preventing this, but as Hannes mentioned it's not a small task. A better solution for now is to re-arrange the animation calls, as others have mentioned.

**Comment by hjanetzek** [comment]
https://github.com/tangrams/tangram-es/pull/776
