### ISSUE TITLE
reduce apk size

### ISSUE THREAD

**Issue by hjanetzek** [tangrams/tangram-es#724]
- Currently we ship 6MB of libc++_shared.so. With the new NDK static linking libc++ might work and safe some MB by stripping out unused stuff.

**Comment by tallytalwar** [comment]
We should also not be bundling fonts for android sdk.. since we look at the
system fonts for android.

**Comment by tallytalwar** [comment]
Currently `core/resource/fonts` size if about 5MB.

**Comment by tallytalwar** [comment]
Ok, tried removing bundled fonts for tangram android! Reduced the aar size from 11MB to 4.7MB. (https://github.com/tangrams/tangram-es/tree/no-font-bundling-android)

And yes libc++_shared.so is 6MB in the the unzipped aar!!!!!! We should definitely try getting rid of this in a sane manner.

**Comment by blair1618** [comment]
Resolved by #752 and #745 

Current AAR size (for one architecture) is 3MB
