### ISSUE TITLE
Possible math error in Polyline builder

### ISSUE THREAD

**Issue by dmvaldman** [tangrams/tangram-es#728]
I believe this line: https://github.com/tangrams/tangram-es/blob/master/core/src/util/builders.cpp#L337 will always evaluate to the value 1. This will give the correct scaling when normal vectors make a 45 degree angle, but will be off otherwise.

The reason why it evaluates to one is that (with `v = normPrev`, `w = normNext`, `m = miter` for brevity):

```
m =  v + w
m.m = v.v + w.w + 2 v.w = 2 + 2 v.w
```

so the scale factor

```
scale = sqrt( 2 / (1 + v.w) / m.m)
      = sqrt( 2 / (1 + v.w) / (2 + 2 v.w))
      = sqrt( 2 / 2 )
      = 1
```

I believe the correct factor is
```
scale = 2 / m.m
```

but unfortunately the margins of this GitHub issue are not big enough to contain the derivation.

**Comment by tallytalwar** [comment]
Your math looks good to me :D. (Of course...).
Will check more tomorrow.

**Comment by karimnaaji** [comment]
The maths looks good, but the parenthesis are probably misleading, the expression in code will be interpreted as:
```
scale = sqrt((2 / (1 + v.w)) / m.m)
```
Where the above statement is true for parenthesis as:
```
scale = sqrt( 2 / ((1 + v.w) / m.m))
```

**Comment by dmvaldman** [comment]
Ahh! Yes, that gives the same result. What a mind bender. You can avoid the `sqrt` and more complicated expression if you like with `scale = 2 / m.m` or `scale = 1 / (1 + v.w)`

**Comment by blair1618** [comment]
Thanks for the simplification! Applied here: https://github.com/tangrams/tangram-es/commit/06eb9f0e339b92ef99aa49cc06ee8b6e38243169
