### ISSUE TITLE
iOS Simulator builds failing to import fonts (and thus can't render labels)

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#730]
I realized I hadn't updated my core tangram repo in about 3-4 weeks, so I went through that and now it appears clean builds using "make ios-sim" can't find any of the TTF files, which means none of the labels render. 
<img width="432" alt="screen shot 2016-05-12 at 4 21 03 pm" src="https://cloud.githubusercontent.com/assets/1163880/15229109/8d0356b6-185d-11e6-964e-72f0a1b6d888.png">

Pertinent console logs:

```
Missing font: error: 1 fonts/NotoSans-Regular.ttf
Missing font: error: 1 fonts/NotoNaskh-Regular.ttf
Missing font: error: 1 fonts/NotoSansHebrew-Regular.ttf
Missing font: error: 1 fonts/DroidSansJapanese.ttf
Missing font: error: 1 fonts/DroidSansFallback.ttf
```

Error seems to be coming from https://github.com/tangrams/tangram-es/blob/master/core/src/text/fontContext.cpp#L63

**Comment by msmollin** [comment]
Dupe of https://github.com/tangrams/tangram-es/issues/643 fixed by https://github.com/tangrams/tangram-es/pull/649

**Comment by karimnaaji** [comment]
@msmollin a fix has been merged on master branch.
