### ISSUE TITLE
Refreshing a layer

### ISSUE THREAD

**Issue by brewin** [tangrams/tangram-es#731]
I have a raster source that is updated every five minutes, so I need to be able to refresh the tiles on the map. I tried `mapController.requestRender()` after the tiles had expired, but that didn't do anything. Is there currently any way to force a refresh of a layer?

**Comment by blair1618** [comment]
Hi @brewin, right now there isn't an easy way to do what you're describing. `requestRender()` will re-draw the tiles that are already in memory, but it won't re-load the tiles from their source. 

We'll consider this need in further revisions, but we might be able to find a work-around for now. Which platform are you using tangram with (Android, C++, iOS)?

**Comment by brewin** [comment]
Thanks @blair1618. I'm using the Android snapshot. A workaround would be great. I've made a custom HttpHandler to avoid caching the tiles, but I can't quite figure out how to get them to reload.

**Comment by blair1618** [comment]
tangram-es is designed to minimize http requests so it's actually rather tricky to force tile data to reload, but there is a hack-y way: you can update the scene to remove and re-add the data source that you want to refresh. Here is how it would look using Mapzen's tiles:
```java
mapController.queueSceneUpdate("sources", "{}");
mapController.applySceneUpdates(); // remove the source and its tile data
mapController.queueSceneUpdate("sources", "{ osm: { type: MVT, url: 'https://vector.mapzen.com/osm/all/{z}/{x}/{y}.mvt' } }");
mapController.applySceneUpdates(); // add the source again, retrieving tile data from the server
```

There may be an easier way to handle this in the future, but I hope that helps for now.

**Comment by brewin** [comment]
It would be cool to have a way to reload a specific source instead of all of them, but this seems to work well enough for now. Thanks for the help!

**Comment by bcamper** [comment]
I agree, this is a reasonable/useful feature to add, we'll look into it.
