### ISSUE TITLE
Integrating to current iOS Project

### ISSUE THREAD

**Issue by sajadkhan** [tangrams/tangram-es#734]
I'm new to cmake and having problems integrating this. 
When I make it for iOS it gives me a blank project with default src(header/Implementation) files and resource (storyboards). 
But I don't want that, what I need is to integrate existing iOS project in to my cmake environment. Or if I make it from the scratch and then move to other computer where I want to use the project and not make it again from scratch. 
How that can be achieve? 
I'll be grateful for little help. 
Thanks

**Comment by blair1618** [comment]
Hi @sajadkhan, we're currently developing an iOS interface for tangram-es that will be much easier to use in a typical iOS workflow (CMake has a steep learning curve and it doesn't fit iOS development especially well). @msmollin is leading the work on that, he may be able to provide advice.

**Comment by msmollin** [comment]
Hello @sajadkhan - thanks for reaching out. Like @blair1618 mentioned we're in the development stages of a much easier workflow for integrating tangram-es into native iOS code using a binary framework that you can install manually or using Cocoapods. If there's an alternative approach that would be easier for you let us know! 

While we're putting the finishing touches on that from having something to show for that, you can always using the existing cmake process to generate a build for iOS, and then create an Xcode workspace which you can import multiple distinct projects into and make them dependent upon each other. The downside with this approach is the build time increase and general management overhead associated with workspaces, but it should get the job done for now.

**Comment by sajadkhan** [comment]
Thanks, I have also found a work around for my scenario. But good news that we are having a binary framework for it in the future, that will make life a lot easier.

**Comment by blair1618** [comment]
Glad you found a solution! Progress on the iOS SDK will be noted [here](https://github.com/tangrams/tangram-es/issues/741). Closing this issue.
