### ISSUE TITLE
Scene should access load textures lazilly based on their URI

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#738]
We should store textures of the scene by their URI; this would be helpful in both scene imports (where several scene could potentially reference the same texture) and scene reloading time (to avoid reloading scene textures for a URI that has already been resolved in a previous scene loading.

**Comment by blair1618** [comment]
This is a good idea! Just to be clear, texture *data* can (and probably should) be referenced by a URI, but texture *objects* cannot be unambiguously referenced this way. For instance, a single PNG can be made into multiple textures with different filtering options, wrapping options, bit depth options, etc.

**Comment by bcamper** [comment]
Yes thank you for pointing that out :)

**Comment by matteblair** [comment]
For textures loaded over network, the HTTP caching layer should take care of any redundancy here. For local file textures, this isn't a big concern. Closing!
