### ISSUE TITLE
make rpi error on Pi2

### ISSUE THREAD

**Issue by ric96** [tangrams/tangram-es#74]
pi@raspberrypi ~/tangram-es $ make rpi
-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.7.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-4.7
-- Check for working CXX compiler: /usr/bin/g++-4.7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Platform chosen : RASPBERRYPI
-- Including raspberrypi dependent cmake file : /home/pi/tangram-es/toolchains/raspberrypi.cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/tangram-es/build/rpi
make[1]: Entering directory '/home/pi/tangram-es/build/rpi'
make[2]: Entering directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
Scanning dependencies of target libtess2
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
[  2%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/sweep.c.o
[  4%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/geom.c.o
[  7%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/mesh.c.o
[  9%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/tess.c.o
[ 11%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/bucketalloc.c.o
[ 14%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/priorityq.c.o
[ 16%] Building C object core/dependencies/tess2/CMakeFiles/libtess2.dir/libtess2/Source/dict.c.o
Linking C static library ../../../lib/liblibtess2.a
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[ 16%] Built target libtess2
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
Scanning dependencies of target core
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
[ 19%] Building CXX object core/CMakeFiles/core.dir/src/scene/directionalLight.cpp.o
[ 21%] Building CXX object core/CMakeFiles/core.dir/src/scene/scene.cpp.o
[ 23%] Building CXX object core/CMakeFiles/core.dir/src/scene/light.cpp.o
[ 26%] Building CXX object core/CMakeFiles/core.dir/src/scene/spotLight.cpp.o
[ 28%] Building CXX object core/CMakeFiles/core.dir/src/scene/pointLight.cpp.o
[ 30%] Building CXX object core/CMakeFiles/core.dir/src/scene/material.cpp.o
[ 33%] Building CXX object core/CMakeFiles/core.dir/src/style/style.cpp.o
[ 35%] Building CXX object core/CMakeFiles/core.dir/src/style/polylineStyle.cpp.o
[ 38%] Building CXX object core/CMakeFiles/core.dir/src/style/polygonStyle.cpp.o
[ 40%] Building CXX object core/CMakeFiles/core.dir/src/style/fontStyle.cpp.o
[ 42%] Building CXX object core/CMakeFiles/core.dir/src/tangram.cpp.o
[ 45%] Building CXX object core/CMakeFiles/core.dir/src/view/view.cpp.o
[ 47%] Building CXX object core/CMakeFiles/core.dir/src/text/fontContext.cpp.o
[ 50%] Building CXX object core/CMakeFiles/core.dir/src/text/textBuffer.cpp.o
[ 52%] Building CXX object core/CMakeFiles/core.dir/src/data/protobufSource.cpp.o
[ 54%] Building CXX object core/CMakeFiles/core.dir/src/data/dataSource.cpp.o
[ 57%] Building CXX object core/CMakeFiles/core.dir/src/data/geoJsonSource.cpp.o
[ 59%] Building CXX object core/CMakeFiles/core.dir/src/util/builders.cpp.o
[ 61%] Building CXX object core/CMakeFiles/core.dir/src/util/rectangle.cpp.o
[ 64%] Building CXX object core/CMakeFiles/core.dir/src/util/error.cpp.o
[ 66%] Building CXX object core/CMakeFiles/core.dir/src/util/geom.cpp.o
[ 69%] Building CXX object core/CMakeFiles/core.dir/src/util/geoJson.cpp.o
[ 71%] Building CXX object core/CMakeFiles/core.dir/src/util/mapProjection.cpp.o
[ 73%] Building CXX object core/CMakeFiles/core.dir/src/util/vboMesh.cpp.o
[ 76%] Building CXX object core/CMakeFiles/core.dir/src/util/shaderProgram.cpp.o
[ 78%] Building CXX object core/CMakeFiles/core.dir/src/util/pbfParser.cpp.o
[ 80%] Building CXX object core/CMakeFiles/core.dir/src/util/vertexLayout.cpp.o
[ 83%] Building CXX object core/CMakeFiles/core.dir/src/util/texture.cpp.o
[ 85%] Building CXX object core/CMakeFiles/core.dir/src/tile/mapTile.cpp.o
[ 88%] Building CXX object core/CMakeFiles/core.dir/src/tile/tileManager.cpp.o
[ 90%] Building CXX object core/CMakeFiles/core.dir/src/tile/labels/label.cpp.o
[ 92%] Building CXX object core/CMakeFiles/core.dir/src/tile/labels/labelContainer.cpp.o
[ 95%] Building CXX object core/CMakeFiles/core.dir/src/tile/tileWorker.cpp.o
Linking CXX static library ../lib/libcore.a
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
[ 95%] Built target core
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
Scanning dependencies of target tangram
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
make[3]: Entering directory '/home/pi/tangram-es/build/rpi'
[ 97%] Building CXX object CMakeFiles/tangram.dir/rpi/src/main.cpp.o
/home/pi/tangram-es/rpi/src/main.cpp:49:2: warning: ‘typedef’ was ignored in this declaration [enabled by default]
/home/pi/tangram-es/rpi/src/main.cpp: In function ‘void initOpenGL()’:
/home/pi/tangram-es/rpi/src/main.cpp:179:124: warning: invalid conversion from ‘int’ to ‘DISPMANX_TRANSFORM_T’ [-fpermissive]
In file included from /opt/vc/include/bcm_host.h:50:0,
                 from /home/pi/tangram-es/core/src/gl.h:30,
                 from /home/pi/tangram-es/rpi/src/main.cpp:14:
/opt/vc/include/interface/vmcs_host/vc_dispmanx.h:85:44: warning:   initializing argument 10 of ‘DISPMANX_ELEMENT_HANDLE_T vc_dispmanx_element_add(DISPMANX_UPDATE_HANDLE_T, DISPMANX_DISPLAY_HANDLE_T, int32_t, const VC_RECT_T*, DISPMANX_RESOURCE_HANDLE_T, const VC_RECT_T*, DISPMANX_PROTECTION_T, VC_DISPMANX_ALPHA_T*, DISPMANX_CLAMP_T*, DISPMANX_TRANSFORM_T)’ [-fpermissive]
/home/pi/tangram-es/rpi/src/main.cpp: In function ‘int main(int, char**)’:
/home/pi/tangram-es/rpi/src/main.cpp:349:75: error: too few arguments to function ‘void Tangram::handlePanGesture(float, float, float, float)’
In file included from /home/pi/tangram-es/rpi/src/main.cpp:12:0:
/home/pi/tangram-es/core/src/tangram.h:42:6: note: declared here
/home/pi/tangram-es/rpi/src/main.cpp:365:56: error: too few arguments to function ‘void Tangram::handlePanGesture(float, float, float, float)’
In file included from /home/pi/tangram-es/rpi/src/main.cpp:12:0:
/home/pi/tangram-es/core/src/tangram.h:42:6: note: declared here
/home/pi/tangram-es/rpi/src/main.cpp:368:57: error: too few arguments to function ‘void Tangram::handlePanGesture(float, float, float, float)’
In file included from /home/pi/tangram-es/rpi/src/main.cpp:12:0:
/home/pi/tangram-es/core/src/tangram.h:42:6: note: declared here
/home/pi/tangram-es/rpi/src/main.cpp:371:56: error: too few arguments to function ‘void Tangram::handlePanGesture(float, float, float, float)’
In file included from /home/pi/tangram-es/rpi/src/main.cpp:12:0:
/home/pi/tangram-es/core/src/tangram.h:42:6: note: declared here
/home/pi/tangram-es/rpi/src/main.cpp:374:57: error: too few arguments to function ‘void Tangram::handlePanGesture(float, float, float, float)’
In file included from /home/pi/tangram-es/rpi/src/main.cpp:12:0:
/home/pi/tangram-es/core/src/tangram.h:42:6: note: declared here
CMakeFiles/tangram.dir/build.make:54: recipe for target 'CMakeFiles/tangram.dir/rpi/src/main.cpp.o' failed
make[3]: *** [CMakeFiles/tangram.dir/rpi/src/main.cpp.o] Error 1
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/tangram.dir/all' failed
make[2]: *** [CMakeFiles/tangram.dir/all] Error 2
make[2]: Leaving directory '/home/pi/tangram-es/build/rpi'
Makefile:72: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/tangram-es/build/rpi'
Makefile:153: recipe for target 'rpi' failed
make: *** [rpi] Error 2
pi@raspberrypi ~/tangram-es $

**Comment by tallytalwar** [comment]
Thanks Sahaj for trying out our raspberry pi build.

We discovered this today and will be pushing out an update soon. Thanks

**Comment by patriciogonzalezvivo** [comment]
Fix pushed! Thanks @ric96 let us know how it works!

**Comment by ric96** [comment]
Works well.

**Comment by Moayidd** [comment]
Could someone let me know how to obtain the fix - I have the same problem and I'm very new to RPI

**Comment by tallytalwar** [comment]
Hey

Thanks for trying our rpi builds.

Can you please post the error logs and we will be happy to help?
Thanks

**Comment by Moayidd** [comment]
Hi,
They are identical to the ones posted above.

**Comment by blair1618** [comment]
I think it's actually a slightly different issue going on now, but it should be fixed in the master branch now. Update your repo with `git pull` and the clean and retry the build with `make clean-rpi rpi`.

**Comment by Moayidd** [comment]
Thanx,
will do and let you know

**Comment by Moayidd** [comment]
It still ends with the same error:
make *** [rpi] Error 2
in the phase:
[10%] Building CXX object core/CmakeFiles/core.dir/src/text/textBuffer.cpp.o

**Comment by blair1618** [comment]
Ah, thanks for the info. This might be due to an out-of-date submodule, can you try running `git submodule update` and trying the build again? If the problem still persists it'd be cool if you could open a new issue and post the full build output there. Thanks!

**Comment by Moayidd** [comment]
ok will do, thanx
