### ISSUE TITLE
iOS SDK

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#741]
This issue tracks progress on the initial version of an iOS SDK. Currently there is a demo application for iOS which directly interfaces with the C++ API (via Objective-C++). An iOS SDK will provide a more conventional Swift API and build process for using tangram-es maps.

**Comment by msmollin** [comment]
We've got preview framework artifacts available now in a separate repository (to keep from littering this one up) over here - https://github.com/tangrams/ios-framework

The build changes and modifications are currently in the obj-c branch here although there are some hardcoded path issues that I'm working through currently https://github.com/tangrams/tangram-es/tree/obj-c 

Feel free to check it out and once I fix those I'll post back here.

**Comment by karimnaaji** [comment]
Follow https://github.com/mapzen/ios for iOS SDK development.
