### ISSUE TITLE
No text or icons on Android versions < 5.0

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#744]
On a 2014 Moto X running Android 6.0, the demo app appears as expected with POI icons and text labels:
![screenshot_20160520-181338](https://cloud.githubusercontent.com/assets/3371850/15443514/f58da89e-1eb6-11e6-83d0-733e56a41055.png)

On a Galaxy S5 running Android 4.4.2 and a Galaxy S3 running Android 4.0.4 (not pictured), the demo app appears with neither POI icons nor text labels:
![screenshot_2016-05-20-18-13-19](https://cloud.githubusercontent.com/assets/3371850/15443551/31922e82-1eb7-11e6-8a63-2bc5f8901b6d.png)

**Comment by blair1618** [comment]
No GL errors are reported, but there are log messages indicating that resource files were not found, possibly including font files.

**Comment by blair1618** [comment]
This also affects the Galaxy Note 8.0 (GT-N5110) running Android 4.2.2

**Comment by karimnaaji** [comment]
Possibly related:
https://github.com/tangrams/tangram-es/issues/385
https://github.com/tangrams/tangram-es/issues/288

**Comment by hak-tpl** [comment]
Text and icons appear on Galaxy S5 running Android 5.0. May be this is an API level issue?

**Comment by blair1618** [comment]
Good catch, I've changed the title to reflect the relationship with Android API level. 

Part of the issue is almost certainly that the font loader on Android is looking for only the newer version of the font index file, introduced in Android L (5.0). 

Here's the line in MapController: https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/MapController.java#L168

And an explanation in fonts.xml: https://github.com/android/platform_frameworks_base/blob/master/data/fonts/fonts.xml

The font resolution code should, ideally, know how to parse both the old and the new files or, at a minimum, safely resolve at least one font when the index file can't be found or parsed.
