### ISSUE TITLE
setFeaturePickListener for Line/Polygon Android

### ISSUE THREAD

**Issue by nomizodiac** [tangrams/tangram-es#748]
can we get callback on touch line or polygon. I only get onFeaturePick callback when touched on a Point, can i do the same for Line?

**Comment by tallytalwar** [comment]
Hey @nomizodiac 

We currently do not support feature selection for line and polygons like how Tangram JS project does. We do plan to support this, but nothing in the works right now.

Can you describe your use case, which can help us prioritize this on our side?

Thanks

**Comment by nomizodiac** [comment]
@tallytalwar Thanks for the response. Basically what i want to achieve is to draw multiple routes based on distance and time. Out of those two routes drawn on map when user tap on a route that route will be selected (color change or something) and other will be deselected . Same is the feature in google maps. Is there any other way to achieve this in tangram maps?

**Comment by westnordost** [comment]
@tallytalwar Another use case: A sparse OSM editor which shows only a few elements superimposed over the tangram map. If you click on them, you can edit properties or similar. Those elements could be points, lines, polygons (and even multipolygons).

@nomizodiac I think you could register a TapResponder, convert the position into latlon via MapController.coordinatesAtScreenPosition and compare that position with every line segment of your route in your MapData to find whether the user clicked on it. (That would basically be the implementation in tangram-es for lines I guess)

**Comment by tallytalwar** [comment]
WIP: https://github.com/tangrams/tangram-es/pull/961
Also closing this in favor of #905, to keep all discussions in one place.
