### ISSUE TITLE
iOS Map Cashe

### ISSUE THREAD

**Issue by haidershahzad** [tangrams/tangram-es#755]
Hello guys, i need to know how tile_cache is working i have seen that the code is written in platform_ios.mm along with the path, I open the directory from device at the same path and saw cache.db but i dont know how i can read the cache file for offline maps.

Please point me in the right direction. I really appreciate the work you guys doing.

**Comment by blair1618** [comment]
Hello! The HTTP caching behavior on iOS is currently determined by the configuration steps [here](https://github.com/tangrams/tangram-es/blob/master/ios/src/platform_ios.mm#L20-L30). You probably care most about the property `requestCachePolicy`. The options for this are described here:

https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSURLRequest_Class/index.html#//apple_ref/c/tdef/NSURLRequestCachePolicy

If you wanted to switch to an "offline" mode and use only cached responses, you could try setting the cache policy to `NSURLRequestReturnCacheDataDontLoad`. 

Hope that helps!

**Comment by blair1618** [comment]
Closing this issue until further help is needed.
