### ISSUE TITLE
Ubuntu running problems

### ISSUE THREAD

**Issue by kkalera** [tangrams/tangram-es#758]
Hi everyone,

I build tangram-es on ubuntu, following the linux instructions. Building went without problems, but I'm having some issues when I run the program. I'm only getting the names of the places, nothing else is displayed.

Any help ,resolving my issue would be appreciated. I'm not entirely sure if its a problem in the build or a problem with my system.

The program seems to start in the shaderProgram.cpp as you can see in my terminal below;

`kalera@ubuntu:~/tangram-es/build/linux/bin$ ./tangram
TANGRAM tangram.cpp:68: initialize
TANGRAM tangram.cpp:120: Loading scene file: scene.yaml
WARNING sceneLoader.cpp:1407: Can't find data source touch for layer touch
TANGRAM tangram.cpp:94: finish initialize
TANGRAM tangram.cpp:529: setup GL
TANGRAM hardware.cpp:57: Driver supports map buffer: 1
TANGRAM hardware.cpp:58: Driver supports vaos: 1
TANGRAM hardware.cpp:72: Hardware max texture size 16384
TANGRAM hardware.cpp:73: Hardware max combined texture units 48
TANGRAM tangram.cpp:154: resize: 800 x 600
TANGRAM tileWorker.cpp:66: Passed new TileBuilder to TileWorker
ERROR shaderProgram.cpp:225: Shader compilation failed {style:heightglow}
ERROR shaderProgram.cpp:226: 0:345(1): error: syntax error, unexpected NEW_IDENTIFIER, expecting $end

ERROR shaderProgram.cpp:225: Shader compilation failed {style:heightglowline}
ERROR shaderProgram.cpp:226: 0:348(1): error: syntax error, unexpected NEW_IDENTIFIER, expecting $end

ERROR shaderProgram.cpp:225: Shader compilation failed {style:lines}
ERROR shaderProgram.cpp:226: 0:346(1): error: syntax error, unexpected NEW_IDENTIFIER, expecting $end

ERROR shaderProgram.cpp:225: Shader compilation failed {style:polygons}
ERROR shaderProgram.cpp:226: 0:343(1): error: syntax error, unexpected NEW_IDENTIFIER, expecting $end

ERROR shaderProgram.cpp:225: Shader compilation failed {style:raster}
ERROR shaderProgram.cpp:226: 0:343(1): error: syntax error, unexpected NEW_IDENTIFIER, expecting $end

ERROR shaderProgram.cpp:225: Shader compilation failed {style:stripeline}
ERROR shaderProgram.cpp:226: 0:350(1): error: syntax error, unexpected NEW_IDENTIFIER, expecting $end

ERROR shaderProgram.cpp:225: Shader compilation failed {style:icons}
ERROR shaderProgram.cpp:226: 0:126(1): error: syntax error, unexpected '{', expecting $end

ERROR shaderProgram.cpp:225: Shader compilation failed {style:points}
ERROR shaderProgram.cpp:226: 0:125(1): error: syntax error, unexpected '{', expecting $end

Failed to read file at path: ./fonts/sans-serif-400normal.ttf
Failed to read file at path: fonts/sans-serif-400normal.ttf
Failed to read file at path: 
ERROR fontContext.cpp:295: Could not load font file sans-serif_400_normal
LOADED Font: Noto Sans Regular size: 28
TANGRAM tileWorker.cpp:66: Passed new TileBuilder to TileWorker
Failed to read file at path: ./fonts/sans-serif-400normal.ttf
Failed to read file at path: fonts/sans-serif-400normal.ttf
Failed to read file at path: 
ERROR fontContext.cpp:295: Could not load font file sans-serif_400_normal
LOADED Font: Noto Sans Regular size: 16
Failed to read file at path: ./fonts/sans-serif-400normal.ttf
Failed to read file at path: fonts/sans-serif-400normal.ttf
Failed to read file at path: 
ERROR fontContext.cpp:295: Could not load font file sans-serif_400_normal
LOADED Font: Noto Sans Regular size: 28
NOTIFY style.cpp:294: Mesh built by style heightglow cannot be drawn
NOTIFY style.cpp:294: Mesh built by style heightglowline cannot be drawn
NOTIFY style.cpp:294: Mesh built by style lines cannot be drawn
NOTIFY style.cpp:294: Mesh built by style polygons cannot be drawn
NOTIFY style.cpp:294: Mesh built by style stripeline cannot be drawn
`

**Comment by boza111** [comment]
I get 3 errors when running on Debian.

NOTIFY style.cpp:294: Mesh built by style heightglowline cannot be drawn
NOTIFY style.cpp:294: Mesh built by style lines cannot be drawn
NOTIFY style.cpp:294: Mesh built by style stripeline cannot be drawn

sans serif 400 doesn't load for me either.. (not in the folder)

Maybe this is why the app looks a little bleak?

![screenshot from 2016-05-30 18-33-43](https://cloud.githubusercontent.com/assets/10471558/15656318/6330d912-2695-11e6-99d0-895ed51c6f35.png)

**Comment by hjanetzek** [comment]
@kkalera, @boza111 thanks for reporting! This issue should be fixed by https://github.com/tangrams/tangram-es/commit/9da0a126d3252898c56f0b598fbb6ca0c17d692e

**Comment by boza111** [comment]
That fixes the errors. New York looks beautiful now. Thank you!
I have put a TTF font in the fonts folder and named the file "sans-serif-400normal.ttf" .. No errors at all now..

![screenshot from 2016-05-30 21-42-07](https://cloud.githubusercontent.com/assets/10471558/15658763/1d8bb5d8-26b0-11e6-9dbd-e3854d0d6392.png)

**Comment by kkalera** [comment]
@hjanetzek  Thank you for fixing this so fast!
