### ISSUE TITLE
Error compiling on Linux Debian

### ISSUE THREAD

**Issue by boza111** [tangrams/tangram-es#760]
Hello everyone,

I followed all the instructions but it is not compiling for some reason.

I get the following output. Am I doing something wrong, or has something changed?

`mkdir -p build/linux
cd build/linux &&\
cmake ../..   -DPLATFORM_TARGET=linux -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE
-- Platform chosen : LINUX
-- Including linux dependent cmake file : /root/Downloads/maps/tangram-es/toolchains/linux.cmake
-- Using gcc 5.3.1

-- USE CXX11_ABI
CMake Error at external/CMakeLists.txt:25 (add_subdirectory):
  The source directory

    /root/Downloads/maps/tangram-es/external/yaml-cpp

  does not contain a CMakeLists.txt file.

You have called ADD_LIBRARY for library geojson-vt-cpp without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at external/CMakeLists.txt:97 (add_subdirectory):
  The source directory

    /root/Downloads/maps/tangram-es/external/glfw

  does not contain a CMakeLists.txt file.

CMake Error at external/CMakeLists.txt:99 (target_include_directories):
  Cannot specify include directories for target "glfw" which is not built by
  this project.

CMake Error at external/CMakeLists.txt:103 (target_link_libraries):
  Cannot specify link libraries for target "glfw" which is not built by this
  project.

-- Configuring incomplete, errors occurred!
See also "/root/Downloads/maps/tangram-es/build/linux/CMakeFiles/CMakeOutput.log".
Makefile:269: recipe for target 'cmake-linux' failed
make: *** [cmake-linux] Error 1
`

**Comment by hjanetzek** [comment]
The checkout is probably missing the submodules. run

```git submodule update --init --recursive```

**Comment by boza111** [comment]
That did the trick. Thank you!
