### ISSUE TITLE
how can i use the "Android Helpers" i want get the "Android.mk" and "Application.mk"

### ISSUE THREAD

**Issue by TGISer** [tangrams/tangram-es#761]
i only want get the "Android.mk" and "Application.mk" file how can i build it

**Comment by blair1618** [comment]
We don't use an Android.mk or Application.mk file. 

The traditional way of building Android applications with the NDK uses very specific forms of Makefiles, named Android.mk and Application.mk. However, most of tangram-es is built using the [CMake](https://cmake.org/) build system. We build our Android NDK application using CMake as well by using a [toolchain file](https://github.com/tangrams/tangram-es/blob/master/toolchains/android.toolchain.cmake) that configures the "make" command to use the NDK compiler (it's a little more complicated than that, but that's the basic idea). 

If you are trying to build the Android library from source, follow the build instructions in the [README](https://github.com/tangrams/tangram-es/blob/master/README.md#build). If you're trying to do something else, please describe more specifically what you would like to accomplish and then maybe we can help you.

**Comment by TGISer** [comment]
@blair1618   thank you for reply!

I just want use tangram-es render offline vectortile data on android and improve it's performance.(windows or Linux is all ok)


I want debug the source code on a compiler(like vs2015、Android stdio、Eclipse).

Before this I used vs2013 write c++ source code then used Android.mk && NDK compile it on eclipse finally use Java call c/c++ by JNI .By this way I can not only write Java code but also debug the c/c++ code in eclipse. 


I want to know your way to write c++ code and test、improve the performance, then use it in Android.

Thank you for your help!

**Comment by hanchao** [comment]
@TGISer If you don't have a macbook, Clion is also a good choice on linux

**Comment by TGISer** [comment]
@hanchao   thank you i will try your suggestion

**Comment by tallytalwar** [comment]
Closing this in favor of https://github.com/tangrams/tangram-es/issues/769
