### ISSUE TITLE
try "make android" on Linux 

### ISSUE THREAD

**Issue by TGISer** [tangrams/tangram-es#769]
this is the error  how can i repair it !  thank you

CMake Error at toolchains/android.toolchain.cmake:616 (message):
  Could not find any working toolchain in the NDK.  Probably your Android NDK
  is broken.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.0/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt:3 (project)

CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_C_COMPILER
CMake Error: Could not find cmake module file: /home/tgiser/ CProject/tangram-es-0.3-android/build/android/CMakeFiles/3.0.0/CMakeCCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may be not be built correctly.
Missing variable is:
CMAKE_CXX_COMPILER
CMake Error: Could not find cmake module file: /home/tgiser/ CProject/tangram-es-0.3-android/build/android/CMakeFiles/3.0.0/CMakeCXXCompiler.cmake
CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_C_COMPILER to the full path to the compiler, or to the compiler name
  if it is in the PATH.

CMake Error at CMakeLists.txt:3 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_CXX_COMPILER to the full path to the compiler, or to the compiler
  name if it is in the PATH.

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

**Comment by hjanetzek** [comment]
@TGISer read the first error: ```Could not find any working toolchain in the NDK. Probably your Android NDK is broken.```

What does ```echo $ANDROID_NDK``` print out? and is that the right path to your NDK?

**Comment by hjanetzek** [comment]
@TGISer Make sure to use the r10e version of the NDK as this is what we use currently (Should be added to the README..)

**Comment by TGISer** [comment]
@hjanetzek  i use the android-ndk-r11c  i will try your suggestion

**Comment by TGISer** [comment]
@hjanetzek  
i try to use android-ndk-r10e but it can not work , have the same error.


tgiser@tgiser-ThinkPad-Edge-E531:~/ CProject/tangram-es-0.3-android$ echo $ANDROID_NDK
/home/tgiser/software/android-ndk-r10e

**Comment by blair1618** [comment]
You might need to run `make clean-android` first, in case CMake cached the old NDK location.

**Comment by TGISer** [comment]
@blair1618  
i try to use make clean-android  first  but it can not work , have the same error.

**Comment by tallytalwar** [comment]
We have not been able to reproduce this issue. @TGISer please try this again and open a new issue if you still can not get android builds to run using the command line.

Thanks
