### ISSUE TITLE
Render state: Texture unit binding should invalidate texture binding

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#777]
@bcamper found out a bug in the tracking of texture unit/id binding within tangram-js that could possibly happen in -es.
We currently don't use multiple texture unit on default shaders but this could happen on user defined uniforms textures. A fix would be, every time a new texture unit is bound the current state tracking of the bound texture should be invalidated.

**Comment by bcamper** [comment]
FYI, fixed in JS here: https://github.com/tangrams/tangram/commit/0cee05f76de2d0c630d209c7ea1d02068f9d46e4

**Comment by tallytalwar** [comment]
Closed #777 via #784
