### ISSUE TITLE
how can i download "https://vector.mapzen.com/osm/all/{z}/{x}/{y}.mvt"

### ISSUE THREAD

**Issue by giseriiii** [tangrams/tangram-es#782]
i want use the mvt data in android by offline model
thank you for your help

**Comment by tallytalwar** [comment]
Kindly refer to an earlier issue addressing the same question: https://github.com/tangrams/tangram-es/issues/774.

Thanks

**Comment by blair1618** [comment]
Information about Mapzen's vector tile service can be found here: https://mapzen.com/documentation/vector-tiles/

As the documentation describes, you should get an API key to start using the vector tile service. Then you can request and save tiles from URLs like the one you've posted above. Note that "{z}", "{x}", and "{y}" are placeholders for numbers that specify an individual vector tile. 

Vector tiles are downloaded over HTTP just like any other file on the web. From a command line, you can use [curl](https://curl.haxx.se/docs/manual.html) to download files with a script. 

A map rendering engine like tangram-es download vector tiles as part of the process of displaying a map, it figures out which vector tiles are needed for a specific view and downloads those automatically. 

Please create a new issue with a detailed description if you encounter further problems with tangram-es. Good luck!
