### ISSUE TITLE
Support data URLs

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-es#783]
Data URLs use base64-encoded data to provide a simple means of directly passing data to interfaces that expect a URL. They are often used in web development for embedding simple resources and/or reducing external dependencies and network requests.

An example of a 1x1 yellow pixel texture:
`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIW2P8/5/hPwAIAgL/oEs8+AAAAABJRU5ErkJggg==`

We should support these in ES for cross-platform compliance.

**Comment by blair1618** [comment]
This specific example of image data encoded as a base64 string seems pretty manageable to implement and I can understand its convenience. Supporting Data URLs _in general_ would be a bit more work, if I am understanding their capabilities correctly from https://en.wikipedia.org/wiki/Data_URI_scheme. We would need to:

 - Add URL handling code to treat "data:" scheme requests specially
 - Parse and recognize alternate character sets from the URL (unclear how this is used)
 - Parse and recognize the 'base64' attribute
 - Decode percent-encoded strings, if base64 is not used
 - Decode a base64 string

This happens to "just work" with the NSURL class for iOS, but for other platforms we would have to implement and test this more-or-less from scratch. I would imagine that this doesn't add a whole lot of value for mobile developers, but it does align with our goal of making scene files drop-in-compatible.

**Comment by bcamper** [comment]
It's totally reasonable to implement a subset -- the most common I've seen by far are images as PNGs or GIFs, which is useful for small embedded textures.

**Comment by tallytalwar** [comment]
A part of this to support base64 texture urls was implemented here: cc399b988a4f73203de16992abe6856de1123bf0, and got merged to master via https://github.com/tangrams/tangram-es/pull/776

**Comment by blair1618** [comment]
Since loading textures via data URL seems to be the primary use case for these, let's consider this "done" for our purposes.
