### ISSUE TITLE
Marker and perspective 2.5D

### ISSUE THREAD

**Issue by yuridiniz** [tangrams/tangram-es#799]
Hello!

I recently met this project and is really very powerful, but I'm having some difficulties with markers.

When we set the camera to `type : perspective` and added a point, we realized that this marker does not follow the perspective of the camera .

Is there any way to set this behavior?

Thanks

![screenshot_2016-06-17-18-38-31](https://cloud.githubusercontent.com/assets/5683101/16165651/8cfb74ee-34bb-11e6-831e-dedbb4781829.png)

**Comment by blair1618** [comment]
Hi Yuri, thanks for the descriptive issue, diagrams are the best!

Our core team here has been thinking about this problem too. The short answer is: you can't do this yet, but we're working on it. 

The long answer is: we have a layout system for icons and text that's highly optimized for resolving collisions (overlap) between objects in *screen space*, and currently it only works for objects that are oriented to face the screen. Adjusting the geometry of an icon to lay flat against the ground is pretty simple, but we also have to adapt our collision system to deal with some icons being flat, which makes this feature bigger than it seems. But! We hope to add this as part of the revised "Marker" system described in #653 (or soon after that).
