### ISSUE TITLE
Label collision detection

### ISSUE THREAD

**Issue by hanchao** [tangrams/tangram-es#80]
![collision](https://cloud.githubusercontent.com/assets/1942091/6977327/91eb4c88-d9ed-11e4-8ea4-d0c9e8606d22.png)

**Comment by tallytalwar** [comment]
Hi Han.

Thanks for trying our cross platform map renderer. 

Tangram-es is currently in development and in no way feature complete.
This specific feature is being worked on at present by @karimnaaji, a developer on our team.

Thanks
