### ISSUE TITLE
How to change the 3D view angle in tangram-es

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#808]

**Comment by blair1618** [comment]
Tangram-es supports variable rotation and tilt. For the C++ interface, see https://github.com/tangrams/tangram-es/blob/master/core/src/tangram.h#L69-L87. For Android, see https://github.com/tangrams/tangram-es/blob/master/android/tangram/src/com/mapzen/tangram/MapController.java#L290-L360.

**Comment by lygstate** [comment]
This is for rotation of x axis, how about the z
Axis rotation

**Comment by blair1618** [comment]
The coordinate system in tangram-es has positive 'x' pointing East, positive 'y' pointing North, and positive 'z' pointing up into the sky. Rotating around the 'z' axis therefore corresponds to the `setRotation` methods.

**Comment by lygstate** [comment]
Then the question turn out to be how to rotating around the 'x' axis

**Comment by blair1618** [comment]
I think `setTilt` does what you want. This "tilt" is the rotation around the angle currently pointing right on the screen, so if "rotation" is zero then "tilt" is around the "x" axis.
