### ISSUE TITLE
Rpi build references g++-4.7 directly instead of testing for a C++11 compiler

### ISSUE THREAD

**Issue by xorgy** [tangrams/tangram-es#81]
I am running a Raspberry Pi with GCC 4.9 instead of GCC 4.7, and had to manually switch `g++-4.7` in `toolchains/raspberrypi.toolchain.cmake` to just `g++`.

Ideally you would use some sort of C++11 detection in CMake, or at least tell people that they'll need to do this to build with anything other than g++ 4.7.

**Comment by karimnaaji** [comment]
Hi,
Thanks for reporting,

**Comment by xorgy** [comment]
That hits the spot, thanks.
