### ISSUE TITLE
Enable the rendering of Mapbox Satellite sources

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#811]
Satellite is a big deal, we may need a option to rendering it under the vector map data.

**Comment by lygstate** [comment]
The data source comes from mapbox [https://www.mapbox.com/help/mapbox-satellite-sources/](Mapbox Satellite Sources)

**Comment by bcamper** [comment]
This should be possible as-is by adding a `raster` tile source to your scene, see here for more info: https://mapzen.com/documentation/tangram/Raster-Overview/

Let us know if you have further questions or issues, thanks.
