### ISSUE TITLE
Use white for invalid textures in release builds

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#813]
To minimize the visual impact of textures that are broken or possibly still loading, release builds should create dummy textures filled with white (currently they are black).

We could make these textures a more distinct color for debugging purposes in non-release builds. Some game engines prefer a bright pink ;)

**Comment by nvkelso** [comment]
+1

**Comment by matteblair** [comment]
Instead of showing a placeholder color for missing textures, the engine now skips rendering any meshes that depend on an unavailable texture.

**Comment by bcamper** [comment]
This is also Tangram JS behavior FYI.
