### ISSUE TITLE
Compile failure on latest Tangram-ES Ver on Raspberry Pi

### ISSUE THREAD

**Issue by mgarcia01752** [tangrams/tangram-es#815]
Unable to compile to the new version of Tangram-ES

Any suggestion???

## Procedure:

brew install cmake
 
sudo apt-get update

sudo apt-get install cmake g++-4.7 libcurl4-openssl-dev

cd ~

git clone https://github.com/tangrams/tangram-es.git

export CXX=/usr/bin/g++-4.9

git submodule update --init --recursive

cd tangram-es

git submodule init && git submodule update

make rpi

cd build/rpi/bin

./tangram

## Output

CMakeFiles/tangram.dir/build.make:77: recipe for target 'CMakeFiles/tangram.dir/rpi/src/platform_rpi.cpp.o' failed
make[3]: *** [CMakeFiles/tangram.dir/rpi/src/platform_rpi.cpp.o] Error 1
make[3]: Leaving directory '/home/pi/tangram-es/build/rpi'
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/tangram.dir/all' failed
make[2]: *** [CMakeFiles/tangram.dir/all] Error 2
make[2]: Leaving directory '/home/pi/tangram-es/build/rpi'
Makefile:137: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/tangram-es/build/rpi'
Makefile:256: recipe for target 'rpi' failed
make: *** [rpi] Error 2
pi@raspberrypi:~/tangram-es $

**Comment by mgarcia01752** [comment]
More information on the errors:

/opt/vc/include/interface/vcos/pthreads/vcos_platform.h: In function ‘void vcos_event_signal(VCOS_EVENT_T*)’:
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:567:8: warning: variable ‘ok’ set but not used [-Wunused-but-set-variable]
    int ok = 0;
        ^
/home/pi/tangram-es/rpi/src/platform_rpi.cpp: In function ‘std::string stringFromFile(const char*)’:
/home/pi/tangram-es/rpi/src/platform_rpi.cpp:59:56: error: invalid initialization of non-const reference of type ‘size_t& {aka unsigned int&}’ from an rvalue of type ‘unsigned int*’
     unsigned char* bytes = bytesFromFile(_path, &length);
                                                        ^
In file included from /home/pi/tangram-es/rpi/src/platform_rpi.cpp:1:0:
/home/pi/tangram-es/core/src/platform.h:46:16: note: in passing argument 2 of ‘unsigned char* bytesFromFile(const char*, size_t&)’
 unsigned char* bytesFromFile(const char* _path, size_t& _size);
                ^
/home/pi/tangram-es/rpi/src/platform_rpi.cpp: In function ‘unsigned char* bytesFromFile(const char*, size_t&)’:
/home/pi/tangram-es/rpi/src/platform_rpi.cpp:73:10: error: invalid type argument of unary ‘*’ (have ‘size_t {aka unsigned int}’)
         *_size = 0;

**Comment by tallytalwar** [comment]
Closing this as we checked it locally, and it worked.
