### ISSUE TITLE
Developer Forum

### ISSUE THREAD

**Issue by mgarcia01752** [tangrams/tangram-es#817]
Is there a developer forum? I compiled the latest and I'm understanding some of the API, but I am trying to understand when the scene.yaml is indicating Manhattan, but I am seeing the world map.  Not much online documentation, but if there, can someone point me to it. I'm working on my senior project and trying to figure this out.

Any help would be great!!!!

Thanks

**Comment by blair1618** [comment]
We don't have a developer forum, but it's true that it would be useful to have a way of asking support questions that didn't involve github issues.

Our team just made a chat room on gitter: https://gitter.im/tangrams/tangram-chat
So we'll give that a try!

**Comment by tallytalwar** [comment]
Updated readme to mention about gitter chat.
