### ISSUE TITLE
Is that possible to implement Google Earth like effect in tangram-es?

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#818]
Cause tangram-es support 3d effect, so maybe that's possible in tangram-es.

**Comment by blair1618** [comment]
I don't understand the question. Can you describe this "effect" or attach a screenshot?

**Comment by lygstate** [comment]
Showing map like this:
![Google Earth Map](https://cloud.githubusercontent.com/assets/121040/16678017/d2c6d5ec-450d-11e6-8e43-83636bf6304a.png)

**Comment by blair1618** [comment]
Oh, I see! Right now there is no built-in way to display the map as a globe in tangram-es. This would be a nice feature, but it requires several additions:

 - Geometry from our tile servers would need to be re-projected from the "web mercator" projection into a 3d position on a sphere.
 - The view management code would need to be able to figure out which map tiles are visible in this re-projected space.
 - Polygons in the re-projected geometry would need to be triangulated with a fixed vertex density to accurately match the curvature of a globe.

And probably other things too. The core tangram-es team is working on other features that have higher priority right now, but we always appreciate pull requests :)

**Comment by lygstate** [comment]
Can this issue to be reopened?
