### ISSUE TITLE
Getting the httprequest using https://github.com/Microsoft/cpprestsdk

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#819]
This sdk contains the code handling HTTP Request for all platforms( Windows desktop, Windows Store, Windows Phone, Ubuntu, OS X, iOS, and Android).
So we have no need to depends curl and other things.

**Comment by tallytalwar** [comment]
Thanks for the suggestion. We will surely evaluate and try to use cpprestsdk library if it fits with our needs. Will keep this issue open for our evaluation.

**Comment by lygstate** [comment]
I found cpprestsdk depends on boost, that's really disappointed.

**Comment by tallytalwar** [comment]
Its a bummer that this depends on `boost`. Closing this for now, and reinvestigate when this library is updated to not use boost.
