### ISSUE TITLE
Investigate accessing iOS system fonts

### ISSUE THREAD

**Issue by msmollin** [tangrams/tangram-es#825]

**Comment by tallytalwar** [comment]
This is what I had found about this before:
http://stackoverflow.com/a/9381326
https://gist.github.com/Jyczeal/1892760

**Comment by karimnaaji** [comment]
The snippet of code that @tallytalwar mentioned can be used to decode the TTF file in memory on the iOS platform side, an interface to upload this data to the tangram font context is available on this branch https://github.com/tangrams/tangram-es/tree/ios-ttf-blob for testing purposes, in `tangram.h`:
```
void addTTFblob(char* _data, size_t _size, const char* _family, const char* _style, const char* _weight);
```
This API can be revised if this techniques of decoding TTF happens to be working on iOS.

cc @msmollin

**Comment by karimnaaji** [comment]
Closed via https://github.com/tangrams/tangram-es/pull/1092
