### ISSUE TITLE
iOS: buildings missing sides

### ISSUE THREAD

**Issue by mjcunningham** [tangrams/tangram-es#830]
Check out the UN there, you can see it's roof near the FDR label. 
I'm also on the iOS 10 beta.
![2016-07-13 11 55 35](https://cloud.githubusercontent.com/assets/307758/16810315/70453bd8-48f1-11e6-8314-fb20b7df33f3.png)

**Comment by blair1618** [comment]
Ah yeah I see. Does this demo app have any way of reporting logs?

**Comment by mjcunningham** [comment]
@msmollin  ^ ?

**Comment by msmollin** [comment]
They can be pulled from the console if you hook it up to xcode.

**Comment by mjcunningham** [comment]
This happens on iOS 9 and 10.

**Comment by blair1618** [comment]
This seems to be caused by image textures failing to load. Both building walls and icons use image textures and neither are visible here. Console sez:
```
Failed to read file at path: /var/containers/Bundle/Application/17B7FD54-90A1-4FDA-B055-49CD37F51603/ios-sdk.app/images/poi_icons_18@2x.png
ERROR sceneLoader.cpp:585: Can't load texture resource at url 'images/poi_icons_18@2x.png'
Failed to read file at path: /var/containers/Bundle/Application/17B7FD54-90A1-4FDA-B055-49CD37F51603/ios-sdk.app/images/building-grid.gif
ERROR sceneLoader.cpp:585: Can't load texture resource at url 'images/building-grid.gif'
Failed to read file at path: /var/containers/Bundle/Application/17B7FD54-90A1-4FDA-B055-49CD37F51603/ios-sdk.app/building-grid
ERROR sceneLoader.cpp:585: Can't load texture resource at url 'building-grid'
WARNING sceneLoader.cpp:1372: Can't load texture with name building-grid
WARNING sceneLoader.cpp:342: Style uniform parsing failure:
'building-grid'
```

**Comment by tallytalwar** [comment]
Are these being fetched with the style sheet? https://github.com/tangrams/bubble-wrap/tree/gh-pages/images

**Comment by blair1618** [comment]
I think it's something to do with how resources are being copied into the bundle. The images are in the bundle, but their relative paths aren't preserved.

**Comment by msmollin** [comment]
Ugh OK that's a build setting I need to set in the iOS SDK. I knew I had to do that for fonts, but didn't realize images needed specific paths too!

**Comment by blair1618** [comment]
Every file that constitutes the scene needs to keep its relative path to the scene file. I've confirmed that with the correct file-copy build phase the icons and building walls appear as expected. New issue in iOS repo to track this: https://github.com/mapzen/ios/issues/38
