### ISSUE TITLE
iOS Fonts not bundled in the the app

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#832]
From @Songcn on (https://github.com/tangrams/tangram-es/pull/649#issuecomment-232412297):

>@karimnaaji , I just cloned master branch to my desktop, then :
>1. make make-ios'
>2. open build/ios/tangram.xcodeproj
>3. Run 'tangram' on my iPad mini2
>
>all steps was done as README.
>The app can run but no text labels on the map, Xcode console says:
>
>issing font: error: 1 fonts/NotoSans-Regular.ttf
>Missing font: error: 1 fonts/NotoNaskh-Regular.ttf
>Missing font: error: 1 fonts/NotoSansHebrew-Regular.ttf
>Missing font: error: 1 fonts/DroidSansJapanese.ttf
>Missing font: error: 1 fonts/DroidSansFallback.ttf
>
>I guess the fonts are bundled in tangram app by default, right?
>So, was anything wrong during my steps? or any other work I need do? Thanks.

cc @msmollin

**Comment by karimnaaji** [comment]
I haven't seen this recently using latest version of tangram on iOS. Closing.

**Comment by Songcn** [comment]
Yes, the problem was gone in latest code. Thanks.
