### ISSUE TITLE
Support WOFF/WOFF2 font formats

### ISSUE THREAD

**Issue by bcamper** [tangrams/tangram-es#838]
The WOFF font format (and increasingly WOFF2, though it has less browser support) is the preferred method of loading custom fonts on the web, due to significantly smaller file sizes.

We should check to see if Tangram ES already supports WOFF, as there is some indication it is supported in newer versions of Freetype, and if it is not currently supported, we should add it.

Supporting WOFF will make it much more palatable to distribute scenes with custom fonts in a cross-platform-friendly way (especially once all resources can be zipped into a single file).

**Comment by karimnaaji** [comment]
It seems that WOFF is supported since version 2.5.1 (https://www.freetype.org/)

We use version Freetype 2.6.3 https://github.com/tangrams/harfbuzz-icu-freetype/tree/master/freetype-2.6 so it should be ok to support that format.

**Comment by bcamper** [comment]
Awesome - can you give it a try with this example from Google Fonts?

https://github.com/tangrams/tangram/blob/master/demos/scene.yaml#L43-L45

**Comment by karimnaaji** [comment]
Working out of the box:

<img width="912" alt="screen shot 2016-07-15 at 6 06 17 pm" src="https://cloud.githubusercontent.com/assets/7061573/16889769/dc6941bc-4ab6-11e6-89e7-409c733dcb7c.png">

We still need to support that `font` yaml block though.

**Comment by bcamper** [comment]
wooo!
