### ISSUE TITLE
Visibility of dynamic point features is inconsistent on Android

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#843]
https://gfycat.com/SourSadAndeancat

This produces no obviously relevant error output and can't be reproduced in the desktop demo.

**Comment by meetar** [comment]
> SourSadAndeancat

**Comment by tallytalwar** [comment]
Some more info here, it seems tiles are not updated for this client datasource, if you move to other zoom levels you start seeing these added points. Still debugging of whats the possible cause of this on "android" platform code specifically!
