### ISSUE TITLE
Crash while panning Eraser Map .11

### ISSUE THREAD

**Issue by mjcunningham** [tangrams/tangram-es#864]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/zerolteuc/zerolteatt:6.0.1/MMB29K/G925AUCS4CPG1:user/release-keys'
Revision: '10'
ABI: 'arm64'
pid: 17403, tid: 17448, name: Thread-25831  >>> com.mapzen.erasermap <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x616c75706f7014
    x0   74616c75706f7014  x1   0000007f6df05110  x2   0000000000000043  x3   00000000000000c5
    x4   45c6060606000000  x5   00000000ffffffff  x6   0000040000000000  x7   0000000000040000
    x8   74616c0a1d9f2104  x9   0000000000000044  x10  5f656b6f7274733a  x11  0000000000000015
    x12  0000000000000002  x13  303030302e323120  x14  33332e31202f2030  x15  00000000000000bb
    x16  0000007f88411af0  x17  0000007fa34a7240  x18  0000007f8b20a4a0  x19  0000007f86738c00
    x20  0000007f87c3ffb8  x21  0000007f8b1d4400  x22  0000007f87c3ffc8  x23  0000007f8b1d4418
    x24  0000007f866d1c88  x25  0000007f6df05110  x26  0000000000000044  x27  0000000000000051
    x28  0000007f866d1e98  x29  0000007f87c3fed0  x30  0000007f880f0770
    sp   0000007f87c3fe00  pc   0000007fa34a7304  pstate 0000000000000000

backtrace:
    #00 pc 000000000001c304  /system/lib64/libc.so (memcmp+196)
    #01 pc 000000000015e76c  /data/app/com.mapzen.erasermap-2/lib/arm64/libtangram.so (_ZN7Tangram16TextStyleBuilder12prepareLabelERNS_9TextStyle10ParametersENS_5Label4TypeE+620)
    #02 pc 000000000015d5c4  /data/app/com.mapzen.erasermap-2/lib/arm64/libtangram.so (_ZN7Tangram16TextStyleBuilder16addFeatureCommonERKNS_7FeatureERKNS_8DrawRuleEb+132)
    #03 pc 000000000019ab18  /data/app/com.mapzen.erasermap-2/lib/arm64/libtangram.so (_ZN7Tangram16DrawRuleMergeSet5applyERKNS_7FeatureERKNS_10SceneLayerERNS_12StyleContextERNS_11TileBuilderE+2232)
    #04 pc 00000000001642a8  /data/app/com.mapzen.erasermap-2/lib/arm64/libtangram.so (_ZN7Tangram11TileBuilder5buildENS_6TileIDERKNS_8TileDataERKNS_10DataSourceE+688)
    #05 pc 00000000000ee0e8  /data/app/com.mapzen.erasermap-2/lib/arm64/libtangram.so (_ZN7Tangram8TileTask7processERNS_11TileBuilderE+84)
    #06 pc 00000000000ee9f4  /data/app/com.mapzen.erasermap-2/lib/arm64/libtangram.so (_ZN7Tangram10TileWorker3runEPNS0_6WorkerE+1172)
    #07 pc 00000000000ef3f4  /data/app/com.mapzen.erasermap-2/lib/arm64/libtangram.so (_ZNSt3__114__thread_proxyINS_5tupleIJMN7Tangram10TileWorkerEFvPNS3_6WorkerEEPS3_S5_EEEEEPvSA_+124)
    #08 pc 0000000000065f20  /system/lib64/libc.so (_ZL15__pthread_startPv+52)
    #09 pc 000000000001edec  /system/lib64/libc.so (__start_thread+16)

**Comment by blair1618** [comment]
Thanks - since the current hypothesis is a single underlying bug for these crashes I'm gonna file them under a single issue, #867, until we know more.
