### ISSUE TITLE
Crash on routing start Eraser Map .11

### ISSUE THREAD

**Issue by mjcunningham** [tangrams/tangram-es#865]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/zerolteuc/zerolteatt:6.0.1/MMB29K/G925AUCS4CPG1:user/release-keys'
Revision: '10'
ABI: 'arm64'
pid: 15694, tid: 15757, name: mali-renderer  >>> com.mapzen.erasermap <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x51
    x0   0000007f8ad46398  x1   0000007f718ba080  x2   0000000000000051  x3   0000000000000051
    x4   0000007f8ad46350  x5   0000000000000013  x6   0000000000000003  x7   0000000000008000
    x8   0000000000008000  x9   0000007f49e7fe00  x10  0000007f718ba408  x11  0000007f8ad46350
    x12  0000007f72e87f00  x13  0000007f79cc20e8  x14  0000000000000001  x15  0000000000000000
    x16  0000007f8ace0b60  x17  0000007fa34f1f74  x18  0000007f799cc650  x19  0000007f4bd600f8
    x20  0000000000000000  x21  0000007f71e26f00  x22  0000007f718ba0c8  x23  0000007f8ad46320
    x24  0000007f8ad422a0  x25  0000007f718ba048  x26  0000007f8ad422a0  x27  0000007f79cc2078
    x28  0000007f98e42958  x29  0000007f8927f410  x30  0000007f897f0864
    sp   0000007f8927f120  pc   0000007f8998a54c  pstate 0000000060000000

backtrace:
    #00 pc 00000000005d654c  /system/vendor/lib64/egl/libGLES_mali.so
    #01 pc 000000000043c860  /system/vendor/lib64/egl/libGLES_mali.so
    #02 pc 0000000000438d18  /system/vendor/lib64/egl/libGLES_mali.so
    #03 pc 0000000000438ca0  /system/vendor/lib64/egl/libGLES_mali.so
    #04 pc 000000000043912c  /system/vendor/lib64/egl/libGLES_mali.so
    #05 pc 000000000042da18  /system/vendor/lib64/egl/libGLES_mali.so
    #06 pc 000000000042d828  /system/vendor/lib64/egl/libGLES_mali.so
    #07 pc 0000000000435eb0  /system/vendor/lib64/egl/libGLES_mali.so
    #08 pc 00000000004361bc  /system/vendor/lib64/egl/libGLES_mali.so
    #09 pc 0000000000438018  /system/vendor/lib64/egl/libGLES_mali.so
    #10 pc 00000000004383a0  /system/vendor/lib64/egl/libGLES_mali.so
    #11 pc 0000000000065f20  /system/lib64/libc.so (_ZL15__pthread_startPv+52)
    #12 pc 000000000001edec  /system/lib64/libc.so (__start_thread+16)

**Comment by blair1618** [comment]
Thanks - since the current hypothesis is a single underlying bug for these crashes I'm gonna file them under a single issue, #867, until we know more.
