### ISSUE TITLE
Label offsets not working on bubble wrap style

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#875]
Possibly a parsing issue from the style bubble-wrap. 

Offsets works on fine on walkabout:
<img width="912" alt="screen shot 2016-07-27 at 2 44 21 pm" src="https://cloud.githubusercontent.com/assets/7061573/17187825/c5c1e10c-5408-11e6-8a07-baf09837858d.png">

With debug mode `draw_all_labels`, we can see that offsets are not applied for city spots:

<img width="912" alt="screen shot 2016-07-27 at 2 45 05 pm" src="https://cloud.githubusercontent.com/assets/7061573/17187826/c67ff750-5408-11e6-99c5-d1d5e5088e92.png">

cc @hjanetzek

**Comment by nvkelso** [comment]
I noticed the same thing over the weekend in the alpha build of Eraser Map. Some labels show up, some don't.

**Comment by nvkelso** [comment]
(If it turns out to be a Bubble Wrap error, please file a bug there.)

**Comment by karimnaaji** [comment]
Yeah it's unclear yet where the error is coming from, we will investigate that more and if it turns out to be a style issue would open a bug there.
