### ISSUE TITLE
RPI fails at execution 

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-es#882]
<img width="655" alt="screen shot 2016-07-28 at 10 10 41 am" src="https://cloud.githubusercontent.com/assets/346914/17215663/a96f2638-54ab-11e6-828a-2e01f7aa9a13.png">

**Comment by blair1618** [comment]
This is on the master branch of tangram-es? If this started happening recently, can you tell the commits before and after this started?

**Comment by patriciogonzalezvivo** [comment]
yes was master. Sorry I can't tell when did start... I have not been compiling/using tangram-es in the RPI for 2~3 weeks I think

**Comment by tallytalwar** [comment]
@patriciogonzalezvivo still having this issue?

**Comment by patriciogonzalezvivo** [comment]
mmmm... right know is failing in linking : /

**Comment by karimnaaji** [comment]
What is the status on that issue? Is it still a link or runtime issue?

**Comment by blair1618** [comment]
This issue is probably outdated. If you encounter a similar problem please file a new issue!
