### ISSUE TITLE
Invalid layer filter can cause an 'assert' to fail

### ISSUE THREAD

**Issue by blair1618** [tangrams/tangram-es#888]
This assert seems to be triggered if a valid filter can't be parsed from the YAML: https://github.com/tangrams/tangram-es/blob/master/core/src/scene/filters.cpp#L125

Malformed YAML is inevitable in the development process and should never cause a hard termination like this.

**Comment by hjanetzek** [comment]
No problem with removing that assert, though we should also drop 'none' filters early.

**Comment by lygstate** [comment]
we should  LOGW instead

**Comment by hjanetzek** [comment]
resolved
