### ISSUE TITLE
raster source

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#899]
I try to create maps from raster source in my android app. I took exampe of scene.yaml from mapzen documentation.
'sources:
  terrain-normals:
        type: Raster
        url: https://terrain-preview.mapzen.com/normal/{z}/{x}/{y}.png
    mapzen-osm:
        type: TopoJSON
        url: https://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson
        rasters: [terrain-normals]

styles:
    normals:
        base: polygons
        raster: normal

lights:
    point1:
        type: point

layers:
    earth:
        data: { source: mapzen-osm }
        draw:
            normals:
                color: white
                order: 0'

**Comment by blair1618** [comment]
Hello!

The example here is for adding shaded elevation contours to illustrate terrain. Here's a simpler example of a map using Stamen raster tiles and Mapzen vector tiles together (loaded in Tangram Play so you can try it out in your browser):
https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fgist.githubusercontent.com%2Fanonymous%2Fce6b54412171d05881fb302e0b85a15a%2Fraw%2F8fa9b675b9b459f6d6fa0ca0a233cf773c2e5ffa%2Fscene.yaml#15.2416/40.7097/-74.0125

Is there a specific effect you are trying to achieve with raster tiles?

**Comment by ivangorelow** [comment]
I have to use my owm tile server. Here I have only png.

**Comment by ivangorelow** [comment]
Now I try use scene file from your example, and i have only dark screen

**Comment by ivangorelow** [comment]
I have download simple example and here I have yhe same problem

**Comment by ivangorelow** [comment]
I want to use this tiles (a.tile.openstreetmap.org/0/0/0.png) on android device and nothing more

**Comment by ivangorelow** [comment]
sources:
    terrain-normals:
        type: Raster
        url: https://terrain-preview.mapzen.com/normal/{z}/{x}/{y}.png
    mapzen-osm:
        type: TopoJSON
        url: https://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson
        rasters: [terrain-normals]
    basemap:
        type: Raster
        #url: http://a.tile.stamen.com/terrain-background/{z}/{x}/{y}.jpg
        url: http://a.tile.openstreetmap.org/{z}/{x}/{y}.png
        rasters: [terrain-normals]

styles:
    normals:
        base: polygons
        raster: custom
        shaders:
            blocks:
                color: |
                    color = sampleRaster(0); // color from first raster (basemap)
                normal: |
                    normal = normalize(sampleRaster(1).xyz * 2. - 1.); // normal from second raster (normal tiles)
lights:
    # point1:
    #     type: point
    #     position: [0, 0, 200px]
    #     origin: ground
    light2: { type: directional, direction: [1, 1, -.9], diffuse: 0.8, ambient: 0.3 }

layers:
    earth:
        data: { source: basemap }
        draw:
            normals:
                color: white
                order: 0


it's a good scene file for me. What assets files should I include to my android project to run it

**Comment by blair1618** [comment]
Glad you've got a scene file that does what you need! To use this on Android you just need to include the YAML scene file in your application's assets and use its path when you call `getMapAsync()`. That is, if your scene file is at "assets/scene/scene.yaml" then you would load your map by calling `mapView.getMapAsync(onMapReadyCallback, "scene/scene.yaml")`.
