### ISSUE TITLE
Raster worning

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#902]
while making an android app. I found warning and problem whith raster sources(I have only screen)

this is a log `08-05 13:01:07.678 5424-5444/? D/Tangram: WARNING sceneLoader.cpp:731: Unrecognized data source type 'Raster', skipping`

**Comment by tallytalwar** [comment]
Hey

What version of tangram android release you are working with?
Also can you share the scene file you are using?
Thanks
