### ISSUE TITLE
Compile Error on Raspberry PI from Master

### ISSUE THREAD

**Issue by mgarcia01752** [tangrams/tangram-es#916]
Updated from Master using new toolchain

```
sudo apt-get install clang-3.5 cmake libcurl4-openssl-dev
export CXX=/usr/bin/clang++-3.5
git clone https://github.com/tangrams/tangram-es.git
cd tangram-es
git submodule init && git submodule update
git submodule update --init --recursive
make rpi
```

In file included from /usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/bits/move.h:57:
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:112:26: fatal error: recursive template instantiation exceeded maximum depth of 256
    : public conditional<_B1::value, _B1, _B2>::type
                         ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:117:14: note: in instantiation of template class
      'std::__or_<std::is_reference<Tangram::UniformTextureArray &>, std::is_void<Tangram::UniformTextureArray &> >' requested here
    : public conditional<_B1::value, _B1, __or_<_B2, _B3, _Bn...>>::type
             ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:145:39: note: in instantiation of template class
      'std::__or_<std::is_function<Tangram::UniformTextureArray &>, std::is_reference<Tangram::UniformTextureArray &>, std::is_void<Tangram::UniformTextureArray &> >'
      requested here
    : public integral_constant<bool, !_Pp::value>
                                      ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:533:14: note: in instantiation of template class
      'std::__not_<std::__or_<std::is_function<Tangram::UniformTextureArray &>, std::is_reference<Tangram::UniformTextureArray &>,
      std::is_void<Tangram::UniformTextureArray &> > >' requested here
    : public __not_<__or_<is_function<_Tp>, is_reference<_Tp>,
             ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:112:26: note: in instantiation of template class
      'std::is_object<Tangram::UniformTextureArray &>' requested here
    : public conditional<_B1::value, _B1, _B2>::type
                         ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:570:14: note: in instantiation of template class
      'std::__or_<std::is_object<Tangram::UniformTextureArray &>, std::is_reference<Tangram::UniformTextureArray &> >' requested here
    : public __or_<is_object<_Tp>, is_reference<_Tp>>::type
             ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:1525:33: note: (skipping 247 contexts in backtrace; use -ftemplate-backtrace-limit=0 to
      see all)
  template<typename _Tp, bool = __is_referenceable<_Tp>::value>
                                ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/bits/alloc_traits.h:399:4: note: in instantiation of function template specialization
      'std::allocator_traits<std::allocator<std::pair<int, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>,
      glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >,
      std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >,
      Tangram::UniformTextureArray> > > >::_S_construct<std::pair<int, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int,
      glm::tvec2<float, 0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float,
      std::allocator<float> >, std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>,
      std::allocator<glm::tvec3<float, 0> > >, Tangram::UniformTextureArray> >, const int &, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>,
      float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>,
      std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>,
      std::allocator<glm::tvec3<float, 0> > >, Tangram::UniformTextureArray> >' requested here
        { _S_construct(__a, __p, std::forward<_Args>(__args)...); }
          ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/bits/vector.tcc:308:21: note: in instantiation of function template specialization
      'std::allocator_traits<std::allocator<std::pair<int, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>,
      glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >,
      std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >,
      Tangram::UniformTextureArray> > > >::construct<std::pair<int, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float,
      0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >,
      std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >,
      Tangram::UniformTextureArray> >, const int &, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>,
      glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >,
      std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >,
      Tangram::UniformTextureArray> >' requested here
            _Alloc_traits::construct(this->_M_impl, this->_M_impl._M_finish,
                           ^
/home/pi/weg/tangram-es/core/src/util/fastmap.h:27:30: note: in instantiation of function template specialization 'std::vector<std::pair<int,
      mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>,
      glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>,
      std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >, Tangram::UniformTextureArray> >,
      std::allocator<std::pair<int, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>,
      glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >,
      std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >,
      Tangram::UniformTextureArray> > > >::emplace<const int &, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>,
      glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >,
      std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >,
      Tangram::UniformTextureArray> >' requested here
            auto entry = map.emplace(it, key, T{});
                             ^
/home/pi/weg/tangram-es/core/src/gl/shaderProgram.h:109:33: note: in instantiation of member function 'Tangram::fastmap<int, mapbox::util::variant<Tangram::none_type,
      bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>,
      glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >,
      std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >, Tangram::UniformTextureArray> >::operator[]' requested here
        auto& v = m_uniformCache[_location];
                                ^
/home/pi/weg/tangram-es/core/src/gl/shaderProgram.cpp:370:23: note: in instantiation of function template specialization 'Tangram::ShaderProgram::getFromCache<int>'
      requested here
        bool cached = getFromCache(location, _value);
                      ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:112:26: note: use -ftemplate-depth=N to increase recursive template instantiation depth
    : public conditional<_B1::value, _B1, _B2>::type
                         ^
1 error generated.
core/CMakeFiles/core.dir/build.make:560: recipe for target 'core/CMakeFiles/core.dir/src/gl/shaderProgram.cpp.o' failed
make[3]: *** [core/CMakeFiles/core.dir/src/gl/shaderProgram.cpp.o] Error 1
make[3]: Leaving directory '/home/pi/weg/tangram-es/build/rpi'
CMakeFiles/Makefile2:810: recipe for target 'core/CMakeFiles/core.dir/all' failed
make[2]: *** [core/CMakeFiles/core.dir/all] Error 2
make[2]: Leaving directory '/home/pi/weg/tangram-es/build/rpi'
Makefile:137: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/weg/tangram-es/build/rpi'
Makefile:256: recipe for target 'rpi' failed
make: *** [rpi] Error 2

**Comment by blair1618** [comment]
Whoa, interesting! Can you tell me which version of the Pi and which OS you're using? I believe I've built this successfully on a Pi 2 with Clang 3.5 but I'll check again.

**Comment by blair1618** [comment]
Ah ok I've reproduced this now. This must be due to something that's changed since the recommended compiler was updated. I have a hunch it might be the "variant" submodule (https://github.com/tangrams/tangram-es/commit/4f211b07070d63957f488c80a0a944fa30e2b4c3) but I'll check.

**Comment by blair1618** [comment]
Indeed, if I revert the variant submodule update then compilation succeeds as before. It must be that the combination of GLM template types and Variant template types results in a disastrous amount of template instantiation. Hence: `fatal error: recursive template instantiation exceeded maximum depth of 256`

We _do_ want to use the newer version of Variant, so reverting the update is not a true fix. GCC may actually handle this situation better, the issue with that is just that tangram-es uses C++ features that aren't supported by GCC until version 5 and there's no easy way to install GCC 5 on a raspberry pi (which is why we switched to recommending clang). Options to proceed:

1. Find a way to use GCC 5 on the Pi and try compiling with that instead of Clang

2. Revise tangram-es such that GCC 4.9 is able to compile it again

**Comment by tallytalwar** [comment]
K, we added some workaround in tangram to make it compatible with GCC 4.9. Can you give this (tangram master) a try on your rpi, using gcc 4.9?

**Comment by mgarcia01752** [comment]
Will do, also I am using PI-3

**Comment by mgarcia01752** [comment]
Same issue, I removed the directory and reinstall

```
sudo apt-get install clang-3.5 cmake libcurl4-openssl-dev
export CXX=/usr/bin/clang++-3.5
git clone https://github.com/tangrams/tangram-es.git
cd tangram-es
git submodule init && git submodule update
git submodule update --init --recursive
make rpi
```

[ 83%] Building CXX object core/CMakeFiles/core.dir/src/gl/shaderProgram.cpp.o
In file included from /home/pi/weg/tangram-es/core/src/gl/shaderProgram.cpp:1:
In file included from /home/pi/weg/tangram-es/core/src/gl/shaderProgram.h:4:
In file included from /home/pi/weg/tangram-es/core/src/gl/disposer.h:3:
In file included from /usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/functional:49:
In file included from /usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/bits/stl_function.h:60:
In file included from /usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/bits/move.h:57:
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:112:26: fatal error: recursive template instantiation exceeded maximum depth of 256
    : public conditional<_B1::value, _B1, _B2>::type
                         ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:117:14: note: in instantiation of template class 'std::__or_<std::is_reference<Tangram::UniformTextureArray &>,
      std::is_void<Tangram::UniformTextureArray &> >' requested here
    : public conditional<_B1::value, _B1, __or_<_B2, _B3, _Bn...>>::type
             ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:145:39: note: in instantiation of template class 'std::__or_<std::is_function<Tangram::UniformTextureArray &>,
      std::is_reference<Tangram::UniformTextureArray &>, std::is_void<Tangram::UniformTextureArray &> >' requested here
    : public integral_constant<bool, !_Pp::value>
                                      ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:533:14: note: in instantiation of template class
      'std::__not_<std::__or_<std::is_function<Tangram::UniformTextureArray &>, std::is_reference<Tangram::UniformTextureArray &>, std::is_void<Tangram::UniformTextureArray &> > >' requested here
    : public __not_<__or_<is_function<_Tp>, is_reference<_Tp>,
             ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:112:26: note: in instantiation of template class 'std::is_object<Tangram::UniformTextureArray &>' requested here
    : public conditional<_B1::value, _B1, _B2>::type
                         ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:570:14: note: in instantiation of template class 'std::__or_<std::is_object<Tangram::UniformTextureArray &>,
      std::is_reference<Tangram::UniformTextureArray &> >' requested here
    : public __or_<is_object<_Tp>, is_reference<_Tp>>::type
             ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:1525:33: note: (skipping 247 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
  template<typename _Tp, bool = __is_referenceable<_Tp>::value>
                                ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/bits/alloc_traits.h:399:4: note: in instantiation of function template specialization
      'std::allocator_traits<std::allocator<std::pair<int, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>,
      glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>,
      std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >, Tangram::UniformTextureArray> > > >::_S_construct<std::pair<int,
      mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>,
      glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >,
      std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >, Tangram::UniformTextureArray> >, const int &, mapbox::util::variant<Tangram::none_type, bool,
      std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>,
      std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> >
      >, Tangram::UniformTextureArray> >' requested here
        { _S_construct(__a, __p, std::forward<_Args>(__args)...); }
          ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/bits/vector.tcc:308:21: note: in instantiation of function template specialization
      'std::allocator_traits<std::allocator<std::pair<int, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>,
      glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>,
      std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >, Tangram::UniformTextureArray> > > >::construct<std::pair<int,
      mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>,
      glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >,
      std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >, Tangram::UniformTextureArray> >, const int &, mapbox::util::variant<Tangram::none_type, bool,
      std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>,
      std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> >
      >, Tangram::UniformTextureArray> >' requested here
            _Alloc_traits::construct(this->_M_impl, this->_M_impl._M_finish,
                           ^
/home/pi/weg/tangram-es/core/src/util/fastmap.h:27:30: note: in instantiation of function template specialization 'std::vector<std::pair<int, mapbox::util::variant<Tangram::none_type, bool,
      std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>,
      std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> >
      >, Tangram::UniformTextureArray> >, std::allocator<std::pair<int, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float,
      0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>,
      std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >, Tangram::UniformTextureArray> > > >::emplace<const int &,
      mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>, float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>,
      glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float> >, std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >,
      std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >, Tangram::UniformTextureArray> >' requested here
            auto entry = map.emplace(it, key, T{});
                             ^
/home/pi/weg/tangram-es/core/src/gl/shaderProgram.h:109:33: note: in instantiation of member function 'Tangram::fastmap<int, mapbox::util::variant<Tangram::none_type, bool, std::basic_string<char>,
      float, int, glm::tvec2<float, 0>, glm::tvec3<float, 0>, glm::tvec4<float, 0>, glm::tmat2x2<float, 0>, glm::tmat3x3<float, 0>, glm::tmat4x4<float, 0>, std::vector<float, std::allocator<float>
      >, std::vector<glm::tvec2<float, 0>, std::allocator<glm::tvec2<float, 0> > >, std::vector<glm::tvec3<float, 0>, std::allocator<glm::tvec3<float, 0> > >, Tangram::UniformTextureArray>
      >::operator[]' requested here
        auto& v = m_uniformCache[_location];
                                ^
/home/pi/weg/tangram-es/core/src/gl/shaderProgram.cpp:370:23: note: in instantiation of function template specialization 'Tangram::ShaderProgram::getFromCache<int>' requested here
        bool cached = getFromCache(location, _value);
                      ^
/usr/bin/../lib/gcc/arm-linux-gnueabihf/4.9/../../../../include/c++/4.9/type_traits:112:26: note: use -ftemplate-depth=N to increase recursive template instantiation depth
    : public conditional<_B1::value, _B1, _B2>::type
                         ^
1 error generated.
core/CMakeFiles/core.dir/build.make:560: recipe for target 'core/CMakeFiles/core.dir/src/gl/shaderProgram.cpp.o' failed
make[3]: *** [core/CMakeFiles/core.dir/src/gl/shaderProgram.cpp.o] Error 1
make[3]: Leaving directory '/home/pi/weg/tangram-es/build/rpi'
CMakeFiles/Makefile2:810: recipe for target 'core/CMakeFiles/core.dir/all' failed
make[2]: *** [core/CMakeFiles/core.dir/all] Error 2
make[2]: Leaving directory '/home/pi/weg/tangram-es/build/rpi'
Makefile:137: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/pi/weg/tangram-es/build/rpi'
Makefile:256: recipe for target 'rpi' failed
make: *** [rpi] Error 2

**Comment by blair1618** [comment]
Oh right, you'll want to choose g++-4.9 instead of clang-3.5 as your compiler now, i.e. `export CXX=/usr/bin/g++-4.9`

If it builds successfully we'll update the README instructions to that effect.

**Comment by mgarcia01752** [comment]
Working!!!  Thanks!!! Great Product!!!

**Comment by tallytalwar** [comment]
Great. Thanks for testing the fixes.
