### ISSUE TITLE
layer

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#922]
in some zoom level I lost my Layer (show in java code with Mapdata)

`sdk-point-overlay-green:
            base: points
            texture: pois2
            interactive: true
            blend: overlay
            blend_order: 1001`

`marker_cam_on:
             data: { source: marker_cam_on }
             draw:
                 sdk-point-overlay-green:
                     interactive: true
                     sprite: segment-green
                     size: [24px,24px]
                     collide: false
                     anchor: top
                     transition:
                                         [show, hide]:
                                             time: 0s`

P.s. Do you know how I can show zoom level?

**Comment by blair1618** [comment]
Can you add a little more description about the issue? I'm not sure what you mean by "lost my Layer". It would also help a lot if you would format the YAML examples to show whitespace accurately (spacing matters in YAML). 

To show zoom level and other information on screen for debugging purposes, you can set the `TANGRAM_INFOS` debug flag with `MapController$setDebugFlag` (assuming you are using tangram-es on Android).

**Comment by blair1618** [comment]
If you continue to have difficulties, feel free to contact our team on Gitter (https://gitter.im/tangrams/tangram-chat) or open a new issue with a detailed description of the problem.
