### ISSUE TITLE
FontContext segfaults if no fonts can be found

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-es#927]
<img width="1426" alt="screen shot 2016-08-23 at 3 33 12 pm" src="https://cloud.githubusercontent.com/assets/346914/17907067/04690ca6-6948-11e6-8d2f-2c066f4fc6d2.png">

**Comment by tallytalwar** [comment]
Just to have more info here, @patriciogonzalezvivo's Paparazzi demo was not including `fonts` directory in and hence fonts files were not available to be added.
But in `FontContext::getFonts` function we assume default fonts are present and query against these, which is when a segfault happens above.
