### ISSUE TITLE
Offline data storage

### ISSUE THREAD

**Issue by matteblair** [tangrams/tangram-es#931]
_This is a general thread to discuss adding offline storage for map data in tangram-es._

**Motivations**

A mapping engine may be tasked with functioning offline in many ways for many reasons:
- A person is using it on a subway with no network signal
- A person is using it in a remote region of the world with no internet access
- A person has internet access, but wants to avoid using bandwidth for reasons of cost or time
- A person needs to view a set of data that cannot be hosted online for security reasons

_Et cetera._

**Current status**

At present, tangram-es must have network access to retrieve data for new tiles whenever the map view changes. Aside from the currently visible tiles, only a small cache of data is kept in memory within the engine (roughly one screen's worth of data). In the Android and iOS tangram SDKs, the networking layers are able to cache some HTTP requests, but depending on the expiration policy in request headers the networking layer may not be permitted to re-use a response after a certain time (or at all). Some tangram users on Android have found ways to store network data indefinitely with OkHTTP, but the process is cumbersome and platform-specific (https://github.com/tangrams/tangram-es/issues/623). 

**Possible goals**

There are many ways think about solving this problem. 
1. _Allow client applications to provide offline storage._ Instead of tangram-es itself storing data for offline use, the library could instead enable client applications to access and redirect all of the network requests it makes, leaving any storage logic up to the client. This allows the most flexibility for application developers, but also requires substantial work from them. 
2. _Provide offline storage in the platform SDKs._ The tangram SDK for each supported platform could implement its own approach to offline storage, using APIs appropriate to that platform. This allows client applications to more easily interact with the caching logic, but also introduces potential divergence in behavior across platforms.
3. _Provide offline storage in the core C++ library._ The cross-platform core of tangram-es could implement offline storage using a platform-agnostic C++ solution. This would ensure consistent behavior across platforms and may provide better performance than the other options, but would also provide the least flexibility to application developers.

**Comment by bcamper** [comment]
We also want to think about how to best support pre-rendered *tile bundles* for offline use, either shipped with an app as a resource, or downloaded at run-time (see apps like Offmaps as an example, where in-app purchase is used to download new tile bundles). We should look at common bundle formats such as MBTiles, as well as more bare-metal approaches like a simple archive of tile files (that could respect a tile URL pattern, with a `file://` protocol or other local access mechanism).

cc @nvkelso

**Comment by hallahan** [comment]
FWIW, Mapbox ditched their MBTiles spec for offline tiles in MapboxGL. Totally [different schema](https://github.com/mapbox/mapbox-gl-native/tree/c034ba4ee16b1a8fc4ff92b4672671f636dadaab/test/fixtures/offline_database) now. However, they are continuing to use SQLite as the container. A big advantage is that it's easy to see what's inside of a SQLite db. Also, I've got [SQLiteCpp CMake build](https://github.com/hallahan/tangram-es/commit/6da7f0d5906b7e51a01a6ab5c5a4e9b305b00136) working in Tangram ES.

[Maps.me](https://github.com/mapsme/omim) has their own undocumented binary format. Not using the vector tile approach... Still, in my opinion, they do an absolutely fantastic job with offline OSM maps. Probably the best out there right now.

[OsmAnd](http://osmand.net/) also has their own binary format. They actually have their own map styling software that creates their map data.

A huge list of toolkits have used MBTiles for raster tiles, however, MBTiles is based on a clever trick: they SHA1 the contents of a PNG and use that to join tables between z/x/y and the image itself. As a result, giant waterbodies do not have duplicate tiles. This isn't really advantageous for vector data. MBTiles are great, but they easily get very large.

It might be a good idea to dive deep into the solutions currently out there and evaluate the pros and cons?

While working on [direct OSM support](https://github.com/tangrams/tangram-es/issues/877), I'm chewing over the idea of having a SQLite DB that has a similar schema to the [OSM API](http://wiki.openstreetmap.org/wiki/API_v0.6). This makes sense for editing, at the high zooms. At low zooms, however, I think caching vector tiles in SQLite makes sense. 

Lastly, in regards to working with systems like [POSM](http://theoutpost.io/posm/), it makes a lot of sense having an external system create our SQLite cache db of data for us. There have been lots of apps out there that do a fantastic job (like [GaiaGPS](https://www.gaiagps.com/)) downloading tiles , but it takes a long time requesting individual tiles, one-by-one, over HTTP. Having a source server prepare our cache for us and send that as one file would be much faster.

Along the idea of Metro Extracts, I could see SQLite vector tile downloads be a very useful service that Mapzen could host?

**Comment by bcamper** [comment]
Yep - the last point - having Mapzen generate tile bundles as part of Metro Extracts, is definitely the plan, so we will want to choose something friendly to that :)

**Comment by hallahan** [comment]
Oh man, that is going to be so cool!!!

**Comment by hallahan** [comment]
Perhaps one thing that should be built into a Mapzen tile bundle is having a set of scene files and related fonts and glyphs included as well? Maybe a simple, clear specification document should describe this?

**Comment by ac87** [comment]
The thing that brought me to Tangram was being steered towards [http://osm2vectortiles.org/](http://osm2vectortiles.org/) which bundle tiles into the MBTiles format. As @Hallahan said MapBox dropped it and their map component has no obvious way of using it anymore, and I found it much easier to make Tangram load the tiles (via a localhost webserver that actually read the file).

The biggest issue with a single database format is if you want to cache something bigger than 4GB you fall over as soon as it's copied to a FAT32 SD card (learned this the hard way a number of years ago with raster tiles and Android). 

To throw another thing out there we had to add support to our desktop GIS for [ESRI Compact Cache](https://blogs.esri.com/esri/arcgis/2010/05/27/introducing-the-compact-cache-storage-format/)  [(great blog post on reverse engineering them)](https://gdbgeek.wordpress.com/2012/08/09/demystifying-the-esri-compact-cache/) there is not one big file but several large files, the real undocumented advantage of this approach is you can add tiles to the .bundle files without any of them risking going over the 4GB limit. Of course this is for raster, how you could calculate a reasonable grid size for vector I don't know.

**Comment by hallahan** [comment]
@ac87 - One example to look at is [maps.me](https://github.com/mapsme/omim). They have cut up the globe into regions (not sure how they came up with the bounds of their data sets). As you are zoomed out, you have a low zoom data set. As you zoom in more, it asks you if you'd like to download data for that given region. I think this approach makes sense, especially since one would rarely want all of the world on their device taking up many GB of space anyway.

![2016-08-31 19 03 05](https://cloud.githubusercontent.com/assets/556367/18142554/03af12d4-6f73-11e6-8ba6-b43d5eee99a9.png)

![2016-08-31 19 03 22](https://cloud.githubusercontent.com/assets/556367/18142560/08bcb560-6f73-11e6-8b79-107e2cfa67c3.png)

**Comment by hallahan** [comment]
Taking a deeper look at http://osm2vectortiles.org/ , maybe we should simply add MBTiles support where we can just read MVT from the MBTiles produced at osm2vectortiles? Since there is already an ecosystem of people using MBTiles packed with MVT, Tangram ES support would likely gain very quick adoption.

**Comment by ac87** [comment]
There was another issue I ran into with osm2vectortiles. The layers only go as far as z14, with that containing the data you'd expect in z14+. Whilst it doesn't seem like a major problem it caused me more pain. Whilst Tangram nicely scales the previous zoom levels data if it can't load any, it (sensibly) doesn't reapply the filtering, so where in my case I had train stations POIs with a minzoom of 15, they and many other things never appeared.

At least this is what I put the issue down to, the solution for me was to create tiles on the fly for the new zoom level (15-18) and re-serve them to Tangram.

**Comment by bcamper** [comment]
@ac87 you should be able to specify filters and styling rules for any zoom level, even one higher than the source's `max_zoom`. So even if we stop loading tiles at z14, Tangram *will* re-build/re-evaluate styling at zooms z15, z16, etc. You can use this to show a subset of features at z14, and add more detail as you zoom in. We do this with Mapzen's vector tiles as well, which contain all features at z16 (we still serve higher-zoom tiles for rendering clients that don't support overzooming, but the best practice is to limit the loading at z16).

**Comment by ac87** [comment]
@bcamper I guess I assumed wrong then, I didn't even see max_zoom on sources, should have read more and copy/pasted less! Thanks.

**Comment by nicklasaven** [comment]
FWIW to get a lot of ideas on the table. I have been thinking quite a lot about offline mapping. 

A short description about where I am:
I prepare the offline data in PostGIS. encode it as twkb. Also preparing all triangels for openGL. 

The result of the preparations is stored in a sqlite database. 

For lines and points the geometry is stored as twkb blobs, with id and other information wanted. For polygons the geometry is stored as a usual twkb-polygon. But there is also another twkb in another field. In that twkb I have encoded a linestring. each point in the linestring has x, y and z value. Those values points into the twkb-polygon and makes up the triangels. 

In the sqlite database is also a spatial index created by the bounding boxes from the original geometries in the PostGIS database (I have written an extension for writing the sqlite base from PostGIS).

So, from this preparation the client can quite efficient decode the twkb directly into arrays that openGL es can render. also the triangels is just "loaded" into arrays. Transformation from "real world" coordinates to pixel coordinates is done at render time in the shader. Works quite well actually. 

I have written some about it here:
http://jordogskog.no/gis/

and there is some code here:
https://github.com/nicklasaven/noTile

and a sqlite db with whole Norway 1:50000 and apk for Android here:
http://twkb.jordogskog.no/maps/

But everything is still very unpolished. 

Major things I haven't solved is:
labeling - text seems challenging  in opengl even if I use sdl2. 
line width - now it is only 1 pixel wide lines in android. In desktop version linewidth seems to work better.

I don't know openGL so thre is a lot of things that can be done better. But the main idea is just to encode single geometries separately in sqlite. And to pregenerate the triangels. This way the client and framwork will not be in the way for proper data modelling. That is compared to formats that more or less force you to a 1:1 relation between geometry and attributes.

**Comment by nvkelso** [comment]
Is the data all at single "max zoom", or is some marked as valid only for a specified zoom range?

**Comment by nicklasaven** [comment]
I have 2 zoom levels in the Norwegian database in the link. it is the Norwegian official map for 1:50000 and the official Norwegian map for 1:1000000. When the differnt layers is showed is controlled by a parameter in the layers table in the project database. The number for max and min zoom id in map units per pixel. In my case it is in UTM 33 srid 32633 so the map unit is in meters

**Comment by matteblair** [comment]
Closing this issue to clean up the backlog a little - but wow lots of great discussion, thanks again all :)

Tangram ES now supports loading vector tiles from MBTiles sources and the Android and iOS SDKs both allow client applications to customize the behavior of network requests, so I think we've made good progress on this.
