### ISSUE TITLE
Scene Not loaded properly in Raspberry Pi 3b

### ISSUE THREAD

**Issue by banagale** [tangrams/tangram-es#932]
Following readme instructions, including setting up gcc 4.9 we found this will build. 

However, it does not load the default scene correctly. Instead of showing Manhattan, it shows a zoomed out world map.

You can zoom and pan, however sometimes the q key does not respond and there is no way to exit the running application. It seems to not see fonts, although they are in the project.

We have a scene that runs fine on tangram-es compiled using the os x readme instructions, that scene causes a segmentation fault when trying to load on the rpi 3.

**Comment by blair1618** [comment]
Hi, sorry for not responding sooner. Unfortunately our team doesn't have an RPi 3 to test this issue. Can you try the build again and send the log output? Thanks.

**Comment by banagale** [comment]
It's okay we found a workaround. I don't have access to this device currently but if I put my hands on it again will test and reply.

**Comment by blair1618** [comment]
Great, thanks for the reply. I'll close this until we're able to repro the problem.
