### ISSUE TITLE
Add parameter to prevent excessively tall text labels

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#933]
Coordinate with https://github.com/tangrams/tangram/issues/357

**Comment by tallytalwar** [comment]
JS Work: https://github.com/tangrams/tangram/pull/396

**Comment by karimnaaji** [comment]
Closing in favor of the more descriptive https://github.com/tangrams/tangram-es/issues/1543.

**Comment by tallytalwar** [comment]
Ahaa.. totally forgot this issue existed.
