### ISSUE TITLE
Share feature properties of interactive labels for child and parent

### ISSUE THREAD

**Issue by hjanetzek** [tangrams/tangram-es#938]
Currently all properties of a feature are stored twice for interactive icon-text labels. Label::Options::properties should share the same `std::shared_ptr<Properties>` instance instead.

**Comment by karimnaaji** [comment]
Now shared and stored in the tile https://github.com/tangrams/tangram-es/blob/fbaee7a917c92263ea568c11e5c427571ee8272c/core/src/tile/tile.h#L77
