### ISSUE TITLE
Text path 

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#939]
Can I right not straight text on roads& Something like text_path?

**Comment by bcamper** [comment]
@ivangorelow not currently but this is a high-priority feature, and initial progress is here: https://github.com/tangrams/tangram-es/pull/889

**Comment by ivangorelow** [comment]
and when will you have next update?

**Comment by bcamper** [comment]
This feature is in early stage development, but I would expect it should be within the next couple months (possibly sooner, but it's hard to predict since any significant change to labels needs to be carefully tuned/tested).
