### ISSUE TITLE
GCC 4.9 error on RaspberryPI

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/tangram-es#940]
<img width="1341" alt="screen shot 2016-08-29 at 1 24 46 pm" src="https://cloud.githubusercontent.com/assets/346914/18060407/1a317eb2-6dec-11e6-8cc0-aec2e3e13d3a.png">

**Comment by blair1618** [comment]
From the logs, it looks like you should be submitting this bug report to GCC :)

**Comment by blair1618** [comment]
More practically though, you could try just running the build again without cleaning, maybe GCC just ran out of memory.

**Comment by patriciogonzalezvivo** [comment]
thanks!
