### ISSUE TITLE
Position Variable - Point Geometry

### ISSUE THREAD

**Issue by Asjad27** [tangrams/tangram-es#946]
Hi, I am trying to add a specific value to the `position.x` variable in the shader block of a point geometry to shift the points. According to my previous issue created in tangram ([#400](https://github.com/tangrams/tangram/issues/400)) the `position.x` variable is in mercator meters. Hence, I am trying to shift the position of the icons by 10 meters to the right as shown below.

![screenshot from 2016-09-01 12 08 56](https://cloud.githubusercontent.com/assets/4342016/18158461/e230d33e-703c-11e6-9a5e-6e3c25720d8e.png)

Doing so, the points shift to the right but upon changing the zoom level, the points start shifting even further. Upon zooming out, the points shift to the right while they shift back towards their original position to the left upon zooming in as shown in the screenshots below. (See the POI of "Open Kitchen" as a reference)

**Initial load:**
![screenshot from 2016-09-01 12 14 23](https://cloud.githubusercontent.com/assets/4342016/18158602/b871ad1a-703d-11e6-8d66-1aca707e4171.png)

**Upon zooming out:**
![screenshot from 2016-09-01 12 14 37](https://cloud.githubusercontent.com/assets/4342016/18158604/b87f0c94-703d-11e6-95b7-743044baaef5.png)

**Upon zooming in:**
![screenshot from 2016-09-01 12 14 52](https://cloud.githubusercontent.com/assets/4342016/18158603/b87858d6-703d-11e6-91d4-96ce2ca8e044.png)

Thankyou!

**Comment by blair1618** [comment]
Hello! Thanks for the detailed description and screenshots. 

If you try this same example on a polygon- or polyline-based style, you'll find that the geometry is indeed moved by 10 Mercator meters to the East. The "points" style and the "text" style behave somewhat differently. 

In tangram-es, "points" and "text" style geometry is arranged in *screen space*, not in world space, so changing `position.x` here will adjust the horizontal location of the point or text in pixels in screen space. 

This example shows that the behavior of the `position` variable for points and text is different between tangram-es and tangram-js, so thanks for bringing this to our attention! We'll consider ways to bring these behaviors into parity in future releases. 

If your goal is to modify the position of point or text geometry, I'd suggest to use the [offset](https://mapzen.com/documentation/tangram/draw/#offset) and [anchor](https://mapzen.com/documentation/tangram/draw/#anchor) parameters instead.

**Comment by Asjad27** [comment]
Thank you. That would have been my next question but you already answered it. Doing the same on Tangram-JS using Tangram Play, the point geometry shifts appropriately and does not move with changing zoom level.

The main goal of shifting the point geometry is that I need to animate a marker from one location to another location in real time. My approach is to get the current location of the marker and take its difference with the next location and subsequently add that difference to the original position to update the location of the marker/point. Currently, I am using a static location stored in a uniform variable and adding that to the position variable. I aim to update that uniform variable from within Tangram to reflect the changes in the position. How do you suggest I do this if the point geometry is in screen space and I'm getting the next location in Lat/Lon or Mercator meters?

Thank you!

**Comment by tallytalwar** [comment]
> The main goal of shifting the point geometry is that I need to animate a marker from one location to another location in real time.

We just merged some code for a more robust marker support (https://github.com/tangrams/tangram-es/pull/930). You can achieve real time update of a marker from one position to another using [this]. (https://github.com/tangrams/tangram-es/blob/master/core/src/tangram.h#L173). 

This still requires some more work specifically to provide API bindings for different platforms including `android` and `ios`. You should expect all this work including platform APIs support in our next release.

For the time being you can use our master branch and use the marker framework on `osx` or `linux` application.

**Comment by Asjad27** [comment]
Thank you for the quick response. I will look into this and will get back to you if I run into any problems. 

Also, can you tell me about when is the next release expected?

Thanks

**Comment by tallytalwar** [comment]
Hey @Asjad27 

We should have a release with Android bindings in a couple of weeks. Will update the thread once we have a release out.

Thanks

**Comment by Asjad27** [comment]
Hi @tallytalwar 

Hope things are going well at your end. I have been trying to use the latest master branch of tangram-es for creation of markers. Currently, I am unable to even create and display the marker(s) in the first place. Can you provide me some test or sample code to at least give me an idea of how to use the marker classes?

Thankyou :)

**Comment by Asjad27** [comment]
Hey I was meddling around with the code and found the problem due to which the marker wasn't showing. See [this (line 249).](https://github.com/tangrams/tangram-es/blob/master/core/src/marker/markerManager.cpp#L249) I changed this line to

`marker.setDrawRule(std::make_unique<DrawRuleData>(marker.stylingString(), 0, std::move(params)));`

and it worked and my marker(s) started to display. Still have a few problems though

**Comment by blair1618** [comment]
@Asjad27 The change you've described should have no bearing on the behavior of markers, I suspect that this is coincidence. An example of creating a polyline marker can be found in the OS X demo app: https://github.com/tangrams/tangram-es/blob/master/osx/src/main.cpp#L111-L115

**Comment by Asjad27** [comment]
@blair1618 Oh okay I got it. I was actually assigning the name of the style for the marker from YAML instead of defining the complete styling string ("markers" as opposed to "{ style: 'markers' }"). Hence the change I did was making it work. It has no effect if the styling string is defined like it is done in the example. Thankyou!
