### ISSUE TITLE
zoom and position

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#968]
Is it possible make eased effect to setPosition and setZoom togezer whith linear effect?

**Comment by blair1618** [comment]
To ease position and zoom together you just need to call `setPositionEased` and `setZoomEased` with the same duration and the `linear` ease type at the same time.

**Comment by blair1618** [comment]
I'll assume this is resolved. If you have more questions feel free to ask here or on [gitter](https://gitter.im/tangrams/tangram-chat).
