### ISSUE TITLE
do you have a way to create bubbleinfo?

### ISSUE THREAD

**Issue by ivangorelow** [tangrams/tangram-es#983]

**Comment by blair1618** [comment]
Can you explain what you mean by "bubbleinfo" or provide an example?

**Comment by ivangorelow** [comment]
![image](https://cloud.githubusercontent.com/assets/20596378/18998338/f9d85546-8740-11e6-877f-83b9262173c7.png)
something like that

**Comment by blair1618** [comment]
No, tangram-es does not currently provide a way to create this kind of "bubble" view or "Info Window", as they are called in the Google Maps API.
