### ISSUE TITLE
Android: Use resources for textures

### ISSUE THREAD

**Issue by westnordost** [tangrams/tangram-es#990]
Currently, tangram searches for textures referenced in the `scene.yaml` in the same directory as where the scene.yaml is defined, which is `assets/`. The suggestion is to make tangram-es use Android's Resource management to get the right textures for the right DPI, in other words, search for textures in `res/drawable/` or similar.

**Reason**:
I read that `px` in the scene definition are device dependent pixels, so icons (i.e. POI markers) scale with the DPI of the Android device. That's good.
However, what does not scale is the _source_ of the icons. So to neatly support every device, I'd have to have a `poi_icons@4x.png` (to support xxxhdpi) in the `assets/` folder and let tangram then scale down these icons for all devices except the xxxhdpi devices.
The Android solution would be to instead supply a `poi_icons.png` for mdpi (1x), hdpi (1.5x), xhdpi (2x), ... separately and let the device choose which texture to load.

**Comment by nvkelso** [comment]
+1

**Comment by blair1618** [comment]
Yep, this is a good way to make images easier to work with on Android! I've been planning to make this available for marker images for a while and it should be usable before too long. 

For textures specified inside a scene file it's a little trickier, but may be possible with more work. The trouble is mainly that the NDK interface doesn't provide any access to Resources, only Assets. So, if we're applying a Resource bitmap to something that's being created from Java code, that's not so bad, but if the core library needs to access Resource bitmaps then we'd have to call into Java, try to get the bitmap, and then go back into the core library with that data - it's just complicated.

**Comment by westnordost** [comment]
Oh, that's too bad. I can think of a few workarounds, but I think each is uglier than just accepting that POIs will be a little blurry on high DPI devices.

**Comment by matteblair** [comment]
Closing this issue to clean up our backlog. In conclusion, reading images from density-dependent Resources on Android is probably more trouble than it's worth. If a project requires images optimized for different screen densities then the best solution for Tangram right now would be to ship different scene files and images for different device densities.
