### ISSUE TITLE
GUI for tangram-es desktop applications and deployment to s3 for internal usage

### ISSUE THREAD

**Issue by tallytalwar** [tangrams/tangram-es#992]
It will be good to have some gui elements for tangram-es desktop applications (OSX, Linux).

Some good C++ Opengl based UI libraries are: https://github.com/ocornut/imgui, https://github.com/wjakob/nanogui

Things to get done for this:

- [ ] Debugging menu to toggle different debug options we have hidden in the demo apps
- [ ] Ability to take a screen crab so that we can test out the "view ready" functionality.
- [ ] Deployment of an osx app to s3 for internal consumption (usage). (To be done as part of https://github.com/tangrams/tangram-es/issues/1571)

**Comment by tallytalwar** [comment]
Updated this Issue to have some more defined tasks. Feel free to add any thing I missed.

**Comment by matteblair** [comment]
IMGUI has been integrated in the desktop demo app now, and it doesn't seem like we've had a very serious need to deploy the desktop build artifacts. I'll go ahead and close this.
