### ISSUE TITLE
Markers behavior when wrapping the world

### ISSUE THREAD

**Issue by karimnaaji** [tangrams/tangram-es#995]
When a marker is added, what behavior do we expect when the world is being wrapped? 

Right now our marker system makes the marker stay where it has been placed and its position doesn't wrap. It would be worth to look at other map renderer to see what behavior is usually adopted.

**Comment by blair1618** [comment]
Just checked out this case in Apple Maps and Google Maps on macOS desktop. They handle this the same way. The marker is repeated each time that the view wraps in longitude. ~But~ this wrapping behavior differs from tangram-es in a crucial way: _the map will not show any point on the Earth more than once in a single view_. This seems to be implemented as a constraint on the minimum view-able zoom level based on the dimensions of the map view. I've always found it weird for a map to show more than one representation of the same point, so I rather like this feature and I would like to implement it in tangram-es. This would mean that we would no longer create different tiles for "wrapped" locations and all geographic points would just take their nearest position to the view modulo 180 degrees longitude.

**Comment by matteblair** [comment]
This has been resolved - Tangram now renders any point on earth at most once at one time, and so we are able to wrap Markers around the anti-meridian correctly.
