### ISSUE TITLE
getting the URL fetcher with context， so it can be implement by using pure C API callback

### ISSUE THREAD

**Issue by lygstate** [tangrams/tangram-es#998]

**Comment by lygstate** [comment]
https://github.com/lygstate/tangram-es/commit/7dfd5d3e1a2a61601a65d85b57e5315c38c34512

**Comment by lygstate** [comment]
refer to https://github.com/lygstate/tangram-es/commit/7dfd5d3e1a2a61601a65d85b57e5315c38c34512

**Comment by tallytalwar** [comment]
Thanks @lygstate 
Fine with this. But it does not affect tangram-es right now, so you can include this with the C API work you are doing. We do like the usage of C API and we do plan include it.

**Comment by lygstate** [comment]
done in a simpler way
